- README.md
Also unify dotnet, DotNet, Dotnet, .NET. Fixes #7.
> Fix image name in readme

- 0.0.1-alpha/Dockerfile
@dleeapho, @naamunds This change is needed as we get ready for our next official release.  This addresses #19
> Updated the Dockerfile to pull a specific version of dotnet.

- 0.0.1-alpha/Dockerfile
This reduces the image size by ~21mb.
/cc @naamunds
> Added logic to cleanup the apt cache.

- 1.0.0-preview2/Dockerfile
- 1.0.0-rc3/core-deps/Dockerfile
> Updated .NET CLI dependencies

- 1.0.0-preview2/nanoserver/Dockerfile
- 1.0.0/nanoserver/core/Dockerfile
The documentation referenced still needs to be updated but there is a PR for that - https://github.com/dotnet/cli/pull/3635
@naamunds, @dleeapho
> Updated forwarders workaround to match recommendation

- 1.0.0-preview2/debian/Dockerfile
- 1.0.0-preview2/nanoserver/Dockerfile
- 1.0.0-preview2/windowsservercore/x64/Dockerfile
- 1.0.0-preview2/windowsservercore/x86/Dockerfile
> Update cli to 1.0.0-preview2-003121

- 1.0.0-preview2/debian/Dockerfile
- 1.0.0-preview2/nanoserver/Dockerfile
- 1.0.0-preview2/windowsservercore/x64/Dockerfile
- 1.0.0-preview2/windowsservercore/x86/Dockerfile
Fixes #58 
@naamunds, @dleeapho
> Triggered the building of local package cache in the SDK images

- 1.0.0/README.md
> Fixed broken links for RTM/Preview2

- 1.0.0/README.md
> Clarify onbuild image description

- 1.0.0-rc2/core-deps/hooks/post_build
- 1.0.0/README.md
- 1.0.0/debian/core-deps/hooks/post_build
> Fix typos in post_build and README

- ISSUE_TEMPLATE
There has been an increase in the number of issues that do not include this basic information.  Hopefully by introducing a template, authors will include this information and the issues will get resolved quicker.
> Added an ISSUE_TEMPLATE

- 1.0.0-preview2/nanoserver/Dockerfile
- 1.0.0-preview2/windowsservercore/Dockerfile
- 1.0.0/nanoserver/core/Dockerfile
- 1.0.0/windowsservercore/core/Dockerfile
> Updated Windows images to be based on specific OS image from Docker Hub

- 1.0.0/debian/core-deps/hooks/post_push
> Added logic to push 1.0-core-deps, 1-core-deps, 1.0-core and 1-core tags

- 1.0/README.md
These cause clutter and confusion for newbies.
@dleeapho
> Removed alpha and preview1/rc2 images from the readme

- 1.0.0-preview2/debian/Dockerfile
- 1.0.0-preview2/nanoserver/Dockerfile
- 1.0.0-preview2/windowsservercore/Dockerfile
- 1.0/README.md
- 1.0/debian/core-deps/hooks/post_push
- 1.0/debian/core/Dockerfile
- 1.0/nanoserver/core/Dockerfile
- 1.0/windowsservercore/core/Dockerfile
> Updated .NET Core to 1.0.1 and SDK to 1.0.0-preview2-003131

- 1.0/README.md
Adding link to Building Docker Images for .NET Core Applications per @stevelasker request.
> Add link to Docker images doc

- 1.0/README.md
> Fix broken README links

- .gitignore
- 1.0/debian/core/Dockerfile
- build-and-test.ps1
- build-and-test.sh
- netci.groovy
- test/create-run-publish-app.ps1
- test/create-run-publish-app.sh
- test/run-test.ps1
- test/run-test.sh
Whenever a PR is created in the master branch, a Jenkins job will build
each Dockerfile in the repo and run tests on the images. The tests
perform a simple smoke test on the images.
cc: @MichaelSimons
> Add Jenkins CI and automated tests 

- 1.0.0-preview2/nanoserver/Dockerfile
- 1.0/nanoserver/core/Dockerfile
> Modified Nano Dockerfiles to make use of new Invoke-WebRequest support

- 1.0.0-preview2/nanoserver/Dockerfile
- 1.0/nanoserver/core/Dockerfile
> Update Nano Dockerfiles to 10.0.14393.321

- build-and-test.ps1
- netci.groovy
> Enable CI on Windows

- 1.0/README.md
> Update readme for 1.1.0-preview1 runtime and 1.0.0-preview2.1 sdk release

- 1.0/README.md
/cc @MichaelSimons @kendrahavens @glennc @shirhatti @billwagner
> Update readme to match Docker norm

- 1.0/README.md
> Fix a typo in README.md

- 1.0/README.md
Fixes #138 
@naamunds, @richlander
> Add sdk and nanoserver-sdk tags

- 1.0/README.md
> Fixed broken links in README.md

- 1.0/README.md
/cc @MichaelSimons, @kendrahavens, @billwagner
> Update flow and cleanup README

- 1.0/README.md
Fixed a typo in the Readme URL
> Fixed a typo in the Readme URL

- 1.0.0-preview2.1/nanoserver/sdk/Dockerfile
- 1.0.0-preview2/nanoserver/sdk/Dockerfile
- 1.0/nanoserver/runtime/Dockerfile
- 1.1.0-preview1/nanoserver/runtime/Dockerfile
> Updating Nano Server Dockerfiles to be based on 10.0.14393.447

- 1.0/README.md
- 1.1/debian/sdk/msbuild/Dockerfile
- test/create-run-publish-app.ps1
- test/create-run-publish-app.sh
> Misc cleanup changes for the 1.1 release

- 1.0/README.md
> Changed single quotes to back-ticks in tags section for better formatting/readability

- 1.0/debian/runtime-deps/hooks/post_push
- 1.0/debian/sdk/msbuild/hooks/post_push
- 1.0/debian/sdk/projectjson/hooks/post_push
- 1.1/debian/runtime-deps/hooks/post_push
- 1.1/debian/sdk/msbuild/hooks/post_push
- 1.1/debian/sdk/projectjson/hooks/post_push
Also cleaned up the existing post_push hooks.
Related to https://github.com/dotnet/dotnet-docker-nightly/issues/112
@naamunds
> Added post_push sdk build hooks to correctly push multi-tags

- build-and-test.ps1
- netci.groovy
- test/create-run-publish-app.ps1
- test/run-test.ps1
Porting https://github.com/dotnet/dotnet-docker-nightly/commit/aaf2f21689d3d3c476b2f845588d234ed6422e2c to official.
@naamunds
> xplat build-and-test script

- 1.0/nanoserver/runtime/Dockerfile
- 1.0/nanoserver/sdk/projectjson/Dockerfile
- 1.1/nanoserver/runtime/Dockerfile
- 1.1/nanoserver/sdk/projectjson/Dockerfile
@dotnet-bot test NanoServer please
> Updating Nano Server Dockerfiles to be based on 10.0.14393.576

- 1.0/nanoserver/runtime/Dockerfile
- 1.0/nanoserver/sdk/projectjson/Dockerfile
- 1.1/nanoserver/runtime/Dockerfile
- 1.1/nanoserver/sdk/projectjson/Dockerfile
Updating Nano Server Dockerfiles to be based on 10.0.14393.693
> Updating Nano Server Dockerfiles to be based on 10.0.14393.693

- 1.0/README.md
- 1.0/debian/sdk/msbuild/Dockerfile
- 1.0/debian/sdk/msbuild/hooks/post_push
- 1.0/nanoserver/sdk/msbuild/Dockerfile
- 1.1/debian/sdk/msbuild/Dockerfile
- 1.1/debian/sdk/msbuild/hooks/post_push
- 1.1/nanoserver/sdk/msbuild/Dockerfile
- test/create-run-publish-app.ps1
- test/create-run-publish-app.sh
These changes were copied directly from [dotnet-docker-nightly](https://github.com/dotnet/dotnet-docker-nightly)
> Updated Dockerfiles for CLI RC3 release

- 1.0/nanoserver/runtime/Dockerfile
- 1.0/nanoserver/sdk/msbuild/Dockerfile
- 1.0/nanoserver/sdk/projectjson/Dockerfile
- 1.1/nanoserver/runtime/Dockerfile
- 1.1/nanoserver/sdk/msbuild/Dockerfile
- 1.1/nanoserver/sdk/projectjson/Dockerfile
1. Add `ProgressPreference` - this will greatly speed up the build because of PowerShell bug: https://github.com/PowerShell/PowerShell/issues/2138#issuecomment-251261324
2. Use PowerShell throughout for consistency
> Simplify windows dockerfiles

- 1.0/README.md
> Removed the number of Docker pulls and stars from readme.

- netci.groovy
- test/Dockerfile.linux.testrunner
Replaces https://github.com/dotnet/dotnet-docker/pull/193
Comments addressed
> use powershell to run tests on linux

- 1.0/README.md
The `dotnet new` template commands have changed.
> Fix dotnet new -t

- 1.0/debian/sdk/Dockerfile
- 1.0/debian/sdk/hooks/post_push
- 1.0/nanoserver/sdk/Dockerfile
- 1.1/debian/sdk/Dockerfile
- 1.1/debian/sdk/hooks/post_push
- 1.1/nanoserver/sdk/Dockerfile
This will get merged after https://github.com/dotnet/dotnet-docker/pull/214 so that the sdk-1.0.0 images get built.
cc @natemcmaster
> Update SDK to 1.0.1

- build-pipeline/dotnet-docker-linux-images.json
- build-pipeline/dotnet-docker-post-image-build.json
- build-pipeline/dotnet-docker-windows-images.json
> Upgrade image builder to address PublishManifest regression

- README.md
> Add nightly repo link to README.md

- 1.0/runtime/nanoserver/Dockerfile
- 1.0/sdk/nanoserver/Dockerfile
- 1.1/runtime/nanoserver/Dockerfile
- 1.1/sdk/nanoserver/Dockerfile
- 2.0/runtime/nanoserver/Dockerfile
- 2.0/sdk/nanoserver/Dockerfile
- manifest.json
Updating Nano Server Dockerfiles to be based on 10.0.14393.1358
> Updating Nano Server Dockerfiles to be based on 10.0.14393.1358

- build-pipeline/dotnet-docker-linux-images.json
- build-pipeline/dotnet-docker-post-image-build.json
- build-pipeline/dotnet-docker-windows-images.json
related to dotnet/docker-tools#13
> Update image-builder to latest version

- build-pipeline/dotnet-docker-linux-images.json
- build-pipeline/dotnet-docker-post-image-build.json
- build-pipeline/dotnet-docker-windows-images.json
Related to dotnet/dotnet-docker#257 and dotnet/dotnet-docker#256
> Update Agent pool and tweak cleanup step settings

- 2.0/runtime-deps/stretch/Dockerfile
- 2.0/runtime/jessie/Dockerfile
- 2.0/runtime/nanoserver/Dockerfile
- 2.0/runtime/stretch/Dockerfile
- 2.0/sdk/jessie/Dockerfile
- 2.0/sdk/nanoserver/Dockerfile
- 2.0/sdk/stretch/Dockerfile
- LICENSE
- README.md
- build-and-test.ps1
- manifest.json
- test/Dockerfile.test
- test/run-test.ps1
FYI - CI is expected to fail until the 2.0.0-preview2 NuGet packages are released.
> Adding 2.0.0-preview2 Dockerfiles

- netci.groovy
Merged https://github.com/dotnet/dotnet-docker-nightly/pull/358 from the nightly repo into the official repo.
Fixes #264
> Broke apart CI into more jobs

- 1.0/runtime/nanoserver/Dockerfile
- 1.0/sdk/nanoserver/Dockerfile
- 1.1/runtime/nanoserver/Dockerfile
- 1.1/sdk/nanoserver/Dockerfile
- 2.0/runtime/nanoserver/Dockerfile
- 2.0/sdk/nanoserver/Dockerfile
- manifest.json
Updating Nano Server Dockerfiles to be based on 10.0.14393.1593
> Updating Nano Server Dockerfiles to be based on 10.0.14393.1593

- README.md
@MichaelSimons I addressed all of your comments from the stale PR.
> Update ReadMe to use multi-stage build sample

- README.md
Attempt to address feedback per https://github.com/dotnet/dotnet-docker-nightly/pull/328#issuecomment-322859900
> Add readme link to ARM32 announcement for additional details

- netci.groovy
Refer https://github.com/dotnet/dotnet-docker-nightly/pull/430
> Switch to image that contains Docker 17.06.1-ee-2.

- manifest.json
- scripts/Get-TagsDocumentation.ps1
Port changes from https://github.com/dotnet/dotnet-docker-nightly/pull/455
Fixes #312
> [Port] Stop producing Nano Server Version suffixed tags.

- build-and-test.ps1
- build-pipeline/dotnet-docker-linux-amd64-images.json
- build-pipeline/dotnet-docker-linux-arm32v7-images.json
- build-pipeline/dotnet-docker-post-image-build.json
- build-pipeline/dotnet-docker-windows-amd64-images.json
- build-pipeline/pipeline.json
- netci.groovy
- test/Dockerfile.linux.testrunner
- test/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
- test/Microsoft.DotNet.Docker.Tests/ImageTests.cs
CI is expected to fail due to the netci.groovy changes.
> Merge build infra and test changes from nightly repo

- 1.0/runtime/nanoserver/Dockerfile
- 1.0/sdk/nanoserver/Dockerfile
- 1.1/runtime/nanoserver/Dockerfile
- 1.1/sdk/nanoserver/Dockerfile
- 2.0/runtime/nanoserver/amd64/Dockerfile
- 2.0/sdk/nanoserver/amd64/Dockerfile
Refer https://github.com/dotnet/dotnet-docker-nightly/pull/463
> [Port] Add escape directive in Nano Server Dockerfiles

- README.md
- manifest.json
> Add <major>-<minor> non-manifest tags

- build-and-test.ps1
- build-pipeline/dotnet-docker-linux-amd64-images.json
- build-pipeline/dotnet-docker-linux-arm32v7-images.json
- build-pipeline/dotnet-docker-windows-1709-amd64-images.json
- build-pipeline/dotnet-docker-windows-amd64-images.json
- build-pipeline/pipeline.json
- manifest.json
- netci.groovy
- test/Microsoft.DotNet.Docker.Tests/ImageTests.cs
- test/run-test.ps1
Port changes from https://github.com/dotnet/dotnet-docker-nightly/pull/490
> [Port] Add support to test Nano Server images

- README.md
> Add Windows 1709 multi-arch tags to readme

- netci.groovy
Enables CI for Windows Server 1709 images.
> [Port] CI for 1709

- 2.1/sdk/jessie/amd64/Dockerfile
- 2.1/sdk/nanoserver-1709/amd64/Dockerfile
- 2.1/sdk/nanoserver-sac2016/amd64/Dockerfile
- 2.1/sdk/stretch/amd64/Dockerfile
- test/Microsoft.DotNet.Docker.Tests/ImageDescriptor.cs
- test/Microsoft.DotNet.Docker.Tests/ImageTests.cs
> Refactor pattern used to initial NuGet package cache

- build-pipeline/dotnet-docker-linux-amd64-images.json
- build-pipeline/dotnet-docker-linux-arm32v7-images.json
- build-pipeline/dotnet-docker-windows-1709-amd64-images.json
- build-pipeline/dotnet-docker-windows-sac2016-amd64-images.json
> Increase build timeout

- test/Microsoft.DotNet.Docker.Tests/Dockerfile.linux.testapp
- test/Microsoft.DotNet.Docker.Tests/Dockerfile.linux.testapp.selfcontained
- test/Microsoft.DotNet.Docker.Tests/Dockerfile.windows.testapp
- test/Microsoft.DotNet.Docker.Tests/ImageTests.cs
- test/Microsoft.DotNet.Docker.Tests/Microsoft.DotNet.Docker.Tests.csproj
This will make it easier to merge changes between the master and nightly branches.
> Eliminate test source differences between master and nightly

- build-pipeline/dotnet-docker-linux-arm32v7-images.json
> Fixup arm build leg which has conflicting refName properties

- samples/aspnetapp/README.md
- samples/aspnetapp/deploy-container-to-aci.md
Thanks to @jamesmontemagno for reporting this.
> Fix bad Docker login instructions

- 2.1/runtime-deps/alpine/amd64/Dockerfile
- 2.1/runtime-deps/bionic/amd64/Dockerfile
- 2.1/runtime-deps/bionic/arm32v7/Dockerfile
- 2.1/runtime-deps/stretch-slim/amd64/Dockerfile
- 2.1/runtime-deps/stretch-slim/arm32v7/Dockerfile
- 2.1/sdk/bionic/amd64/Dockerfile
- 2.1/sdk/stretch/amd64/Dockerfile
Based on https://github.com/dotnet/coreclr/issues/16642
> Remove libuuid dependency from 2.1

- 2.0/runtime-deps/jessie/amd64/Dockerfile
- 2.0/runtime-deps/stretch/amd64/Dockerfile
- 2.0/runtime-deps/stretch/arm32v7/Dockerfile
- 2.0/runtime/nanoserver-1709/amd64/Dockerfile
- 2.0/runtime/nanoserver-sac2016/amd64/Dockerfile
- 2.0/sdk/jessie/amd64/Dockerfile
- 2.0/sdk/nanoserver-1709/amd64/Dockerfile
- 2.0/sdk/nanoserver-sac2016/amd64/Dockerfile
- 2.0/sdk/stretch/amd64/Dockerfile
Same as #445. Replaces #447.
Also based on feedback given in #434
> Add environment variables to 2.0

- build-pipeline/dotnet-docker-linux-arm32v7-images.json
- build-pipeline/dotnet-docker-windows-1709-amd64-images.json
- build-pipeline/dotnet-docker-windows-sac2016-amd64-images.json
> Changes to build infrastructure to build on arm hardware

- 2.1/runtime-deps/alpine/amd64/Dockerfile
- 2.1/runtime-deps/bionic/amd64/Dockerfile
- 2.1/runtime-deps/bionic/arm32v7/Dockerfile
- 2.1/runtime-deps/stretch-slim/amd64/Dockerfile
- 2.1/runtime-deps/stretch-slim/arm32v7/Dockerfile
- 2.1/sdk/bionic/amd64/Dockerfile
- 2.1/sdk/bionic/arm32v7/Dockerfile
- 2.1/sdk/stretch/amd64/Dockerfile
- 2.1/sdk/stretch/arm32v7/Dockerfile
> Sync runtime-deps dependencies with product

- 2.0/runtime-deps/jessie/amd64/Dockerfile
- 2.0/runtime-deps/stretch/amd64/Dockerfile
- 2.0/runtime-deps/stretch/arm32v7/Dockerfile
- 2.0/runtime/nanoserver-1709/amd64/Dockerfile
- 2.0/runtime/nanoserver-sac2016/amd64/Dockerfile
- 2.0/sdk/jessie/amd64/Dockerfile
- 2.0/sdk/nanoserver-1709/amd64/Dockerfile
- 2.0/sdk/nanoserver-sac2016/amd64/Dockerfile
- 2.0/sdk/stretch/amd64/Dockerfile
> Revert change to add ENV ASPNETCORE_URLS=http://+:80 to 2.0 images

- README.md
- samples/aspnetapp/aspnet-docker-dev-in-container.md
- samples/dotnetapp/dotnet-docker-dev-in-container.md
- scripts/TagsDocumentationTemplate.md
> Update 'Preview 2' references in readme and samples to 'RC1'

- manifest.json
> Update variant in manifest for arm images to be 'v7'

- 2.0/runtime/nanoserver-1803/amd64/Dockerfile
- 2.0/sdk/nanoserver-1803/amd64/Dockerfile
- 2.1/aspnetcore-runtime/nanoserver-1803/amd64/Dockerfile
- 2.1/runtime/nanoserver-1803/amd64/Dockerfile
- 2.1/sdk/nanoserver-1803/amd64/Dockerfile
- README.md
- build-pipeline/dotnet-docker-linux-amd64-images.json
- build-pipeline/dotnet-docker-linux-arm32v7-images.json
- build-pipeline/dotnet-docker-post-image-build.json
- build-pipeline/dotnet-docker-windows-1709-amd64-images.json
- build-pipeline/dotnet-docker-windows-1803-amd64-images.json
- build-pipeline/dotnet-docker-windows-sac2016-amd64-images.json
- build-pipeline/pipeline-samples.json
- build-pipeline/pipeline.json
- manifest.json
- manifest.samples.json
- samples/README.DockerHub.md
- scripts/TagsDocumentationTemplate.md
- test/Microsoft.DotNet.Docker.Tests/ImageTests.cs
- test/Microsoft.DotNet.Docker.Tests/OS.cs
> Add Windows RS4 Dockerfiles

- README.md
- manifest.json
- scripts/TagsDocumentationTemplate.md
> Update tags for 2.1 RTM

- README.md
People have asked about this. Search for "containers" in the referenced document.
> Add licensing link for Windows

- samples/dotnetapp/Dockerfile.alpine-x64-selfcontained
- samples/dotnetapp/README.md
- samples/dotnetapp/dotnet-docker-selfcontained.md
> Add Alpine self-contained sample

- netci.groovy
> Add Server RS4 support

- netci.groovy
This enables Windows Server, version 1803 CI
> Merge latest changes from `master` into `nightly`

- 2.1/aspnetcore-runtime/alpine3.7/amd64/Dockerfile
Fix typo in comment: `laod` => `load`
> Fix typo in comment

- .vsts.pipelines/templates/build-all.yml
Pull in fix for https://github.com/dotnet/docker-tools/issues/101.
> Pull in latest image-builder to fix issue with updating DH readme

- .vsts.pipelines/templates/build-all.yml
- .vsts.pipelines/templates/build-windows-amd64.yml
> Update queue used for Windows Server 2016 legs

- build-pipeline/dotnet-docker-windows-sac2016-amd64-images.json
> Update sac2016 build queue

- samples/dotnetapp/Dockerfile.nanoserver-x64-selfcontained
I noticed this issue while investigating #625.
> Fix broken copy from reference in nano selfcontained Dockerfile

- .vsts-pipelines/phases/test-linux-amd64.yml
- .vsts-pipelines/phases/test-linux-arm32v7.yml
- .vsts-pipelines/phases/test-windows-amd64.yml
Fixing the broken test run titles that appear in the test results - see https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=1847705&view=ms.vss-test-web.test-result-details
> [build pipeline] Update testRunTitle to reference the correct variable

- samples/dotnetapp/Dockerfile.alpine-x64-selfcontained
- samples/dotnetapp/Dockerfile.debian-arm32-selfcontained
- samples/dotnetapp/Dockerfile.debian-x64-selfcontained
- samples/dotnetapp/Dockerfile.nanoserver-x64-selfcontained
- samples/dotnetapp/build.ps1
- samples/test-samples.ps1
- Add script
- Update linker version
- Fix user reported bugs
#fixes 626
> Add script to test samples

- .vsts-pipelines/phases/build-windows-amd64.yml
- .vsts-pipelines/phases/copy-images-windows.yml
- .vsts-pipelines/phases/test-windows-amd64.yml
- .vsts-pipelines/steps/docker-init-windows.yml
Encapsulate the logic to initialize ImageBuilder within docker-init-windows.yml
> [Build YAML] Encapsulate ImageBuilder initialization within docker-init-windows

- 2.1/sdk/alpine3.7/amd64/Dockerfile
- 2.1/sdk/bionic/amd64/Dockerfile
- 2.1/sdk/bionic/arm32v7/Dockerfile
- 2.1/sdk/nanoserver-1709/amd64/Dockerfile
- 2.1/sdk/nanoserver-1803/amd64/Dockerfile
- 2.1/sdk/nanoserver-sac2016/amd64/Dockerfile
- 2.1/sdk/stretch/amd64/Dockerfile
- 2.1/sdk/stretch/arm32v7/Dockerfile
- README.md
- manifest.json
- scripts/TagsDocumentationTemplate.md
> Updates for SDK 2.1.400 release

- .vsts-pipelines/steps/docker-init-windows.yml
- samples/aspnetapp/Dockerfile
- samples/aspnetapp/aspnetapp/NuGet.config
- samples/aspnetapp/aspnetapp/aspnetapp.csproj
- samples/dotnetapp/Dockerfile.alpine-x64-selfcontained
- samples/dotnetapp/Dockerfile.debian-arm32-selfcontained
- samples/dotnetapp/Dockerfile.debian-x64-selfcontained
- samples/dotnetapp/Dockerfile.nanoserver-x64-selfcontained
- samples/dotnetapp/build.ps1
- samples/test-samples.ps1
> Merge master into nightly

- .vsts-pipelines/builds/microsoft-dotnet-nightly.yml
- .vsts-pipelines/builds/microsoft-dotnet-samples.yml
- .vsts-pipelines/builds/microsoft-dotnet.yml
- .vsts-pipelines/phases/build-all.yml
- .vsts-pipelines/phases/build-linux-amd64.yml
- .vsts-pipelines/phases/build-linux-arm32v7.yml
- .vsts-pipelines/phases/build-windows-amd64.yml
- .vsts-pipelines/phases/copy-images-linux.yml
- .vsts-pipelines/phases/copy-images-windows.yml
- .vsts-pipelines/phases/publish-finalize.yml
- .vsts-pipelines/phases/test-linux-amd64.yml
- .vsts-pipelines/phases/test-linux-arm32v7.yml
- .vsts-pipelines/phases/test-windows-amd64.yml
- .vsts-pipelines/steps/docker-cleanup-linux.yml
- .vsts-pipelines/steps/docker-cleanup-windows.yml
- .vsts-pipelines/steps/docker-init-linux.yml
- .vsts-pipelines/steps/docker-init-windows.yml
- Removed the majority of the parameters being passed around.  Replaced with variables.
- Encapsulated more shared setup/cleanup logic in templates.
> Misc changes that simplify build definitions

- .vsts-pipelines/builds/microsoft-dotnet-nightly.yml
- .vsts-pipelines/builds/microsoft-dotnet-samples.yml
- .vsts-pipelines/builds/microsoft-dotnet.yml
- .vsts-pipelines/phases/build-all.yml
- .vsts-pipelines/phases/build-linux-amd64.yml
- .vsts-pipelines/phases/build-linux-arm32v7.yml
- .vsts-pipelines/phases/build-windows-amd64.yml
- .vsts-pipelines/phases/copy-images-linux.yml
- .vsts-pipelines/phases/copy-images-windows.yml
- .vsts-pipelines/phases/publish-finalize.yml
- .vsts-pipelines/phases/test-linux-amd64.yml
- .vsts-pipelines/phases/test-linux-arm32v7.yml
- .vsts-pipelines/phases/test-windows-amd64.yml
- .vsts-pipelines/steps/docker-cleanup-linux.yml
- .vsts-pipelines/steps/docker-cleanup-windows.yml
- .vsts-pipelines/steps/docker-init-linux.yml
- .vsts-pipelines/steps/docker-init-windows.yml
> Merge build-infra changes from nightly to master

- 1.0/runtime/jessie/amd64/Dockerfile
- 1.0/runtime/nanoserver-sac2016/amd64/Dockerfile
- 1.1/runtime-deps/stretch/amd64/Dockerfile
- 1.1/runtime/jessie/amd64/Dockerfile
- 1.1/runtime/nanoserver-sac2016/amd64/Dockerfile
- 1.1/runtime/stretch/amd64/Dockerfile
- 1.1/sdk/jessie/amd64/Dockerfile
- 1.1/sdk/nanoserver-sac2016/amd64/Dockerfile
- 1.1/sdk/stretch/amd64/Dockerfile
- README.md
- TAGS.md
- manifest.json
- scripts/ReadmeTagsDocumentationTemplate.md
- scripts/TagsDocumentationTemplate.md
- tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs
> [Nightly] Updates for the 1.0.13 and 1.1.10 releases

- 2.1/runtime-deps/alpine3.8/amd64/Dockerfile
- 3.0/runtime-deps/alpine3.8/amd64/Dockerfile
> Update alpine 3.8 images to be based on the 3.8 tag

- .vsts-pipelines/builds/microsoft-dotnet-nightly.yml
- .vsts-pipelines/builds/microsoft-dotnet-samples.yml
- .vsts-pipelines/builds/microsoft-dotnet.yml
- .vsts-pipelines/jobs/build-all.yml
- .vsts-pipelines/jobs/build-images-linux-client.yml
- .vsts-pipelines/jobs/build-images-windows-client.yml
- .vsts-pipelines/jobs/copy-images-linux.yml
- .vsts-pipelines/jobs/copy-images-windows.yml
- .vsts-pipelines/jobs/publish-finalize.yml
- .vsts-pipelines/jobs/test-images-linux-client.yml
- .vsts-pipelines/jobs/test-images-windows-client.yml
- .vsts-pipelines/steps/init-docker-windows.yml
The build yaml schema changed from preview to release.  This change updates the build definition to use the latest schema.
> Update build YAML schema to latest

- samples/aspnetapp/README.md
Just fixing a typo - you obviously meant "terminated"
> Fixing Typo

- 3.0/aspnetcore-runtime/bionic/amd64/Dockerfile
- 3.0/aspnetcore-runtime/bionic/arm32v7/Dockerfile
- 3.0/sdk/bionic/arm64v8/Dockerfile
- 3.0/sdk/stretch/arm64v8/Dockerfile
- TAGS.md
- manifest.json
- scripts/TagsDocumentationTemplate.md
> Add linux arm64 sdk 3.0 images

- scripts/Get-TagsDocumentation.ps1
picks up https://github.com/dotnet/docker-tools/commit/764f90fd23fe2d896d6c4668bf58097baa286e66
> Update Get-TagsDocumentation.ps1 to use latest ImageBuilder

- .vsts-pipelines/steps/init-docker-linux.yml
- .vsts-pipelines/steps/init-docker-windows.yml
Pick up https://github.com/dotnet/docker-tools/pull/123
> Update ImageBuilder version used in builds

- .vsts-pipelines/steps/docker-init-linux.yml
- .vsts-pipelines/steps/docker-init-windows.yml
> update image builder to latest to support latest docker version

- .vsts-pipelines/phases/build-all.yml
- .vsts-pipelines/phases/copy-images-linux.yml
- .vsts-pipelines/phases/copy-images-windows.yml
- .vsts-pipelines/phases/publish-finalize.yml
- 2.1/aspnetcore-runtime/nanoserver-1809/amd64/Dockerfile
- 2.1/runtime/nanoserver-1809/amd64/Dockerfile
- 2.1/sdk/nanoserver-1809/amd64/Dockerfile
- 2.2/aspnetcore-runtime/nanoserver-1809/amd64/Dockerfile
- 2.2/runtime/nanoserver-1809/amd64/Dockerfile
- 2.2/sdk/nanoserver-1809/amd64/Dockerfile
- README.md
- TAGS.md
- manifest.json
- manifest.samples.json
- netci.groovy
- samples/README.DockerHub.md
- samples/dotnetapp/Dockerfile.nanoserver-x64-selfcontained
- scripts/Invoke-CleanupDocker.ps1
- scripts/ReadmeTagsDocumentationTemplate.md
- scripts/TagsDocumentationTemplate.md
- tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/OS.cs
> Add Windows Server 2019 images

- 3.0/aspnetcore-runtime/nanoserver-1809/amd64/Dockerfile
- 3.0/runtime/nanoserver-1809/amd64/Dockerfile
- 3.0/sdk/nanoserver-1809/amd64/Dockerfile
- README.md
- TAGS.md
- manifest.json
- scripts/ReadmeTagsDocumentationTemplate.md
- scripts/TagsDocumentationTemplate.md
- tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs
Related to #746
2.1 and 2.2 1809 images were merged in from master with #812
> Add 3.0 nanoserver-1809 images

- 3.0/aspnetcore-runtime/nanoserver-1809/amd64/Dockerfile
- 3.0/runtime/nanoserver-1809/amd64/Dockerfile
- 3.0/sdk/nanoserver-1809/amd64/Dockerfile
> Fixup 3.0 1809 FROM

- 2.1/runtime-deps/alpine3.7/amd64/Dockerfile
- 2.1/runtime-deps/bionic/amd64/Dockerfile
- 2.1/runtime-deps/bionic/arm32v7/Dockerfile
- 2.1/runtime-deps/stretch-slim/amd64/Dockerfile
- 2.1/runtime-deps/stretch-slim/arm32v7/Dockerfile
- 2.1/runtime/nanoserver-1709/amd64/Dockerfile
- 2.1/runtime/nanoserver-1803/amd64/Dockerfile
- 2.1/runtime/nanoserver-1809/amd64/Dockerfile
- 2.1/runtime/nanoserver-sac2016/amd64/Dockerfile
- 2.1/sdk/bionic/amd64/Dockerfile
- 2.1/sdk/bionic/arm32v7/Dockerfile
- 2.1/sdk/nanoserver-1709/amd64/Dockerfile
- 2.1/sdk/nanoserver-1803/amd64/Dockerfile
- 2.1/sdk/nanoserver-1809/amd64/Dockerfile
- 2.1/sdk/nanoserver-sac2016/amd64/Dockerfile
- 2.1/sdk/stretch/amd64/Dockerfile
- 2.1/sdk/stretch/arm32v7/Dockerfile
- 2.2/runtime-deps/alpine3.8/amd64/Dockerfile
- 2.2/runtime/nanoserver-1709/amd64/Dockerfile
- 2.2/runtime/nanoserver-1803/amd64/Dockerfile
- 2.2/runtime/nanoserver-1809/amd64/Dockerfile
- 2.2/runtime/nanoserver-sac2016/amd64/Dockerfile
- 2.2/sdk/bionic/amd64/Dockerfile
- 2.2/sdk/bionic/arm32v7/Dockerfile
- 2.2/sdk/nanoserver-1709/amd64/Dockerfile
- 2.2/sdk/nanoserver-1803/amd64/Dockerfile
- 2.2/sdk/nanoserver-1809/amd64/Dockerfile
- 2.2/sdk/nanoserver-sac2016/amd64/Dockerfile
- 2.2/sdk/stretch/amd64/Dockerfile
- 2.2/sdk/stretch/arm32v7/Dockerfile
Merging from nightly branch.
Fixes #826
> Update ASPNETCORE_URLS comment to be consistent across Dockerfiles

- .vsts-pipelines/steps/init-docker-linux.yml
- .vsts-pipelines/steps/init-docker-windows.yml
This brings in the latest version of the manifest-tool which adds support for Windows arm.
> [Infra] Update image-builder to latest

- 1.0/runtime/nanoserver-sac2016/amd64/Dockerfile
- 1.1/runtime/nanoserver-sac2016/amd64/Dockerfile
- 1.1/sdk/nanoserver-sac2016/amd64/Dockerfile
- 2.1/aspnetcore-runtime/nanoserver-1709/amd64/Dockerfile
- 2.1/aspnetcore-runtime/nanoserver-1803/amd64/Dockerfile
- 2.1/aspnetcore-runtime/nanoserver-sac2016/amd64/Dockerfile
- 2.1/runtime/nanoserver-1709/amd64/Dockerfile
- 2.1/runtime/nanoserver-1803/amd64/Dockerfile
- 2.1/runtime/nanoserver-sac2016/amd64/Dockerfile
- 2.1/sdk/nanoserver-1709/amd64/Dockerfile
- 2.1/sdk/nanoserver-1803/amd64/Dockerfile
- 2.1/sdk/nanoserver-sac2016/amd64/Dockerfile
- 2.2/aspnetcore-runtime/nanoserver-1709/amd64/Dockerfile
- 2.2/aspnetcore-runtime/nanoserver-1803/amd64/Dockerfile
- 2.2/aspnetcore-runtime/nanoserver-sac2016/amd64/Dockerfile
- 2.2/runtime/nanoserver-1709/amd64/Dockerfile
- 2.2/runtime/nanoserver-1803/amd64/Dockerfile
- 2.2/runtime/nanoserver-sac2016/amd64/Dockerfile
- 2.2/sdk/nanoserver-1709/amd64/Dockerfile
- 2.2/sdk/nanoserver-1803/amd64/Dockerfile
- 2.2/sdk/nanoserver-sac2016/amd64/Dockerfile
- samples/dotnetapp/Dockerfile.nanoserver-x64-selfcontained
- scripts/Invoke-CleanupDocker.ps1
> Update Dockerfiles to reference Windows images from MCR

- samples/README.md
Minor change to fix the issue 846
> Update broken link to Dokerfile (#846)

- samples/aspnetapp/Dockerfile
- samples/aspnetapp/Dockerfile.alpine-x64
- samples/aspnetapp/Dockerfile.nanoserver-sac2016
- samples/aspnetapp/README.md
- samples/aspnetapp/aspnet-docker-dev-in-container.md
- samples/aspnetapp/aspnetapp/aspnetapp.csproj
- samples/aspnetapp/aspnetcore-docker-https-development.md
- samples/aspnetapp/aspnetcore-docker-https.md
- samples/dotnetapp/Dockerfile
- samples/dotnetapp/Dockerfile.alpine-x64
- samples/dotnetapp/Dockerfile.alpine-x64-globalization
- samples/dotnetapp/Dockerfile.alpine-x64-selfcontained
- samples/dotnetapp/Dockerfile.debian-arm32-selfcontained
- samples/dotnetapp/Dockerfile.debian-x64-selfcontained
- samples/dotnetapp/Dockerfile.nanoserver-x64-selfcontained
- samples/dotnetapp/README.md
- samples/dotnetapp/dotnet-docker-dev-in-container.md
- samples/dotnetapp/dotnetapp/dotnetapp.csproj
> Update samples to be based on 2.2

- samples/aspnetapp/Dockerfile
- samples/aspnetapp/Dockerfile.alpine-x64
- samples/aspnetapp/Dockerfile.nanoserver-sac2016
- samples/aspnetapp/README.md
- samples/aspnetapp/aspnet-docker-dev-in-container.md
- samples/aspnetapp/aspnetapp/aspnetapp.csproj
- samples/aspnetapp/aspnetcore-docker-https-development.md
- samples/aspnetapp/aspnetcore-docker-https.md
- samples/dotnetapp/Dockerfile
- samples/dotnetapp/Dockerfile.alpine-x64
- samples/dotnetapp/Dockerfile.alpine-x64-globalization
- samples/dotnetapp/Dockerfile.alpine-x64-selfcontained
- samples/dotnetapp/Dockerfile.debian-arm32-selfcontained
- samples/dotnetapp/Dockerfile.debian-x64-selfcontained
- samples/dotnetapp/Dockerfile.nanoserver-x64-selfcontained
- samples/dotnetapp/README.md
- samples/dotnetapp/dotnet-docker-dev-in-container.md
- samples/dotnetapp/dotnetapp/dotnetapp.csproj
> Update samples to be based on 2.2 (#849)

- .vsts-pipelines/jobs/test-images-windows-client.yml
> [Infrastructure] Add cleanup trx files build step in Windows test leg

- samples/README.DockerHub.md
- scripts/Get-TagsDocumentation.ps1
- scripts/SamplesReadmeTagsDocumentationTemplate.md
This is being done because of markdown rendering changed in Docker Hub
> Update samples readme headers

- manifest.samples.json
- samples/README.DockerHub.md
- scripts/SamplesReadmeTagsDocumentationTemplate.md
> Update dotnet-samples to include Windows arm32 images

- .vsts-pipelines/jobs/build-images.yml
- 2.2/sdk/nanoserver-1809/arm32/Dockerfile
> Revert win arm lzma

- .vsts-pipelines/jobs/copy-images.yml
- .vsts-pipelines/jobs/publish-finalize.yml
> Update samples build to accommodate for no linux arm64 samples

- .vsts-pipelines/jobs/copy-images.yml
- .vsts-pipelines/jobs/publish-finalize.yml
- manifest.samples.json
- samples/README.DockerHub.md
- scripts/SamplesReadmeTagsDocumentationTemplate.md
> Merging latest changes from master into nightly

- README.aspnet.md
- README.md
- README.runtime-deps.md
- README.runtime.md
- README.sdk.md
> Update the readmes with the move to MCR

- 3.0/aspnet/alpine3.8/amd64/Dockerfile
- 3.0/aspnet/bionic/amd64/Dockerfile
- 3.0/aspnet/bionic/arm32v7/Dockerfile
- 3.0/aspnet/bionic/arm64v8/Dockerfile
- 3.0/aspnet/nanoserver-1709/amd64/Dockerfile
- 3.0/aspnet/nanoserver-1803/amd64/Dockerfile
- 3.0/aspnet/nanoserver-1809/amd64/Dockerfile
- 3.0/aspnet/nanoserver-1809/arm32/Dockerfile
- 3.0/aspnet/stretch-slim/amd64/Dockerfile
- 3.0/aspnet/stretch-slim/arm32v7/Dockerfile
- 3.0/aspnet/stretch-slim/arm64v8/Dockerfile
- manifest.json
> Refactor 3.0 aspnet images to be based on the runtime

- 3.0/aspnet/alpine3.9/amd64/Dockerfile
- 3.0/runtime-deps/alpine3.9/amd64/Dockerfile
- 3.0/runtime/alpine3.9/amd64/Dockerfile
- 3.0/sdk/alpine3.9/amd64/Dockerfile
- README.aspnet.md
- README.runtime-deps.md
- README.runtime.md
- README.sdk.md
- manifest.json
- scripts/documentation-templates/aspnet-tags.md
- scripts/documentation-templates/runtime-deps-tags.md
- scripts/documentation-templates/runtime-tags.md
- scripts/documentation-templates/sdk-tags.md
- tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/OS.cs
> Update 3.0 alpine images to be based on alpine 3.9

- 2.2/aspnet/nanoserver-1809/arm32/Dockerfile
- 2.2/runtime/nanoserver-1809/arm32/Dockerfile
- 2.2/sdk/nanoserver-1809/arm32/Dockerfile
- 3.0/runtime/nanoserver-1809/arm32/Dockerfile
- 3.0/sdk/nanoserver-1809/arm32/Dockerfile
> Merging change from master to nightly

- 2.2/aspnet/nanoserver-1809/arm32/Dockerfile
- 2.2/runtime/nanoserver-1809/arm32/Dockerfile
- 2.2/sdk/nanoserver-1809/arm32/Dockerfile
- 3.0/runtime/nanoserver-1809/arm32/Dockerfile
- 3.0/sdk/nanoserver-1809/arm32/Dockerfile
> Fix issue with calling mkdir incorrectly in nanoserver ARM Dockerfiles

- README.aspnet.md
- README.md
- README.runtime-deps.md
- README.runtime.md
- README.samples.md
- README.sdk.md
- samples/README.md
- samples/aspnetapp/README.md
- samples/dotnetapp/README.md
- samples/dotnetapp/dotnet-docker-selfcontained.md
> Replace old Docker Hub references with MCR references (#995)

- .vsts-pipelines/variables/docker-images.yml
Apparently my copy-paste didn't go as planned when updating image names.
> Update tag name for windows image builder

- .vsts-pipelines/jobs/build-test-publish-repo.yml
> Adds missing suffix for publish matrix output variable

- .vsts-pipelines/jobs/build-images.yml
- samples/aspnetapp/aspnetcore-docker-arm32.md
> Merging recent changes from master into nightly

- 2.1/sdk/alpine3.7/amd64/Dockerfile
- 2.1/sdk/alpine3.9/amd64/Dockerfile
- 2.1/sdk/bionic/amd64/Dockerfile
- 2.1/sdk/bionic/arm32v7/Dockerfile
- 2.1/sdk/nanoserver-1709/amd64/Dockerfile
- 2.1/sdk/nanoserver-1803/amd64/Dockerfile
- 2.1/sdk/nanoserver-1809/amd64/Dockerfile
- 2.1/sdk/stretch/amd64/Dockerfile
- 2.1/sdk/stretch/arm32v7/Dockerfile
- 2.2/sdk/alpine3.8/amd64/Dockerfile
- 2.2/sdk/alpine3.9/amd64/Dockerfile
- 2.2/sdk/bionic/amd64/Dockerfile
- 2.2/sdk/bionic/arm32v7/Dockerfile
- 2.2/sdk/nanoserver-1709/amd64/Dockerfile
- 2.2/sdk/nanoserver-1803/amd64/Dockerfile
- 2.2/sdk/nanoserver-1809/amd64/Dockerfile
- 2.2/sdk/nanoserver-1809/arm32v7/Dockerfile
- 2.2/sdk/stretch/amd64/Dockerfile
- 2.2/sdk/stretch/arm32v7/Dockerfile
- README.sdk.md
- manifest.json
Updating the SDK images to align with the SDKs included with VS 2019.
> Update SDK to 2.1.602 and 2.2.202

- 3.0/aspnet/nanoserver-1809/amd64/Dockerfile
Cherry-pick of c227fd9 from master.
> Fix to use correct default image repo (#1035)

- tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs
> Refactor pwsh test to reduce fragility

- 3.0/aspnet/alpine3.9/amd64/Dockerfile
- 3.0/aspnet/bionic/amd64/Dockerfile
- 3.0/aspnet/bionic/arm32v7/Dockerfile
- 3.0/aspnet/bionic/arm64v8/Dockerfile
- 3.0/aspnet/nanoserver-1803/amd64/Dockerfile
- 3.0/aspnet/nanoserver-1809/amd64/Dockerfile
- 3.0/aspnet/nanoserver-1809/arm32v7/Dockerfile
- 3.0/aspnet/stretch-slim/amd64/Dockerfile
- 3.0/aspnet/stretch-slim/arm32v7/Dockerfile
- 3.0/aspnet/stretch-slim/arm64v8/Dockerfile
- 3.0/runtime/alpine3.9/amd64/Dockerfile
- 3.0/runtime/bionic/amd64/Dockerfile
- 3.0/runtime/bionic/arm32v7/Dockerfile
- 3.0/runtime/bionic/arm64v8/Dockerfile
- 3.0/runtime/nanoserver-1803/amd64/Dockerfile
- 3.0/runtime/nanoserver-1809/amd64/Dockerfile
- 3.0/runtime/nanoserver-1809/arm32v7/Dockerfile
- 3.0/runtime/stretch-slim/amd64/Dockerfile
- 3.0/runtime/stretch-slim/arm32v7/Dockerfile
- 3.0/runtime/stretch-slim/arm64v8/Dockerfile
- 3.0/sdk/alpine3.9/amd64/Dockerfile
- 3.0/sdk/bionic/amd64/Dockerfile
- 3.0/sdk/bionic/arm32v7/Dockerfile
- 3.0/sdk/bionic/arm64v8/Dockerfile
- 3.0/sdk/nanoserver-1803/amd64/Dockerfile
- 3.0/sdk/nanoserver-1809/amd64/Dockerfile
- 3.0/sdk/nanoserver-1809/arm32v7/Dockerfile
- 3.0/sdk/stretch/amd64/Dockerfile
- 3.0/sdk/stretch/arm32v7/Dockerfile
- 3.0/sdk/stretch/arm64v8/Dockerfile
This reverts commit 32f03511b222aa31ab5d80de8e6da71c0ebd4239.
Windows Arm32 has a test failure.
> Revert "Update to the lastest 3.0 (#1043)"

- .vsts-pipelines/variables/docker-images.yml
Roll-out of https://github.com/dotnet/docker-tools/pull/171
> Update ImageBuilder to get publish optimizations

- 3.0/aspnet/buster-slim/amd64/Dockerfile
- 3.0/aspnet/buster-slim/arm32v7/Dockerfile
- 3.0/aspnet/buster-slim/arm64v8/Dockerfile
- 3.0/runtime-deps/buster-slim/amd64/Dockerfile
- 3.0/runtime-deps/buster-slim/arm32v7/Dockerfile
- 3.0/runtime-deps/buster-slim/arm64v8/Dockerfile
- 3.0/runtime/buster-slim/amd64/Dockerfile
- 3.0/runtime/buster-slim/arm32v7/Dockerfile
- 3.0/runtime/buster-slim/arm64v8/Dockerfile
- 3.0/sdk/buster/amd64/Dockerfile
- 3.0/sdk/buster/arm32v7/Dockerfile
- 3.0/sdk/buster/arm64v8/Dockerfile
- README.aspnet.md
- README.runtime-deps.md
- README.runtime.md
- README.sdk.md
- manifest.json
- scripts/documentation-templates/aspnet-tags.md
- scripts/documentation-templates/runtime-deps-tags.md
- scripts/documentation-templates/runtime-tags.md
- scripts/documentation-templates/sdk-tags.md
- tests/Microsoft.DotNet.Docker.Tests/ImageData.cs
- tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/OS.cs
- tests/Microsoft.DotNet.Docker.Tests/StringExtensions.cs
> Add support for Debian Bionic in 3.0

- .vsts-pipelines/steps/test-images-linux-client.yml
Cherry-pick of 13cde6d9287cd8740e2d776d0d85c1612cc5682f (nightly) into master.
> Cleanup test runner container (#1084)

- .vsts-pipelines/variables/docker-images.yml
Cherry-pick https://github.com/dotnet/dotnet-docker/commit/f9a772cca3f1dd2244c93d2258e3d2c84aecbd38 from nightly
> Update image-builder (#1120)

- .vsts-pipelines/stages/build-test-publish-repo.yml
- 2.1/aspnet/nanoserver-1903/amd64/Dockerfile
- 2.1/runtime/nanoserver-1903/amd64/Dockerfile
- 2.1/sdk/nanoserver-1903/amd64/Dockerfile
- 2.2/aspnet/nanoserver-1903/amd64/Dockerfile
- 2.2/runtime/nanoserver-1903/amd64/Dockerfile
- 2.2/sdk/nanoserver-1903/amd64/Dockerfile
- 3.0/aspnet/nanoserver-1903/amd64/Dockerfile
- 3.0/runtime/nanoserver-1903/amd64/Dockerfile
- 3.0/sdk/nanoserver-1903/amd64/Dockerfile
- README.aspnet.md
- README.runtime.md
- README.samples.md
- README.sdk.md
- manifest.json
- manifest.samples.json
- samples/aspnetapp/Dockerfile.nanoserver-1903
- samples/aspnetapp/README.md
- samples/aspnetapp/aspnetapp.sln
- samples/aspnetapp/deploy-container-to-aci.md
- samples/dotnetapp/Dockerfile.nanoserver-x64-selfcontained
- scripts/documentation-templates/aspnet-tags.md
- scripts/documentation-templates/runtime-tags.md
- scripts/documentation-templates/samples-tags.md
- scripts/documentation-templates/sdk-tags.md
- tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/OS.cs
> Add support for Window Server, version 1903

- 3.0/aspnet/alpine3.9/arm64v8/Dockerfile
- README.aspnet.md
- manifest.json
- scripts/documentation-templates/aspnet-tags.md
- tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs
> Add 3.0 alpine arm64 aspnet images

- 3.0/sdk/alpine3.9/amd64/Dockerfile
- 3.0/sdk/bionic/amd64/Dockerfile
- 3.0/sdk/bionic/arm32v7/Dockerfile
- 3.0/sdk/bionic/arm64v8/Dockerfile
- 3.0/sdk/buster/amd64/Dockerfile
- 3.0/sdk/buster/arm32v7/Dockerfile
- 3.0/sdk/buster/arm64v8/Dockerfile
- 3.0/sdk/disco/amd64/Dockerfile
- 3.0/sdk/disco/arm32v7/Dockerfile
- 3.0/sdk/disco/arm64v8/Dockerfile
- 3.0/sdk/nanoserver-1803/amd64/Dockerfile
- 3.0/sdk/nanoserver-1809/amd64/Dockerfile
- 3.0/sdk/nanoserver-1809/arm32v7/Dockerfile
- 3.0/sdk/nanoserver-1903/amd64/Dockerfile
Update the version of PowerShell to the latest patch.
> Update PowerShell to version 6.2.1

- 3.0/aspnet/alpine3.9/arm64v8/Dockerfile
This was introduced with https://github.com/dotnet/dotnet-docker/pull/1133.
This is completely my fault.  CI caught this but I misread the results and thought it was the intermittent alpine3.9 failure we have.
> Fix incorrect FROM in aspnet alpine arm64 Dockerfile

- 3.0/sdk/alpine3.9/amd64/Dockerfile
- 3.0/sdk/bionic/amd64/Dockerfile
- 3.0/sdk/bionic/arm32v7/Dockerfile
- 3.0/sdk/bionic/arm64v8/Dockerfile
- 3.0/sdk/buster/amd64/Dockerfile
- 3.0/sdk/buster/arm32v7/Dockerfile
- 3.0/sdk/buster/arm64v8/Dockerfile
- 3.0/sdk/disco/amd64/Dockerfile
- 3.0/sdk/disco/arm32v7/Dockerfile
- 3.0/sdk/disco/arm64v8/Dockerfile
- 3.0/sdk/nanoserver-1803/amd64/Dockerfile
- 3.0/sdk/nanoserver-1809/amd64/Dockerfile
- 3.0/sdk/nanoserver-1809/arm32v7/Dockerfile
- 3.0/sdk/nanoserver-1903/amd64/Dockerfile
Update to include the latest release of PowerShell
> Update docker images to include PowerShell `7.0.0-preview.2`

- 2.1/sdk/alpine3.7/amd64/Dockerfile
- 2.1/sdk/alpine3.9/amd64/Dockerfile
- 2.1/sdk/bionic/amd64/Dockerfile
- 2.1/sdk/bionic/arm32v7/Dockerfile
- 2.1/sdk/nanoserver-1803/amd64/Dockerfile
- 2.1/sdk/nanoserver-1809/amd64/Dockerfile
- 2.1/sdk/nanoserver-1903/amd64/Dockerfile
- 2.1/sdk/stretch/amd64/Dockerfile
- 2.1/sdk/stretch/arm32v7/Dockerfile
- 2.2/sdk/alpine3.8/amd64/Dockerfile
- 2.2/sdk/alpine3.9/amd64/Dockerfile
- 2.2/sdk/bionic/amd64/Dockerfile
- 2.2/sdk/bionic/arm32v7/Dockerfile
- 2.2/sdk/nanoserver-1803/amd64/Dockerfile
- 2.2/sdk/nanoserver-1809/amd64/Dockerfile
- 2.2/sdk/nanoserver-1809/arm32v7/Dockerfile
- 2.2/sdk/nanoserver-1903/amd64/Dockerfile
- 2.2/sdk/stretch/amd64/Dockerfile
- 2.2/sdk/stretch/arm32v7/Dockerfile
- README.sdk.md
- manifest.json
Update SDK to 2.1.801 and 2.2.401.
Also cherry picking https://github.com/dotnet/dotnet-docker/pull/1123 from nightly.
> 2.2.401 2.1.801 sdk

- 2.1/sdk/alpine3.7/amd64/Dockerfile
- 2.1/sdk/alpine3.9/amd64/Dockerfile
- 2.1/sdk/bionic/amd64/Dockerfile
- 2.1/sdk/bionic/arm32v7/Dockerfile
- 2.1/sdk/nanoserver-1803/amd64/Dockerfile
- 2.1/sdk/nanoserver-1809/amd64/Dockerfile
- 2.1/sdk/nanoserver-1903/amd64/Dockerfile
- 2.1/sdk/stretch/amd64/Dockerfile
- 2.1/sdk/stretch/arm32v7/Dockerfile
- 2.2/sdk/alpine3.8/amd64/Dockerfile
- 2.2/sdk/alpine3.9/amd64/Dockerfile
- 2.2/sdk/bionic/amd64/Dockerfile
- 2.2/sdk/bionic/arm32v7/Dockerfile
- 2.2/sdk/nanoserver-1803/amd64/Dockerfile
- 2.2/sdk/nanoserver-1809/amd64/Dockerfile
- 2.2/sdk/nanoserver-1809/arm32v7/Dockerfile
- 2.2/sdk/nanoserver-1903/amd64/Dockerfile
- 2.2/sdk/stretch/amd64/Dockerfile
- 2.2/sdk/stretch/arm32v7/Dockerfile
- README.sdk.md
- manifest.json
* Update SDK to 2.1.801 and 2.2.401 (Cherry-picked from master)
> 2.2.401 2.1.801 sdk (#1228)

- eng/common/templates/jobs/publish.yml
- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
- eng/common/templates/variables/common.yml
- eng/common/templates/variables/docker-images.yml
Integrates the latest contents of the eng/common folder from https://github.com/dotnet/docker-tools.
> Integrate latest eng/common folder

- 3.0/sdk/alpine3.10/amd64/Dockerfile
- 3.0/sdk/alpine3.9/amd64/Dockerfile
- 3.0/sdk/bionic/amd64/Dockerfile
- 3.0/sdk/bionic/arm32v7/Dockerfile
- 3.0/sdk/bionic/arm64v8/Dockerfile
- 3.0/sdk/buster/amd64/Dockerfile
- 3.0/sdk/buster/arm32v7/Dockerfile
- 3.0/sdk/buster/arm64v8/Dockerfile
- 3.0/sdk/disco/amd64/Dockerfile
- 3.0/sdk/disco/arm32v7/Dockerfile
- 3.0/sdk/disco/arm64v8/Dockerfile
- 3.0/sdk/nanoserver-1803/amd64/Dockerfile
- 3.0/sdk/nanoserver-1809/amd64/Dockerfile
- 3.0/sdk/nanoserver-1809/arm32v7/Dockerfile
- 3.0/sdk/nanoserver-1903/amd64/Dockerfile
Update to the latest PowerShell release and add new environment variable which will be used by PowerShell telemetry.
> Update PowerShell version to `v7.0.0-preview.3`

- 3.0/sdk/alpine3.10/amd64/Dockerfile
- 3.0/sdk/alpine3.9/amd64/Dockerfile
- 3.0/sdk/bionic/amd64/Dockerfile
- 3.0/sdk/bionic/arm32v7/Dockerfile
- 3.0/sdk/bionic/arm64v8/Dockerfile
- 3.0/sdk/buster/amd64/Dockerfile
- 3.0/sdk/buster/arm32v7/Dockerfile
- 3.0/sdk/buster/arm64v8/Dockerfile
- 3.0/sdk/disco/amd64/Dockerfile
- 3.0/sdk/disco/arm32v7/Dockerfile
- 3.0/sdk/disco/arm64v8/Dockerfile
- 3.0/sdk/nanoserver-1803/amd64/Dockerfile
- 3.0/sdk/nanoserver-1809/amd64/Dockerfile
- 3.0/sdk/nanoserver-1809/arm32v7/Dockerfile
- 3.0/sdk/nanoserver-1903/amd64/Dockerfile
> Remove ASPNETCORE_URLS env var from 3.0 SDK

- 3.0/sdk/alpine3.10/amd64/Dockerfile
- 3.0/sdk/alpine3.9/amd64/Dockerfile
- 3.0/sdk/bionic/amd64/Dockerfile
- 3.0/sdk/bionic/arm32v7/Dockerfile
- 3.0/sdk/bionic/arm64v8/Dockerfile
- 3.0/sdk/buster/amd64/Dockerfile
- 3.0/sdk/buster/arm32v7/Dockerfile
- 3.0/sdk/buster/arm64v8/Dockerfile
- 3.0/sdk/disco/amd64/Dockerfile
- 3.0/sdk/disco/arm32v7/Dockerfile
- 3.0/sdk/disco/arm64v8/Dockerfile
- 3.0/sdk/nanoserver-1803/amd64/Dockerfile
- 3.0/sdk/nanoserver-1809/amd64/Dockerfile
- 3.0/sdk/nanoserver-1809/arm32v7/Dockerfile
- 3.0/sdk/nanoserver-1903/amd64/Dockerfile
Update to the latest PowerShell release.
> Update PowerShell version to `v7.0.0-preview.4`

- README.aspnet.md
- README.runtime-deps.md
- README.runtime.md
- README.samples.md
- README.sdk.md
- manifest.json
> Move the 'latest' tag to the 3.0 images

- 3.0/aspnet/alpine3.10/amd64/Dockerfile
- 3.0/aspnet/alpine3.10/arm64v8/Dockerfile
- 3.0/aspnet/alpine3.9/amd64/Dockerfile
- 3.0/aspnet/alpine3.9/arm64v8/Dockerfile
- 3.0/aspnet/bionic/amd64/Dockerfile
- 3.0/aspnet/bionic/arm32v7/Dockerfile
- 3.0/aspnet/bionic/arm64v8/Dockerfile
- 3.0/aspnet/buster-slim/amd64/Dockerfile
- 3.0/aspnet/buster-slim/arm32v7/Dockerfile
- 3.0/aspnet/buster-slim/arm64v8/Dockerfile
- 3.0/aspnet/disco/amd64/Dockerfile
- 3.0/aspnet/disco/arm32v7/Dockerfile
- 3.0/aspnet/disco/arm64v8/Dockerfile
- 3.0/aspnet/nanoserver-1803/amd64/Dockerfile
- 3.0/aspnet/nanoserver-1809/amd64/Dockerfile
- 3.0/aspnet/nanoserver-1809/arm32v7/Dockerfile
- 3.0/aspnet/nanoserver-1903/amd64/Dockerfile
- tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/NuGet.config.nightly
> Remove workarounds for 3.0 release

- 3.1/sdk/alpine3.10/amd64/Dockerfile
- 3.1/sdk/bionic/amd64/Dockerfile
- 3.1/sdk/bionic/arm32v7/Dockerfile
- 3.1/sdk/bionic/arm64v8/Dockerfile
- 3.1/sdk/buster/amd64/Dockerfile
- 3.1/sdk/buster/arm32v7/Dockerfile
- 3.1/sdk/buster/arm64v8/Dockerfile
- 3.1/sdk/nanoserver-1803/amd64/Dockerfile
- 3.1/sdk/nanoserver-1809/amd64/Dockerfile
- 3.1/sdk/nanoserver-1809/arm32v7/Dockerfile
- 3.1/sdk/nanoserver-1903/amd64/Dockerfile
Update the version on SDK images to the latest release of PowerShell
> Update PowerShell to v7.0.0-preview.5

- samples/README.md
- samples/snippets/README.md
- samples/snippets/nuget-credentials.md
Cherry-pick of 82083e8c4e399177e9d1b221932ce7206f9593db
> Sample snippets for NuGet authentication scenarios

- samples/README.md
- samples/snippets/README.md
- samples/snippets/installing-dotnet.md
- samples/snippets/using-system-drawing-common.md
Merges two snippet docs from master to nightly.
[skip ci]
> Merge snippets

- samples/aspnetapp/deploy-container-to-aci.md
> Update the deploy to ACI sample to include Windows

- samples/aspnetapp/deploy-container-to-aci.md
Merging changes from master to nightly.  Cherry-pick 0971f57836be1876ac969f68924254e8b53520e6 from master.
> Update the deploy to ACI sample to include Windows (#1452)

- 3.1/aspnet/focal/amd64/Dockerfile
- 3.1/aspnet/focal/arm32v7/Dockerfile
- 3.1/aspnet/focal/arm64v8/Dockerfile
- 3.1/runtime-deps/focal/amd64/Dockerfile
- 3.1/runtime-deps/focal/arm32v7/Dockerfile
- 3.1/runtime-deps/focal/arm64v8/Dockerfile
- 3.1/runtime/focal/amd64/Dockerfile
- 3.1/runtime/focal/arm32v7/Dockerfile
- 3.1/runtime/focal/arm64v8/Dockerfile
- 3.1/sdk/focal/amd64/Dockerfile
- 3.1/sdk/focal/arm32v7/Dockerfile
- 3.1/sdk/focal/arm64v8/Dockerfile
- README.aspnet.md
- README.runtime-deps.md
- README.runtime.md
- README.sdk.md
- eng/mcr-tags-metadata-templates/aspnet-tags.yml
- eng/mcr-tags-metadata-templates/runtime-deps-tags.yml
- eng/mcr-tags-metadata-templates/runtime-tags.yml
- eng/mcr-tags-metadata-templates/sdk-tags.yml
- manifest.json
- tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/OS.cs
> Add 3.1 support for Ubuntu focal

- README.aspnet.md
- README.md
- README.runtime-deps.md
- README.runtime.md
- README.samples.md
- README.sdk.md
Fixed the broken `File an issue for other components` feedback link in the readmes.
> Fix broken feedback link in the readmes

- README.aspnet.md
- README.md
- README.runtime-deps.md
- README.runtime.md
- README.samples.md
- README.sdk.md
> Fix broken feedback link in the readmes (#1498)

- CONTRIBUTING.md
- documentation/platform-matrix-suport.md
Cherry-picking changes from master.
> Merging changes from master to nightly

- samples/aspnetapp/Dockerfile
- samples/aspnetapp/Dockerfile.alpine-x64
- samples/aspnetapp/Dockerfile.linux-arm32
- samples/aspnetapp/Dockerfile.nanoserver-1909
- samples/aspnetapp/Dockerfile.nanoserver-arm32
- samples/aspnetapp/aspnet-docker-dev-in-container.md
- samples/aspnetapp/aspnetapp/aspnetapp.csproj
- samples/dotnetapp/Dockerfile
- samples/dotnetapp/Dockerfile.alpine-x64
- samples/dotnetapp/Dockerfile.alpine-x64-globalization
- samples/dotnetapp/Dockerfile.alpine-x64-selfcontained
- samples/dotnetapp/Dockerfile.debian-arm32-selfcontained
- samples/dotnetapp/Dockerfile.debian-arm64-selfcontained
- samples/dotnetapp/Dockerfile.debian-x64-selfcontained
- samples/dotnetapp/Dockerfile.linux-arm32
- samples/dotnetapp/Dockerfile.nanoserver-arm32
- samples/dotnetapp/Dockerfile.nanoserver-x64-selfcontained
- samples/dotnetapp/README.md
- samples/dotnetapp/dotnet-docker-dev-in-container.md
- samples/dotnetapp/dotnetapp/dotnetapp.csproj
- samples/dotnetapp/tests/tests.csproj
Merge commit cb7a9c35dacf6d34fcf7bab7995e60faef55f61f for updating to samples to 3.1
> Update samples to 3.1 (#1517)

- eng/common/templates/jobs/generate-matrix.yml
- eng/common/templates/jobs/post-build.yml
- eng/common/templates/stages/build-test-publish-repo.yml
This reverts commit 7058937e1bccc842dc8dc0a7e4af4621554c8cfd.
> Revert "Update to use temporary agent pool (#1522)"

- eng/common/templates/jobs/generate-matrix.yml
- eng/common/templates/jobs/post-build.yml
- eng/common/templates/stages/build-test-publish-repo.yml
This reverts commit 6a0bd8e633c102ffab099e7cd89d4e17ca354314.
> Revert "Update to use temporary agent pool (#1521)"

- README.aspnet.md
- README.runtime-deps.md
- README.runtime.md
- README.sdk.md
Cherry-picked change from master.
> Combine LTS/Current tag descriptions

- tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/AssemblyInfo.cs
- tests/Microsoft.DotNet.Docker.Tests/CommonRuntimeImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/ImageData.cs
- tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/LinuxImageTheoryAttribute.cs
- tests/Microsoft.DotNet.Docker.Tests/OS.cs
- tests/Microsoft.DotNet.Docker.Tests/RuntimeDepsImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/RuntimeImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/TestData.cs
Cherry-picked test changes from nightly.
> Split tests into separate classes (#1504)

- 3.1/sdk/alpine3.10/amd64/Dockerfile
- 3.1/sdk/bionic/amd64/Dockerfile
- 3.1/sdk/bionic/arm32v7/Dockerfile
- 3.1/sdk/bionic/arm64v8/Dockerfile
- 3.1/sdk/buster/amd64/Dockerfile
- 3.1/sdk/buster/arm32v7/Dockerfile
- 3.1/sdk/buster/arm64v8/Dockerfile
- 3.1/sdk/focal/amd64/Dockerfile
- 3.1/sdk/focal/arm32v7/Dockerfile
- 3.1/sdk/focal/arm64v8/Dockerfile
- 3.1/sdk/nanoserver-1809/amd64/Dockerfile
- 3.1/sdk/nanoserver-1809/arm32v7/Dockerfile
- 3.1/sdk/nanoserver-1903/amd64/Dockerfile
- 3.1/sdk/nanoserver-1909/amd64/Dockerfile
Update PowerShell to the latest version 7.0.0-rc.1
> Update PowerShell version to 7.0.0-rc.1

- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
- eng/update-dependencies/NuGet.config
- eng/update-dependencies/Program.cs
- eng/update-dependencies/update-dependencies.csproj
- tests/Microsoft.DotNet.Docker.Tests/Config.cs
- tests/Microsoft.DotNet.Docker.Tests/ImageData.cs
- tests/run-tests.ps1
Cherry-picking infra changes from nightly
> Merge infra changes from nightly to master

- tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/CommonRuntimeImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/EnvironmentVariableInfo.cs
- tests/Microsoft.DotNet.Docker.Tests/ImageData.cs
- tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs
- tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/Microsoft.DotNet.Docker.Tests.csproj
- tests/Microsoft.DotNet.Docker.Tests/ProductImageData.cs
- tests/Microsoft.DotNet.Docker.Tests/RuntimeDepsImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/RuntimeImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/TestData.cs
- tests/run-tests.ps1
> Unit test refactoring

- eng/pipelines/dotnet-core-samples.yml
- tests/Microsoft.DotNet.Docker.Tests/CommonRuntimeImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs
- tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/SampleImageData.cs
- tests/Microsoft.DotNet.Docker.Tests/SampleImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/SampleImageType.cs
- tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/TestData.cs
- tests/run-tests.ps1
> Tests for published sample images

- manifest.samples.json
This is needed in response to the PR which overhauled the samples - https://github.com/dotnet/dotnet-docker/pull/1538
> Update manifest with the new sample Dockerfiles

- 3.1/sdk/alpine3.10/amd64/Dockerfile
- 3.1/sdk/alpine3.11/amd64/Dockerfile
- 3.1/sdk/bionic/amd64/Dockerfile
- 3.1/sdk/bionic/arm32v7/Dockerfile
- 3.1/sdk/bionic/arm64v8/Dockerfile
- 3.1/sdk/buster/amd64/Dockerfile
- 3.1/sdk/buster/arm32v7/Dockerfile
- 3.1/sdk/buster/arm64v8/Dockerfile
- 3.1/sdk/focal/amd64/Dockerfile
- 3.1/sdk/focal/arm32v7/Dockerfile
- 3.1/sdk/focal/arm64v8/Dockerfile
- 3.1/sdk/nanoserver-1809/amd64/Dockerfile
- 3.1/sdk/nanoserver-1809/arm32v7/Dockerfile
- 3.1/sdk/nanoserver-1903/amd64/Dockerfile
- 3.1/sdk/nanoserver-1909/amd64/Dockerfile
Update to the latest release of PowerShell
> Update PowerShell to 7.0.0-rc.2

- README.aspnet.md
- README.md
- README.runtime-deps.md
- README.runtime.md
- README.samples.md
- README.sdk.md
> Add REAMDE Feedback links for MCR and VS Docker Tools

- tests/Microsoft.DotNet.Docker.Tests/ImageData.cs
- tests/Microsoft.DotNet.Docker.Tests/SampleImageData.cs
- tests/Microsoft.DotNet.Docker.Tests/SampleImageTests.cs
Merges commit 51ee5a5 to master branch.
> Ensure sample tag generation works in nightly

- eng/update-dependencies/DockerfileShaUpdater.cs
- eng/update-dependencies/ErrorTraceListener.cs
- eng/update-dependencies/Program.cs
Cherrypick of dfc325d 
Fixes #1579
> Ensure update-dependencies fails if sha not found

- eng/common/templates/jobs/publish.yml
- eng/common/templates/steps/publish-readmes.yml
- eng/pipelines/update-readmes.yml
Related to #331
I will port the common infra back to docker-tools and dotnet-framework-docker once merged.
> Add update-readmes pipeline

- README.aspnet.md
- README.runtime-deps.md
- README.runtime.md
- README.sdk.md
- manifest.json
> Move latest tag in nightly to 5.0 images

- .github/ISSUE_TEMPLATE/releases/new-distro-release.md
- .github/ISSUE_TEMPLATE/releases/new-windows-release.md
- eng/pipelines/dotnet-core-nightly.yml
- eng/pipelines/dotnet-core-samples.yml
Adds issue templates for managing new Linux/Windows releases.
Fixes dotnet/docker-tools#383
> Issue templates for new OS release

- samples/aspnetapp/aspnetapp/Pages/Index.cshtml
Invalid HTML, tag h5 is opened but h1 is closed.
Closing h5.
> Fix header tags for Environment and Metrics

- samples/snippets/nuget-credentials.md
* Make feed path match in config and env var
* Don't pass secret on the command-line
> Azure Artifacts tweaks

- tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs
> Re-enable PowerShell scenario tests for 5.0 images

- eng/pipelines/dotnet-core-nightly.yml
> Trigger nightly build on Dockerfile or manifest change only

- samples/run-aspnetcore-https-development.md
Hello,
Tweaked the readme on the go, look forward to knowing your opinion on it.
Thank you
Alberto
> A valid HTTPS certificate is already present

- 5.0/sdk/alpine3.11/amd64/Dockerfile
- 5.0/sdk/buster/amd64/Dockerfile
- 5.0/sdk/buster/arm32v7/Dockerfile
- 5.0/sdk/buster/arm64v8/Dockerfile
- 5.0/sdk/focal/amd64/Dockerfile
- 5.0/sdk/focal/arm32v7/Dockerfile
- 5.0/sdk/focal/arm64v8/Dockerfile
- 5.0/sdk/nanoserver-1809/amd64/Dockerfile
- 5.0/sdk/nanoserver-1809/arm32v7/Dockerfile
- 5.0/sdk/nanoserver-1903/amd64/Dockerfile
- 5.0/sdk/nanoserver-1909/amd64/Dockerfile
Update to the latest version of PowerShell
> Update PowerShell to v7.1.0-preview.1

- eng/update-dependencies/ManifestUpdater.cs
> Adjust update-dependencies ManifestUpdator to account for new version string format

- 2.1/runtime-deps/alpine3.10/amd64/Dockerfile
- 2.1/runtime-deps/alpine3.11/amd64/Dockerfile
- 2.1/runtime-deps/bionic/amd64/Dockerfile
- 2.1/runtime-deps/focal/amd64/Dockerfile
- 2.1/runtime-deps/stretch-slim/amd64/Dockerfile
- 2.1/sdk/bionic/amd64/Dockerfile
- 2.1/sdk/focal/amd64/Dockerfile
- 2.1/sdk/stretch/amd64/Dockerfile
- 3.1/runtime-deps/alpine3.10/amd64/Dockerfile
- 3.1/runtime-deps/alpine3.11/amd64/Dockerfile
- 3.1/runtime-deps/bionic/amd64/Dockerfile
- 3.1/runtime-deps/buster-slim/amd64/Dockerfile
- 3.1/runtime-deps/focal/amd64/Dockerfile
- 3.1/sdk/bionic/amd64/Dockerfile
- 3.1/sdk/buster/amd64/Dockerfile
- 3.1/sdk/focal/amd64/Dockerfile
- 5.0/runtime-deps/alpine3.11/amd64/Dockerfile
- 5.0/runtime-deps/buster-slim/amd64/Dockerfile
- 5.0/runtime-deps/focal/amd64/Dockerfile
- 5.0/sdk/buster/amd64/Dockerfile
- 5.0/sdk/focal/amd64/Dockerfile
- README.aspnet.md
- README.md
- README.runtime-deps.md
- README.runtime.md
- README.samples.md
- README.sdk.md
> Merge master branch to nightly

- tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs
Cherry-pick of e4e48d50bcf4ddd87c301dec32b58aa1d64d0b53
Related to https://github.com/dotnet/dotnet-docker/issues/1796
> Add workaround for web templates

- .github/ISSUE_TEMPLATE/releases/net-core-release.md
Update .NET Core release checklist to explicitly call out things to merge.
> Update release checklist

- tests/Microsoft.DotNet.Docker.Tests/ImageData.cs
Cherrypick of 56f1a76d9774d31933245a9fabc0434588c17686
> Fix test logic to support new image info schema (#1779)

- 3.1/sdk/alpine3.11/amd64/Dockerfile
- 5.0/sdk/alpine3.11/amd64/Dockerfile
> Correct POWERSHELL_DISTRIBUTION_CHANNEL ENV in Alpine 3.11 Dockerfiles

- eng/update-dependencies/VariableHelper.cs
Example of what this fixes:  https://github.com/dotnet/dotnet-docker/pull/1846/files#diff-cec618429bb5599c14ae90538e3a88deR6
> Refactor update-dependencies to handle multi-line ENVs

- 5.0/sdk/alpine3.11/amd64/Dockerfile
- 5.0/sdk/buster-slim/amd64/Dockerfile
- 5.0/sdk/buster-slim/arm32v7/Dockerfile
- 5.0/sdk/buster-slim/arm64v8/Dockerfile
- 5.0/sdk/focal/amd64/Dockerfile
- 5.0/sdk/focal/arm32v7/Dockerfile
- 5.0/sdk/focal/arm64v8/Dockerfile
- 5.0/sdk/nanoserver-1809/amd64/Dockerfile
- 5.0/sdk/nanoserver-1903/amd64/Dockerfile
- 5.0/sdk/nanoserver-1909/amd64/Dockerfile
Update the PowerShell version to 7.1.0-preview.2. This is based on .NET 5 Preview 3.
> Update PowerShell to 7.1.0-preview.2

- 3.1/sdk/alpine3.11/amd64/Dockerfile
- 3.1/sdk/bionic/amd64/Dockerfile
- 3.1/sdk/bionic/arm32v7/Dockerfile
- 3.1/sdk/bionic/arm64v8/Dockerfile
- 3.1/sdk/buster/amd64/Dockerfile
- 3.1/sdk/buster/arm32v7/Dockerfile
- 3.1/sdk/buster/arm64v8/Dockerfile
- 3.1/sdk/focal/amd64/Dockerfile
- 3.1/sdk/focal/arm32v7/Dockerfile
- 3.1/sdk/focal/arm64v8/Dockerfile
- 3.1/sdk/nanoserver-1809/amd64/Dockerfile
- 3.1/sdk/nanoserver-1903/amd64/Dockerfile
- 3.1/sdk/nanoserver-1909/amd64/Dockerfile
Update PowerShell to the latest patch.
> Update PowerShell to latest patch 7.0.1

- 5.0/sdk/alpine3.11/amd64/Dockerfile
- 5.0/sdk/buster-slim/amd64/Dockerfile
- 5.0/sdk/buster-slim/arm32v7/Dockerfile
- 5.0/sdk/buster-slim/arm64v8/Dockerfile
- 5.0/sdk/focal/amd64/Dockerfile
- 5.0/sdk/focal/arm32v7/Dockerfile
- 5.0/sdk/focal/arm64v8/Dockerfile
- 5.0/sdk/nanoserver-1809/amd64/Dockerfile
- 5.0/sdk/nanoserver-1903/amd64/Dockerfile
- 5.0/sdk/nanoserver-1909/amd64/Dockerfile
Update to PowerShell preview based on .NET 5 preview 4
> Update PowerShell to 7.1.0-preview.3

- README.aspnet.md
- README.aspnet.preview.md
- README.md
- README.runtime-deps.md
- README.runtime-deps.preview.md
- README.runtime.md
- README.runtime.preview.md
- README.samples.md
- README.sdk.md
- README.sdk.preview.md
Related #1906 
Here is a [sample repo](https://hub.docker.com/repository/docker/msimons/sandbox) I published the readme to so that you can see the rendered description.
cc @mbrown555
> Adjust formatting of the MCR firewall change notification 

- README.aspnet.md
- README.aspnet.preview.md
- README.md
- README.runtime-deps.md
- README.runtime-deps.preview.md
- README.runtime.md
- README.runtime.preview.md
- README.samples.md
- README.sdk.md
- README.sdk.preview.md
Related #1906
Here is a [sample repo](https://hub.docker.com/repository/docker/msimons/test2) I published the readme to so that you can see the rendered description.
The formatting of the nightly repos are slightly different as compared to the [official repos](https://github.com/dotnet/dotnet-docker/pull/1925) because of the existing prelude text.
cc @mbrown555
> Adjust formatting of the MCR firewall change notification

- 3.1/sdk/alpine3.10/amd64/Dockerfile
- 3.1/sdk/alpine3.11/amd64/Dockerfile
- 3.1/sdk/bionic/amd64/Dockerfile
- 3.1/sdk/bionic/arm32v7/Dockerfile
- 3.1/sdk/bionic/arm64v8/Dockerfile
- 3.1/sdk/buster/amd64/Dockerfile
- 3.1/sdk/buster/arm32v7/Dockerfile
- 3.1/sdk/buster/arm64v8/Dockerfile
- 3.1/sdk/focal/amd64/Dockerfile
- 3.1/sdk/focal/arm32v7/Dockerfile
- 3.1/sdk/focal/arm64v8/Dockerfile
- 3.1/sdk/nanoserver-1809/amd64/Dockerfile
- 3.1/sdk/nanoserver-1903/amd64/Dockerfile
- 3.1/sdk/nanoserver-1909/amd64/Dockerfile
- README.sdk.md
- manifest.json
Update 3.1 SDK to align with VS 16.6.
> Update 3.1 SDK to 3.1.300

- 3.1/sdk/nanoserver-1809/amd64/Dockerfile
- 3.1/sdk/nanoserver-1903/amd64/Dockerfile
- 3.1/sdk/nanoserver-1909/amd64/Dockerfile
- 3.1/sdk/nanoserver-2004/amd64/Dockerfile
- 5.0/sdk/buster-slim/amd64/Dockerfile
- 5.0/sdk/buster-slim/arm32v7/Dockerfile
- 5.0/sdk/buster-slim/arm64v8/Dockerfile
- 5.0/sdk/focal/amd64/Dockerfile
- 5.0/sdk/focal/arm32v7/Dockerfile
- 5.0/sdk/focal/arm64v8/Dockerfile
- 5.0/sdk/nanoserver-1809/amd64/Dockerfile
- 5.0/sdk/nanoserver-1903/amd64/Dockerfile
- 5.0/sdk/nanoserver-1909/amd64/Dockerfile
- 5.0/sdk/nanoserver-2004/amd64/Dockerfile
> Remove redundant DOTNET_RUNNING_IN_CONTAINER ENVs

- 3.1/sdk/alpine3.11/amd64/Dockerfile
- 3.1/sdk/bionic/amd64/Dockerfile
- 3.1/sdk/bionic/arm32v7/Dockerfile
- 3.1/sdk/bionic/arm64v8/Dockerfile
- 3.1/sdk/buster/amd64/Dockerfile
- 3.1/sdk/buster/arm32v7/Dockerfile
- 3.1/sdk/buster/arm64v8/Dockerfile
- 3.1/sdk/focal/amd64/Dockerfile
- 3.1/sdk/focal/arm32v7/Dockerfile
- 3.1/sdk/focal/arm64v8/Dockerfile
- 3.1/sdk/nanoserver-1809/amd64/Dockerfile
- 3.1/sdk/nanoserver-1903/amd64/Dockerfile
- 3.1/sdk/nanoserver-1909/amd64/Dockerfile
- 3.1/sdk/nanoserver-2004/amd64/Dockerfile
Update the version of PowerShell to 7.0.2
> Update PowerShell to v7.0.2

- src/sdk/5.0/alpine3.12/amd64/Dockerfile
Another occurrence of https://github.com/dotnet/dotnet-docker/issues/1819
> Fix incorrect POWERSHELL_DISTRIBUTION_CHANNEL value

- src/sdk/3.1/alpine3.12/amd64/Dockerfile
> Update SDK 3.1 Alpine 3.12 PS version

- src/runtime-deps/2.1/focal/amd64/Dockerfile
- src/runtime-deps/2.1/focal/arm32v7/Dockerfile
> Add liblttng-ust0 to 2.1 runtime-deps focal images

- src/sdk/5.0/focal/amd64/Dockerfile
- src/sdk/5.0/focal/arm32v7/Dockerfile
- src/sdk/5.0/focal/arm64v8/Dockerfile
Related to #https://github.com/dotnet/dotnet-docker/issues/2028
> Remove unnecessary DEBIAN_FRONTEND=noninteractive from 5.0 sdk images

- src/sdk/5.0/alpine3.12/amd64/Dockerfile
- src/sdk/5.0/buster-slim/amd64/Dockerfile
- src/sdk/5.0/buster-slim/arm32v7/Dockerfile
- src/sdk/5.0/buster-slim/arm64v8/Dockerfile
- src/sdk/5.0/focal/amd64/Dockerfile
- src/sdk/5.0/focal/arm32v7/Dockerfile
- src/sdk/5.0/focal/arm64v8/Dockerfile
- src/sdk/5.0/nanoserver-1809/amd64/Dockerfile
- src/sdk/5.0/nanoserver-1903/amd64/Dockerfile
- src/sdk/5.0/nanoserver-1909/amd64/Dockerfile
- src/sdk/5.0/nanoserver-2004/amd64/Dockerfile
Update PowerShell to 7.1.0-preview.4
> Update PowerShell to v7.1.0-preview.4

- README.aspnet.md
- README.aspnet.preview.md
- README.md
- README.runtime-deps.md
- README.runtime-deps.preview.md
- README.runtime.md
- README.runtime.preview.md
- README.samples.md
- README.sdk.md
- README.sdk.preview.md
we want a standard link to license info in all readmes
> remove announcement and add license notice

- .github/ISSUE_TEMPLATE/releases/net-core-release.md
- eng/pipelines/update-dependencies.yml
* Fixed update-dependencies pipeline to use the correct option name for the ASP.NET version.
* Fixes the issue template instructions to include the required parameter.
> Fix a couple issues with update-dependencies

- eng/update-dependencies/Dockerfile
- eng/update-dependencies/Program.cs
Cherry-pick of 2f533450ea8155cd460af3e2ca8059f186169edb
Fixes #1898
> Publish update-deps with rid

- eng/common/templates/jobs/generate-matrix.yml
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
- eng/common/templates/variables/docker-images.yml
- eng/pipelines/dotnet-core-nightly-pr.yml
- eng/pipelines/dotnet-core-nightly.yml
- eng/pipelines/dotnet-core-samples.yml
- eng/pipelines/dotnet-core.yml
- manifest.json
- manifest.samples.json
> Update common Docker engineering infrastructure with latest

- manifest.json
- src/sdk/3.1/alpine3.12/amd64/Dockerfile
Related to https://github.com/dotnet/dotnet-docker/issues/2163
> 3.1 servicing for Alpine 3.12 SDK

- documentation/scenarios/installing-dotnet.md
- documentation/scenarios/nuget-credentials.md
- documentation/scenarios/using-system-drawing-common.md
Fixes #1892
I was motivated to fix this today because I had a user ping me on how to workaround the noninteractive frontend issue on ubuntu today.
> Update scenarios documentation to use .NET 3.1 and latest OS versions

- eng/Get-TagsDocumentation.ps1
- eng/common/Invoke-ReadmeGeneration.ps1
- eng/common/templates/variables/docker-images.yml
- tests/Microsoft.DotNet.Docker.Tests/GeneratedArtifactTests.cs
> Add unit test to ensure the full tags listing of the READMEs are up-to-date

- eng/common/templates/jobs/publish.yml
- eng/common/templates/variables/docker-images.yml
- eng/dockerfile-templates/aspnet/2.1/Dockerfile.linux
- eng/dockerfile-templates/aspnet/3.1/Dockerfile.alpine
- eng/dockerfile-templates/aspnet/3.1/Dockerfile.linux
- eng/dockerfile-templates/aspnet/5.0/Dockerfile.alpine
- eng/dockerfile-templates/aspnet/5.0/Dockerfile.linux
- eng/dockerfile-templates/runtime/2.1/Dockerfile.linux
- eng/dockerfile-templates/runtime/3.1/Dockerfile.alpine
- eng/dockerfile-templates/runtime/3.1/Dockerfile.linux
- eng/dockerfile-templates/runtime/5.0/Dockerfile.alpine
- eng/dockerfile-templates/runtime/5.0/Dockerfile.linux
- eng/dockerfile-templates/sdk/5.0/Dockerfile.linux
> Maintain generated tags with new ImageBuilder version (#2276)

- tests/run-tests.ps1
> Skip pre-build tests on Windows containers

- tests/run-tests.ps1
Cherry-pick of 221477179dbb0dc56860b74e597d0f953d1a2318
> Skip pre-build tests on Windows containers (#2290)

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature-request.md
- README.aspnet.md
- README.aspnet.preview.md
- README.md
- README.runtime-deps.md
- README.runtime-deps.preview.md
- README.runtime.md
- README.runtime.preview.md
- README.samples.md
- README.sdk.md
- README.sdk.preview.md
- eng/readme-templates/README.md
1. Added a `Feature request` issue template.
2. Refactored the `Bug report` issue template.
3. Added an issue config file with entries for the common types of issues .NET Docker users encounter.
4. Simplified the `Feedback` section of the readmes to contain one `File an issue` link which takes users to the new issue selection page of this repo.
You can see how the new issue page looks in [my fork](https://github.com/MichaelSimons/dotnet-docker/issues/new/choose).
[skip ci]
> Enhance issue templates and issue choices

- README.aspnet.md
- README.runtime-deps.md
- README.runtime.md
- README.sdk.md
- eng/readme-templates/README.md
> Document 5.0 as current release version

- README.md
- eng/readme-templates/About.md
Added snippet to README on using F# for writing .NET apps.
> Add F# information to README

- documentation/image-artifact-details.md
- documentation/scenarios/installing-dotnet.md
- documentation/scenarios/nuget-credentials.md
- documentation/scenarios/using-system-drawing-common.md
- documentation/tagging-guidelines.md
- samples/aspnetapp/README.md
- samples/build-in-sdk-container.md
- samples/complexapp/README.md
- samples/dotnetapp/Program.cs
- samples/dotnetapp/README.md
- samples/run-in-sdk-container.md
- samples/run-tests-in-sdk-container.md
- samples/selecting-tags.md
- tests/Microsoft.DotNet.Docker.Tests/SampleImageTests.cs
Fixes https://github.com/dotnet/dotnet-docker/issues/2348
> Update docs to use 5.0 instead of 3.1

- samples/run-aspnetcore-https-development.md
Notes for using aspnetapp sample with ssl dependencies (.pfx with password).
> ssl dependencies for asp.net

- build-and-test.ps1
- eng/common/Get-ImageBuilder.ps1
- eng/common/Invoke-ImageBuilder.ps1
- tests/run-tests.ps1
> Ensure ImageBuilder is pulled before running tests

- eng/update-dependencies/Dockerfile
- eng/update-dependencies/update-dependencies.csproj
> Upgrade update-dependencies tool to 5.0

- samples/aspnetapp/Dockerfile.windowsservercore-x64
- samples/aspnetapp/Dockerfile.windowsservercore-x64-slim
- samples/dotnetapp/Dockerfile.windowsservercore-x64
- samples/dotnetapp/Dockerfile.windowsservercore-x64-slim
- tests/Microsoft.DotNet.Docker.Tests/SampleImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/TestData.cs
> Sample Dockerfiles for Windows Server Core

- tests/Microsoft.DotNet.Docker.Tests/Microsoft.DotNet.Docker.Tests.csproj
- tests/run-tests.ps1
> Upgrade test project to .NET 5

- eng/pipelines/dotnet-core-pr.yml
- eng/pipelines/dotnet-core-samples-pr.yml
> Add main branch to list of pipeline trigger branches

- eng/update-dependencies/DockerfileShaUpdater.cs
This fixes a few issues with the update-dependencies tool that have been bugging me.
There's a dependency on the order of the `product-version` CLI arguments.  If `--product-version sdk=X` is set before `--product-version runtime=Y`, it can cause an inability to retrieve the the SHA values for the SDK artifacts.
The SHA updater for the SDK will execute first in that case.  If it attempts to download the consolidated release checksum file (e.g. https://dotnetcli.blob.core.windows.net/dotnet/checksums/3.1.11-sha.txt) at that point, it will try to generate the correct URL to download from by using the runtime version.
The problem is that it uses the runtime version that's defined in the existing manifest.versions.json file which hasn't been updated yet.  So it'll download the incorrect …
> Fix update-dependencies tool issues

- samples/dotnetapp/README.md
This is pedantic, but the actual dockerfile has this ENTRYPOINT. I know they are equivalent... perhaps it's better to keep them different for educational purposes, but I figure they should be the same?
Thanks
> Update README.md to match the actual Dockerfile

- README.aspnet.md
- README.md
- README.monitor.md
- README.runtime-deps.md
- README.runtime.md
- README.samples.md
- README.sdk.md
- build-and-test.ps1
- eng/dockerfile-templates/monitor/5.0/Dockerfile.alpine
- eng/mcr-tags-metadata-templates/monitor-tags.yml
- eng/readme-templates/Get-GeneratedReadmes.ps1
- eng/readme-templates/README.md
- eng/readme-templates/Use.monitor.md
- manifest.json
- manifest.versions.json
- src/monitor/5.0/alpine/amd64/Dockerfile
- tests/Microsoft.DotNet.Docker.Tests/MonitorImageData.cs
- tests/Microsoft.DotNet.Docker.Tests/MonitorImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/TestData.cs
- tests/run-tests.ps1
In addition to the Dockerfile, it includes all the associated infra for managing the new variant.
> Merge .NET Monitor Dockerfile from nightly branch

- README.aspnet.md
- README.md
- README.monitor.md
- README.runtime-deps.md
- README.runtime.md
- README.samples.md
- README.sdk.md
- eng/readme-templates/README.md
> Remove readme header about repo name transition

- samples/aspnetapp/aspnetapp/Pages/Index.cshtml
Hostname and ipaddress added to aspnetapp project.
> Hostname and ipaddress added to aspnetapp project

- eng/dockerfile-templates/runtime/5.0/Dockerfile.windowsservercore
- eng/dockerfile-templates/runtime/6.0/Dockerfile.windowsservercore
- src/runtime/5.0/windowsservercore-ltsc2019/amd64/Dockerfile
- src/runtime/6.0/windowsservercore-ltsc2019/amd64/Dockerfile
Related to https://github.com/dotnet/dotnet-docker/issues/2865
> Merge main to nightly

- README.monitor.md
- eng/dockerfile-templates/monitor/5.0/Dockerfile.alpine
- manifest.versions.json
- src/monitor/5.0/alpine/amd64/Dockerfile
- tests/performance/ImageSize.nightly.linux.json
Related to https://github.com/dotnet/dotnet-docker/issues/2852
> .NET Monitor release

- tests/Microsoft.DotNet.Docker.Tests/MonitorImageTests.cs
> Update dotnet-monitor environment variable test.

- manifest.samples.json
> Syndicate sample tags to old dotnet/core/samples repository

- tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs
> Remove test workaround for PowerShell crash in 6.0

- README.sdk.md
This reverts commit 04925259f3dbbf7ddd8a4001d467d0f11c924ef4.
> Revert "Test readme publishing by introducing a diff (#2948)"

- README.monitor.md
- eng/dockerfile-templates/monitor/5.0/Dockerfile.alpine
- manifest.versions.json
- src/monitor/5.0/alpine/amd64/Dockerfile
- tests/Microsoft.DotNet.Docker.Tests/MonitorImageTests.cs
Related to https://github.com/dotnet/dotnet-docker/issues/2985
> Updates for .NET Monitor 5.0 Preview 6 release

- samples/aspnetapp/aspnetapp/Pages/Index.cshtml
- samples/dotnetapp/Program.cs
- Added more data to ASP.NET sample.
- Fixed bootstrap table in ASP.NET sample.
- Simplified sample implementation.
> Update environment data in samples

- README.monitor.md
- eng/dockerfile-templates/monitor/6.0/Dockerfile.alpine
- eng/mcr-tags-metadata-templates/monitor-tags.yml
- eng/readme-templates/README.md
- manifest.json
- manifest.versions.json
- src/monitor/5.0/alpine/amd64/Dockerfile
- src/monitor/6.0/alpine/amd64/Dockerfile
- tests/Microsoft.DotNet.Docker.Tests/MonitorImageData.cs
- tests/Microsoft.DotNet.Docker.Tests/TestData.cs
- tests/performance/ImageSize.nightly.linux.json
> Updates for .NET Monitor 6 Preview 8

- tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/RuntimeImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs
* Re-enables tests for scenarios that are working.
* Remove tests and checks for EOL versions.
> Clean up test code

- eng/pipelines/stages/build-test-publish-repo.yml
(cherry picked from commit 75c74f49c800204efc6a92c40191cf08e2b09452)
> Set correct matrix type for PR builds

- tests/Microsoft.DotNet.Docker.Tests/CommonRuntimeImageTests.cs
The latest version of CBL-Mariner has fixed https://github.com/dotnet/dotnet-docker/issues/3222. Now that a shell no longer exists in the container, it is causing tests to fail when verifying environment variable values because the tests expect a shell to exist. I've updated the tests to follow the pattern of building a derived image that includes bash for testing purposes. I've also added a test to verify that the shell doesn't not exist in the container by default.
> Fix tests for shell removal in Mariner distroless

- .github/ISSUE_TEMPLATE/releases/dotnet-monitor-release.md
- eng/Set-DotnetVersions.ps1
> Add .NET Monitor to set versions script.

- samples/aspnetapp/aspnetapp/EnvironmentInfo.cs
- samples/aspnetapp/aspnetapp/Program.cs
This change enables getting the same info as the website, but via an API call. Seems like a good idea!
> Add Environment API

- README.monitor.md
- eng/dockerfile-templates/monitor/Dockerfile
- eng/mcr-tags-metadata-templates/monitor-tags.yml
- eng/readme-templates/README.md
- manifest.json
- manifest.versions.json
- src/monitor/6.2/alpine/amd64/Dockerfile
- tests/Microsoft.DotNet.Docker.Tests/ImageVersion.cs
- tests/Microsoft.DotNet.Docker.Tests/TestData.cs
- tests/performance/ImageSize.nightly.linux.json
> Add .NET Monitor 6.2

- eng/dockerfile-templates/monitor/Dockerfile
- manifest.json
- src/monitor/7.0/cbl-mariner/amd64/Dockerfile
- tests/Microsoft.DotNet.Docker.Tests/OS.cs
- tests/Microsoft.DotNet.Docker.Tests/TestData.cs
- tests/performance/ImageSize.nightly.linux.json
> Add .NET Monitor 7.0 CBL-Mariner 2.0 amd64 image

- manifest.json
- src/monitor/6.1/cbl-mariner/amd64/Dockerfile
- tests/Microsoft.DotNet.Docker.Tests/TestData.cs
- tests/performance/ImageSize.nightly.linux.json
> Add .NET Monitor 6.1 CBL-Mariner 1.0 amd64 image

- eng/dockerfile-templates/sdk/Dockerfile.linux.install-sdk
- eng/update-dependencies/DockerfileShaUpdater.cs
- src/sdk/6.0/cbl-mariner1.0/amd64/Dockerfile
Related to https://github.com/dotnet/dotnet-docker/issues/3615
> Update ASP.NET Core targeting pack file name for .NET 6

- README.aspnet.md
- README.md
- README.monitor.md
- README.runtime-deps.md
- README.runtime.md
- README.samples.md
- README.sdk.md
- eng/readme-templates/README.md
Fixes https://github.com/dotnet/dotnet-docker/issues/3631
> Update link to announcements

- README.aspnet.md
- README.monitor.md
- README.runtime-deps.md
- README.runtime.md
- README.samples.md
- README.sdk.md
- eng/common/templates/variables/docker-images.yml
Related to https://github.com/dotnet/docker-tools/pull/1006
> Update generated readmes to include end of tags marker

- eng/dockerfile-templates/Dockerfile.common-dotnet-envs
- src/runtime-deps/6.0/cbl-mariner1.0-distroless/amd64/Dockerfile
- src/runtime-deps/6.0/cbl-mariner2.0-distroless/amd64/Dockerfile
- src/runtime-deps/6.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile
- tests/Microsoft.DotNet.Docker.Tests/CommonRuntimeImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/ImageData.cs
- tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs
- tests/Microsoft.DotNet.Docker.Tests/SampleImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.linux
- tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.windows
> Set default port for distroless Mariner to a non-privileged port

- eng/dockerfile-templates/aspnet/Dockerfile.linux
- eng/dockerfile-templates/runtime-deps/Dockerfile
- eng/dockerfile-templates/runtime/Dockerfile.linux
- manifest.json
- src/aspnet/6.0/cbl-mariner1.0-distroless/amd64/Dockerfile
- src/runtime-deps/6.0/cbl-mariner1.0-distroless/amd64/Dockerfile
- src/runtime/6.0/cbl-mariner1.0-distroless/amd64/Dockerfile
Fixes https://github.com/dotnet/dotnet-docker/issues/3849
> Fix cache clean-up in Mariner 1.0 distroless

- README.sdk.md
- eng/dockerfile-templates/aspnet/Dockerfile.linux
- eng/dockerfile-templates/monitor/Dockerfile
- eng/dockerfile-templates/runtime-deps/Dockerfile
- eng/dockerfile-templates/runtime/Dockerfile.linux
- eng/dockerfile-templates/sdk/Dockerfile.linux
- manifest.json
- src/aspnet/6.0/cbl-mariner1.0-distroless/amd64/Dockerfile
- src/monitor/6.1/alpine/amd64/Dockerfile
- src/monitor/6.2/alpine/amd64/Dockerfile
- src/monitor/6.2/alpine/arm64v8/Dockerfile
- src/monitor/7.0/alpine/amd64/Dockerfile
- src/monitor/7.0/alpine/arm64v8/Dockerfile
- src/runtime-deps/6.0/cbl-mariner1.0-distroless/amd64/Dockerfile
- src/runtime/6.0/cbl-mariner1.0-distroless/amd64/Dockerfile
- src/sdk/3.1/alpine3.14/amd64/Dockerfile
- src/sdk/3.1/alpine3.15/amd64/Dockerfile
- src/sdk/3.1/alpine3.16/amd64/Dockerfile
- src/sdk/6.0/alpine3.16/amd64/Dockerfile
- src/sdk/6.0/alpine3.16/arm32v7/Dockerfile
- src/sdk/6.0/alpine3.16/arm64v8/Dockerfile
- src/sdk/7.0/alpine3.16/amd64/Dockerfile
- src/sdk/7.0/alpine3.16/arm32v7/Dockerfile
- src/sdk/7.0/alpine3.16/arm64v8/Dockerfile
- tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs
- tests/Microsoft.DotNet.Docker.Tests/Microsoft.DotNet.Docker.Tests.csproj
- tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.linux
- tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.windows
- tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/UnitTests.cs
Merge the hot fixes from #3847 and #3850
> Merge main into nightly

- manifest.versions.json
- src/monitor/7.0/alpine/amd64/Dockerfile
- src/monitor/7.0/alpine/arm64v8/Dockerfile
- src/monitor/7.0/cbl-mariner-distroless/amd64/Dockerfile
- src/monitor/7.0/cbl-mariner-distroless/arm64v8/Dockerfile
- src/monitor/7.0/cbl-mariner/amd64/Dockerfile
- src/monitor/7.0/cbl-mariner/arm64v8/Dockerfile
Manually updating to latest candidate build due to broken update dependencies pipeline.
> .NET Monitor 7.0.0 Preview 7 update

- eng/update-dependencies/DockerfileShaUpdater.cs
The update-dependencies-internal pipeline is broken because it's not able to resolve the checksums for the binaries.
This happens because it's not using the correct base URL. It ends up using `https://dotnetcli.azureedge.net/dotnet` as the base URL when it should be using `https://dotnetbuilds.blob.core.windows.net/internal`. So when it attempts to download files to resolve the checksums, it's getting errors on the HTTP requests.
The base URL is determined by looking up the appropriate `base-url` variable in the manifest.versions.json file. It's looking up the variable with the correct variable name. The problem is that it's looking it up before it's been modified by the `BaseUrlUpdater`.
The solution to this is to simply lazy load the reading of the manifest.versions.json file. This …
> Fix update-dependencies for internal builds

- documentation/scenarios/installing-dotnet.md
- eng/dockerfile-templates/sdk/Dockerfile.linux.install-sdk
Cleaned up a few remaining references to .NET 5 in the documentation and Dockerfile templates.
> Clean up references to .NET 5

- manifest.versions.json
- src/monitor/7.0/alpine/amd64/Dockerfile
- src/monitor/7.0/alpine/arm64v8/Dockerfile
- src/monitor/7.0/cbl-mariner-distroless/amd64/Dockerfile
- src/monitor/7.0/cbl-mariner-distroless/arm64v8/Dockerfile
- src/monitor/7.0/cbl-mariner/amd64/Dockerfile
- src/monitor/7.0/cbl-mariner/arm64v8/Dockerfile
- src/monitor/7.0/ubuntu-chiseled/amd64/Dockerfile
- src/monitor/7.0/ubuntu-chiseled/arm64v8/Dockerfile
> Update .NET Monitor 7.0 to RC 1 candidate

- eng/dockerfile-templates/runtime-deps/Dockerfile.distroless-mariner
- src/runtime-deps/6.0/cbl-mariner2.0-distroless/amd64/Dockerfile
- src/runtime-deps/6.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile
- src/runtime-deps/7.0/cbl-mariner2.0-distroless/amd64/Dockerfile
- src/runtime-deps/7.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile
> Refactor distroless Dockerfile base image usage

- eng/update-dependencies/DockerfileShaUpdater.cs
The update-dependencies tool is not outputting the incorrect SHA values for the nightly branch when targeting a release build of 7.0. This is specific to the difference in targeting a build from the daily build blob container (dotnetbuilds) vs the release blob container (dotnetcli). As part of the merge yesterday from main to nightly, the nightly branch was updated to target the release blob container for 7.0 because the released version didn't exist in the dotnetbuilds blob container (since it had an MSRC fix). Normally the nightly branch would target the dotnetbuilds blob container. But as a result of that change, running the update-dependencies tool grabbed the incorrect SHA values. It was assuming that since it was in nightly, it should not use the release checksum file. But it should …
> update-deps: use release checksums when appropriate

- eng/pipelines/update-dependencies-monitor.yml
Depends on the completion of #4242 
> Add .NET Monitor 8 to version update pipeline

- .config/tsaoptions.json
- eng/pipelines/cg-code.yml
Port of https://github.com/dotnet/dotnet-docker/pull/4435
> [main] Enable CodeQL Scanning

- build-and-test.ps1
Fixes https://github.com/dotnet/dotnet-docker/issues/4368
> Check and fix version formatting in build-and-test script

- build-and-test.ps1
- tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.windows
> Workaround intermittent Arm Windows tests and fix version input for build-and-test.ps1

- samples/aspnetapp/Dockerfile.alpine-non-root
- samples/aspnetapp/Dockerfile.nanoserver-containeruser
- samples/aspnetapp/Dockerfile.windowsservercore-containeruser
- samples/aspnetapp/README.md
This one is .NET 8.
Like the file name?
We need a Dockerfile like this for the blog post.
Fixes https://github.com/dotnet/dotnet-docker/issues/1623
> Add non-root Dockerfile

- eng/update-dependencies/DockerfileShaUpdater.cs
> Fix update-dependencies file formatting exceptions

- tests/Microsoft.DotNet.Docker.Tests/RuntimeDepsImageTests.cs
See https://github.com/dotnet/dotnet-docker/issues/4537
> Pin anchore/syft to v0.75.0

- .github/ISSUE_TEMPLATE/releases/dotnet-release.md
I added a couple of undocumented steps to the release checklist and combined the step about queueing the dotnet-docker pipeline twice.
> Update release process checklist

- manifest.versions.json
- src/sdk/8.0/alpine3.17/amd64/Dockerfile
- src/sdk/8.0/bookworm-slim/amd64/Dockerfile
- src/sdk/8.0/bookworm-slim/arm32v7/Dockerfile
- src/sdk/8.0/bookworm-slim/arm64v8/Dockerfile
- src/sdk/8.0/cbl-mariner2.0/amd64/Dockerfile
- src/sdk/8.0/cbl-mariner2.0/arm64v8/Dockerfile
- src/sdk/8.0/jammy/amd64/Dockerfile
- src/sdk/8.0/jammy/arm32v7/Dockerfile
- src/sdk/8.0/jammy/arm64v8/Dockerfile
- src/sdk/8.0/nanoserver-1809/amd64/Dockerfile
- src/sdk/8.0/nanoserver-ltsc2022/amd64/Dockerfile
- src/sdk/8.0/windowsservercore-ltsc2019/amd64/Dockerfile
- src/sdk/8.0/windowsservercore-ltsc2022/amd64/Dockerfile
Update PowerShell for the v7.4.0-preview.3 release
> Update PowerShell for the v7.4.0-preview.3 release

- samples/aspnetapp/README.md
> Update README.md to remove typo in link

- eng/dockerfile-templates/runtime-deps/Dockerfile
- src/runtime-deps/8.0/alpine3.17/amd64/Dockerfile
- src/runtime-deps/8.0/alpine3.17/arm32v7/Dockerfile
- src/runtime-deps/8.0/alpine3.17/arm64v8/Dockerfile
- src/runtime-deps/8.0/alpine3.18/amd64/Dockerfile
- src/runtime-deps/8.0/alpine3.18/arm32v7/Dockerfile
- src/runtime-deps/8.0/alpine3.18/arm64v8/Dockerfile
- src/runtime-deps/8.0/bookworm-slim/amd64/Dockerfile
- src/runtime-deps/8.0/bookworm-slim/arm32v7/Dockerfile
- src/runtime-deps/8.0/bookworm-slim/arm64v8/Dockerfile
- src/runtime-deps/8.0/cbl-mariner2.0/amd64/Dockerfile
- src/runtime-deps/8.0/cbl-mariner2.0/arm64v8/Dockerfile
- src/runtime-deps/8.0/jammy/amd64/Dockerfile
- src/runtime-deps/8.0/jammy/arm32v7/Dockerfile
- src/runtime-deps/8.0/jammy/arm64v8/Dockerfile
It looks like I left off a newline in #4616. Fixing that.
> Add missing newline in non-root 8.0 images

- eng/dockerfile-templates/sdk/Dockerfile.windows.install-powershell
- src/sdk/8.0/nanoserver-1809/amd64/Dockerfile
- src/sdk/8.0/nanoserver-ltsc2022/amd64/Dockerfile
- src/sdk/8.0/windowsservercore-ltsc2019/amd64/Dockerfile
- src/sdk/8.0/windowsservercore-ltsc2022/amd64/Dockerfile
- tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.linux
cherry picked from commits d866f74914ef53eebd5f69ab8c9b9cce1881bdc2 and be061376d55ee2d3c312f2a9a5c8642d0fc3307b
> Fixes for .NET 8 release

- samples/README.md
Fixes https://github.com/dotnet/dotnet-docker/issues/4725
> Remove broken container best practices link

- README.aspnet.md
- README.monitor-base.md
- README.monitor.md
- README.runtime-deps.md
- README.runtime.md
- README.sdk.md
- eng/mcr-tags-metadata-templates/aspnet-tags.yml
- eng/mcr-tags-metadata-templates/monitor-base-tags.yml
- eng/mcr-tags-metadata-templates/monitor-tags.yml
- eng/mcr-tags-metadata-templates/runtime-deps-tags.yml
- eng/mcr-tags-metadata-templates/runtime-tags.yml
- eng/mcr-tags-metadata-templates/sdk-tags.yml
- manifest.json
- samples/aspnetapp/Dockerfile.alpine-non-root
- tests/Microsoft.DotNet.Docker.Tests/ImageVersion.cs
> Remove preview designation from 8.0 tags

- eng/dockerfile-templates/sdk/Dockerfile.windows.install-powershell
- manifest.versions.json
- src/sdk/8.0/alpine3.18/amd64/Dockerfile
- src/sdk/8.0/bookworm-slim/amd64/Dockerfile
- src/sdk/8.0/bookworm-slim/arm32v7/Dockerfile
- src/sdk/8.0/bookworm-slim/arm64v8/Dockerfile
- src/sdk/8.0/cbl-mariner2.0/amd64/Dockerfile
- src/sdk/8.0/cbl-mariner2.0/arm64v8/Dockerfile
- src/sdk/8.0/jammy/amd64/Dockerfile
- src/sdk/8.0/jammy/arm32v7/Dockerfile
- src/sdk/8.0/jammy/arm64v8/Dockerfile
- src/sdk/8.0/nanoserver-1809/amd64/Dockerfile
- src/sdk/8.0/nanoserver-ltsc2022/amd64/Dockerfile
- src/sdk/8.0/windowsservercore-ltsc2019/amd64/Dockerfile
- src/sdk/8.0/windowsservercore-ltsc2022/amd64/Dockerfile
Update PowerShell for the v7.4.0-preview.5 release
> Update PowerShell for the v7.4.0-preview.5 release

- .mar/portal/README.aspnet.portal.md
- .mar/portal/README.monitor-base.portal.md
- .mar/portal/README.monitor.portal.md
- .mar/portal/README.runtime-deps.portal.md
- .mar/portal/README.runtime.portal.md
- .mar/portal/README.sdk.portal.md
- README.aspnet.md
- README.monitor-base.md
- README.monitor.md
- README.runtime-deps.md
- README.runtime.md
- README.sdk.md
- eng/readme-templates/FeaturedTags.md
Port of https://github.com/dotnet/dotnet-docker/pull/4875 to main.
> Add RC section to readmes

- samples/releasesapi/nuget.config
Update config file to comply with secure supply chain rules.
> Update releasesapi nuget.config

- manifest.versions.json
- src/sdk/8.0/alpine3.18/amd64/Dockerfile
- src/sdk/8.0/bookworm-slim/amd64/Dockerfile
- src/sdk/8.0/bookworm-slim/arm32v7/Dockerfile
- src/sdk/8.0/bookworm-slim/arm64v8/Dockerfile
- src/sdk/8.0/cbl-mariner2.0/amd64/Dockerfile
- src/sdk/8.0/cbl-mariner2.0/arm64v8/Dockerfile
- src/sdk/8.0/jammy/amd64/Dockerfile
- src/sdk/8.0/jammy/arm32v7/Dockerfile
- src/sdk/8.0/jammy/arm64v8/Dockerfile
- src/sdk/8.0/nanoserver-1809/amd64/Dockerfile
- src/sdk/8.0/nanoserver-ltsc2022/amd64/Dockerfile
- src/sdk/8.0/windowsservercore-ltsc2019/amd64/Dockerfile
- src/sdk/8.0/windowsservercore-ltsc2022/amd64/Dockerfile
Update for the v7.4.0-preview.6 release
> Update for the v7.4.0-preview.6 release

- .mar/portal/README.aspnet.portal.md
- .mar/portal/README.monitor-base.portal.md
- .mar/portal/README.monitor.portal.md
- .mar/portal/README.runtime-deps.portal.md
- .mar/portal/README.runtime.portal.md
- .mar/portal/README.samples.portal.md
- .mar/portal/README.sdk.portal.md
- README.aspnet.md
- README.md
- README.monitor-base.md
- README.monitor.md
- README.runtime-deps.md
- README.runtime.md
- README.samples.md
- README.sdk.md
- eng/readme-templates/Support.md
- WIP
- Add additional support info to samples readme
> Clarify support policy in dotnet/samples README

- samples/dotnetapp/Dockerfile.alpine-icu
This is blocking samples publishing.
> Fix Alpine ICU sample build

- .mar/portal/README.aspnet.portal.md
- .mar/portal/README.monitor-base.portal.md
- .mar/portal/README.monitor.portal.md
- .mar/portal/README.runtime-deps.portal.md
- .mar/portal/README.runtime.portal.md
- .mar/portal/README.sdk.portal.md
- README.aspnet.md
- README.monitor-base.md
- README.monitor.md
- README.runtime-deps.md
- README.runtime.md
- README.sdk.md
- eng/mcr-tags-metadata-templates/aspnet-tags.yml
- eng/mcr-tags-metadata-templates/monitor-base-tags.yml
- eng/mcr-tags-metadata-templates/monitor-tags.yml
- eng/mcr-tags-metadata-templates/runtime-deps-tags.yml
- eng/mcr-tags-metadata-templates/runtime-tags.yml
- eng/mcr-tags-metadata-templates/sdk-tags.yml
- eng/readme-templates/FeaturedTags.md
See https://github.com/dotnet/dotnet-docker/issues/4897
> Update READMEs for .NET 8

- README.sdk.md
- manifest.json
- manifest.versions.json
> Fix tagging for alpine arm images with PowerShell update

- samples/releasesapi/Program.cs
- samples/releasesapi/ReleaseJson.cs
- samples/releasesapi/ReportGenerator.cs
- samples/releasesapi/ReportJson.cs
- samples/releasesapp/ReleaseJson.cs
- samples/releasesapp/ReportGenerator.cs
- samples/releasesapp/ReportJson.cs
I updated this code when I published this post, but never in this repo. They now match.
https://devblogs.microsoft.com/dotnet/the-convenience-of-system-text-json/
https://github.com/richlander/convenience/tree/main/releasejson/releasejson
> Update JSON schema

- manifest.json
Port of #5080 
I tested this to make sure it fixes the current failing scenario in internal CI.
> Port #5080 to main

- documentation/scenarios/nuget-credentials.md
Fixes #5086 
Replace Azure pipeline task Docker@0 with Docker@2
> Replace Docker@0 with Docker@2 task in documenation.

- manifest.json
- manifest.versions.json
Port of https://github.com/dotnet/dotnet-docker/pull/5096 to nightly.
> Remove PowerShell Alpine ARM tagging workaround

- tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
- tests/Microsoft.DotNet.Docker.Tests/TestScenarios/WebScenario.cs
> Use graceful shutdown with retry for web scenario tests

- tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
- tests/Microsoft.DotNet.Docker.Tests/TestScenarios/WebScenario.cs
Follow up to https://github.com/dotnet/dotnet-docker/pull/5130#discussion_r1467951977
> Always stop containers before deleting them in tests

- .github/ISSUE_TEMPLATE/bug-report.md
- CONTRIBUTING.md
- README.md
- SECURITY.md
- documentation/guiding-principles.md
- documentation/supported-platforms.md
- documentation/vulnerability-reporting.md
> Add policy for rebuilding container images in response to CVEs

- .github/ISSUE_TEMPLATE/releases/dotnet-release-lifecycle.md
Related to https://github.com/dotnet/dotnet-docker/pull/5157
> Add checklist item for adding new .NET version to featured tags

- README.aspire-dashboard.md
- manifest.versions.json
- src/aspire-dashboard/8.0/cbl-mariner-distroless/amd64/Dockerfile
- src/aspire-dashboard/8.0/cbl-mariner-distroless/arm64v8/Dockerfile
I built and ran the Dashboard image manually to confirm the process still starts.
I observed that when I access `localhost:18889` from the browser, I get the following output. I added no additional environment variables to the running container:
```
info: Aspire.Dashboard.Model.DashboardClient[0]
DOTNET_RESOURCE_SERVICE_ENDPOINT_URL is not specified. Dashboard client services are unavailable.
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
Unhandled exception rendering component: DashboardClient is disabled. Check the IsEnabled property before calling this.
System.InvalidOperationException: DashboardClient is disabled. Check the IsEnabled property before calling this.
at Aspire.Dashboard.Model.DashboardClient.EnsureInitialized() in …
```
> Update to Aspire Dashboard Preview 4

- eng/pipelines/steps/update-dotnet-dependencies.yml
This fixes the latest failure in the update-dependencies pipeline.
> Fix PowerShell Module usage in Update Deps pipeline

- manifest.versions.json
- src/aspire-dashboard/8.0/cbl-mariner-distroless/amd64/Dockerfile
- src/aspire-dashboard/8.0/cbl-mariner-distroless/arm64v8/Dockerfile
cc: @lbussell 
FYI: @kvenkatrajan @drewnoakes
> Updating Aspire Dashboard version

- tests/Microsoft.DotNet.Docker.Tests/TestData.cs
Fixes https://github.com/dotnet/dotnet-docker/issues/5138
> Add published Chiseled samples to sample test data

- manifest.versions.json
- src/aspire-dashboard/8.0/cbl-mariner-distroless/amd64/Dockerfile
- src/aspire-dashboard/8.0/cbl-mariner-distroless/arm64v8/Dockerfile
> Update aspire dashbarod to version 8.0.0-preview.4.24122.1

- .mar/portal/README.aspire-dashboard.portal.md
- .mar/portal/README.aspnet.portal.md
- .mar/portal/README.monitor-base.portal.md
- .mar/portal/README.monitor.portal.md
- .mar/portal/README.runtime-deps.portal.md
- .mar/portal/README.runtime.portal.md
- .mar/portal/README.samples.portal.md
- .mar/portal/README.sdk.portal.md
- README.aspire-dashboard.md
- README.aspnet.md
- README.md
- README.monitor-base.md
- README.monitor.md
- README.runtime-deps.md
- README.runtime.md
- README.samples.md
- README.sdk.md
- documentation/scripts/check-tag-support.ps1
- documentation/supported-tags.md
- eng/readme-templates/README.md
- eng/readme-templates/Support.md
Fixes:
- https://github.com/dotnet/dotnet-docker/issues/5174
- https://github.com/dotnet/dotnet-docker/issues/5175
- https://github.com/dotnet/dotnet-docker/issues/5176
- https://github.com/dotnet/dotnet-docker/issues/5177
> Update various documentation and scripts for Aspire Dashboard and .NET Monitor

- README.aspire-dashboard.md
- manifest.versions.json
- src/aspire-dashboard/8.0/cbl-mariner-distroless/amd64/Dockerfile
- src/aspire-dashboard/8.0/cbl-mariner-distroless/arm64v8/Dockerfile
> Update Aspire to version 8.0.0-preview.5.24157.3

- tests/Microsoft.DotNet.Docker.Tests/MonitorImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/TestScenarios/WebScenario.cs
Fixes https://github.com/dotnet/dotnet-docker/issues/5224
> Revert workaround for missing AOT musl cross package

- eng/common/templates/jobs/build-images.yml
- eng/common/templates/jobs/cg-build-projects.yml
- eng/common/templates/jobs/copy-base-images.yml
- eng/common/templates/jobs/generate-matrix.yml
- eng/common/templates/jobs/post-build.yml
- eng/common/templates/jobs/publish.yml
- eng/common/templates/jobs/test-images-linux-client.yml
- eng/common/templates/jobs/test-images-windows-client.yml
- eng/common/templates/stages/build-test-publish-repo.yml
- eng/common/templates/stages/dotnet/build-test-publish-repo.yml
- eng/common/templates/steps/copy-base-images.yml
- eng/common/templates/steps/init-docker-linux.yml
- eng/common/templates/steps/init-docker-windows.yml
- eng/common/templates/steps/publish-artifact.yml
- eng/common/templates/steps/publish-readmes.yml
- eng/common/templates/steps/set-dry-run.yml
- eng/common/templates/steps/test-images-linux-client.yml
- eng/common/templates/steps/test-images-windows-client.yml
- eng/common/templates/variables/common.yml
- eng/common/templates/variables/docker-images.yml
- eng/common/templates/variables/dotnet/build-test-publish.yml
- eng/common/templates/variables/dotnet/common.yml
- eng/pipelines/dotnet-core-nightly.yml
- eng/pipelines/stages/build-test-publish-repo.yml
- eng/pipelines/variables/core.yml
I included all changes from https://github.com/dotnet/dotnet-docker/pull/5266. I submitted this as a new PR to insulate against my changes being overwritten by additional eng/common updates by the dotnet docker bot. You can review just the new commit in this PR.
> Convert dotnet-docker-nightly pipeline to 1ES Pipeline Templates

- manifest.json
> Add integral test dependencies for Mariner distroless extra images

- eng/pipelines/dotnet-core-nightly.yml
- eng/pipelines/dotnet-core-samples.yml
Test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2407281&view=results
Part of https://github.com/dotnet/dotnet-docker-internal/issues/4475
> Update dotnet-docker-samples pipeline to 1ES Pipeline Template

- eng/pipelines/cg-code.yml
Port of #5290 to main. Fixes #5289.
> Fix CG Code build (main)

- manifest.versions.json
- src/aspire-dashboard/8.0/cbl-mariner-distroless/amd64/Dockerfile
- src/aspire-dashboard/8.0/cbl-mariner-distroless/arm64v8/Dockerfile
- tests/Microsoft.DotNet.Docker.Tests/TestScenarios/AspireDashboardBasicScenario.cs
cc: @lbussell 
FYI: @davidfowl @kvenkatrajan @drewnoakes
> Update Aspire dashboard version to latest preview 5

- manifest.versions.json
- src/aspire-dashboard/8.0/cbl-mariner-distroless/amd64/Dockerfile
- src/aspire-dashboard/8.0/cbl-mariner-distroless/arm64v8/Dockerfile
- tests/Microsoft.DotNet.Docker.Tests/TestScenarios/AspireDashboardBasicScenario.cs
Updating image to latest Preview 5.
> Updating Aspire to latest

- README.aspire-dashboard.md
- manifest.versions.json
- src/aspire-dashboard/8.0/cbl-mariner-distroless/amd64/Dockerfile
- src/aspire-dashboard/8.0/cbl-mariner-distroless/arm64v8/Dockerfile
Update Aspire image to use Preview 6 build.
cc: @lbussell, @kvenkatrajan
> Update Aspire image to Preview 6 version

- eng/update-dependencies/update-dependencies.csproj
> [nightly] Update System.Data.SqlClient transient dependency in update-dependencies project

- README.aspire-dashboard.md
- manifest.versions.json
- src/aspire-dashboard/8.0/cbl-mariner-distroless/amd64/Dockerfile
- src/aspire-dashboard/8.0/cbl-mariner-distroless/arm64v8/Dockerfile
cc: @lbussell 
This is the PR against main. Reminder that this version of Aspire is not out yet, it will ship tomorrow.
> Update Aspire to Preview 7 version

- README.aspire-dashboard.md
- manifest.versions.json
- src/aspire-dashboard/8.0/cbl-mariner-distroless/amd64/Dockerfile
- src/aspire-dashboard/8.0/cbl-mariner-distroless/arm64v8/Dockerfile
cc: @lbussell 
This is shipping to NuGet tomorrow (5/7)
> Update aspire to Preview 7 build

- .mar/portal/README.aspire-dashboard.portal.md
- README.aspire-dashboard.md
- eng/mcr-tags-metadata-templates/aspire-dashboard-tags.yml
- eng/readme-templates/FeaturedTags.md
- manifest.versions.json
- src/aspire-dashboard/8.0/cbl-mariner-distroless/amd64/Dockerfile
- src/aspire-dashboard/8.0/cbl-mariner-distroless/arm64v8/Dockerfile
- tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
- tests/Microsoft.DotNet.Docker.Tests/ImageVersion.cs
- tests/Microsoft.DotNet.Docker.Tests/TestData.cs
Release notes: https://github.com/dotnet/aspire/releases/tag/v8.0.0
/cc @joperezr
> Update Aspire Dashboard to 8.0

- .mar/portal/README.aspire-dashboard.portal.md
- README.aspire-dashboard.md
- eng/mcr-tags-metadata-templates/aspire-dashboard-tags.yml
- eng/readme-templates/FeaturedTags.md
- manifest.versions.json
- src/aspire-dashboard/8.0/cbl-mariner-distroless/amd64/Dockerfile
- src/aspire-dashboard/8.0/cbl-mariner-distroless/arm64v8/Dockerfile
- tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
- tests/Microsoft.DotNet.Docker.Tests/ImageVersion.cs
- tests/Microsoft.DotNet.Docker.Tests/TestData.cs
Port of https://github.com/dotnet/dotnet-docker/pull/5482 to nightly
> Update Aspire Dashboard to 8.0 (nightly)

- manifest.versions.json
- src/sdk/9.0/alpine3.19/amd64/Dockerfile
- src/sdk/9.0/azurelinux3.0/amd64/Dockerfile
- src/sdk/9.0/azurelinux3.0/arm64v8/Dockerfile
- src/sdk/9.0/bookworm-slim/amd64/Dockerfile
- src/sdk/9.0/bookworm-slim/arm32v7/Dockerfile
- src/sdk/9.0/bookworm-slim/arm64v8/Dockerfile
- src/sdk/9.0/nanoserver-1809/amd64/Dockerfile
- src/sdk/9.0/nanoserver-ltsc2022/amd64/Dockerfile
- src/sdk/9.0/noble/amd64/Dockerfile
- src/sdk/9.0/noble/arm64v8/Dockerfile
- src/sdk/9.0/windowsservercore-ltsc2019/amd64/Dockerfile
- src/sdk/9.0/windowsservercore-ltsc2022/amd64/Dockerfile
Update PowerShell for the v7.5.0-preview.3 release
> Update PowerShell for the v7.5.0-preview.3 release

- eng/dockerfile-templates/Dockerfile.linux.install-deps
- eng/dockerfile-templates/Dockerfile.linux.install-pkgs
- src/runtime-deps/8.0/azurelinux3.0-distroless-aot/amd64/Dockerfile
- src/runtime-deps/8.0/azurelinux3.0-distroless-aot/arm64v8/Dockerfile
- src/runtime-deps/8.0/azurelinux3.0-distroless-extra/amd64/Dockerfile
- src/runtime-deps/8.0/azurelinux3.0-distroless-extra/arm64v8/Dockerfile
- src/runtime-deps/8.0/azurelinux3.0-distroless/amd64/Dockerfile
- src/runtime-deps/8.0/azurelinux3.0-distroless/arm64v8/Dockerfile
- src/runtime-deps/8.0/azurelinux3.0/amd64/Dockerfile
- src/runtime-deps/8.0/azurelinux3.0/arm64v8/Dockerfile
This reverts PR #5485, fixing #5528
> Revert "Workaround symcrypt openssl issue in Azure Linux 3.0 base image"

- README.md
- eng/readme-templates/README.md
Fixes https://github.com/dotnet/dotnet-docker/issues/5573
> Include Aspire Dashboard in Featured Repos

- .github/ISSUE_TEMPLATE/new-distro-release.md
- .github/ISSUE_TEMPLATE/new-windows-release.md
Related to https://github.com/dotnet/dotnet-docker/issues/5430
> Move new os issue templates from dotnet/release repo

- .portal-docs/docker-hub/README.aspire-dashboard.md
- .portal-docs/docker-hub/README.aspnet.md
- .portal-docs/docker-hub/README.monitor-base.md
- .portal-docs/docker-hub/README.monitor.md
- .portal-docs/docker-hub/README.runtime-deps.md
- .portal-docs/docker-hub/README.runtime.md
- .portal-docs/docker-hub/README.samples.md
- .portal-docs/docker-hub/README.sdk.md
- .portal-docs/mar/README.aspire-dashboard.portal.md
- .portal-docs/mar/README.aspnet.portal.md
- .portal-docs/mar/README.monitor-base.portal.md
- .portal-docs/mar/README.monitor.portal.md
- .portal-docs/mar/README.runtime-deps.portal.md
- .portal-docs/mar/README.runtime.portal.md
- .portal-docs/mar/README.samples.portal.md
- .portal-docs/mar/README.sdk.portal.md
- README.aspire-dashboard.md
- README.aspnet.md
- README.md
- README.monitor-base.md
- README.monitor.md
- README.runtime-deps.md
- README.runtime.md
- README.samples.md
- README.sdk.md
- eng/readme-templates/Support.md
> Add link to security policy and vulnerability workflow from READMEs

- README.aspire-dashboard.md
- manifest.versions.json
- src/aspire-dashboard/8.0/cbl-mariner-distroless/amd64/Dockerfile
- src/aspire-dashboard/8.0/cbl-mariner-distroless/arm64v8/Dockerfile
Release notes: https://github.com/dotnet/aspire/releases/tag/v8.0.2
> Update Aspire Dashboard to 8.0.2

- eng/Get-DropVersions.ps1
> Add BuildId option to Get-DropVersions script

- eng/dockerfile-templates/runtime-deps/Dockerfile.chiseled-ubuntu
- manifest.versions.json
> Add manifest versions variable for golang version

- tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs
> Re-enable PowerShell Arm32 tests for 9.0

- eng/dockerfile-templates/runtime-deps/Dockerfile.distroless-mariner
- src/runtime-deps/8.0/azurelinux3.0-distroless-aot/amd64/Dockerfile
- src/runtime-deps/8.0/azurelinux3.0-distroless-aot/arm64v8/Dockerfile
- src/runtime-deps/8.0/azurelinux3.0-distroless-extra/amd64/Dockerfile
- src/runtime-deps/8.0/azurelinux3.0-distroless-extra/arm64v8/Dockerfile
- src/runtime-deps/8.0/azurelinux3.0-distroless/amd64/Dockerfile
- src/runtime-deps/8.0/azurelinux3.0-distroless/arm64v8/Dockerfile
- tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs
> Use UID environment variable for non-root user in Azure Linux 3.0 images

- samples/aspnetapp/README.md
> Update health check link

- .portal-docs/docker-hub/README.aspire-dashboard.md
- .portal-docs/docker-hub/README.aspnet.md
- .portal-docs/docker-hub/README.monitor-base.md
- .portal-docs/docker-hub/README.monitor.md
- .portal-docs/docker-hub/README.runtime-deps.md
- .portal-docs/docker-hub/README.runtime.md
- .portal-docs/docker-hub/README.samples.md
- .portal-docs/docker-hub/README.sdk.md
- .portal-docs/mar/README.aspire-dashboard.portal.md
- .portal-docs/mar/README.aspnet.portal.md
- .portal-docs/mar/README.monitor-base.portal.md
- .portal-docs/mar/README.monitor.portal.md
- .portal-docs/mar/README.runtime-deps.portal.md
- .portal-docs/mar/README.runtime.portal.md
- .portal-docs/mar/README.samples.portal.md
- .portal-docs/mar/README.sdk.portal.md
- README.md
- README.monitor-base.md
- eng/readme-templates/DefaultLayout.md
- eng/readme-templates/FeaturedRepos.md
- eng/readme-templates/README.mcr.md
- eng/readme-templates/RelatedRepos.md
- eng/readme-templates/RepoList.md
- eng/readme-templates/ReposProvider.md
Port of #5685 to main + 1 small change (this PR should be a merged or rebased instead of squashed for that reason)
Fixes https://github.com/dotnet/dotnet-docker/issues/5596
> Re-write related repos readme template

- documentation/image-variants.md
- documentation/supported-platforms.md
- documentation/supported-tags.md
- documentation/vulnerability-reporting.md
Fixes #5703 
I also update many of the version numbers I came across while I was at it.
> Add references to Azure Linux in various docs

- .markdownlint.json
- README.md
- documentation/azurelinux.md
- documentation/image-variants.md
- documentation/scenarios/nuget-credentials.md
- eng/pipelines/README.md
- eng/readme-templates/About.product-family.md
- samples/build-for-a-platform.md
- samples/enable-globalization.md
- samples/releasesapp/README.md
Related to https://github.com/dotnet/dotnet-docker/issues/5316
This PR is part of a series of changes to address various markdown syntax violations.
> Fix markdown syntax violations

- eng/update-dependencies/SyftUpdater.cs
- eng/update-dependencies/UpdateDependencies.cs
Fixes: https://github.com/dotnet/dotnet-docker/issues/4545
Adds a simple syft updater.
> Add syft updater

- .markdownlint.json
- documentation/vulnerability-reporting.md
- samples/run-in-sdk-container.md
Related to https://github.com/dotnet/dotnet-docker/issues/5316
> Configure duplicate headers markdown rule and address violations

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/new-windows-release.md
- .github/ISSUE_TEMPLATE/releases/dotnet-release-lifecycle.md
- .github/workflows/lint-code-base.yml
Related to #https://github.com/dotnet/dotnet-docker/issues/5316
This was an oversight on my part with https://github.com/dotnet/dotnet-docker/pull/5809.  I included the necessary markdown syntax corrections.
> Update linter to validate all code

- eng/pipelines/cg-code.yml
Fixes #5369 
This is a follow-up to the changes in https://github.com/dotnet/docker-tools/pull/1371
> Add pipeline parameter for CG dry run

- tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
- tests/Microsoft.DotNet.Docker.Tests/Microsoft.DotNet.Docker.Tests.csproj
- tests/Microsoft.DotNet.Docker.Tests/TestScenarios/ConsoleAppScenario.cs
- tests/Microsoft.DotNet.Docker.Tests/TestScenarios/WebScenario.cs
Port of test changes from #5891.
> Add exponential retry to web scenario tests and capture test container logs

- samples/releasesapi/nuget.config
> Update realeasesapi NuGet config

- documentation/supported-tags.md
Backport of changes from https://github.com/microsoft/dotnet-framework-docker/pull/1177.
> Misc updates to supported-tags.md

- documentation/scenarios/README.md
- documentation/scenarios/installing-dotnet.md
- documentation/scenarios/nuget-credentials.md
> Update scenarios documentation for .NET 9

- manifest.json
- src/aspnet/9.0/azurelinux3.0-distroless-composite-extra/arm64v8/Dockerfile
- src/aspnet/9.0/azurelinux3.0-distroless-extra/arm64v8/Dockerfile
- tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/CommonRuntimeImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/RuntimeImageTests.cs
> Fix base image for ASP.NET Azure Linux 3.0 `extra` images 

- tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
This test was failing in #5983. I tried to give this specific test a more actionable error output. Also, it should now allow `-rtm` versions to pass tests in the main branch... this was intended to allow me to add the current public 9.0 RTM build to #5983 in order to unblock PR validation, but I ran into other issues with that related to templates.
Before:
```
Error Message: Expected actualMajorVersion to be 8 because expected latest tag to be on
the latest major version, but found 9.
```
After:
```
Error Message: Expected latestImageData.SharedTags {"9.0.0-rc.2-bookworm-slim", 
"9.0-bookworm-slim", "9.0.0-rc.2", "9.0", "latest"} to contain a match of "8.*"
because latest tag should be on .NET 8 in repo dotnet/runtime-deps.
```
> Improve latest tag test output

- eng/pipelines/variables/core.yml
Contributes to https://github.com/dotnet/docker-tools/issues/1201
> Enable EOL annotations for publish pipeline

- samples/aspnetapp/Dockerfile.chiseled-composite
I was looking for the hair in the soup... and I found it.
> Tiny format change of Dockerfile.chiseled-composite

- samples/kubernetes/graceful-shutdown/graceful-shutdown.md
Avoid memory leak on combined CancellationTokenSource
> Update graceful-shutdown.md - Avoid memory leak on combined CancellationTokenSource

- tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/CommonRuntimeImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/MonitorImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/OS.cs
- tests/Microsoft.DotNet.Docker.Tests/ProductImageData.cs
- tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/RuntimeDepsImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/RuntimeImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/SampleImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs
- tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs
- tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/NuGet.config.nightly
- tests/Microsoft.DotNet.Docker.Tests/TestScenarios/ProjectTemplateTestScenario.cs
- tests/Microsoft.DotNet.Docker.Tests/TestScenarios/WebScenario.cs
- tests/Microsoft.DotNet.Docker.Tests/TestSolution.cs
> Clean up .NET 6 references from tests

- eng/update-dependencies/BaseUrlUpdater.cs
- eng/update-dependencies/DockerfileShaUpdater.cs
- eng/update-dependencies/GitHubHelper.cs
- eng/update-dependencies/GitHubReleaseUpdaterBase.cs
- eng/update-dependencies/JsonHelper.cs
- eng/update-dependencies/NuGetConfigUpdater.cs
- eng/update-dependencies/Options.cs
- eng/update-dependencies/UpdateDependencies.cs
- eng/update-dependencies/VersionUpdater.cs
> Clean up update-dependencies project

- eng/update-dependencies/UpdateDependencies.cs
The [latest `syft` update](https://github.com/dotnet/dotnet-docker/pull/6126) received a new, identical commit every time the update-dependencies tool was run. This PR adds some additional logging to help debug this in case it happens again.
> Add additional logging to update dependencies tool for PR updates

- eng/dockerfile-templates/runtime-deps/Dockerfile
- eng/dockerfile-templates/runtime/Dockerfile.linux
The regressions came from https://github.com/dotnet/dotnet-docker/pull/6074
Related:
- #6136
- #5935
> Fix regressions in internal Dockerfile templates

- tests/Microsoft.DotNet.Docker.Tests/Config.cs
Ports the changes from https://github.com/dotnet/dotnet-docker/pull/6205 to the main branch.
> Fix environment variable checks to account for empty value

- tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs
> [nightly] Add SymCrypt packages to expected list for Azure Linux 3 

- eng/common/templates/variables/dotnet/build-test-publish.yml
See https://github.com/dotnet/dotnet-docker-internal/issues/7655 for context.
If this works out, then I'll backport this to docker-tools so the change can flow to the other repos.
> Update mcrdocs access token variable

- documentation/ubuntu-chiseled.md
> Update Ubuntu Chisel slice installation doc with chisel-wrapper dpkg status merge feature

- documentation/sample-image-size-report.md
This PR fixes one broken link and updates some of the other links to point to the latest information.
> Update links in sample image size report

- .github/linters/.linkspector.yml
> [nightly] Ignore https://aka.ms/ in markdown link checker

- .portal-docs/docker-hub/README.monitor-base.md
- .portal-docs/mar/README.monitor-base.portal.md
- README.monitor-base.md
- eng/readme-templates/Use.monitor-base.md
Port of https://github.com/dotnet/dotnet-docker/pull/6461 to main
> [main] Update .NET Monitor Dockerfile sample link

- README.aspnet.md
- README.runtime-deps.md
- README.runtime.md
- README.sdk.md
- manifest.json
- manifest.versions.json
Fixes https://github.com/dotnet/dotnet-docker/issues/6497
Related: https://github.com/dotnet/dotnet-docker/issues/6464, https://github.com/dotnet/dotnet-docker/issues/6178
> Move Alpine floating tags to 3.22

- samples/aspnetapp/Dockerfile.nanoserver
> Update HEALTHCHECK port to 8080 in Nano Server aspnetapp sample image

- documentation/scenarios/installing-dotnet.md
Related:
- https://github.com/dotnet/dotnet-docker/issues/6266
- https://github.com/dotnet/dotnet-docker/issues/6495
- #6508 
- #6511
> Update installing-dotnet.md to use online checksums

- eng/pipelines/release-promotion.yml
- eng/pipelines/release-staging.yml
- eng/pipelines/stages/build-and-test.yml
- eng/pipelines/stages/build-test-publish-repo.yml
- eng/pipelines/stages/publish.yml
- eng/pipelines/steps/set-custom-test-variables.yml
- eng/update-dependencies/DotNetVersion.cs
- eng/update-dependencies/NuGetConfigUpdater.cs
- tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs
Related:
- https://github.com/dotnet/dotnet-docker/pull/6544
- #6485 
- #6435
> Port release staging changes to main

- eng/pipelines/release-promotion-unofficial.yml
- eng/pipelines/stages/publish.yml
Fixes https://github.com/dotnet/dotnet-docker-internal/issues/8737
Successful internal pipeline run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2786596&view=results
> Implement release-promotion-unofficial pipeline
