0.0.1-alpha/Dockerfile
0.0.1-alpha/onbuild/Dockerfile

Changed Dockerfile to be based on Ubuntu since CLI doesn't yet have full support for Debian.  This is a short term change until CLI has full support for Debian.
Fix #6

Changed Dockerfile to be based on Ubuntu

---

0.0.1-alpha/Dockerfile

Modified the base Dockerfile to install dotnet via the public Debian package repo.  Also removed the logic that set the DOTNET_HOME environment variable since .NET CLI addressed the issue that required this.
fixes #12

Modified the base Dockerfile to install dotnet Debian repo

---

0.0.1-alpha/Dockerfile

Same change as in https://github.com/dotnet/dotnet-docker-preview/pull/2
cc: @MichaelSimons @dleeapho

Temporarily work around LTTng failed assertion

---

0.0.1-alpha/README.md

Tag names are case-insensitive in Docker, and Docker 1.10 introduced
validation logic that causes `docker build` to fail if the specified tag
contains uppercase characters, as stated in https://github.com/docker/distribution/issues/1433.
It appears that Docker container names are case-sensitive (in contrast
with tag names), but the default container names are all-lowercase with
underscores, and I think it looks better to use the same naming
convention for tag names and container names in the `docker run` example
command.
I chose hyphens over underscores because our tags in this repo use
hyphens (e.g. 0.0.1-alpha-onbuild), but underscores would be fine too.
cc: @dleeapho @MichaelSimons

Fix example tag name in README

---

1.0.0-preview1/Dockerfile

The llvm repo was taken down unexpectedly and there is no immediate signs of it coming back soon. The microsoft/dotnet repo uses this to get the liblldb-3.6 package. This package is only used if you try to use the sos plugin for lldb. It is not a critical dependency and has been argued that it should be an optional dependency. As a result the Dockerfile is failing to build. Additionally if you pull the latest image, you will get errors when running apt-get update because this repo is registered in the image yet is unavailable.
Fixes #48 
@dleeapho, @naamunds

Removed the liblldb package from the image

---

1.0.0/README.md

I manually ported https://github.com/MichaelSimons/dotnet-docker/pull/3 over to master and addressed the PR feedback.  I didn't want to duplicate all of the documentation for the windowsservercore and nanoserver variants - there are 6 of them.  A decision was made to take a different approach and left the `image variants` section alone since that is just intended to describe the 4 main variations (sdk, onbuild, core, core-deps) of the images.  The variations will remain the same as we move towards a docker manifest.  A Windows Containers section was then added which contains the differentiated verbiage.
@naamunds, @dleeapho, @blackdwarf, @PatrickLang

Update readme for Windows Containers

---

test/create-run-publish-app.sh
test/run-test.sh

Test core-deps by creating a self-contained app in the sdk container,
and then running the self-contained app's published executable in a
core-deps container.
Also fix running with DEBUGTEST by putting the trailing space in
"optional_docker_run_args" instead of in the "docker run" commands to
eliminate the two consecutive spaces.
Fixes #117 
cc: @MichaelSimons

Add CI for core-deps images

---

1.0.0-preview2/nanoserver/Dockerfile
1.0.0-preview2/windowsservercore/Dockerfile
1.0/nanoserver/core/Dockerfile
1.0/windowsservercore/core/Dockerfile

With this new version the forwarders workaround is no longer needed therefore it was removed.
Fixes #120 
Fixes #75
cc @naamunds

Update to windows 10.0.14393.206

---

1.0/README.md

The tag `1.0.0-preview2` does not exist.  This should either be `1.0.0-preview2-sdk` or should just refer to the `latest` tag.  I think the latter makes more sense, because that is what is used in other examples in the README, e.g. `FROM microsoft/dotnet:nanoserver` and `docker run -it --rm microsoft/dotnet`
/cc @richlander @MichaelSimons

Fix tag in README

---

1.0/README.md

In regards to https://github.com/dotnet/dotnet-docker/pull/156#discussion_r88139619, we should still have a 1.X versioned tags.  I think it is reasonable to add them with the *-sdk-msbuild suffix.  Having these tags allow us to run our CI tests against the DH artifacts which is valuable.
@naamunds, @richlander

Add 1.1-sdk-msbuild and 1.0-sdk-msbuild tags

---

1.0/README.md
1.0/debian/runtime-deps/Dockerfile
1.0/debian/runtime-deps/hooks/post_push
1.0/debian/runtime/Dockerfile
1.0/debian/sdk/msbuild/Dockerfile
1.0/debian/sdk/msbuild/hooks/post_push
1.0/debian/sdk/projectjson/Dockerfile
1.0/debian/sdk/projectjson/hooks/post_push
1.0/nanoserver/runtime/Dockerfile
1.0/nanoserver/sdk/projectjson/Dockerfile
1.1/debian/runtime-deps/hooks/post_push
1.1/debian/sdk/msbuild/hooks/post_push
1.1/debian/sdk/projectjson/hooks/post_push
test/create-run-publish-app.ps1
test/create-run-publish-app.sh

This change won't be merged until the 1.0.3 runtime packages are published.  Until then Debian CI will fail.
Fixes #121
@naamunds

Upgrading 1.0 Dockerfiles to be based on 1.0.3 of the runtime

---

build-and-test.ps1

The usage of this parameter was removed in https://github.com/dotnet/dotnet-docker/commit/6ce7bf25a74f8097e18757b484b4cd2c9399302c but in order to update CI to not specify it, it can't be a required parameter.

Removed mandatory attribute from the Platform param of build-and-test.ps1

---

netci.groovy

Logic was added to the CI script to self detect the Platform therefore it is no longer being used and can be removed.  Once this PR is merged I will make a follow-up PR to remove the parameter from the build-and-test script.

Remove the Platform param from nano CI

---

build-and-test.ps1
test/Dockerfile.linux.testrunner
test/run-test.ps1

With 6ce7bf25a74f8097e18757b484b4cd2c9399302c, logic was added to self-detect the platform.  With 5d594b45e08ed2c24d0555d221bc50ac980fcf54, CI was updated to not specify the parameter.  This PR completes the cleanup by removing the parameter from the script.

Remove the Platform parameter from build-an-test.ps1

---

README.md

Fixes #228 
The preview sample was removed with https://github.com/dotnet/dotnet-docker-samples/pull/27.

Removed old preview sample link

---

build-and-test.ps1
build-pipeline/dotnet-docker-linux-images.json
build-pipeline/dotnet-docker-post-image-build.json
build-pipeline/dotnet-docker-windows-images.json
manifest.json
test/run-test.ps1

- Upgraded to use latest image builder tool.  This required a manifest schema change.  
- Refactored manifest to make use of tagVariables which will make patch Tuesday work easier/less error prone.
- Minor build-pipeline build definitions cleanup.

Upgrade to use latest image builder

---

build-and-test.ps1
build-pipeline/dotnet-docker-linux-images.json
build-pipeline/dotnet-docker-post-image-build.json
build-pipeline/dotnet-docker-windows-images.json
build-pipeline/pipeline.json
manifest.json
test/run-test.ps1

Migration of https://github.com/dotnet/dotnet-docker-nightly/pull/352 from dotnet-docker-nightly to dotnet-docker.

Split official builds into smaller legs to decrease overall build time

---

1.0/sdk/jessie/Dockerfile
1.0/sdk/nanoserver/Dockerfile
1.1/sdk/jessie/Dockerfile
1.1/sdk/nanoserver/Dockerfile
manifest.json

This is needed to align the SDK images with VS 15.3 which included CLI 1.1.0.

Upgrade 1.0.5 and 1.1.2 SDK images to include CLI 1.1.0

---

1.0/runtime/nanoserver/Dockerfile
1.0/sdk/nanoserver/Dockerfile
1.1/runtime/nanoserver/Dockerfile
1.1/sdk/nanoserver/Dockerfile
2.0/runtime/nanoserver/amd64/Dockerfile
2.0/sdk/nanoserver/amd64/Dockerfile
manifest.json

Updating Nano Server Dockerfiles to be based on 10.0.14393.1715

Updating Nano Server Dockerfiles to be based on 10.0.14393.1715

---

1.0/runtime/jessie/Dockerfile
1.0/runtime/nanoserver/Dockerfile
1.0/sdk/jessie/Dockerfile
1.0/sdk/nanoserver/Dockerfile
1.1/runtime/jessie/Dockerfile
1.1/runtime/nanoserver/Dockerfile
1.1/sdk/jessie/Dockerfile
1.1/sdk/nanoserver/Dockerfile
README.md
build-pipeline/dotnet-docker-linux-amd64-images.json
build-pipeline/dotnet-docker-linux-arm32v7-images.json
build-pipeline/dotnet-docker-post-image-build.json
build-pipeline/dotnet-docker-windows-amd64-images.json
manifest.json

This is a pseudo migration of the changes from dotnet-docker-nightly.  This release will not include the image consolidation changes that were recently made in nightly.  This is an update for https://github.com/dotnet/dotnet-docker/pull/292.

Updates for 1.0.7/1.1.4 release

---

1.0/runtime/nanoserver/Dockerfile
1.0/sdk/nanoserver/Dockerfile
1.1/runtime/nanoserver/Dockerfile
1.1/sdk/nanoserver/Dockerfile
2.0/runtime/nanoserver/amd64/Dockerfile
2.0/sdk/nanoserver/amd64/Dockerfile
manifest.json

Updating Nano Server Dockerfiles to be based on 10.0.14393.1770

Updating Nano Server Dockerfiles to be based on 10.0.14393.1770

---

README.md
manifest.json

Nano Server version tag is updated to be in the format -
`<version of the .Net Core app the sdk image is intended to build>-sdk-<version of the sdk the image includes>-nanoserver`
Updated `README.md` accordingly.

Fix 2.0.2 Nano Server tag.

---

build-pipeline/dotnet-docker-linux-amd64-images.json
build-pipeline/dotnet-docker-linux-arm32v7-images.json
build-pipeline/dotnet-docker-post-image-build.json

Refer https://github.com/dotnet/dotnet-docker-nightly/pull/464
Note that Windows leg already has `"cleanOptions": "3",`.

[Port] Set build cleanup options

---

2.0/runtime/nanoserver-1709/amd64/Dockerfile
2.0/sdk/nanoserver-1709/amd64/Dockerfile
README.md
build-and-test.ps1
build-pipeline/dotnet-docker-windows-1709-amd64-images.json
build-pipeline/pipeline.json
manifest.json
test/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
test/Microsoft.DotNet.Docker.Tests/Dockerfile.windows.testapp
test/Microsoft.DotNet.Docker.Tests/ImageDescriptor.cs
test/Microsoft.DotNet.Docker.Tests/ImageTests.cs
test/run-test.ps1

Fixes #298 
Remaining changes:

Add nanoserver Dockerfiles for 1709 release

---

manifest.json
scripts/Get-TagsDocumentation.ps1

Rollout of https://github.com/dotnet/docker-tools/issues/56

Update Get-TagsDocumentation.ps1 for RS3 images

---

README.md
manifest.json

Per guidance from Windows team - nanoserver RS1 is not ltsc2016 it it sac2016

Renamed ltsc2016 to sac2016

---

1.1/sdk/jessie/amd64/Dockerfile
1.1/sdk/nanoserver-sac2016/amd64/Dockerfile
README.md
manifest.json

SDK 1.1.6 release was rolled backed - therefore the Docker images need to as well.

Rollback release of 1.1.6

---

update-dependencies/Program.cs

[update-dependencies] Use ProductVersion from build info

---

build-pipeline/dotnet-docker-linux-amd64-images.json
build-pipeline/dotnet-docker-linux-arm32v7-images.json
build-pipeline/dotnet-docker-post-image-build.json
build-pipeline/dotnet-docker-windows-1709-amd64-images.json
build-pipeline/dotnet-docker-windows-sac2016-amd64-images.json
build-pipeline/pipeline.json
manifest.json
test/Microsoft.DotNet.Docker.Tests/ImageTests.cs
test/run-test.ps1

Fixes https://github.com/dotnet/docker-tools/issues/21
- Updated image builder to latest.  Required renaming `--test-var` to `--var`.
- Updated pipebuild to latest in order to make use of functionality to pass any variables with `PB_` prefix.
- Added PB_image-builder_queueCustomArgs variable to build defs to flow custom args such as `--repo-owner`

Add support for specifying a custom repo-owner when building

---

2.1/sdk/alpine/amd64/Dockerfile
README.md
manifest.json
test/Microsoft.DotNet.Docker.Tests/ImageTests.cs

_Copied from https://github.com/dotnet/dotnet-docker-nightly/pull/508 by @richlander_
This PR isn't quite ready. Work items:
~* [ ] Consider globalization invariant mode support for the SDK.~
Sample I used for testing: https://github.com/dotnet/dotnet-docker-samples/tree/alpine/dotnetapp-prod
I got the image to work as expected but needed to remove invariant-mode support for the SDK. it seems like the SDK fails to run with invariant mode.
This is the error that I saw before removing globalization invariant mode / adding ICU:
```console
Step 7/11 : RUN dotnet publish -c Release -o out
---> Running in 0f3ff19e0e0f
Microsoft (R) Build Engine version 15.6.22.57775 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.
Restore completed in 46.27 ms for /app/dotnetapp.csproj. …
```

Add Alpine SDK image

---

2.1/runtime-deps/bionic/amd64/Dockerfile
2.1/runtime-deps/bionic/arm32v7/Dockerfile
2.1/runtime-deps/stretch-slim/amd64/Dockerfile
2.1/runtime-deps/stretch-slim/arm32v7/Dockerfile
2.1/runtime/bionic/amd64/Dockerfile
2.1/runtime/bionic/arm32v7/Dockerfile
2.1/runtime/stretch-slim/amd64/Dockerfile
2.1/runtime/stretch-slim/arm32v7/Dockerfile
2.1/sdk/bionic/amd64/Dockerfile
README.md
build-pipeline/pipeline.json
manifest.json
netci.groovy
test/Microsoft.DotNet.Docker.Tests/ImageTests.cs
test/Microsoft.DotNet.Docker.Tests/OS.cs

- Switch to `stretch-slim` instead of `stretch` for all runtime images. Keep SDK as-is (no buildpack-deps for slim images)
- Keep using Stretch for MA tags like `2-sdk`, `2.1-runtime` and `latest`
- Drop Jessie SDK and Runtime (X64)
- Add Ubuntu:18.04 (bionic) for SDK and Runtime (X64 and ARM)

2.1 images

---

build-pipeline/README.md
build-pipeline/dotnet-docker-linux-amd64-images.json
build-pipeline/dotnet-docker-linux-arm32v7-images.json
build-pipeline/dotnet-docker-post-image-build.json
build-pipeline/dotnet-docker-windows-1709-amd64-images.json
build-pipeline/dotnet-docker-windows-sac2016-amd64-images.json
build-pipeline/pipeline-samples.json
build-pipeline/pipeline.json
manifest.samples.json
samples/README.DockerHub.md
scripts/Get-TagsDocumentation.ps1

These changes were based on the existing [pipebuild in dotnet-docker-samples](https://github.com/dotnet/dotnet-docker-samples/tree/master/build-pipeline)
Fixes #384 
Related #396

Add infrastructure to build and push samples to Docker Hub

---

samples/dotnetapp/Dockerfile.alpine-x64
samples/dotnetapp/Dockerfile.alpine-x64-globalization

- Switch to use base images from microsoft/dotnet over microsoft/dotnet-docker
- Switch build stage to use Alpine sdk base image
- Fix bug in Dockerfile.alpine-x64-globalization where the publish output was being copied from the wrong stage.

Misc Alpine sample Dockerfile fixes

---

README.md
manifest.json
samples/README.DockerHub.md
scripts/Get-TagsDocumentation.ps1
scripts/TagsDocumentationTemplate.md

Fixes #337 
Fixes #397 
In order to support this new format, a template file was introduced that is input into the generateTagsReadme cmd of image-builder.  This will make it easier in the future to change the tags format of the readme.

Refactor ordering of tags in readme

---

2.1/runtime-deps/bionic/amd64/Dockerfile
2.1/runtime-deps/bionic/arm32v7/Dockerfile
2.1/sdk/bionic/amd64/Dockerfile

Related to #416.
libcurl3 and libcurl4 both install libcurl.so.4.5.0 which is what dotnet runtime depends on.  This is why both versions cannot be installed at once (installing one removes the other).

Update bionic images to include libcurl4

---

README.md

Fixes #408 
* Simplified the `How to use this image` section.  We would like to direct to the samples which are more in-depth.
* Refactored the samples section to reference the newly refactored samples. I also move the section to follow the simplified `How to use this image` section.
* Copied the `Related Repos` pattern used in the various samples readmes.

Refactor readme to reference new samples

---

2.1/runtime-deps/alpine/amd64/Dockerfile
2.1/runtime-deps/bionic/amd64/Dockerfile
2.1/runtime-deps/bionic/arm32v7/Dockerfile
2.1/runtime-deps/stretch-slim/amd64/Dockerfile
2.1/runtime-deps/stretch-slim/arm32v7/Dockerfile
2.1/runtime/nanoserver-1709/amd64/Dockerfile
2.1/runtime/nanoserver-sac2016/amd64/Dockerfile
2.1/sdk/alpine/amd64/Dockerfile
2.1/sdk/bionic/amd64/Dockerfile
2.1/sdk/nanoserver-1709/amd64/Dockerfile
2.1/sdk/nanoserver-sac2016/amd64/Dockerfile
2.1/sdk/stretch/amd64/Dockerfile

Fix for #426 and supporting #420.

Add Environment variables

---

2.0/sdk/jessie/amd64/Dockerfile
2.0/sdk/nanoserver-1709/amd64/Dockerfile
2.0/sdk/nanoserver-sac2016/amd64/Dockerfile
2.0/sdk/stretch/amd64/Dockerfile

Workaround https://github.com/Microsoft/DockerTools/issues/87.
Fixes https://github.com/dotnet/dotnet-docker/issues/429
Please review @natemcmaster, @glennc

Set RestoreUseSkipNonexistentTargets=false in the 2.0 SDK image to workaround changes between 2.1.4 and 2.1.101

---

samples/aspnetapp/README.md

`docker run` cmd does not run the image that was built in the previous instruction.

Fixup broken instructions in aspnet sample readme

---

scripts/update-dependencies/Program.cs

The underlying issue is that the DockerfileShaUpdator updated files in this scenario but it doesn't rely on any build info to do this - it reads the version info out of the Dockerfile.  Later on the code tried to read the SDK version from the used build info (in order to generate the commit message) but it wasn't found.  I refactored how this was retrieved to use the information from the versions repo.

Refactor update-dependencies to handle cli rebuild without version change

---

.gitignore
scripts/update-dependencies/DockerfileShaUpdater.cs
scripts/update-dependencies/Options.cs
scripts/update-dependencies/Program.cs

* Add support for reading local build info file.
* Add support for 2.0 sdk scenarios where the sdk version does not align with the dockerfile version folder layout.  Runtime version info is used to find Dockerfiles now.
* Add support for reading checksums from `https://dotnetcli.blob.core.windows.net/dotnet/checksums` if not found in `https://dotnetclichecksums.blob.core.windows.net`

Refactor update-dependencies to support additional scenarios

---

build-and-test.ps1
test/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
test/Microsoft.DotNet.Docker.Tests/ImageTests.cs

Builds have been failing frequently due to DockerHelper.Kill failing to remove the container.  This is an attempt to cleanup the container in a more robust fashion.

Refactor test cleanup logic

---

2.1/aspnetcore-runtime/alpine3.7/amd64/Dockerfile
2.1/runtime-deps/alpine3.7/amd64/Dockerfile
2.1/runtime/alpine3.7/amd64/Dockerfile
2.1/sdk/alpine3.7/amd64/Dockerfile
README.md
build-and-test.ps1
manifest.json
scripts/TagsDocumentationTemplate.md
test/Microsoft.DotNet.Docker.Tests/ImageTests.cs

As part of this I am proposing the introduction of fixed `alpine3.7` suffixed tags along with the stable `alpine` tags.  This aligns with what is done in the official Docker repos.  This will afford us the opportunity to upgrade Alpine versions within any given .NET release.
Related to #488

Update 2.1 Alpine 3.6 images to 3.7

---

README.md
manifest.json
scripts/TagsDocumentationTemplate.md

In response to https://github.com/dotnet/dotnet-docker/pull/494 and https://github.com/dotnet/cli/pull/9101

Update 2.1 tags to align with the product versions (preview2 -> rc1)

---

.dockerignore
test/Microsoft.DotNet.Docker.Tests/ImageTests.cs

1. Add a workaround for https://github.com/dotnet/cli/issues/9162 to get tests passing on arm.
2. Add exclusions to .dockerignore to avoid coping so much into testrunner image.
3. Fix for #503

Misc test fixups

---

samples/README.DockerHub.md
samples/README.md
samples/aspnetapp/README.md
samples/aspnetapp/aspnet-docker-dev-in-container.md
samples/aspnetapp/aspnetcore-docker-https-development.md
samples/aspnetapp/aspnetcore-docker-https.md
samples/dotnetapp/Directory.Build.props
samples/dotnetapp/dotnet-docker-dev-in-container.md
samples/dotnetapp/dotnet-docker-unit-testing.md

- `aspnetcore-docker-https-development.md` is a new document. It contains the information that used to be in `aspnetcore-docker-https.md`, with updates.
- The content in `aspnetcore-docker-https.md` is new. The diff isn't meaningful as a result.

Update HTTPS instructions

---

build-pipeline/pipeline.json

This was overlooked as part of the changes for #515.  The build leg was running and was no-oping because there are no 2.0 arm images to build.

Remove unused 2.0 ARM build leg

---

samples/aspnetapp/Dockerfile
samples/aspnetapp/Dockerfile.alpine-x64
samples/aspnetapp/Dockerfile.nanoserver-sac2016
samples/aspnetapp/Dockerfile.preview
samples/aspnetapp/README.md
samples/dotnetapp/README.md
samples/dotnetapp/dotnet-docker-dev-in-container.md

The aspnet docker samples and docs have been using `-c release` while the dotnet ones have already been using `-c Release`.
This PR corrects the capitalisation to `Release`.  since `release` may cause issues like https://github.com/dotnet/cli/issues/8920
To reproduce:
Use VS project property pages to enable documentation file generation. VS will change the csproj to:
```xml
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
<DocumentationFile>bin\Debug\netcoreapp2.1\WebApplication9.xml</DocumentationFile>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
<DocumentationFile>bin\Release\netcoreapp2.1\WebApplication9.xml</DocumentationFile>
</PropertyGroup>
```
which will now fail to build on *nix with `-c release` due to …

Correct capitalization of Release configuration.

---

.vsts.pipelines/microsoft-dotnet-samples.yml
.vsts.pipelines/templates/build-all.yml
.vsts.pipelines/templates/build-windows-amd64.yml
manifest.json
manifest.samples.json
test/Microsoft.DotNet.Docker.Tests/ImageData.cs
test/Microsoft.DotNet.Docker.Tests/ImageTests.cs

- Combined the PlatformOS and OSVariant concepts within the unit tests.
- Simplified the build inputs by utilizing the `os-version` functionality within Image-Builder.  This eliminates the version filter and os filter from being specified multiple times.

Refactor how the os-filter is used within build infra

---

.vsts.pipelines/phases/build-all.yml

We are always adding more Docker image variants, so this change will run the longest build legs first which is a decent optimization when build agents are limited.  e.g. Longer legs will get running first and when additional agents are available the shorter legs will run.

Invert build leg order

---

README.md

Looks like a documentation typo on the correct asp.net core runtime image when compared to the docker hub repository:

Resolve documentation typo for the aspnetcore-runtime docker image tag

---

.vsts.pipelines/builds/microsoft-dotnet-nightly.yml
.vsts.pipelines/builds/microsoft-dotnet-samples.yml
.vsts.pipelines/builds/microsoft-dotnet.yml
.vsts.pipelines/phases/build-all.yml
.vsts.pipelines/phases/build-linux-amd64.yml
.vsts.pipelines/phases/build-linux-arm32v7.yml
.vsts.pipelines/phases/build-windows-amd64.yml
.vsts.pipelines/phases/copy-images-linux.yml
.vsts.pipelines/phases/copy-images-windows.yml
.vsts.pipelines/phases/publish-finalize.yml
.vsts.pipelines/phases/test-linux-amd64.yml
.vsts.pipelines/phases/test-linux-arm32v7.yml
.vsts.pipelines/phases/test-windows-amd64.yml
.vsts.pipelines/steps/docker-cleanup-linux.yml
.vsts.pipelines/steps/docker-cleanup-windows.yml
build-and-test.ps1
test/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
test/Microsoft.DotNet.Docker.Tests/ImageTests.cs
test/run-test.ps1

These changes refactor the VSTS build definition to do the following:
- Break the build into build, test, and publish phases.  This allows the build to be distributed into smaller units which provides better scaling capabilities.
- Utilizes a staging ACR during the build prior to final publish
- Allows the build to be started at either the build, test or publish phases.
Future work:
- Generate the queue matrix dynamically to eliminate the maintenance issue and to further break the build down into smaller units.
- General cleanup once VSTS support yaml global variables
- Better support for re-queuing a partial build - VSTS has some bugs that blocking this effort.

Refactor build to utilize a staging registry

---

2.1/runtime-deps/buster-slim/amd64/Dockerfile
2.1/runtime-deps/buster-slim/arm32v7/Dockerfile
2.1/sdk/buster/amd64/Dockerfile
2.1/sdk/buster/arm32v7/Dockerfile

`libicu57` is no longer in the default `buster` package cache, upgrading to `libicu60`.

Update libicu on buster images to libicu60

---

.vsts-pipelines/builds/microsoft-dotnet-samples.yml
.vsts-pipelines/phases/build-all.yml
.vsts-pipelines/phases/build-linux-amd64.yml
.vsts-pipelines/phases/build-linux-arm32v7.yml
.vsts-pipelines/phases/build-windows-amd64.yml
.vsts-pipelines/phases/copy-images-linux.yml
.vsts-pipelines/phases/copy-images-windows.yml
.vsts-pipelines/phases/test-linux-amd64.yml
.vsts-pipelines/phases/test-linux-arm32v7.yml
.vsts-pipelines/phases/test-windows-amd64.yml

* Renamed the `buildPath` variable to `dotnetVersion` as it more accurately describes what the variable contains.  It is used for more than the imageBuilder `path` option.
* Dropped the `Build_` prefix from the build queue names.  The `Build_` prefix was confusing to see in the build output for the Test and Copy phases - e.g. `Test_Linux_amd64 Build_2_0_Jessie`

Rename build queues and the 'buildPath' variable

---

.vsts-pipelines/phases/test-linux-amd64.yml
.vsts-pipelines/phases/test-linux-arm32v7.yml
.vsts-pipelines/phases/test-windows-amd64.yml
tests/Microsoft.DotNet.Docker.Tests/Microsoft.DotNet.Docker.Tests.csproj
tests/run-tests.ps1

* Upgrade tests to be based on .NET Core 2.1
* Update run-tests.ps1 to emit trx files with the test results
* Added build steps to publish the test results.  This makes them accessible in the `tests` tab in the VSTS build results.

Add build steps to publish tests results

---

.vsts-pipelines/builds/microsoft-dotnet-samples.yml
.vsts-pipelines/phases/build-all.yml
.vsts-pipelines/phases/build-linux-amd64.yml
.vsts-pipelines/phases/build-linux-arm32v7.yml
.vsts-pipelines/phases/build-windows-amd64.yml
.vsts-pipelines/phases/copy-images-linux.yml
.vsts-pipelines/phases/copy-images-windows.yml
.vsts-pipelines/phases/publish-finalize.yml
.vsts-pipelines/phases/test-linux-amd64.yml
.vsts-pipelines/phases/test-linux-arm32v7.yml
.vsts-pipelines/phases/test-windows-amd64.yml
.vsts-pipelines/steps/docker-create-repo-volume-linux.yml

* Update arm32 build legs to run on a linux client. Currently a Windows 10 machine is used as the Docker client.  This has proven to be very unstable.  Note: A remote client must be used because the VSTS build agent doesn't currently support arm.
* Refactored how tests were skipped for the samples repo.
* Fixed an issue with the publish logic in that it wouldn't skip all legs if there were any failures in build/tests.
* General simplification cleanup by removing some unnecessary parameters and variables.

Update arm32 build legs to run on a linux client

---

2.1/aspnetcore-runtime/alpine-edge/amd64/Dockerfile
2.1/runtime/alpine-edge/amd64/Dockerfile
2.1/sdk/alpine-edge/amd64/Dockerfile

A suitable version of openssl is getting previously installed by libressl2.7-libcrypto-2.7.4-r0 which is causing a conflict.
This issue is blocking the build.

[2.1 alpine-edge] remove 'virtual' openssl from aspnet and runtime dockerfiles

---

scripts/update-dependencies/DockerfileShaUpdater.cs

1. Added a checksum cache which helps speed up the app since several of the Dockerfiles download the same dotnet components.
1. Added logic to compute the checksum which is useful in special cases were the published checksums are not available.

[update-dependencies] Add checksum cache and compute logic

---

.vsts-pipelines/phases/build-all.yml
.vsts-pipelines/phases/build-linux-amd64.yml
.vsts-pipelines/phases/build-linux-arm32v7.yml
.vsts-pipelines/phases/build-windows-amd64.yml
.vsts-pipelines/phases/copy-images-linux.yml
.vsts-pipelines/phases/copy-images-windows.yml
.vsts-pipelines/phases/publish-finalize.yml
.vsts-pipelines/phases/test-linux-amd64.yml
.vsts-pipelines/phases/test-linux-arm32v7.yml
.vsts-pipelines/phases/test-windows-amd64.yml
.vsts-pipelines/steps/docker-create-repo-volume-linux.yml
.vsts-pipelines/steps/docker-init-linux.yml
.vsts-pipelines/steps/docker-init-windows.yml
scripts/Invoke-PullImage.ps1
scripts/pull-image.sh

- Use latest image builder with fix for https://github.com/dotnet/docker-tools/issues/105
- Add retry logic when pulling Docker images
- Refactor `startingPhase` into `singlePhase`.  This provides more robust control such as being able to only perform a build.

Changes to address intermittent build failueres

---

2.1/sdk/bionic/arm32v7/Dockerfile
2.1/sdk/buster/arm32v7/Dockerfile
2.1/sdk/stretch/arm32v7/Dockerfile
scripts/update-dependencies/DockerfileShaUpdater.cs
scripts/update-dependencies/Program.cs

- Updated ARM 2.1 Dockerfiles to include the NuGet package cache.
- Updated the update-dependencies tool to handle updating the LZMA sha.
Fixes #546

Add NuGet cache to arm sdk images

---

netci.groovy

Rename the `Debian - * Dockerfiles` CI jobs to `Linux - * Dockerfiles`.  The usage of `Debian` is from the time when the repo only supported Debian distro based images.  The repo now supports multiple distros so a more abstract name is appropriate.

Refactor CI job names

---

tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs

The unit test will fail periodically in the official builds when pulling images from ACR.  This retry logic should help eliminate this issue.

Add retry logic to tests that pull images

---

.vsts-pipelines/builds/microsoft-dotnet-nightly.yml
.vsts-pipelines/builds/microsoft-dotnet-samples.yml

Path filters are only supported in VSTS git repos therefore they are not valid in this repo.  Cleaning them up.

Cleanup unused build triggers

---

.vsts-pipelines/phases/build-all.yml
2.0/runtime/stretch/amd64/Dockerfile

The build matrix introduced here was generated by ImageBuilder - see https://github.com/dotnet/docker-tools/pull/112.  This breaks the build apart into the smallest possible dependency graphs as defined by the intra-repo Dockerfile depencencies.  In practice this cuts the build time in half.

Refactored build matrix to smallest possible legs

---

2.1/aspnetcore-runtime/nanoserver-1709/amd64/Dockerfile
2.1/aspnetcore-runtime/nanoserver-1803/amd64/Dockerfile
2.1/aspnetcore-runtime/nanoserver-sac2016/amd64/Dockerfile
2.2/aspnetcore-runtime/nanoserver-1709/amd64/Dockerfile
2.2/aspnetcore-runtime/nanoserver-1803/amd64/Dockerfile
2.2/aspnetcore-runtime/nanoserver-sac2016/amd64/Dockerfile
3.0/aspnetcore-runtime/nanoserver-1709/amd64/Dockerfile
3.0/aspnetcore-runtime/nanoserver-1803/amd64/Dockerfile
3.0/aspnetcore-runtime/nanoserver-sac2016/amd64/Dockerfile

This PR is a potential fix for issue #677
- 2.1 images for windows declare both environment variables (DOTNET_RUNNING_IN_CONTAINERS and DOTNET_RUNNING_IN_CONTAINER)
- 2.2 and 3.0 images declare only DOTNET_RUNNING_IN_CONTAINER (breaking change)

Consistent environment variable names for DOTNET_RUNNING_IN_CONTAINER

---

samples/aspnetapp/aspnetcore-docker-https-development.md

On Linux, `dotnet user-secrets` will create a lowercase `usersecrets` directory and Linux is case sensitive.

UserSecrets should be lowercase for Linux

---

TAGS.md
manifest.json
scripts/TagsDocumentationTemplate.md

#685 contains the changes to update the Dockerfiles to bring in 2.2-preview2.  I would like to merge this change in first as to preserve the integrity of the `preview1` tags.

Update tagging for 2.2 Preview 2

---

.vsts-pipelines/builds/microsoft-dotnet-samples.yml
.vsts-pipelines/phases/build-all.yml
.vsts-pipelines/phases/build-linux-amd64.yml
.vsts-pipelines/phases/build-linux-arm32v7.yml
.vsts-pipelines/phases/build-windows-amd64.yml
.vsts-pipelines/phases/copy-images-linux.yml
.vsts-pipelines/phases/copy-images-windows.yml
.vsts-pipelines/phases/test-linux-amd64.yml
.vsts-pipelines/phases/test-linux-arm32v7.yml
.vsts-pipelines/phases/test-windows-amd64.yml

Start utilizing the new functionality added to the image builder tool that will emit the matrix.  See https://github.com/dotnet/docker-tools/pull/113 for details.

Add build step to dynamically produce matrix from info in manifest

---

.vsts-pipelines/builds/microsoft-dotnet-samples.yml
.vsts-pipelines/phases/build-all.yml
.vsts-pipelines/phases/build-linux-amd64.yml
.vsts-pipelines/phases/build-linux-arm32v7.yml
.vsts-pipelines/phases/build-windows-amd64.yml
.vsts-pipelines/phases/copy-images-linux.yml
.vsts-pipelines/phases/copy-images-windows.yml
.vsts-pipelines/phases/test-linux-amd64.yml
.vsts-pipelines/phases/test-linux-arm32v7.yml
.vsts-pipelines/phases/test-windows-amd64.yml

This brings in the logic to dynamically produce the build matrix.  This should dramatically reduce the number of times the build needs to be updated as the manifest.json is the single place that defines the metadata the informs the build.

Merge build changes from nightly into master

---

.vsts-pipelines/phases/build-linux-arm32v7.yml
.vsts-pipelines/phases/test-linux-amd64.yml
.vsts-pipelines/phases/test-linux-arm32v7.yml
.vsts-pipelines/steps/docker-cleanup-linux.yml
.vsts-pipelines/steps/docker-init-linux.yml
.vsts-pipelines/steps/docker-init-windows.yml

Our build agents for arm builds aren't doing much because they utilize a remote arm docker daemon for most of the work.  As such we can get by with running multiple agents on a single host to reduce our costs.  In order to do this some build changes are necessary.
@ilyas1974 - I'm proposing two changes within /data/agent/.env of our arm build agents.
1. Duplicate the value of PIIP and call it DOCKER_HOST_IP.  We will eventually remove PIIP, but this PR has to flow to all of our branches first.  PIIP was a poor choice on my part.  DOCKER_HOST_IP is more meaningful and doesn't assume the type of the remote docker machine.
2. Add DOCKER_CERTS_PATH and set the value to the agent specific location on the machine of where the certs are stored.  I think /data/docker-certs/<docker machine name> …

Updates to support multiple build agents running on a single host

---

.vsts-pipelines/steps/docker-cleanup-linux.yml
.vsts-pipelines/steps/docker-init-linux.yml

One more change is needed to be able to run multiple build agent on a single host.  The cleanup logic when invoked during init, shouldn't be doing the full cleanup.  It should only be removing unused local docker resources.
The YAML constructs make this a little ugly.  I am open to suggestions on how to make this cleaner.

Refactor docker-cleanup-linux for remote docker scenarios

---

.vsts-pipelines/builds/microsoft-dotnet-nightly.yml
.vsts-pipelines/builds/microsoft-dotnet-samples.yml
.vsts-pipelines/builds/microsoft-dotnet.yml
.vsts-pipelines/jobs/build-all.yml
.vsts-pipelines/jobs/build-images-linux-client.yml
.vsts-pipelines/jobs/build-images-windows-client.yml
.vsts-pipelines/jobs/copy-images-linux.yml
.vsts-pipelines/jobs/copy-images-windows.yml
.vsts-pipelines/jobs/publish-finalize.yml
.vsts-pipelines/jobs/test-images-linux-client.yml
.vsts-pipelines/jobs/test-images-windows-client.yml
.vsts-pipelines/steps/cleanup-docker-linux.yml
.vsts-pipelines/steps/cleanup-docker-windows.yml
.vsts-pipelines/steps/init-docker-linux.yml
.vsts-pipelines/steps/init-docker-windows.yml

1. Broke all of the long lines down into multiple lines that are more readable.
2. Fixed the indentation of all sequence types to follow the standard yaml format.
If might be easier to view each commit separately.

Build YAML formatting cleanup

---

.vsts-pipelines/jobs/build-test-publish-repo.yml
.vsts-pipelines/jobs/copy-images.yml
.vsts-pipelines/jobs/publish-finalize.yml
.vsts-pipelines/steps/init-docker-linux.yml
.vsts-pipelines/steps/init-docker-windows.yml
3.0/runtime-deps/bionic/arm64v8/Dockerfile
3.0/runtime-deps/stretch-slim/arm64v8/Dockerfile
3.0/runtime/bionic/arm64v8/Dockerfile
3.0/runtime/stretch-slim/arm64v8/Dockerfile
README.md
TAGS.md
manifest.json
scripts/ReadmeTagsDocumentationTemplate.md
scripts/TagsDocumentationTemplate.md
tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs

These are the initial changes to add Linux Arm64 images (runtime and runtime-deps).  The aspnetcore-runtime and sdk images are blocked on product support.
Related to #504

Add support for Linux Arm64

---

3.0/runtime/alpine3.8/amd64/Dockerfile
3.0/runtime/bionic/amd64/Dockerfile
3.0/runtime/bionic/arm32v7/Dockerfile
3.0/runtime/bionic/arm64v8/Dockerfile
3.0/runtime/nanoserver-1709/amd64/Dockerfile
3.0/runtime/nanoserver-1803/amd64/Dockerfile
3.0/runtime/nanoserver-sac2016/amd64/Dockerfile
3.0/runtime/stretch-slim/amd64/Dockerfile
3.0/runtime/stretch-slim/arm32v7/Dockerfile
3.0/runtime/stretch-slim/arm64v8/Dockerfile
3.0/sdk/alpine3.8/amd64/Dockerfile
3.0/sdk/bionic/amd64/Dockerfile
3.0/sdk/bionic/arm32v7/Dockerfile
3.0/sdk/nanoserver-1709/amd64/Dockerfile
3.0/sdk/nanoserver-1803/amd64/Dockerfile
3.0/sdk/nanoserver-sac2016/amd64/Dockerfile
3.0/sdk/stretch/amd64/Dockerfile
3.0/sdk/stretch/arm32v7/Dockerfile
TAGS.md
manifest.json
scripts/Get-TagsDocumentation.ps1
scripts/TagsDocumentationTemplate.md

As part of this change, I dropped the preview # from the headers in the TAGS.md.  IMO the headers should be more stable and not changing every release.  This makes the maintenance easier as well.

Update to latest 3.0; rename 3.0 tags from alpha to preview

---

README.md
TAGS.md
manifest.json
scripts/Get-TagsDocumentation.ps1
scripts/ReadmeTagsDocumentationTemplate.md
scripts/TagsDocumentationTemplate.md

Updated the readme templates to reference the <major>.<minor> tags versus the <major>.<minor>.<patch> tags.  This eases the maintenance as the templates don't have to be updated when picking up new patch versions.  
In order to support this, a new version of the image-builder is used which has dotnet/docker-tools#119.  Along with getting this change comes the new change to not include the Dockerfile path in the readme.  This is to reduce this size of the readme to fit into Docker Hub which has a 25 K limit.

Improve maintainablity of readme templates

---

.vsts-pipelines/jobs/build-images.yml
manifest.json

The manifest.json currently has test instructions specified within it.  These can be invoked when using the ImageBuilder tool.  We no longer use these so they should be cleaned up.

Remove test instructions from manifest

---

README.md
TAGS.md
manifest.json
scripts/ReadmeTagsDocumentationTemplate.md
scripts/TagsDocumentationTemplate.md

Pulling out Readme changes from #772 as it is blocked on product issues.  These changes had to be manually created while the rest of the changes in #772 are generated.

Update readme in preparation for 2.2 RTM

---

.gitignore
build-and-test.ps1
manifest.json
scripts/update-dependencies/ManifestUpdater.cs
scripts/update-dependencies/Program.cs
scripts/update-dependencies/ReadmeUpdator.cs

There are three parts to these changes:
1. Update the manifest to use variables to encapsulate the full version part of the tag.  This makes it easier to on-board new patches as only one place within the manifest needs to be updated.
2. In order to support variable usage within the manifest tag names, the build-and-test script needs to be updated to use the ImageBuilder tool which supports variable substitution.
3. By using manifest variables to encapsulate the full version, the update-dependencies tool can easily update the versions and regenerate the tags readme.
The end result of these changes is that Maestro will now automatically update everything needed when a new `patch` version is created.

Updates to ease/automate on-boarding new patch versions

---

netci.groovy

Windows 2.1 and 2.2 CI jobs can be run independently.  Linux 2.1 and 2.2 CI jobs must be run together because a common runtime-deps image is shared between the two versions.

Break Windows CI apart into smaller jobs

---

.vsts-pipelines/jobs/build-images.yml
.vsts-pipelines/jobs/build-test-publish-repo.yml
.vsts-pipelines/jobs/copy-images.yml
.vsts-pipelines/jobs/publish-finalize.yml
.vsts-pipelines/jobs/test-images-linux-client.yml
.vsts-pipelines/jobs/test-images-windows-client.yml
.vsts-pipelines/steps/cleanup-docker-windows.yml
.vsts-pipelines/steps/init-docker-windows.yml

The workspace cleanup logic is failing to cleanup consistently.  Refactored the build logic to cleanup the ImageBuilder tool which is the reason for using the built-in cleanup in the first place.

Remove use of workspace clean within builds as it is not reliable

---

3.0/aspnetcore-runtime/bionic/arm64v8/Dockerfile
3.0/aspnetcore-runtime/stretch-slim/arm64v8/Dockerfile
TAGS.md
manifest.json
scripts/TagsDocumentationTemplate.md

AspNetCore recently started producing Arm64 builds which now enables the production of the aspnetcore-runtime arm64 images.
Related #504

Add 3.0 aspnetcore-runtime arm64 images

---

tests/Microsoft.DotNet.Docker.Tests/ImageData.cs
tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs

Related #692
There are still a number of disabled tests that are blocked on product issues.

Enable tests on 3.0 images

---

tests/Microsoft.DotNet.Docker.Tests/Arch.cs
tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
tests/Microsoft.DotNet.Docker.Tests/Dockerfile.linux.testapp
tests/Microsoft.DotNet.Docker.Tests/ImageData.cs
tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/ImageVersion.cs

Refactor the ImageData class used in the tests.
- version properties are of type `Version`
- architecture is an enum
- compute sdkOs versus defining it
- shorten member names
- reformat test data declaration to be more readable
- misc cleanup

[TEST] Refactor ImageData to be more strongly typed

---

2.1/aspnetcore-runtime/alpine3.7/amd64/Dockerfile
2.1/aspnetcore-runtime/bionic/amd64/Dockerfile
2.1/aspnetcore-runtime/bionic/arm32v7/Dockerfile
2.1/aspnetcore-runtime/nanoserver-1709/amd64/Dockerfile
2.1/aspnetcore-runtime/nanoserver-1803/amd64/Dockerfile
2.1/aspnetcore-runtime/nanoserver-sac2016/amd64/Dockerfile
2.1/aspnetcore-runtime/stretch-slim/amd64/Dockerfile
2.1/aspnetcore-runtime/stretch-slim/arm32v7/Dockerfile
2.1/runtime/alpine3.7/amd64/Dockerfile
2.1/runtime/bionic/amd64/Dockerfile
2.1/runtime/bionic/arm32v7/Dockerfile
2.1/runtime/nanoserver-1709/amd64/Dockerfile
2.1/runtime/nanoserver-1803/amd64/Dockerfile
2.1/runtime/nanoserver-sac2016/amd64/Dockerfile
2.1/runtime/stretch-slim/amd64/Dockerfile
2.1/runtime/stretch-slim/arm32v7/Dockerfile
2.1/sdk/alpine3.7/amd64/Dockerfile
2.1/sdk/bionic/amd64/Dockerfile
2.1/sdk/bionic/arm32v7/Dockerfile
2.1/sdk/nanoserver-1709/amd64/Dockerfile
2.1/sdk/nanoserver-1803/amd64/Dockerfile
2.1/sdk/nanoserver-sac2016/amd64/Dockerfile
2.1/sdk/stretch/amd64/Dockerfile
2.1/sdk/stretch/arm32v7/Dockerfile
2.2/runtime-deps/alpine3.8/amd64/Dockerfile
README.md
TAGS.md
manifest.json
scripts/ReadmeTagsDocumentationTemplate.md
scripts/TagsDocumentationTemplate.md

CI is expected to fail until 2.1.6 is released.

Updates for 2.1.6

---

.vsts-pipelines/steps/cleanup-docker-linux.yml
.vsts-pipelines/steps/init-docker-linux.yml
.vsts-pipelines/steps/init-docker-windows.yml

- Update image-builder to pickup https://github.com/dotnet/docker-tools/pull/127
- Refactor remote Docker cleanup logic to preserve base images.  This really helps with slow arm machines.

Update image-builder and tweak remote docker cleanup

---

3.0/runtime-deps/bionic/amd64/Dockerfile
3.0/runtime-deps/bionic/arm32v7/Dockerfile
3.0/runtime-deps/bionic/arm64v8/Dockerfile
3.0/runtime-deps/stretch-slim/amd64/Dockerfile
3.0/runtime-deps/stretch-slim/arm32v7/Dockerfile
3.0/runtime-deps/stretch-slim/arm64v8/Dockerfile
3.0/sdk/bionic/amd64/Dockerfile
3.0/sdk/bionic/arm32v7/Dockerfile
3.0/sdk/bionic/arm64v8/Dockerfile
3.0/sdk/stretch/amd64/Dockerfile
3.0/sdk/stretch/arm32v7/Dockerfile
3.0/sdk/stretch/arm64v8/Dockerfile

Alpine is still on 1.0 as libssl1.1 is not yet released.
related to #797

Update libssl runtime dependency to 1.1

---

2.1/sdk/stretch/amd64/Dockerfile
2.2/sdk/stretch/amd64/Dockerfile
3.0/sdk/bionic/arm32v7/Dockerfile
3.0/sdk/bionic/arm64v8/Dockerfile
3.0/sdk/stretch/amd64/Dockerfile
3.0/sdk/stretch/arm32v7/Dockerfile
3.0/sdk/stretch/arm64v8/Dockerfile

Fixes #793
As part of this I noticed a couple errant Dockerfiles that had rogue `sha512sum` calls.  I included the necessary cleanup changes for these as well.

Remove lzma cache from 3.0 arm images

---

3.0/sdk/alpine3.8/amd64/Dockerfile
3.0/sdk/bionic/amd64/Dockerfile
3.0/sdk/bionic/arm32v7/Dockerfile
3.0/sdk/bionic/arm64v8/Dockerfile
3.0/sdk/nanoserver-1709/amd64/Dockerfile
3.0/sdk/nanoserver-1803/amd64/Dockerfile
3.0/sdk/nanoserver-1809/amd64/Dockerfile
3.0/sdk/nanoserver-sac2016/amd64/Dockerfile
3.0/sdk/stretch/amd64/Dockerfile
3.0/sdk/stretch/arm32v7/Dockerfile
3.0/sdk/stretch/arm64v8/Dockerfile

The _first run_ comment in the 3.0 SDK dockerfiles is out of date with the removal of the NuGet package cache.  The comment was updated appropriately.
Related #793

Update sdk first run comment

---

tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs

Enable 3.0 Linux ARM32 tests now that https://github.com/dotnet/cli/issues/10291 is fixed.  Updated the current issue that is blocking the ASP.NET Core tests.
Related to #692

Enable 3.0 tests previously blocked by product issues

---

README.md
TAGS.md
scripts/ReadmeTagsDocumentationTemplate.md
scripts/TagsDocumentationTemplate.md

Currently we list all amd tags first since it has the most usage
- Linux amd64 tags
- Windows Server, version 1809 amd64 tags
- Windows Server 2016, version 1709, and version 1803 amd64 tags
- Linux arm64 tags
- Linux arm32 tags
- Windows Server, version 1809 arm32 tags
I believe the mixture of Linux on Windows tags may get confusing.  I conjecture it would be better to group all OS tags.  I don't recommend having an OS header (e.g. `Linux` and `Windows`) for two reasons.  First, the `Linux` section will easily fill the entire screen therefore you will lose this context.  Second, Docker Hub's poor markdown rendering only has two headers that are differentiable (e.g. # and ##).  We already have a `Tags` parent header.
- Linux amd64 tags
- Linux arm64 tags
- Linux arm32 tags
- Windows …

Group all linux and windows platforms in the tags documentation

---

2.1/aspnetcore-runtime/bionic/amd64/Dockerfile
2.1/aspnetcore-runtime/bionic/arm32v7/Dockerfile
2.1/aspnetcore-runtime/nanoserver-1809/amd64/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/Dockerfile.windows.testapp

- Removed extra WS from 2.1 ASP.NET Core Dockerfiles
- Added `DOTNET_RUNNING_IN_CONTAINERS` to the nanoserver-1809 2.1 ASP.NET Core Dockerfile to provide alignment with other nanoserver 2.1 Dockerfiles 
- Modified a test Dockerfile to work in master when no additional NuGet feeds are specified.

Misc cleanup

---

3.0/aspnetcore-runtime/nanoserver-1809/arm32/Dockerfile
3.0/sdk/nanoserver-1809/arm32/Dockerfile
TAGS.md
manifest.json
scripts/TagsDocumentationTemplate.md

Finish adding the 3.0 Windows ARM32 images - this includes the sdk and aspnetcore-runtime images.

Add 3.0 images for Windows ARM32

---

README.md
TAGS.md
scripts/Get-TagsDocumentation.ps1
scripts/ReadmeTagsDocumentationTemplate.md
scripts/TagsDocumentationTemplate.md

Docker Hub's markdown rendering used to render '##' headers with a larger font than '#' headers therefore the readme worked around that.  This has changed recently therefore the readme was adjusted accordingly.
I uploaded the readme to my [personal Docker Hub repository](https://hub.docker.com/r/msimons/dotnet) so you can see what it looks like.

Update headers in readme due to markdown rendering changed in Docker Hub

---

2.2/sdk/nanoserver-1809/arm32/Dockerfile

This is already done for the Linux arm images.  This isn't needed post 3.0 because of the ref assemblies feature.

Add lzma to pre 3.0 Windows arm images since it isn't included by default

---

3.0/runtime-deps/alpine3.8/amd64/Dockerfile
3.0/runtime-deps/bionic/amd64/Dockerfile
3.0/runtime-deps/bionic/arm32v7/Dockerfile
3.0/runtime-deps/bionic/arm64v8/Dockerfile
3.0/runtime-deps/stretch-slim/amd64/Dockerfile
3.0/runtime-deps/stretch-slim/arm32v7/Dockerfile
3.0/runtime-deps/stretch-slim/arm64v8/Dockerfile
3.0/sdk/bionic/amd64/Dockerfile
3.0/sdk/bionic/arm32v7/Dockerfile
3.0/sdk/bionic/arm64v8/Dockerfile
3.0/sdk/stretch/amd64/Dockerfile
3.0/sdk/stretch/arm32v7/Dockerfile
3.0/sdk/stretch/arm64v8/Dockerfile

Liblttng (and it's dependency userspacercu) are not actually required to build or run .NET Core applications. They are only required when building the CoreCLR product.
Liblttng is an optional component that can be used alongside lttng-tools to collect tracing data from running .NET Core applications. Removing liblttng saves some disk space (~1MB on alpine). Given that it can't be used on its own without lttng-tools, there isn't a reason to have it built into the image. We should remove it to help those who are striving for super-small images.
cc: @richlander

Remove LTTng Dependency from Images

---

2.1/aspnet/nanoserver-1709/amd64/Dockerfile
2.1/aspnet/nanoserver-1803/amd64/Dockerfile
2.1/aspnet/nanoserver-1809/amd64/Dockerfile
2.1/runtime/nanoserver-1709/amd64/Dockerfile
2.1/runtime/nanoserver-1803/amd64/Dockerfile
2.1/runtime/nanoserver-1809/amd64/Dockerfile
2.1/sdk/nanoserver-1709/amd64/Dockerfile
2.1/sdk/nanoserver-1803/amd64/Dockerfile
2.1/sdk/nanoserver-1809/amd64/Dockerfile
2.2/aspnet/nanoserver-1709/amd64/Dockerfile
2.2/aspnet/nanoserver-1803/amd64/Dockerfile
2.2/aspnet/nanoserver-1809/amd64/Dockerfile
2.2/runtime/nanoserver-1709/amd64/Dockerfile
2.2/runtime/nanoserver-1803/amd64/Dockerfile
2.2/runtime/nanoserver-1809/amd64/Dockerfile
2.2/sdk/nanoserver-1709/amd64/Dockerfile
2.2/sdk/nanoserver-1803/amd64/Dockerfile
2.2/sdk/nanoserver-1809/amd64/Dockerfile
3.0/aspnet/nanoserver-1709/amd64/Dockerfile
3.0/aspnet/nanoserver-1803/amd64/Dockerfile
3.0/aspnet/nanoserver-1809/amd64/Dockerfile
3.0/runtime/nanoserver-1709/amd64/Dockerfile
3.0/runtime/nanoserver-1803/amd64/Dockerfile
3.0/runtime/nanoserver-1809/amd64/Dockerfile
3.0/sdk/nanoserver-1709/amd64/Dockerfile
3.0/sdk/nanoserver-1803/amd64/Dockerfile
3.0/sdk/nanoserver-1809/amd64/Dockerfile

The Windows Dockerfiles were inconsistently using rooted paths in the COPY syntax.  These changes ensure a consistent pattern is used and eliminates the need to escape the back slashes by using forward slashes.  I decided to also simplify the name of the installer phase since the multi-phase Dockerfiles are already being editted.  The dash in the name hurts the readability IMO.

Refactor COPY syntax to use rooted source

---

build-and-test.ps1
scripts/Invoke-ImageBuilder.ps1
tests/performance/ImageSize.nightly.linux.json
tests/performance/ImageSize.nightly.windows.json
tests/performance/Validate-ImageSize.ps1

Depends on https://github.com/dotnet/docker-tools/pull/141.  Once that PR is merged, the image-builder version will need to be updated in this PR.

Add tests to detect regressions in the size of the images

---

2.2/aspnetcore-runtime/nanoserver-1809/arm32/Dockerfile
2.2/runtime/nanoserver-1809/arm32/Dockerfile
2.2/sdk/nanoserver-1809/arm32/Dockerfile
3.0/aspnetcore-runtime/nanoserver-1809/arm32/Dockerfile
3.0/runtime/nanoserver-1809/arm32/Dockerfile
3.0/sdk/nanoserver-1809/arm32/Dockerfile

This is needed because windows stopped servicing their old tagging schema.

Update nanoserver-arm tag references to newest convention

---

.vsts-pipelines/jobs/test-images-linux-client.yml
.vsts-pipelines/jobs/test-images-windows-client.yml

This is a workaround for #938.  We will need a better long term solution that preserves the retry logic.
While investigating this, I realized docker logout was not being called correctly so I corrected that issue as well.

Fix regression in docker login within build test legs

---

.vsts-pipelines/builds/dotnet-nightly-size-validation.yml
.vsts-pipelines/builds/dotnet-nightly.yml
.vsts-pipelines/builds/dotnet-samples.yml
.vsts-pipelines/builds/dotnet.yml
.vsts-pipelines/builds/update-dependencies.yml

This eliminates the need for any settings in the build definitions which I forgot in the build size validation build def.

Disable PR validation in build definitions

---

tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs

The product issues that were blocking this scenario have been fixed.

Enable nanoserver-1809 arm tests for 3.0

---

scripts/Invoke-ImageBuilder.ps1

In the Windows scenario, a container may not be created when Invoke-ImageBuilder.ps1 is invoked.  So it should not attempt to remove a container in the `finally` block.  Fixed this by adding a flag which is set when the script has created the container and checking the flag before removing the container.

Fix Invoke-ImageBuilder for Windows scenario

---

.vsts-pipelines/jobs/copy-images.yml
.vsts-pipelines/jobs/test-images-linux-client.yml
.vsts-pipelines/jobs/test-images-windows-client.yml

Quick fix to unblock the samples build.  This logic is for skipping the test phase when building the samples. 
During the MCR work (in nightly) the repo variable was removed.   This code path wasn't exercised until it was merged into master.

Update build to fix issues with tests not getting skipped for samples

---

.vsts-pipelines/steps/init-docker-linux.yml
.vsts-pipelines/steps/init-docker-windows.yml
scripts/Invoke-ImageBuilder.ps1

This is so that we can take advantage of the changes in dotnet/docker-tools#152.

Update to use latest ImageBuilder

---

scripts/update-dependencies/Options.cs
scripts/update-dependencies/Program.cs

This change makes the update-dependencies tool easy to use for devs outside of Maestro.  Without this change you have to construct a custom build-info.xml file.  This allows you to do something like the following instead: 
`dotnet update-dependencies.dll --sdk-version 3.01`

Refactor update-dependencies to support passing version #s on cmd line

---

.vsts-pipelines/builds/dotnet-nightly-size-validation.yml
.vsts-pipelines/builds/dotnet-nightly.yml
.vsts-pipelines/builds/dotnet-samples.yml
.vsts-pipelines/builds/dotnet.yml
.vsts-pipelines/builds/update-dependencies.yml
.vsts-pipelines/jobs/build-images.yml
.vsts-pipelines/jobs/build-test-publish-repo.yml
.vsts-pipelines/jobs/copy-images.yml
.vsts-pipelines/steps/init-docker-linux.yml
.vsts-pipelines/steps/init-docker-windows.yml
manifest.samples.json
scripts/Invoke-ImageBuilder.ps1

- Pull in newest image builder with fix for building samples - see https://github.com/dotnet/docker-tools/pull/155
- Add dependent variable groups into pipeline yaml
- Simplify multi-line demands
- Simplify dockerfile paths in samples manifest and make them consistent with the main manifest.  Just like with the docker cli, 'dockerfile' is optional if your Dockerfile is named 'dockerfile'
- Fix issue with update-dependencies build definition caused by https://github.com/dotnet/dotnet-docker/pull/961.  build-info is now a named optional arg.

Fixup build to work with Samples repo and misc build cleanup

---

2.1/runtime/nanoserver-1709/amd64/Dockerfile
2.1/runtime/nanoserver-1803/amd64/Dockerfile
2.1/runtime/nanoserver-1809/amd64/Dockerfile
2.1/sdk/nanoserver-1709/amd64/Dockerfile
2.1/sdk/nanoserver-1803/amd64/Dockerfile
2.1/sdk/nanoserver-1809/amd64/Dockerfile
2.2/aspnet/nanoserver-1809/arm32/Dockerfile
2.2/runtime/nanoserver-1709/amd64/Dockerfile
2.2/runtime/nanoserver-1803/amd64/Dockerfile
2.2/runtime/nanoserver-1809/amd64/Dockerfile
2.2/runtime/nanoserver-1809/arm32/Dockerfile
2.2/sdk/nanoserver-1709/amd64/Dockerfile
2.2/sdk/nanoserver-1803/amd64/Dockerfile
2.2/sdk/nanoserver-1809/amd64/Dockerfile
2.2/sdk/nanoserver-1809/arm32/Dockerfile
3.0/runtime/nanoserver-1709/amd64/Dockerfile
3.0/runtime/nanoserver-1803/amd64/Dockerfile
3.0/runtime/nanoserver-1809/amd64/Dockerfile
3.0/sdk/nanoserver-1709/amd64/Dockerfile
3.0/sdk/nanoserver-1803/amd64/Dockerfile
3.0/sdk/nanoserver-1809/amd64/Dockerfile
3.0/sdk/nanoserver-1809/arm32/Dockerfile

There is a trailing space that has been getting copied with each new version...time to clean things up.

Whitespace cleanup

---

2.2/aspnet/nanoserver-1809/arm32v7/Dockerfile
2.2/runtime/nanoserver-1809/arm32v7/Dockerfile
2.2/sdk/nanoserver-1809/arm32v7/Dockerfile
3.0/aspnet/nanoserver-1809/arm32v7/Dockerfile
3.0/runtime/nanoserver-1809/arm32v7/Dockerfile
3.0/sdk/nanoserver-1809/arm32v7/Dockerfile
README.aspnet.md
README.runtime.md
README.samples.md
README.sdk.md
manifest.json
manifest.samples.json
scripts/documentation-templates/aspnet-tags.md
scripts/documentation-templates/runtime-tags.md
scripts/documentation-templates/samples-tags.md
scripts/documentation-templates/sdk-tags.md

Fixes #983
This to be done as the Windows team are not going to be updating the old tags.  We will be preserving the old 2.2-arm32 tags as undocumented tags.  Since 3.0 is in preview, the old tags will not be preserved.

Update Windows arm tagging to match base OS tagging

---

README.aspnet.md
README.md
README.runtime-deps.md
README.runtime.md
README.samples.md
README.sdk.md
samples/README.md
samples/aspnetapp/README.md
samples/dotnetapp/README.md
samples/dotnetapp/dotnet-docker-selfcontained.md

There changes are mostly about updating the microsoft/dotnet-framework references in response to https://github.com/Microsoft/dotnet-framework-docker/pull/235.  While making these changes, I found a couple other Docker Hub references that needed updating as well.

Replace old Docker Hub references with MCR references

---

.vsts-pipelines/jobs/build-images.yml

The samples build is failing for arm32 Linux leg because the build agents have an architecture of aarch64 and the multi-arch manifest description doesn't have a matching architecture for the 2.2 SDK and runtime images that we reference.  To fix this, we eventually want to make use of the `--platform` option on the Docker CLI to explicitly set what platform we want to get but that's only available in experimental mode.  To workaround this, we are going to modify the Dockerfile dynamically so it uses the platform-specific tag for the image instead of the 2.2 flag.

Rewrite Dockerfile for arm32 Linux samples

---

.vsts-pipelines/builds/version-monitor.yml

This is a port of a modeled build that exists today to monitor the Docker version dependencies this repo depends on so that automatic builds will get triggered as base images are updated.

Add version monitor build pipeline

---

tests/performance/ImageSize.nightly.linux.json
tests/performance/ImageSize.nightly.windows.json

A few 3.0 size baseline changes after merging the latest 3.0 in last week.

Update 3.0 perf baseline

---

.vsts-pipelines/jobs/build-test-publish-repo.yml
.vsts-pipelines/steps/generate-matrix.yml
.vsts-pipelines/variables/docker-images.yml

Reference the newest version of ImageBuilder which has renamed the matrix types when generating a matrix.  As part of these changes, I've factored out the identifiers for those matrix types into parameters such that they map to the particular jobs that are being execute (i.e. build, test, publish).  The matrix values are then referenced dynamically by referencing the appropriate parameter.  This was done in order to better position things for better support for the PR build refactoring that will require the ability to dynamically select which matrix type will be used for the build jobs.  I would have preferred using variables defined in common.yml for defining these matrix type mappings instead of parameters but it wasn't possible due to limitations in AzDO with being able to use …

Reference new version of image builder

---

2.1/runtime-deps/alpine3.9/amd64/Dockerfile
2.2/runtime-deps/alpine3.8/amd64/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs

1. Update the 3.8 alpine runtime-deps image to pull lttng-ust from the main package feed vs edge.
2. Update the 3.8 and 3.9 alpine runtime-deps Dockerfile formatting to follow the Dockerfile best practices.

Update alpine runtime-deps to get lttng-ust from main package feed

---

3.0/aspnet/alpine3.9/amd64/Dockerfile
3.0/aspnet/bionic/amd64/Dockerfile
3.0/aspnet/bionic/arm32v7/Dockerfile
3.0/aspnet/bionic/arm64v8/Dockerfile
3.0/aspnet/nanoserver-1803/amd64/Dockerfile
3.0/aspnet/nanoserver-1809/amd64/Dockerfile
3.0/aspnet/stretch-slim/amd64/Dockerfile
3.0/aspnet/stretch-slim/arm32v7/Dockerfile
3.0/aspnet/stretch-slim/arm64v8/Dockerfile
3.0/runtime/alpine3.9/amd64/Dockerfile
3.0/runtime/bionic/amd64/Dockerfile
3.0/runtime/bionic/arm32v7/Dockerfile
3.0/runtime/bionic/arm64v8/Dockerfile
3.0/runtime/nanoserver-1803/amd64/Dockerfile
3.0/runtime/nanoserver-1809/amd64/Dockerfile
3.0/runtime/stretch-slim/amd64/Dockerfile
3.0/runtime/stretch-slim/arm32v7/Dockerfile
3.0/runtime/stretch-slim/arm64v8/Dockerfile
3.0/sdk/alpine3.9/amd64/Dockerfile
3.0/sdk/bionic/amd64/Dockerfile
3.0/sdk/bionic/arm32v7/Dockerfile
3.0/sdk/bionic/arm64v8/Dockerfile
3.0/sdk/nanoserver-1803/amd64/Dockerfile
3.0/sdk/nanoserver-1809/amd64/Dockerfile
3.0/sdk/stretch/amd64/Dockerfile
3.0/sdk/stretch/arm32v7/Dockerfile
3.0/sdk/stretch/arm64v8/Dockerfile

The Windows arm32 Dockerfile aren't being updated because the latest bits surface a docker issue that is being investigated separately.

Update to latest 3.0 (excluding windows arm32)

---

3.0/aspnet/nanoserver-1809/arm32v7/Dockerfile
3.0/runtime/nanoserver-1809/arm32v7/Dockerfile
3.0/sdk/nanoserver-1809/arm32v7/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs
tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.windows.arm

These changes include a test workaround for issue #1054.  Once the underlying Windows/Docker issue gets resolved, the workaround can be removed.

Update 3.0 Windows Arm32 images and Add test workaround for Docker issue

---

tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.windows.arm

The original Dockerfile pattern is used because it is what we recommend when building locally where you build numerous time and would benefit from restoring in a separate layer (establishing cached layer).  Because of the intermittent Docker ARM described in issue (#1054), I am simplifying the Dockerfile to help reduce the chances of encountering this failure.
@dotnet-bot skip CI please.

Simplification of Windows Arm test Dockerfile to eliminate flakiness

---

samples/aspnetapp/Directory.Build.props
samples/dotnetapp/Directory.Build.props
samples/dotnetapp/dotnet-docker-dev-in-container.md

Changing `BaseIntermediateOutputPath` prevents "dotnet ef" from working.
Resolves aspnet/EntityFrameworkCore#12220
cc @richlander @divega @ajcvickers

Sample: Use default bin and obj directories locally

---

.vsts-pipelines/jobs/build-images.yml
.vsts-pipelines/jobs/build-test-publish-repo.yml

Fixes #373 
The 2.2 Windows Arm leg tags ~90 minutes.  Getting this checked in will allow us to more easily iterate on trying out changes to improve this time in addition to getting better hardware (hummingboards).

Enable PR validation for Arm32 images

---

.vsts-pipelines/steps/test-images-linux-client.yml

The builds are leaking the test runner container as a result of this.

Cleanup test runner container

---

3.0/runtime-deps/alpine3.9/arm64v8/Dockerfile
3.0/runtime/alpine3.9/arm64v8/Dockerfile
README.runtime-deps.md
README.runtime.md
manifest.json
scripts/documentation-templates/runtime-deps-tags.md
scripts/documentation-templates/runtime-tags.md
tests/Microsoft.DotNet.Docker.Tests/ImageData.cs
tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/OS.cs

This set of changes introduces only a runtime image. There aren't product builds available yet for ASP.NET Core and SDK.
Related to #360

Add 3.0 Alpine arm64v8 images

---

.vsts-pipelines/jobs/build-test-publish-repo.yml
.vsts-pipelines/variables/common.yml

Ensure that the Component Detection task is only executed once for the entire build.  Currently it gets run in every job which is not necessary.  These changes explicitly add it to one job and sets a variable to ensure it is not automatically added to other jobs.  Note that these changes only need to be done for builds on the master branch since the auto-injected task is only done for the default branch of repos.

Explicitly add Component Detection task

---

.vsts-pipelines/builds/update-dependencies-from-drop.yml
.vsts-pipelines/builds/update-dependencies-from-versions.yml
scripts/get-drop-versions.sh

Extracts the runtime, SDK, and ASP.NET versions from the SDK.zip file and passes those values to the update dependencies tool.  The channel to target is defined as a build argument.

Add pipeline for updating .NET Core dependencies from drop location

---

samples/aspnetapp/Directory.Build.props
samples/dotnetapp/Directory.Build.props
samples/dotnetapp/dotnet-docker-dev-in-container.md

* Use default bin and obj directories locally
Changing BaseIntermediateOutputPath prevents "dotnet ef" from working.
Resolves aspnet/EntityFrameworkCore#12220
* Update dotnet-docker-dev-in-container.md

Sample: Use default bin and obj directories locally (#1033)

---

.vsts-pipelines/stages/build-test-publish-repo.yml

During build stage of the pipeline, the pipeline cannot be cancelled.  Things will keep right on running until all the jobs in the stage have finished.  This is due to a `succeeded()` check missing in the condition of the build stage.  Adding this to the condition fixes the issue.

Allow builds to be cancelled

---

.vsts-pipelines/stages/build-test-publish-repo.yml

During build stage of the pipeline, the pipeline cannot be cancelled. Things will keep right on running until all the jobs in the stage have finished. This is due to a succeeded() check missing in the condition of the build stage. Adding this to the condition fixes the issue.
Cherry pick of 4879e9a

Add succeeded check to build stage (#1117)

---

manifest.json

These tags should have been removed from the manifest a while ago.  Since they are undocumented tags, there is no reason to produce new versions whenever .NET Core is patched.  Customers are expected to migrate to a documented tag in this scenario.

Remove undocumented versioned windows arm tags

---

scripts/get-drop-versions.sh

In order to allow us to target releases for the master branch of .NET Core SDK for the update-dependencies-from-drop pipeline, we need to update the URL that is called by the script. The master branch doesn't use "release" in the path. So we'll baseline it to support master and then for other branches, we'll prepend "release/" in the pipeline variable.

Change URL path for get-drops-version script

---

tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/NuGet.config.nightly

The myget NuGet feed used in the nightly tests is not longer being used.  .NET and ASP.NET now utilize separate feeds.  This is causing the CI failures in https://github.com/dotnet/dotnet-docker/pull/1126

Update the dotnet-core feed used by tests in nightly branch

---

.vsts-pipelines/stages/build-test-publish-repo.yml

This was a side effect of starting the 1903 changes prior to switching from jenkins to Azure Pipelines for PR validation.

Use correct AzDO Pipelines pool for nanoserver-1903 PR validation

---

.vsts-pipelines/variables/docker-images.yml

This brings in the fix for https://github.com/dotnet/docker-tools/pull/190.

Update to latest image-builder

---

.vsts-pipelines/jobs/build-images.yml
.vsts-pipelines/jobs/publish.yml
.vsts-pipelines/steps/init-docker-linux.yml
.vsts-pipelines/steps/init-docker-windows.yml
.vsts-pipelines/variables/common.yml
.vsts-pipelines/variables/docker-images.yml

Updates the build pipeline so that the built images have their image info collected and published to the master image info file.
Here's how the flow works:
1. In the build stage, each build job writes to a file its own image info containing metadata about only the images it just built.  This file is published as a pipeline artifact with a unique name specific to that job so it doesn't conflict with the other jobs.
2. During the publish stage, all of the pipeline artifacts are downloaded and fed into the ImageBuilder command to merge all of the content from the files into the master image info file.
Notes:
* In order to get files into and out of the container that ImageBuilder runs in, a volume mount is used that maps to the $(Build.ArtifactStagingDirectory) of the build agent.
* In order …

Publish image info

---

eng/common/templates/stages/build-test-publish-repo.yml
eng/pipelines/dotnet-core-nightly.yml

The build pipeline was failing to parse because it was referencing parameter names that weren't defined.  Fixed the names of the build timeout variables in build-test-publish-repo.yml.  Also updated the nightly build to use longer timeout for Windows ARM legs in public build.

Fix build timeout variable in pipeline yaml.

---

eng/common/templates/steps/test-images-linux-client.yml
eng/common/templates/steps/test-images-windows-client.yml

As part of merging the common engineering infra to dotnet-framework-docker, I discovered a difference between the two repos in how filters are specified in tests.  The dotnet-framework-docker repo had the wildcard character removed from the VersionFilter parameter.  This ensured that you could run tests for just '4.7' and not end up including '4.7.x'.  So I'm incorporating that difference here.

 Remove wildcards from filters in test steps

---

3.0/sdk/alpine3.9/amd64/Dockerfile
3.0/sdk/bionic/amd64/Dockerfile
3.0/sdk/bionic/arm32v7/Dockerfile
3.0/sdk/bionic/arm64v8/Dockerfile
3.0/sdk/buster/amd64/Dockerfile
3.0/sdk/buster/arm32v7/Dockerfile
3.0/sdk/buster/arm64v8/Dockerfile
3.0/sdk/disco/amd64/Dockerfile
3.0/sdk/disco/arm32v7/Dockerfile
3.0/sdk/disco/arm64v8/Dockerfile
3.0/sdk/nanoserver-1803/amd64/Dockerfile
3.0/sdk/nanoserver-1809/amd64/Dockerfile
3.0/sdk/nanoserver-1809/arm32v7/Dockerfile
3.0/sdk/nanoserver-1903/amd64/Dockerfile

The release uses netcore 3.0 and has the fix for https://github.com/OneGet/oneget/pull/443 and resolves: https://github.com/dotnet/dotnet-docker/issues/1069#issuecomment-489744320

Update PowerShell to v7.0.0-preview.1

---

eng/common/templates/jobs/publish.yml
eng/common/templates/steps/download-build-artifact.yml

It is invalid for Azure Pipeline YAML files to use condition attributes for a reference to a template.  This was being done in publish.yml and causing a parsing failure.  Unfortunately, we need to know the value of a variable and YAML pipelines don't allow you to pass custom variables as parameter values.  Instead, I've introduced a requiresPublicRepoPrefix to the download-build-artifact template that works around this problem.  It's not pretty but I can't think of a better option due to the limitations with YAML pipelines.

Remove invalid condition from download-build-artifact template ref

---

eng/common/templates/jobs/build-images.yml
eng/common/templates/steps/init-docker-linux.yml
eng/common/templates/steps/init-docker-windows.yml
tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
tests/Microsoft.DotNet.Docker.Tests/ImageData.cs
tests/Microsoft.DotNet.Docker.Tests/Microsoft.DotNet.Docker.Tests.csproj
tests/run-tests.ps1

In order to support https://github.com/dotnet/docker-tools/issues/218, these changes update the test code to account for not having all images required by the test available in the staging ACR location.  In that case, the test will pull them directly from MCR.
Also needed to make some changes to the pipeline.  These are ugly but necessary due to issues dealing with multi-line variables in the pipeline YAML stuff.

Update tests to support dynamically pulling missing images

---

tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs
tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.linux
tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.windows

The primary change here is to utilize the `--no-restore` option in several places where restoring is unnecessary.
Fixes #1078

Minor tweaks to speed up tests

---

tests/Dockerfile.linux.testrunner

This to be a leftover after the refactoring of the common eng infra.

Remove obsolete Dockerfile.linux.testrunner

---

.dockerignore

I noticed on the official build machines the build context was ~600MB.  It was taking well over a minute to run the `Build Image for Image Builder` step.  With this change the build context is 3.24MB and the step takes ~15-17s.

Update dockerignore to reduce size of Docker context during official builds

---

.dockerignore

The `.git` directory cannot be excluded because the update-dependencies tool has a dependency on it (https://github.com/dotnet/dotnet-docker/blob/master/eng/pipelines/update-dependencies-from-drop.yml#L12).  The long term solution for this is https://github.com/moby/moby/issues/12886 or possibly BuildKit which lazy loads only the build context items that are referenced.

Revert .dockerignore change to exclude .git directory

---

eng/common/readme.md
eng/common/templates/jobs/build-images.yml
eng/common/templates/jobs/post-build.yml
eng/common/templates/jobs/publish.yml
eng/common/templates/stages/build-test-publish-repo.yml
eng/common/templates/steps/download-build-artifact.yml
eng/common/templates/steps/init-docker-linux.yml
eng/common/templates/steps/init-docker-windows.yml
eng/common/templates/steps/test-images-linux-client.yml
eng/common/templates/steps/test-images-windows-client.yml
eng/common/templates/variables/common.yml
eng/common/templates/variables/docker-images.yml
tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
tests/Microsoft.DotNet.Docker.Tests/ImageData.cs
tests/Microsoft.DotNet.Docker.Tests/Microsoft.DotNet.Docker.Tests.csproj
tests/run-tests.ps1

Integrates eng/common from the nightly branch as well as the associated test project changes (#1217).  We don't want to actually roll out test changes in #1217 to master yet though.  This has been explicitly disabled in the run-tests.ps1 file by ensuring the image info path is not set.  This will prevent the tests from attempting to pull any image that doesn't exist locally.  This is just a precaution for the master branch while we evaluate the test functionality in nightly.
I've preserved the commits in the PR so that the changes being applied can be viewed separately.

Integrate eng/common

---

eng/common/Invoke-CleanupDocker.ps1

Pulling ImageBuilder in the Windows legs of official builds take about 2 minutes.  This is primarily because the base OS image isn't cached locally.  This change will avoid cleaning up the image and therefore will avoid re-pulling it in each build leg.
This optimization applies only to non-hosted agents and is really only an issue for Windows because of the large os images.

Refactor Invoke-CleanupDocker.ps1 to preserve the eng infra images to avoid re-pulls

---

eng/common/templates/jobs/publish.yml

When the different .NET Docker repos build images and publish the results to the [image-info.json](https://github.com/dotnet/versions/blob/master/build-info/docker/image-info.json) file, it is possible they can be overwriting data if not all of the repos are using the same image info schema.  In addition, it'd also be beneficial from a readability perspective, to view the image info content for just a single GitHub repo.
For those reasons, we're going to split the existing [image-info.json](https://github.com/dotnet/versions/blob/master/build-info/docker/image-info.json) into a set of image info files, each one specific to a particular GitHub repo and branch.  Until this is completely rolled out, we're going to maintain the original image info file but also introduce each of these new …

Publish branch-specific image info file

---

eng/pipelines/dotnet-core.yml

Fixes #1314 
The current Windows ARM build legs for CI are taking ~30 min which is well under the default 60 min timeout.

Adjust timeout for Windows arm build leg

---

samples/aspnetapp/aspnet-docker-dev-in-container.md

Because of the changes in #1322, the ASP.NET development scenario docs do not work; the site is not accessible in the browser.  These changes fix the documentation to explicitly set the ASPNETCORE_URLS so that the site will be accessible.
Fixes #1331

Fix ASP.NET dev sample docs to use ASPNETCORE_URLS

---

README.samples.md
manifest.samples.json
samples/aspnetapp/Dockerfile.linux-arm32
samples/dotnetapp/Dockerfile.linux-arm32

The Linux ARM32 Docker images for the sample images cause an error when trying to run them: `standard_init_linux.go:211: exec user process caused "exec format error"`.   This is because the images are actually built targeting ARM64.  The Dockerfiles are authored to use the multi-arch tag of `3.0` but since the build is being run on an AArch64 machine, it's actually pulling down ARM64 base images, not ARM32.  This is fixed by defining ARM32-specific versions of the Dockerfile that explicitly use the `3.0-buster-arm32v7` and `3.0-buster-slim-arm32v7` tags.
Fixes #1383

Fix Linux ARM32 builds of samples

---

3.1/sdk/alpine3.10/amd64/Dockerfile
3.1/sdk/bionic/amd64/Dockerfile
3.1/sdk/bionic/arm32v7/Dockerfile
3.1/sdk/bionic/arm64v8/Dockerfile
3.1/sdk/buster/amd64/Dockerfile
3.1/sdk/buster/arm32v7/Dockerfile
3.1/sdk/buster/arm64v8/Dockerfile
3.1/sdk/nanoserver-1803/amd64/Dockerfile
3.1/sdk/nanoserver-1809/amd64/Dockerfile
3.1/sdk/nanoserver-1809/arm32v7/Dockerfile
3.1/sdk/nanoserver-1903/amd64/Dockerfile
README.aspnet.md
README.runtime-deps.md
README.runtime.md
manifest.json

There were some extraneous SDK builds that got picked up.  Resetting the SDK back to the official version.

Update 3.1 preview 2 SDK version

---

eng/update-dependencies/ManifestUpdater.cs

This fixes the underlying issue for the manifest to not be updated correctly - https://github.com/dotnet/dotnet-docker/pull/1431/files#diff-4b1eb3dc48c4e16d49db5b42298fe654
This code is specific to the .NET versioning format and there is currently a variation between the runtime and sdk which makes this more complicated.  This is illustrated by the parameters generated by the auto update infra.
```
--runtime-version 3.1.0-preview3.19530.5 --sdk-version 3.1.100-preview2-014589 --aspnet-version 3.1.0-preview3.19530.9
```

Update ManifestUpdater to better handle versions

---

eng/update-dependencies/DockerfileShaUpdater.cs

The changes from #1450 caused the update-dependencies tool to fail when attempting to calculate the checksums.  It constructs a URL based off of `dotnetcli.blob.core.net` and ends up trying to access `dotnetclichecksums.azureedge.net` which doesn't exist.  To keep the logic simple, I've just reverted the change in that file back to using `dotnetcli.blob.core.net`.

Use blob hostname for accessing SHAs

---

3.1/sdk/nanoserver-1909/amd64/Dockerfile

Looks like the fix for #1444 was missed when creating the nanoserver-1909 images.  This is causing the builds to fail with the recently added ENV utests - #1446.

Fixup incorrect POWERSHELL_DISTRIBUTION_CHANNEL ENV in nanoserver-1909 image

---

tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/NuGet.config.nightly

This NuGet feed was added temporarily to validate the 3.1 release in the nightly branch before the NuGet packages had been published externally.  It can be removed now.

Remove temp workaround for 3.1 nuget feed

---

documentation/tagging-guidelines.md

Update the tagging-guidelines to reflect changes to the latest tag behavior in nightly

---

eng/update-dependencies/NuGet.config
eng/update-dependencies/Program.cs
eng/update-dependencies/update-dependencies.csproj

The current behavior of update-dependencies is that it will update an existing PR by force-pushing.  The consequence of this is that it triggers another build.  This happens even when there were no changes that were made from the previous state of the PR's branch.  That's because there's no logic to compare what the state of the PR's branch is.  All it does is detect what files have changed in the _local_ repo and produced a commit that contains those files and force-pushes them blindly into the PR.
Making use of `PullRequestCreator` isn't a good option in this case.  It has to do a force push because it doesn't know about or require a local repo to compare files against.  It's up to the caller to produce a correct commit.  In theory, we could implement logic in update-dependencies that …

Prevent force-pushes on PR in update-dependencies

---

tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/CommonRuntimeImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/EnvironmentVariableInfo.cs
tests/Microsoft.DotNet.Docker.Tests/ImageData.cs
tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs
tests/Microsoft.DotNet.Docker.Tests/ImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/Microsoft.DotNet.Docker.Tests.csproj
tests/Microsoft.DotNet.Docker.Tests/ProductImageData.cs
tests/Microsoft.DotNet.Docker.Tests/RuntimeDepsImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/RuntimeImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/TestData.cs
tests/run-tests.ps1

Several unit test refactoring changes in order to support #391:
* Adds Category trait to unit tests so that specific categories of tests can be executed.
* Factors `ImageData` into an abstract class with a derived `ProductImageData` class.  `ImageData` is meant for generic images in general, providing support for sample images in the future.  `ProductImageData` provides functionality specific to the "product" images (SDK, runtime, etc).
* Upgrades the test project to .NET Core 3.1

Unit test refactoring

---

tests/performance/Validate-ImageSize.ps1

The changes in https://github.com/dotnet/dotnet-docker/pull/1554 cause the image size validation script to be executed when running the `build-and-test.ps1` script.  Attempting to run it from the master branch will cause it to fail because the master branch has no associated image size baseline files.
Fixing this by checking whether the baseline file exists and display a warning if it does not.

Prevent image size validation script from failing in master

---

samples/aspnetapp/Dockerfile.nanoserver-x64-slim

The nanoserver slim sample produced an app that was inaccessible when run because it was missing the `ASPNETCORE_URLS` environment variable.

Add URLS env var to nanoserver slim sample

---

eng/pipelines/dotnet-core-samples.yml

Public builds for the sample pipeline are failing because generation of the build matrix is using the wrong matrix type.

Use correct matrix type for sample builds in public

---

3.0/aspnet/nanoserver-1903/amd64/Dockerfile
3.0/aspnet/nanoserver-1909/amd64/Dockerfile
3.1/aspnet/nanoserver-1903/amd64/Dockerfile
3.1/aspnet/nanoserver-1909/amd64/Dockerfile

Several ASP.NET Dockerfiles had incorrectly been set to reference `core-nightly` for the base image's repo instead of `core`.  These didn't affect the actual images that were published since the build system explicitly sets the `REPO` arg.  It would be an issue for anyone copying these Dockerfiles for their own use, however.
Fixes #1612

Fix repo ref in some aspnet Dockerfiles

---

samples/complexapp/README.md

The `run-test-stage.ps1` script has been removed so updating the readme to longer refer to it.

Remove mention of script for complexapp in readme

---

README.aspnet.md
README.md
README.runtime-deps.md
README.runtime.md
README.samples.md
README.sdk.md

Added an 'Image Update Policy' section to the READMEs to call out when .NET Core images will be updated.  The purpose is to communicate our policy so that customers can know what to expect.  The desired outcome is that more customers feel compelled to take a dependency on our images.
I also tweaked one of the licensing URLs which was language specific to be neutral.
/cc @rotata - this is related to the question I asked in regards to changing the MCR readme template to make it more obvious that the full tag listing is the complete list of supported tags.

Added 'Image Update Policy' section to the READMEs

---

eng/update-dependencies/Dockerfile
eng/update-dependencies/NuGet.config
eng/update-dependencies/update-dependencies.csproj

Fixes #1572 
PowerShell doesn't have a package feed for Buster therefore I needed to refactor the Dockerfile to install PowerShell via a tarball.
The NuGet.config change looks to be necessary as the expected version of System.CommandLine cannot be found with the previous configuration.

Upgrade update-dependencies to .NET Core 3.1

---

eng/update-dependencies/DockerfileShaUpdater.cs
eng/update-dependencies/ErrorTraceListener.cs
eng/update-dependencies/Program.cs

The `update-dependencies` tool will succeed (return a zero exit code) even if there was a SHA value that could not be retrieved when updating the files.
Fixed this by adding a trace listener that checks for any errors. If a SHA value wasn't found, it logs it as an error. At the end of the processing, it checks whether any errors occurred and then outputs the results accordingly.
Fixes #1579

Ensure update-dependencies fails if sha not found

---

eng/pipelines/dotnet-core-nightly.yml
eng/pipelines/dotnet-core-size-validation-pr.yml
eng/pipelines/dotnet-core.yml

Ensures that PR builds will not trigger for commits that only consist of README or documentation changes.
Fixes #1609

Update path exclusions for pipelines

---

samples/aspnetapp/aspnetapp/Properties/launchSettings.json
samples/run-in-sdk-container.md

The launch profile added in the sample is not container-specific, so changing its name, to "publicdev" (a more accurate description of what the profile is accomplishing). After that, will start a conversation to get this change into the .NET 5.0 templates.
@glennc suggested that we switch to a port like `5050`, for two reasons:
* Maps more closely to the localhost:5000 that is used by default.
* Proxies and other things apparently use the 80xx range, so there could be conflicts. 
If we want to do that, we may want to do that throughout the samples. We could also wait to have that conversation as part of adding this concept to the official ASP.NET Core templates.

Rename launch profile

---

.github/ISSUE_TEMPLATE/releases/patch-tuesday-release.md

When queueing builds for PT, only the Windows images should be built.  Updated the issue template to set the appropriate parameters to target only the Windows images.

Fix PT template to specify appropriate build params

---

.github/ISSUE_TEMPLATE/releases/net-core-release.md

The task to run the test/publish stages was missing a variable to set the `sourceBuildId`.

Update .NET Core Release issue template

---

eng/pipelines/update-dependencies.yml
eng/update-dependencies/DockerfileShaUpdater.cs
eng/update-dependencies/Options.cs
eng/update-dependencies/Program.cs

* Fixes the logic for retrieving SHAs from dotnetcli blob storage. The SHAs are contained in one file and need to be parsed out.
* Provides a summary of any errors that were encountered.
* Changed to not compute SHAs by default. A new option is provided that will enable this logic: `--compute-shas`.
https://github.com/dotnet/core/issues/4278 does impact the use of this functionality currently, requiring that the `--compute-shas` option be used.
Fixes #1576

Update Dockerfile SHA updater

---

.github/ISSUE_TEMPLATE/releases/patch-tuesday-release.md

Now that there's a [script](https://github.com/dotnet/docker-tools/pull/411) to check the status of the base Windows images, the Patch Tuesday issue template can make use of it in the workflow.

Update PT issue template to check Windows images w/ script

---

2.1/runtime-deps/focal/amd64/Dockerfile
2.1/runtime-deps/focal/arm32v7/Dockerfile
2.1/sdk/focal/amd64/Dockerfile
2.1/sdk/focal/arm32v7/Dockerfile
3.1/runtime-deps/focal/amd64/Dockerfile
3.1/runtime-deps/focal/arm32v7/Dockerfile
3.1/runtime-deps/focal/arm64v8/Dockerfile
3.1/sdk/focal/amd64/Dockerfile
3.1/sdk/focal/arm32v7/Dockerfile
3.1/sdk/focal/arm64v8/Dockerfile
5.0/runtime-deps/focal/amd64/Dockerfile
5.0/runtime-deps/focal/arm32v7/Dockerfile
5.0/runtime-deps/focal/arm64v8/Dockerfile
5.0/sdk/focal/amd64/Dockerfile
5.0/sdk/focal/arm32v7/Dockerfile
5.0/sdk/focal/arm64v8/Dockerfile

The libicu63 package has been replaced with libicu65 in the Ubuntu Focal package feed.  Updating Dockerfiles to reflect this.

Update to libicu65 package for focal

---

eng/pipelines/update-dependencies.yml
eng/pipelines/update-readmes.yml

The update-dependencies pipeline was not making use of the new .NET Docker bot so I've updated it to do so.

Ensure .NET Docker bot is used in pipelines

---

.github/ISSUE_TEMPLATE/releases/new-distro-release.md
.github/ISSUE_TEMPLATE/releases/new-windows-release.md
build-and-test.ps1
tests/Microsoft.DotNet.Docker.Tests/TestData.cs
tests/run-tests.ps1

Updating the build and test scripts in response to the parameter name changes in https://github.com/dotnet/docker-tools/pull/429.

Update build/test scripts to use new parameter names

---

README.aspnet.md
README.runtime-deps.md
README.runtime.md
README.sdk.md
eng/mcr-tags-metadata-templates/aspnet-tags.yml
eng/mcr-tags-metadata-templates/runtime-deps-tags.yml
eng/mcr-tags-metadata-templates/runtime-tags.yml
eng/mcr-tags-metadata-templates/sdk-tags.yml
manifest.json

Works around #1747 by removing 5.0 Focal ARM32 from the set of published tags.
Related to https://github.com/dotnet/dotnet-docker/issues/1745

Remove 5.0 Focal ARM32 from manifest and tags

---

.github/ISSUE_TEMPLATE/releases/net-core-release.md

Now that we're releasing 5.0 preview versions, I've updated the release issue template to specify the appropriate build parameters for such releases.

Update release issue template for preview release

---

eng/get-drop-versions.sh

Updates the URL that is used to check for latest .NET Core drops.  This URL is better because it avoids cases where spurious builds are indicated as latest.

Update preview drop location

---

5.0/runtime-deps/focal/amd64/Dockerfile
5.0/runtime-deps/focal/arm32v7/Dockerfile
5.0/runtime-deps/focal/arm64v8/Dockerfile
5.0/sdk/focal/amd64/Dockerfile
5.0/sdk/focal/arm32v7/Dockerfile
5.0/sdk/focal/arm64v8/Dockerfile

Focal Dockerfiles were using the `libicu65` package which is no longer available in the Focal feed.  Updating it to reference `libicu66` instead.

Update Focal Dockerfiles to use libicu66

---

eng/common/templates/jobs/publish.yml
eng/common/templates/variables/docker-images.yml
manifest.json
manifest.samples.json

References a version of Image Builder that is configured to use the new image info schema as defined by https://github.com/dotnet/docker-tools/issues/438.

Update Image Builder ref that uses new image info schema

---

tests/Microsoft.DotNet.Docker.Tests/ImageData.cs

The test code reads from the image info file to determine whether it needs to pull any images.  Since the image info schema was changed as part of https://github.com/dotnet/docker-tools/issues/438, the code is being updated to support this new schema.

Fix test logic to support new image info schema

---

2.1/runtime-deps/alpine3.10/amd64/Dockerfile
2.1/runtime-deps/alpine3.11/amd64/Dockerfile
2.1/runtime-deps/bionic/amd64/Dockerfile
2.1/runtime-deps/stretch-slim/amd64/Dockerfile
2.1/sdk/bionic/amd64/Dockerfile
2.1/sdk/stretch/amd64/Dockerfile
3.1/runtime-deps/alpine3.10/amd64/Dockerfile
3.1/runtime-deps/alpine3.11/amd64/Dockerfile
3.1/runtime-deps/bionic/amd64/Dockerfile
3.1/runtime-deps/buster-slim/amd64/Dockerfile
3.1/sdk/bionic/amd64/Dockerfile
3.1/sdk/buster/amd64/Dockerfile
5.0/runtime-deps/alpine3.11/amd64/Dockerfile
5.0/runtime-deps/buster-slim/amd64/Dockerfile
5.0/runtime-deps/focal/amd64/Dockerfile
5.0/sdk/buster/amd64/Dockerfile
5.0/sdk/focal/amd64/Dockerfile

The AMD64 Dockerfiles that reference an external base image tag are using a multi-arch tag.  This would cause those Dockerfiles to not build correctly if built on a machine with a different platform.  Since these Dockerfiles are platform-specific, they should be using platform-specific base image tags.
Fixes #1758

Use platform-specific base image tags

---

5.0/aspnet/alpine3.11/amd64/Dockerfile
5.0/aspnet/alpine3.11/amd64/nuget.config

Initial stab at producing composite image for aspnet docker container
- I had difficulty getting versioning to work without doing it all at once including producing an SDK image, this feels like something that should be better
- Crossgen2 is currently only published as a nuget package, so my technique for acquiring it is to dotnet publish some dummy app using crossgen2, then use the nuget image cache to find crossgen2. This isn't pretty, and it makes the build dependent on nuget package server install latency, but it does work.
- Docker multistage build has been used to control the size of the final image to something in the range of reasonable
- The produced image is 152MB, 86MB of which is the composite shared image with just the R2R code in it. Previous efforts on size reduction of the …

Produce composite crossgen2 image for entire aspnet docker contents

---

5.0/sdk/alpine3.11/amd64/Dockerfile
5.0/sdk/buster/amd64/Dockerfile
5.0/sdk/buster/arm32v7/Dockerfile
5.0/sdk/buster/arm64v8/Dockerfile
5.0/sdk/focal/amd64/Dockerfile
5.0/sdk/focal/arm32v7/Dockerfile
5.0/sdk/focal/arm64v8/Dockerfile
5.0/sdk/nanoserver-1809/amd64/Dockerfile
5.0/sdk/nanoserver-1809/arm32v7/Dockerfile
5.0/sdk/nanoserver-1903/amd64/Dockerfile
5.0/sdk/nanoserver-1909/amd64/Dockerfile

5.0 Preview 2 SDK version had been incorrect updated due to inadvertent builds caused by dependency flow commits.  Updating to the correct version.

Revert 5.0 preview 2 to earlier SDK version

---

eng/common/templates/jobs/build-images.yml

The nightly build pipeline is out of sync with the version of Image Builder it uses.  This results in a build failure because the `source-repo` parameter is not set for the `build` command.  This change was originally made in https://github.com/dotnet/docker-tools/pull/457 but didn't get merged over.

Update build to set source repo

---

eng/common/templates/variables/docker-images.yml

Reverts a change that had been made when integrating master branch changes from docker-tools (https://github.com/dotnet/dotnet-docker/pull/1792).

Reverts an unintended ImageBuilder tag change

---

eng/common/templates/jobs/publish.yml

Reverts changes that were inadvertently made to the publish stage when integrate the eng/common contents from docker-tools (https://github.com/dotnet/dotnet-docker/pull/1792).

Revert inadvertent publish stage changes

---

3.1/sdk/alpine3.10/amd64/Dockerfile
3.1/sdk/alpine3.11/amd64/Dockerfile
3.1/sdk/nanoserver-1809/amd64/Dockerfile
3.1/sdk/nanoserver-1903/amd64/Dockerfile
3.1/sdk/nanoserver-1909/amd64/Dockerfile
5.0/sdk/alpine3.11/amd64/Dockerfile
5.0/sdk/nanoserver-1809/amd64/Dockerfile
5.0/sdk/nanoserver-1903/amd64/Dockerfile
5.0/sdk/nanoserver-1909/amd64/Dockerfile
manifest.json

In order to allow for more layer sharing amongst images, the 5.0 SDK images for Alpine and Nano Server have been changed to be based on their respective ASP.NET images.  This requires that the runtime and ASP.NET components of the SDK be omitted when extracting its contents since they are derived from base layers.
Fixes #1351

Update base image of 5.0 SDK for Alpine and Nano

---

eng/get-drop-versions.sh

The `.version` file for ASP.NET has been renamed to `Microsoft.AspNetCore.App.versions.txt` which broke the automation from determining the version of ASP.NET in the downloaded the SDK.  See https://github.com/dotnet/aspnetcore/issues/21177.  Updating the script to look for the new file name.

Update name of ASP.NET versions file

---

tests/performance/ImageSize.nightly.linux.json

A size change occurred in the runtime-deps layer that installs packages.  This was most likely a result of the official release of Focal.  Updating the baseline numbers to reflect the change in image size.

Update image size baselines for Focal images

---

5.0/sdk/alpine3.11/amd64/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs

Removes the `LC_ALL` and `LANG` environment variables from the 5.0 SDK image for Alpine in order to be consistent with all SDK images.
Fixes #1516

Remove locale env vars from 5.0 SDK on Alpine

---

eng/pipelines/dotnet-core-size-validation.yml
eng/pipelines/update-dependencies.yml

There are a couple pipelines that run on a schedule but are configured incorrectly such that they will only run if there had been a new commit since the last run.  Updated the configuration to set them to always run, regardless of commits.

Fix pipeline schedules to always run

---

README.aspnet.md
README.aspnet.preview.md
README.runtime-deps.md
README.runtime-deps.preview.md
README.runtime.md
README.runtime.preview.md
README.sdk.md
README.sdk.preview.md
eng/Get-TagsDocumentation.ps1

Addresses the remaining review comments from https://github.com/dotnet/dotnet-docker/pull/1888.

Readme updates for 5.0 repo name change

---

5.0/runtime-deps/buster-slim/amd64/Dockerfile
5.0/runtime-deps/buster-slim/arm32v7/Dockerfile
5.0/runtime-deps/buster-slim/arm64v8/Dockerfile
5.0/runtime-deps/focal/amd64/Dockerfile
5.0/runtime-deps/focal/arm32v7/Dockerfile
5.0/runtime-deps/focal/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs
tests/Microsoft.DotNet.Docker.Tests/Microsoft.DotNet.Docker.Tests.csproj

Adds the `ca-certificates` package to the runtime-deps images to allow HTTPS connections to succeed by default.  Alpine doesn't require this package in order for this scenario to work since it has the `ca-certificates-cacert` package by default.
Updates the tests to inject custom logic to the `Main` method which verifies the scenario.
Related to #1897

Include ca-certificates pkg in 5.0 runtime-deps

---

README.aspnet.preview.md
README.md
README.runtime-deps.preview.md
README.runtime.preview.md
README.sdk.preview.md

Merged in a change from nightly branch (#1915).
Updated the base readme to reference both `dotnet` and `dotnet-core` product families.  
Updated the 5.0 readmes to not reference nightly content.

Update readme content

---

5.0/runtime-deps/alpine3.11/amd64/Dockerfile
5.0/runtime-deps/alpine3.11/arm64v8/Dockerfile
5.0/sdk/alpine3.11/amd64/Dockerfile
5.0/sdk/buster-slim/amd64/Dockerfile
5.0/sdk/buster-slim/arm32v7/Dockerfile
5.0/sdk/buster-slim/arm64v8/Dockerfile
5.0/sdk/focal/amd64/Dockerfile
5.0/sdk/focal/arm32v7/Dockerfile
5.0/sdk/focal/arm64v8/Dockerfile

Because of the changes in https://github.com/dotnet/dotnet-docker/pull/1908, we no longer need to be installing `ca-certificates` in the SDK images.  These changes remove that package from the Dockerfiles.
Since `ca-certificates` is missing from the Alpine `runtime-deps` image, that package is being moved from `sdk` to `runtime-deps`.  This enables parity across the distros.
It was also found that .NET dependencies were still being installed in the `sdk` images which no longer needs to be done because those `sdk` images have been switched from `buildpack-deps` to `aspnet` as the base image.

Update package dependencies in 5.0 images

---

manifest.json

Updates the manifest so that 5.0 images are published to the `dotnet/core` repo in addition to the `dotnet` repo.  For example, the 5.0 SDK image for Ubuntu Focal will have a tag like `mcr.microsoft.com/dotnet/core/sdk:5.0-focal` in addition to `mcr.microsoft.com/dotnet/sdk:5.0-focal`.  The 5.0 tags using the `dotnet/core` repo will not be published in readme tags table.
This ensures that consumers of the old repo, `dotnet/core`, will continue to get the latest 5.0 images.  This is intended to be a temporary measure for the transition to the new repo name.  The intent is to no longer tag the images with the `dotnet/core` repo in .NET 5 Preview 5.
Related to #1765

Include 5.0 in core repos

---

README.aspnet.preview.md
README.runtime-deps.preview.md
README.runtime.preview.md
README.sdk.preview.md

Update the link to point to the official announcement for the Docker repo name change.

Update link to Docker repo name for 5.0

---

samples/aspnetapp/README.md
samples/dotnetapp/README.md

A few missed references related to https://github.com/dotnet/dotnet-docker/issues/1859

Remove obsolete nanoserver-arm32 references from samples documentation

---

monitor/5.0/alpine/amd64/Dockerfile

With dotnet-monitor running in ASP.NET Core 3.1, it establishes its own diagnostics pipe server, which is visible through the REST API that dotnet-monitor provides. We should set the COMPlus_EnableDiagnostics environment variable to 0 in order to disable the diagnostics pipe server within dotnet-monitor. If absolutely necessary, users of the image can override this by setting the value  to 1 within their orchestration environment.

Exclude diagnostics on monitor image to prevent self-diagnosis.

---

tests/performance/ImageSize.nightly.windows.json

This isn't required today because of the way the validate command works but eventually it will be needed once 3.1 reaches EOL.  The Linux baseline already has the 5.0 images within the new non-core repos.

Update Windows image size baseline w/non-core repos

---

src/aspnet/5.0/buster-slim/amd64/Dockerfile
src/aspnet/5.0/focal/amd64/Dockerfile
src/runtime/5.0/buster-slim/amd64/Dockerfile
src/runtime/5.0/focal/amd64/Dockerfile
src/sdk/5.0/nanoserver-1903/amd64/Dockerfile

Update amd64 buildpack-deps references to be explicit.  The explicit references make the Dockerfiles consistent across the various Dockerfiles (e.g. `amd64/alpine:3.12`).  These changes also make it easier to define the Dockerfile templates as part of #1933.

Update amd64 buildpack-deps references

---

src/sdk/3.1/buster/arm32v7/Dockerfile
src/sdk/3.1/focal/arm32v7/Dockerfile
src/sdk/5.0/buster-slim/arm32v7/Dockerfile
src/sdk/5.0/focal/arm32v7/Dockerfile

This fixes an inconsistency in the sdk Dockerfiles regarding a PowerShell code comment.
https://github.com/dotnet/dotnet-docker/blob/nightly/src/sdk/5.0/focal/amd64/Dockerfile#L43
`# To reduce image size, remove the copy nupkg that nuget keeps.`
vs
https://github.com/dotnet/dotnet-docker/blob/nightly/src/sdk/5.0/focal/arm32v7/Dockerfile#L43
`# Remove the copy nupkg that nuget keeps to reduce size.`
This is being fixed in preparation for introducing Dockerfile templates (#1933)

Fix inconsistent PowerShell nupkg Dockerfile comment

---

README.monitor.md
eng/get-drop-versions.sh
eng/pipelines/update-dependencies.yml
eng/update-dependencies/DockerfileShaUpdater.cs
eng/update-dependencies/Options.cs
eng/update-dependencies/Program.cs
eng/update-dependencies/VariableHelper.cs
manifest.json
src/monitor/5.0/alpine/amd64/Dockerfile

Modify the update-dependencies tool to be able to check for the latest dotnet-monitor 5.0 tool and update its version and checksum in the Dockerfiles as well as update the manifest with corresponding version tag. I will update the update-dependencies pipeline to provide the dotnet-monitor channel, which is currently "net5/dev", after merging in these changes.

Modify update-dependencies to handle dotnet-monitor.

---

eng/common/templates/variables/docker-images.yml
manifest.json

This change is required for the [Dockerfile templates feature](https://github.com/dotnet/dotnet-docker/issues/1933)

Update osVersion metadata to include slim os information

---

eng/update-dependencies/Program.cs

With the inclusion of https://github.com/dotnet/dotnet-docker/pull/2027, a separate PR will be generated for changes to dotnet-monitor.  The update-dependencies tool now doesn't correctly handle the situation when it is executed and an existing PR already exists.  It makes no distinction between whether the PR is for core-sdk or for dotnet-monitor.  If the PR had changes for core-sdk and the tool found changes for dotnet-monitor, it would attempt to update the core-sdk branch's PR with the dotnet-monitor changes.  And vice versa.
Fixed the logic to check that the branch of the PR matches what is expected before attempting to update that PR.

Fix update-dependencies to handle separate branches

---

samples/aspnetapp/aspnetapp/aspnetapp.csproj

The ASP.NET Core sample project is not defined with a `UserSecretsId` property by default, even though the [instructions](https://github.com/dotnet/dotnet-docker/blob/master/samples/run-aspnetcore-https-development.md#application-secrets) state that it is already configured.  Since it is not set, the following error will occur when attempting to run the `dotnet user-secrets -p aspnetapp\aspnetapp.csproj set "Kestrel:Certificates:Development:Password" "crypticpassword"` command of the sample: `Could not find the global property 'UserSecretsId' in MSBuild project 'C:\repos\dotnet-docker\samples\aspnetapp\aspnetapp\aspnetapp.csproj'. Ensure this property is set in the project or use the '--id' command line option.`

Add UserSecretsId to ASP.NET Core sample

---

eng/common/templates/variables/docker-images.yml
eng/update-dependencies/ManifestUpdater.cs
eng/update-dependencies/Program.cs
manifest.json
manifest.versions.json

This is being added to support the [Dockerfile templates feature](#1933).  Eventually the versions file will contain the product build versions along with the product checksums.

Add manifest.versions.json file to encapsulate version variables

---

eng/pipelines/wait-for-ingestion.yml

This pipeline can be used to wait for MCR ingestion on any publish for this repo. This is intended to be used to monitor official builds from the master branch which aren't currently configured to wait for ingestion since the implementation is still being validated.  So if anything goes wrong with the logic in this pipeline, it won't affect the result of the official build pipeline.
The following queue-time variables will be defined for this pipeline:
* manifest (default: manifest.json)
* sourceBuildId
* commitDigest

Adds pipeline to wait for MCR ingestion

---

manifest.json

Due to an issue with VS 16.6, 5.0 Dockerfiles are still being generated with "core" in the repo name (see https://github.com/dotnet/dotnet-docker/issues/1939#issuecomment-658252795).  That causes version discrepancies.  Updating the manifest to include 5.0 images in the original "core" repos as undocumented tags to allow for backwards compatibility.

Include 5.0 images in the "core" repos

---

eng/pipelines/dotnet-core-nightly-pr.yml
eng/pipelines/dotnet-core-nightly.yml
eng/pipelines/dotnet-core-samples.yml
eng/pipelines/dotnet-core.yml

Define separate pipeline YAML file for the nightly pipeline: an internal one to trigger from commits and a public one to trigger from PRs. There's not a way to define a single file with conditional logic around the trigger and pr keywords because AzDO doesn't support that.
Fixes #1991

Split off PR-specific pipeline for nightly pipeline

---

eng/pipelines/dotnet-core-nightly-pr.yml
eng/pipelines/dotnet-core-nightly.yml

The pipeline YAML needs to explicitly disable the `pr` and `trigger` actions to avoid the default behavior.

Need to explicitly disable pr/trigger in pipelines

---

eng/update-dependencies/Dockerfile
eng/update-dependencies/Program.cs

The following exception occurs when update-dependencies attempts to update an existing PR:
```
System.TypeInitializationException: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception.
---> System.DllNotFoundException: Unable to load shared library 'git2-106a5f2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgit2-106a5f2: cannot open shared object file: No such file or directory
at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
at LibGit2Sharp.Core.NativeMethods.InitializeNativeLibrary()
at LibGit2Sharp.Core.NativeMethods..cctor()
--- End of inner exception stack trace ---
at LibGit2Sharp.Core.NativeMethods.git_clone(git_repository*& repo, String origin_url, FilePath workdir_path, …
```

Publish update-deps with rid

---

src/monitor/5.0/alpine/amd64/Dockerfile

As part of https://github.com/dotnet/dotnet-docker/pull/2115, the Dockerfiles were not regenerated.  The infrastructure issues that caused this is being fixed with #2114

Regenerate out of date monitor Dockerfile

---

build-and-test.ps1
eng/common/templates/jobs/build-images.yml
eng/common/templates/jobs/test-images-linux-client.yml
eng/common/templates/stages/build-test-publish-repo.yml
eng/common/templates/steps/test-images-linux-client.yml
eng/dockerfile-templates/Get-GeneratedDockerfiles.ps1
eng/update-dependencies/ScriptRunnerUpdater.cs
tests/Microsoft.DotNet.Docker.Tests/Config.cs
tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
tests/Microsoft.DotNet.Docker.Tests/ExecuteHelper.cs
tests/Microsoft.DotNet.Docker.Tests/Microsoft.DotNet.Docker.Tests.csproj
tests/Microsoft.DotNet.Docker.Tests/SampleImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/TemplateTests.cs
tests/run-tests.ps1

related #1933
These changes introduce a pre-build validation step in the builds.  This works nicely for validating the templates and Dockerfiles are in-sync.  It will also provide a nice place to validate the readme tag listing is up-to-date as well.  I will back port the common eng infrastructure changes to docker-tools once merged.

Create tests that verifies the Dockerfiles and templates are in sync

---

eng/dockerfile-templates/runtime-deps/2.1/Dockerfile.linux
eng/dockerfile-templates/runtime-deps/3.1/Dockerfile.alpine
eng/dockerfile-templates/runtime-deps/3.1/Dockerfile.linux
eng/dockerfile-templates/runtime-deps/5.0/Dockerfile.alpine
eng/dockerfile-templates/runtime-deps/5.0/Dockerfile.linux
src/runtime-deps/2.1/bionic/amd64/Dockerfile
src/runtime-deps/2.1/bionic/arm32v7/Dockerfile
src/runtime-deps/2.1/focal/amd64/Dockerfile
src/runtime-deps/2.1/stretch-slim/amd64/Dockerfile
src/runtime-deps/2.1/stretch-slim/arm32v7/Dockerfile
src/runtime-deps/3.1/alpine3.11/amd64/Dockerfile
src/runtime-deps/3.1/alpine3.11/arm64v8/Dockerfile
src/runtime-deps/3.1/alpine3.12/amd64/Dockerfile
src/runtime-deps/3.1/alpine3.12/arm64v8/Dockerfile
src/runtime-deps/3.1/bionic/amd64/Dockerfile
src/runtime-deps/3.1/bionic/arm32v7/Dockerfile
src/runtime-deps/3.1/bionic/arm64v8/Dockerfile
src/runtime-deps/3.1/buster-slim/amd64/Dockerfile
src/runtime-deps/3.1/buster-slim/arm32v7/Dockerfile
src/runtime-deps/3.1/buster-slim/arm64v8/Dockerfile
src/runtime-deps/3.1/focal/amd64/Dockerfile
src/runtime-deps/3.1/focal/arm64v8/Dockerfile
src/runtime-deps/5.0/alpine3.12/amd64/Dockerfile
src/runtime-deps/5.0/alpine3.12/arm64v8/Dockerfile
src/runtime-deps/5.0/buster-slim/amd64/Dockerfile
src/runtime-deps/5.0/buster-slim/arm32v7/Dockerfile
src/runtime-deps/5.0/buster-slim/arm64v8/Dockerfile
src/runtime-deps/5.0/focal/amd64/Dockerfile
src/runtime-deps/5.0/focal/arm64v8/Dockerfile

The inconsistencies are around indentation of the list of packages getting installed and the `.NET Core dependencies` code comment.

Correct inconsistent formatting in runtime-deps Dockerfiles

---

eng/pipelines/update-dependencies.yml

There's a need to be able to optionally define which of the products gets updated by the update-dependencies pipeline.  These changes define two queue-time variables for controlling this behavior: `update-dotnet-enabled` and `update-diagnostics-enabled`. It turns out that the easiest way to consume these was through the use of stages since a stage can have a condition.  Using `${{ if }}` expressions isn't possible because they can't reference custom variables.  I also looked at templatizing the UpdateDependencies jobs but it turned out there's just enough variation between them that it made it pointless.
Fixes #2125

Enable optional jobs for update-dependencies pipeline

---

tests/performance/ImageSize.nightly.linux.json

These were set incorrectly when adding these back in from https://github.com/dotnet/dotnet-docker/pull/2151.

Update Focal ARM32 image size baselines

---

README.aspnet.md
README.aspnet.preview.md
README.monitor.md
README.runtime-deps.md
README.runtime-deps.preview.md
README.runtime.md
README.runtime.preview.md
README.sdk.md
README.sdk.preview.md
manifest.json

Related to #2188 
The plan would be to merge these changes to master during the next servicing event at which point the current tags become unsupported because of the new .NET version.

Removed <Major.Minor.Patch .NET Version>-alpine tags

---

README.aspnet.md
README.aspnet.preview.md
README.md
README.monitor.md
README.runtime-deps.md
README.runtime-deps.preview.md
README.runtime.md
README.runtime.preview.md
README.samples.md
README.sdk.md
README.sdk.preview.md

https://github.com/dotnet/dotnet-docker/pull/2143 didn't get merged from master to nightly.  This is a direct result of the READMEs being different between the two branches and therefore difficult to merge.

Cleanup formatting of the readme License

---

README.aspnet.md
README.runtime-deps.md
README.runtime.md
README.sdk.md

The _core_ repo readmes in nightly have a duplicated `.NET 5.0+:` section.  The PR is cleaning that up.

Remove redundant Related Repos section

---

README.aspnet.md
README.aspnet.preview.md
README.md
README.runtime-deps.md
README.runtime-deps.preview.md
README.runtime.md
README.runtime.preview.md
README.sdk.md
README.sdk.preview.md

The changes included the following:
1. Fixed unintentional inconsistencies across the READMEs
1. For the 5.0 repos the .NET branding was used instead of .NET Core.  This makes it difficult to ensure consistency across all of the READMEs.  The proposal is to use the .NET Core brand across all of the repos until .NET 5.0 is released and then switch to the new branding consistently across all READMEs.
1. Added a header at the top of the 5.0 repos calling out the repo split.  This header will be added to the _core_ branded repos once 5.0 is released.
1. Added _Related Repos_ links between the core and non-core repos for the specific image type.  For example if you are on dotnet/core/aspnet and want to get to dotnet/aspnet, a link was added to make this easy.
1. Fixed a few bad links.

Fix inconsistencies across READMEs

---

.editorconfig
tests/Microsoft.DotNet.Docker.Tests/EnvironmentVariableInfo.cs
tests/Microsoft.DotNet.Docker.Tests/ImageData.cs
tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs
tests/Microsoft.DotNet.Docker.Tests/ProductImageData.cs
tests/Microsoft.DotNet.Docker.Tests/SampleImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs

The goal of adding this is to get more consistency in the code style used. This editor config is a copy of what is used in the dotnet/runtime repo. I propose we work on addressing the inconsistencies by proactively addressing the problems within the files we touch. I've included the fixes to the unit tests.

Add .editorconfig and correct problems in tests

---

src/aspnet/5.0/windowsservercore-ltsc2019/amd64/Dockerfile
src/runtime/5.0/windowsservercore-ltsc2019/amd64/Dockerfile
src/sdk/5.0/windowsservercore-ltsc2019/amd64/Dockerfile

An update was made in https://github.com/dotnet/dotnet-docker/pull/2267 without updating the new Server Core Dockerfiles.

Update Server Core Dockerfiles to reference latest 5.0 build

---

eng/common/templates/jobs/publish.yml
eng/common/templates/variables/docker-images.yml
eng/dockerfile-templates/aspnet/2.1/Dockerfile.linux
eng/dockerfile-templates/aspnet/3.1/Dockerfile.alpine
eng/dockerfile-templates/aspnet/3.1/Dockerfile.linux
eng/dockerfile-templates/aspnet/5.0/Dockerfile.alpine
eng/dockerfile-templates/aspnet/5.0/Dockerfile.linux
eng/dockerfile-templates/runtime/2.1/Dockerfile.linux
eng/dockerfile-templates/runtime/3.1/Dockerfile.alpine
eng/dockerfile-templates/runtime/3.1/Dockerfile.linux
eng/dockerfile-templates/runtime/5.0/Dockerfile.alpine
eng/dockerfile-templates/runtime/5.0/Dockerfile.linux
eng/dockerfile-templates/sdk/5.0/Dockerfile.linux

References the new version of Image Builder that now always sets `ARCH_TAG_SUFFIX` template variable to a value, instead of leaving it blank for AMD64 arch.  This requires updates to the Dockerfile templates to compensate for this change, using conditional logic to only output an arch suffix if the arch is not AMD64.

Maintain generated tags with new ImageBuilder version

---

eng/pipelines/dotnet-core-nightly-pr-no-cache.yml

Defines a new pipeline YAML file that is intended to be used to validate PRs without caching enabled.  The pipeline should only build/test a subset of the images.  Rather than defining that subset within the YAML, I felt it more appropriate to define it in the variables of the build definition in AzDO where it can be more easily adjusted as necessary.  See https://github.com/dotnet/dotnet-docker/issues/2247#issuecomment-704325852 for the suggested set of paths to use.
This pipeline is configured to be triggered only by changes to the eng and tests folders.  A change to the src folder would likely end up causing a cache miss in the existing PR pipeline so this one wouldn't need to run in that case.  The primary use case for this pipeline is to validate infrastructure changes in the eng …

Pipeline to validate PR without caching

---

README.aspnet.preview.md
README.runtime-deps.preview.md
README.runtime.preview.md
README.sdk.preview.md
eng/common/templates/variables/docker-images.yml
eng/dockerfile-templates/aspnet/5.0/Dockerfile.nanoserver
eng/dockerfile-templates/aspnet/5.0/Dockerfile.windowsservercore
eng/dockerfile-templates/sdk/5.0/Dockerfile.nanoserver
eng/dockerfile-templates/sdk/5.0/Dockerfile.windowsservercore
eng/mcr-tags-metadata-templates/aspnet-tags.yml
eng/mcr-tags-metadata-templates/runtime-tags.yml
eng/mcr-tags-metadata-templates/sdk-tags.yml
manifest.json
src/aspnet/5.0/nanoserver-1809/amd64/Dockerfile
src/aspnet/5.0/nanoserver-1903/amd64/Dockerfile
src/aspnet/5.0/nanoserver-1909/amd64/Dockerfile
src/aspnet/5.0/nanoserver-2004/amd64/Dockerfile
src/aspnet/5.0/windowsservercore-ltsc2019/amd64/Dockerfile
src/sdk/5.0/nanoserver-1809/amd64/Dockerfile
src/sdk/5.0/nanoserver-1903/amd64/Dockerfile
src/sdk/5.0/nanoserver-1909/amd64/Dockerfile
src/sdk/5.0/nanoserver-2004/amd64/Dockerfile
src/sdk/5.0/windowsservercore-ltsc2019/amd64/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/ProductImageData.cs

Defines a multi-arch tag for each Linux distro for 5.0.  Because of limitations in the manifest schema, this required duplicating the platforms in order to assign them a distinct set of shared tags.
Related to #2182

Define multi-arch tags for each Linux distro

---

README.aspnet.preview.md
README.runtime.preview.md
README.sdk.preview.md
eng/mcr-tags-metadata-templates/aspnet-tags.yml
eng/mcr-tags-metadata-templates/runtime-tags.yml
eng/mcr-tags-metadata-templates/sdk-tags.yml
manifest.json
src/aspnet/5.0/nanoserver-1809/amd64/Dockerfile
src/runtime/5.0/nanoserver-1809/amd64/Dockerfile
src/sdk/5.0/nanoserver-1809/amd64/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/TestData.cs
tests/performance/ImageSize.nightly.windows.json

This PR adds back .NET 5.0 support for nanoserver-1809 which was recently removed in https://github.com/dotnet/dotnet-docker/pull/2298

Add back nanoserver-1809 support for 5.0

---

.github/ISSUE_TEMPLATE/releases/patch-tuesday-release.md

Adds `windowsservercore` to the paths now that Server Core is supported for .NET 5.0.

Update PT release template

---

manifest.json

I don't think these are needed any longer. They were needed when we were sharing the runtime-deps between multiple versions.  This pattern has been replaced with defining multiple manifest entries in order to avoid rebuilding the runtime-deps when they haven't changed.

Remove unused documentationGroups from the manifest

---

eng/get-drop-versions.sh
eng/pipelines/update-dependencies.yml
eng/update-dependencies/DockerfileShaUpdater.cs

When nearing release, .NET switches to stable branding for its versioning scheme.  This means that the versions of shared frameworks contained in the SDK zip file are not build-specific.  In the case of the upcoming 5.0 release, the versions of runtime and ASP.NET Core being referenced are just labeled as 5.0.0.  This breaks the existing logic in the `get-drop-versions.sh` script because it relies on this value being build-specific in order to generate the correct input to the update-dependencies tool.
I've updated the logic to account for this scenario by not relying on the .version files for the shared frameworks and instead lookup up the build-specific version numbers associated with the SDK build by using the Version.Details.xml file.
This also required changes to the …

Update version resolution logic

---

eng/pipelines/dotnet-core-nightly-pr-2.1.yml
eng/pipelines/dotnet-core-nightly-pr-3.1.yml
eng/pipelines/dotnet-core-nightly-pr-5.0.yml
eng/pipelines/dotnet-core-nightly-pr-monitor.yml
eng/pipelines/dotnet-core-pr-2.1.yml
eng/pipelines/dotnet-core-pr-3.1.yml
eng/pipelines/dotnet-core-pr-5.0.yml
eng/pipelines/dotnet-core-pr-monitor.yml

Breaks up the single PR pipeline that we had into more granular pipelines that are triggered by changes to specific folders in the repo.  This allows us to only run builds for .NET Core 2.1, 3.1, 5.0, or the monitor images based on which Dockerfiles had changed.
Fixes #2161

Define more granular PR pipelines

---

samples/aspnetapp/Dockerfile.nanoserver-x64-slim
samples/dotnetapp/Dockerfile.nanoserver-x64-slim
tests/Microsoft.DotNet.Docker.Tests/CommonRuntimeImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/EnvironmentVariableInfo.cs
tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/SampleImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs

Explicitly adds the `DOTNET_RUNNING_IN_CONTAINER` environment variable to the "slim" variant sample Dockerfiles because it doesn't get the benefit of deriving from the `runtime` image which defines that variable.
Add unit tests to ensure sample Dockerfiles have the required environment variables in the same way as is done for the product.
Fixes #2319

Add required env vars to samples

---

README.samples.md
eng/mcr-tags-metadata-templates/samples-tags.yml
manifest.samples.json
tests/Microsoft.DotNet.Docker.Tests/ImageData.cs
tests/Microsoft.DotNet.Docker.Tests/ProductImageData.cs

Maintains the tagging pattern used in https://github.com/dotnet/dotnet-docker/issues/2182 by ensuring that all concrete Linux tags for the samples are arch-specific.
Fixes #2284

Define arch-specific tags for samples

---

tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs

The comparison of the contents of SDK archive's shared aspnetcore runtime folder is different than the contents of the sdk image which derives its content from the aspnet image.  This is because of https://github.com/dotnet/aspnetcore/issues/27670.

Disabling content verification test

---

eng/dockerfile-templates/monitor/5.0/Dockerfile.alpine
src/monitor/5.0/alpine/amd64/Dockerfile

Currently `dotnet-monitor` has permissions of 744. When attempting run as a non-root UID (as is recommended for containers) dotnet-monitor fails to start with the familiar `standard_init_linux.go:211: exec user process caused "exec format error"`.
Given that there are there are no security implications here, I think this change makes sense.
The only limiting thing should be whether dotnet-monitor has access to the AF_UNIX socket created by the target process' runtime which is not impacted by this change

Change permissions on dotnet-monitor

---

README.sdk.md
eng/readme-templates/Use.sdk.md

These links have been broken for a long time.  It looks like they regressed with https://github.com/dotnet/dotnet-docker/pull/1538.  Surprising nobody pointed them out.  It makes me question the value of them.

Fix broken links in the SDK readme

---

eng/common/templates/variables/docker-images.yml

Rolling this out to nightly branch first to avoid any potential churn.

Update ImageBuilder tag

---

eng/common/templates/stages/build-test-publish-repo.yml

Fixes an issue that prevents the pipeline from generating build jobs for Windows 20H2.  Will port this to docker-tools once things are verified.

Update job name for Windows 20H2 to match build matrix output

---

manifest.json

The manifest was misconfigured for 2.1 and 3.1 to include 20H2 tags for syndication to the "core" repos.

Remove unintended syndication of 20H2 tags

---

eng/dockerfile-templates/monitor/5.0/Dockerfile.alpine
eng/get-drop-versions-monitor.sh
eng/pipelines/update-dependencies.yml
manifest.versions.json
src/monitor/5.0/alpine/amd64/Dockerfile

The ability to scrape the dotnet-monitor package version from the nupkg file located at the aka.ms link was broken. I've updated dotnet/diagnostics to publish a version file which contains the version of the dotnet-monitor package and generate a latest aka.ms link for it. The link no longer contains the dotnet product version, so there is no longer an update channel for dotnet-montior. I've also updated the docker image to pull the package from the Azure Artifacts NuGet feed rather than from blob storage since the NuGet package is no longer published to blob storage.

Update dotnet-monitor version detection and pull package from Azure Artifacts feed.

---

eng/get-drop-versions.sh

The content of the `Version.Details.xml` file has changed for .NET 6.0 which requires some updates to the target dependency names in order to gather the correct version numbers to pass to the update-dependencies tool.
Example of `Version.Details.xml` that is being used: https://raw.githubusercontent.com/dotnet/installer/8efbfffe79d15d851d2a34ae502fa53f9430a708/eng/Version.Details.xml

Fix update-dependencies for .NET 6.0

---

eng/dockerfile-templates/sdk/5.0/Dockerfile.linux
src/sdk/5.0/buster-slim/amd64/Dockerfile
src/sdk/5.0/buster-slim/arm32v7/Dockerfile
src/sdk/5.0/buster-slim/arm64v8/Dockerfile
src/sdk/5.0/focal/amd64/Dockerfile
src/sdk/5.0/focal/arm32v7/Dockerfile
src/sdk/5.0/focal/arm64v8/Dockerfile

The `pgrep` utility is needed in order to run `dotnet watch` in a 5.0 sdk container.  This utility does not exist in the Debian base images.  It does exist in the base Alpine images.  For Ubuntu, the base image has it as well due to having the `procps` package installed.  
These changes update the 5.0 sdk Dockerfiles to explicitly ensure that the `procps` package is installed for Debian and Ubuntu in order to provide the `pgrep` utility.  The `procps` package will not be added to the Alpine Dockerfile because Alpine already provides `pgrep` and the intent is to keep Alpine images lean.  So adding `procps` just to make it consistent is not the right choice.
Fixes #2396

Add procps package to 5.0 SDK

---

eng/dockerfile-templates/sdk/5.0/Dockerfile.alpine
eng/dockerfile-templates/sdk/6.0/Dockerfile.alpine
src/sdk/5.0/alpine3.12/amd64/Dockerfile
src/sdk/6.0/alpine3.12/amd64/Dockerfile

This corrects a minor formatting difference between the alpine sdk and [runtime-deps](https://github.com/dotnet/dotnet-docker/blob/master/src/runtime-deps/3.1/alpine3.12/amd64/Dockerfile#L3) Dockerfiles.

Correctly indent 'apk add' packages in alpine sdk Dockerfiles

---

eng/update-dependencies/NuGet.config
eng/update-dependencies/Options.cs
eng/update-dependencies/Program.cs
eng/update-dependencies/update-dependencies.csproj

Removes the use of an older, unsupported version of `System.CommandLine` that is no longer available from the deprecated `dotnet.myget.org` feed.  Replaces it with the new version of `System.CommandLine` from https://github.com/dotnet/command-line-api. This has a new API model that the code has been refactored to consume.
Fixes #2493

Upgrade System.CommandLine version

---

eng/dockerfile-templates/monitor/5.0/Dockerfile.alpine
manifest.versions.json
src/monitor/5.0/alpine/amd64/Dockerfile

This change has the dotnet-monitor tool output its logging in the JSON format, which is a better format for ingesting into analytic platforms, such as Container Insights, because it allows for discrete field selection with minimal parsing.

Update dotnet-monitor to output JSON logging by default.

---

eng/pipelines/update-dependencies.yml
manifest.versions.json
src/monitor/5.0/alpine/amd64/Dockerfile

Since moving the nightly update dependencies pipeline to the 6.0 product version, dotnet-monitor has not had its Dockerfile updated. This change fixes the Dockerfile version passed into the update-dependencies tool to move the version back to 5.0 for dotnet-monitor only. This change will require an update to the pipeline to include monitorDockerfileVersion as a new variable with a value of 5.0 to complete the fix.

Fix update-dependencies to update 5.0 Dockerfiles for dotnet-monitor.

---

eng/common/templates/variables/docker-images.yml

Related to https://github.com/dotnet/docker-tools/issues/719.
Testing in nightly before larger rollout.

Update ImageBuilder to track layers in VersionInfo

---

eng/common/templates/variables/docker-images.yml

Reverts dotnet/dotnet-docker#2524
These changes don't work correctly with the build staging location.

Revert "Update ImageBuilder to track layers in VersionInfo"

---

samples/aspnetapp/aspnetapp/Pages/Index.cshtml
samples/dotnetapp/Program.cs

I was starting to test our container images on Apple M1 machines. The samples don't demonstrate the architecture. It would be very useful to see that information.

Add architecture to samples

---

tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs

The fix for https://github.com/dotnet/aspnetcore/issues/29092 is now available in the 6.0 builds so the test workaround can be removed.  The fix for 5.0 (https://github.com/dotnet/aspnetcore/issues/27670) should be available in the next 5.0 servicing release.
Related to https://github.com/dotnet/dotnet-docker/issues/2373

Remove 6.0 SDK content verification workaround

---

tests/Microsoft.DotNet.Docker.Tests/RuntimeImageTests.cs

Remove .NET 6 console test workaround

---

eng/dockerfile-templates/monitor/5.0/Dockerfile.alpine
src/monitor/5.0/alpine/amd64/Dockerfile

dotnet-monitor uses arguments to specify default bindings, and uses configuration to alter these. Remove the default binding url from the image.

Remove default hosting URL for dotnet-monitor

---

README.sdk.md
eng/dockerfile-templates/sdk/6.0/Dockerfile.alpine
eng/mcr-tags-metadata-templates/sdk-tags.yml
manifest.json
manifest.versions.json
src/sdk/6.0/alpine3.13/arm32v7/Dockerfile
src/sdk/6.0/alpine3.13/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/TestData.cs
tests/performance/ImageSize.nightly.linux.json

Things of note:
* Buster SDK is now no longer needed in order to test the runtime and aspnet images for Arm.
* PowerShell doesn't provide an Arm version of Alpine (see https://github.com/PowerShell/PowerShell/issues/12937 and https://github.com/PowerShell/PowerShell/issues/14667) so PowerShell needed to be removed from the sdk for Arm.
Related to #2504

Add SDK Dockerfiles for Arm arch on Alpine

---

tests/performance/ImageSize.nightly.linux.json

Correcting the sizes for these images.  There wasn't an actual change.  The initial values were just not set correctly.

Initial sizes for Alpine 3.13 arm images

---

README.runtime-deps.md
manifest.json
src/runtime-deps/5.0/alpine3.13/amd64/Dockerfile
src/runtime-deps/5.0/alpine3.13/arm64v8/Dockerfile
tests/performance/ImageSize.nightly.linux.json

Because we will not be publishing Alpine 3.13 images for the servicing release of .NET Core 2.1 and 3.1 next week, I'm restructuring the files here in order to prep for that release next week.  We will be publishing Alpine 3.13 images for 5.0 and 6.0 Preview 1.  So I'm making a copy of the runtime-deps Dockerfile to be contained in the 5.0 folder and shared between 5.0 and 6.0 instead of before where it was shared by 3.1, 5.0, and 6.0.  It wouldn't have made sense to have the 3.1 folder contain a Alpine 3.13 Dockerfile when aren't going to be release that Alpine version for 3.1.
It still will use the `runtime-deps/3.1/Dockerfile.alpine` Dockerfile template because the content we need is still exactly the same; it's just the placement of the generated Dockerfile that's being changed.
Once …

Define Alpine 3.13 runtime-deps in 5.0 folder

---

eng/common/Get-ImageBuilder.ps1

The script that pulls Image Builder just recently started to fail on some of our build agents.  This is the same as what happened in https://github.com/dotnet/docker-tools/pull/735.  By changing the script to use `$?` instead of `$LASTEXITCODE`, it works.

Fix script to pull Image Builder

---

build-and-test.ps1
tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/DotNetTheoryAttribute.cs
tests/Microsoft.DotNet.Docker.Tests/DotNetTheoryDiscoverer.cs
tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs
tests/Microsoft.DotNet.Docker.Tests/LinuxImageTheoryAttribute.cs
tests/Microsoft.DotNet.Docker.Tests/MonitorImageData.cs
tests/Microsoft.DotNet.Docker.Tests/MonitorImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/RuntimeImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/SampleImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/SkippableTheoryAttribute.cs
tests/Microsoft.DotNet.Docker.Tests/TestData.cs
tests/run-tests.ps1

These changes add two unit tests for dotnet-monitor:
- Basic environment variable test
- Basic metrics endpoint availability test (tests that the container does run and that the metrics endpoint is accessible).
I plan to add additional tests in a future change for the other endpoints once https://github.com/dotnet/diagnostics/pull/1820 is completed.

Add dotnet-monitor variable and metrics endpoint tests.

---

README.monitor.md
eng/get-drop-versions-monitor.sh
eng/pipelines/update-dependencies.yml
manifest.versions.json
src/monitor/5.0/alpine/amd64/Dockerfile

Arcade made a change recently that prevented the ability to create aka.ms latest links for repositories that do not have aka.ms channel names. Thus dotnet-monitor has not been able to provide updated versions to dotnet-docker. This change temporarily fixes the version of dotnet-monitor while Arcade resolves the issue and pushes out a new SDK.
Additionally, dotnet-monitor has moved to its own repository (https://github.com/dotnet/dotnet-monitor) so I've updated the version source to reflect that.
I'll create an issue in dotnet-docker and assign it to myself to undo the temporary version fixing.

Update dotnet-monitor version source and manually update to latest version

---

tests/performance/ImageSize.nightly.linux.json
tests/performance/ImageSize.nightly.windows.json

Some size changes to the SDK were introduced from the transition of 6.0 Preview 1 to Preview 2.  See https://github.com/dotnet/sdk/issues/15996.

Update image size baselines

---

tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
tests/Microsoft.DotNet.Docker.Tests/DockerRunArgsBuilder.cs
tests/Microsoft.DotNet.Docker.Tests/ImageData.cs
tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs
tests/Microsoft.DotNet.Docker.Tests/MonitorImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/SampleImageData.cs
tests/Microsoft.DotNet.Docker.Tests/TestData.cs

These changes refactor the existing tests and add a few more.
Basic container tests:
- VerifyMonitorDefault: Run image without modification and test that it has a viable metrics endpoint.
- VerifyMonitorNoHttps: Disables HTTPS on the artifacts port and checks that /processes returns 401 due to lack of authentication.
- VerifyMonitorNoHttpsNoAuth: Disables HTTPS and authentication and checks that /processes returns empty list of processes.
Basic scenario tests:
- VerifyConnectModeNoAuth: Verifies that dotnet-monitor can discover the samples app running in another container when both have a mounted volumne at /tmp.
- VerifyListenModeNoAuth: Verifies that dotnet-monitor can be set to listening mode and the samples app in the other container can connect to dotnet-monitor and dotnet-monitor is …

Additional dotnet-monitor tests

---

eng/get-drop-versions-monitor.sh

Arcade now shortens aka.ms latest URLs to only include the channel name and the file name.

Update dotnet-monitor latest version URL.

---

eng/get-drop-versions.sh

There have been some recent changes to the generated aka.ms links that point to the blob locations for .NET bits.  The `Sdk` portion of the path is no longer needed since the link implicitly points to that location.

Update aka.ms path to sdk zip file

---

samples/aspnetapp/Dockerfile.alpine-x64-slim
samples/aspnetapp/Dockerfile.nanoserver-x64-slim
samples/aspnetapp/Dockerfile.ubuntu-x64-slim
samples/aspnetapp/Dockerfile.windowsservercore-x64-slim
samples/dotnetapp/Dockerfile.alpine-x64-slim
samples/dotnetapp/Dockerfile.debian-x64-slim
samples/dotnetapp/Dockerfile.nanoserver-x64-slim
samples/dotnetapp/Dockerfile.ubuntu-x64-slim
samples/dotnetapp/Dockerfile.windowsservercore-x64-slim

The slim variants of the sample Dockerfiles are intended to be optimized for size.  So we should probably make them smaller by using the `PublishSingleFile` publish option.  This wraps all the published files into a single file and actually ends up with a net decrease in disk size used (see results published in [App Trimming in .NET 5](https://devblogs.microsoft.com/dotnet/app-trimming-in-net-5/)).
By applying this option to the slim variants of the sample Dockerfiles I was able to get a worthwhile reduction in the overall image size: 12 MB for Linux and 6 MB for Windows.  In the case of Alpine, that 12 MB is significant, percentage-wise, resulting in a 12% reduction in the image size.

Add PublishSingleFile option for slim samples

---

eng/common/templates/jobs/generate-matrix.yml
eng/common/templates/variables/common.yml

Reverts https://github.com/dotnet/dotnet-docker/pull/2654
Sets a default value for the additionalGenerateBuildMatrixOptions variable to ensure it's always set.  If it's not set, it results in the following error: `/home/vsts/work/_temp/c2410e43-b3c7-4799-bd06-9b9dbd8833f5.sh: line 1: additionalGenerateBuildMatrixOptions: command not found`.  Before today, that error was still occurring but being ignored.  Today, it causes the script task to fail.

Set default value for additionalGenerateBuildMatrixOptions var

---

.github/ISSUE_TEMPLATE/releases/dotnet-release.md

In order to ensure we rebuild the runtime-deps images to include any new package updates, I've updated the release workflow to se the `noCache` option.  This will disable the image caching behavior and always rebuild images even if their Dockerfile or base image has not changed.

Update release workflow

---

eng/get-drop-versions-monitor.sh

Arcade has fixed the flattening of the aka.ms link generation (see https://github.com/dotnet/arcade/pull/7036). Update the link in get-drop-versions-monitor.sh to reflect the change.

Update dotnet-monitor version aka.ms link

---

eng/get-drop-versions-monitor.sh
eng/pipelines/update-dependencies.yml

A change was made to the aka.ms link generation for dotnet-monitor to allow differentiating build channels. The anticipated channel values are:
- "5.0/daily": corresponds to daily builds from the dotnet-monitor main branch
- "5.0/preview.#": corresponds to builds from a dotnet-monitor prerelease branch
- "5.0/release": corresponds to builds from the dotnet-monitor release branch.
The preview.# and release names allow for stabilizing dotnet-monitor for the corresponding release while the main branch cotinues to evolve more changes. This should allow dotnet-docker to consume deliberately updated builds as we approach preview and final releases.
With the channel set to "5.0/daily" for now, the nightly branch will consume the latest version from the …

Add channel differentiation to get-drop-versions-monitor.sh

---

eng/pipelines/update-dependencies.yml
eng/update-dependencies/DockerfileShaUpdater.cs
eng/update-dependencies/Options.cs
manifest.versions.json
src/monitor/5.0/alpine/amd64/Dockerfile

The dotnet-monitor tool changed its version and hash file naming to include a channel name. This broke update-dependencies because it was not aware of the channel differentiation. This change adds the optional channel name notion that can be used in the url templates for the checksum files.
Overview of changes:
- Add optional --channel-name parameter to update-dependencies.
- Use --channel-name when updating dotnet-monitor.
- Update dotnet-monitor version using '5.0/daily' channel name.

Use channel name parameter in update-dependencies for dotnet-monitor

---

tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs
tests/Microsoft.DotNet.Docker.Tests/RuntimeImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs

Several test scenarios were disabled due to the following product issues that have been resolved:
* https://github.com/dotnet/runtime/issues/47423: 6.0 works now, 5.0 should be fixed in 5.0.7
* https://github.com/dotnet/aspnetcore/issues/27670
* https://github.com/dotnet/sdk/issues/11327
Related to:
* #2353
* #2373

Enable tests for fixed issues

---

.github/ISSUE_TEMPLATE/releases/dotnet-release.md
.github/ISSUE_TEMPLATE/releases/new-distro-release.md
.github/ISSUE_TEMPLATE/releases/new-windows-release.md
.github/ISSUE_TEMPLATE/releases/patch-tuesday-release.md
README.aspnet.md
README.md
README.monitor.md
README.runtime-deps.md
README.runtime.md
README.samples.md
README.sdk.md
documentation/guiding-principles.md
documentation/supported-platforms.md
documentation/supported-tags.md
eng/readme-templates/README.md
samples/selecting-tags.md

In some cases there were references to https://hub.docker.com/_/microsoft-dotnet-nightly/ in order to specifically refer to nightly repositories as a whole.  In that case, I replaced it with a link to the [README in the nightly branch](https://github.com/dotnet/dotnet-docker/blob/nightly/README.md).  
Fixes #2361

Replace references to dotnet-nightly product family in Docker Hub

---

README.aspnet.md
README.monitor.md
README.runtime-deps.md
README.runtime.md
README.sdk.md
eng/readme-templates/README.md

This fixes some issues introduced by https://github.com/dotnet/dotnet-docker/pull/2773.  
* It adds back samples as a related repo for repo-specific readmes.
* Addresses issues with the nightly readme generation:
* Fixes featured repos section to include nightly repos
* Excludes nightly repos from related repos of nightly product family readme

Fix readme template

---

eng/dockerfile-templates/runtime/5.0/Dockerfile.windowsservercore
eng/dockerfile-templates/runtime/6.0/Dockerfile.windowsservercore
src/runtime/5.0/windowsservercore-ltsc2019/amd64/Dockerfile
src/runtime/6.0/windowsservercore-ltsc2019/amd64/Dockerfile

Related to https://github.com/dotnet/dotnet-docker/issues/2782
Note that the download URL uses KB4601558 but this actually maps to KB5001879 for the 5B release.

Apply WSC 2019 patch

---

eng/common/templates/jobs/validate-image-sizes.yml
eng/common/templates/stages/build-test-publish-repo.yml

Rolling out the changes to consume scale set agent pools for internal builds in the nightly branch for testing.
Related to https://github.com/dotnet/docker-tools/issues/532

Use scale set agent pools for internal builds

---

eng/common/templates/steps/publish-readmes.yml
eng/common/templates/variables/docker-images.yml

Consumes the `exclude-product-family` option that was added in https://github.com/dotnet/docker-tools/pull/788 in order to avoid publishing the product family repository in the nightly branch.  While this is in the common infra, I chose to reference the `nightly` branch directly even though it's not relevant to the other repositories that consume the common infra.  This decision was based purely on keeping things simple. The alternative is to provide a way to do task injection which would require flowing a parameter value across a bunch of YAML files.
Related to #2361

Set exclude-product-family readme option for nightly branch

---

eng/dockerfile-templates/monitor/5.0/Dockerfile.alpine
src/monitor/5.0/alpine/amd64/Dockerfile

As a result of https://github.com/dotnet/dotnet-monitor/pull/299, we will need to add a default process filter for the docker image.

Default process filter for dotnet-monitor

---

samples/dotnetapp/Program.cs

Updating existing sample to use GCMemoryInfoAPI.
Based on this guidance: https://github.com/dotnet/runtime/issues/46889#issuecomment-826508484

Add use of GCMemoryInfo.TotalAvailableMemoryBytes

---

manifest.versions.json
src/sdk/6.0/alpine3.13/amd64/Dockerfile
src/sdk/6.0/bullseye-slim/amd64/Dockerfile
src/sdk/6.0/bullseye-slim/arm32v7/Dockerfile
src/sdk/6.0/bullseye-slim/arm64v8/Dockerfile
src/sdk/6.0/focal/amd64/Dockerfile
src/sdk/6.0/focal/arm32v7/Dockerfile
src/sdk/6.0/focal/arm64v8/Dockerfile
src/sdk/6.0/nanoserver-1809/amd64/Dockerfile
src/sdk/6.0/nanoserver-2004/amd64/Dockerfile
src/sdk/6.0/nanoserver-20H2/amd64/Dockerfile
src/sdk/6.0/windowsservercore-ltsc2019/amd64/Dockerfile

This PR is a result of running `dotnet run --project .\eng\update-dependencies\ -- 6.0 --product-version powershell=7.2.0-preview.6 --compute-shas` with Docker in Linux container mode.

Updated 6.0 images to use latest PowerShell Preview build 7.2.0-preview.6

---

manifest.json

Split 5.0 runtime-deps Buster tags to have separate product version

---

eng/dockerfile-templates/runtime/5.0/Dockerfile.windowsservercore
eng/dockerfile-templates/runtime/6.0/Dockerfile.windowsservercore
src/runtime/5.0/windowsservercore-ltsc2019/amd64/Dockerfile
src/runtime/6.0/windowsservercore-ltsc2019/amd64/Dockerfile

Removes the application of the .NET Fx patch for the 6B release since the .NET Fx patches will now be applied in the base image.
Related to https://github.com/dotnet/dotnet-docker/issues/2865

Remove apply .NET Fx patch since it exists in base image

---

tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs

The changes from https://github.com/dotnet/dotnet-docker/pull/2878 had missed removing the workaround for the ASP.NET Core tests.
Fixes https://github.com/dotnet/dotnet-docker/issues/2539

Reenables test for 5.0 on Alpine arm

---

eng/update-dependencies/DockerfileShaUpdater.cs

Changes from https://github.com/dotnet/dotnet-docker/pull/2841 broke the ability to update the checksum for `powershell|<version>|Linux.Alpine|sha` because it doesn't contain an architecture value. This was discovered in https://github.com/dotnet/dotnet-docker/pull/2903#issuecomment-863552655. This is fixed by properly distinguishing the differences of `powershell|<version>|Linux.Alpine|sha` and `netstandard-targeting-pack-2.1.0|linux-rpm|x64|sha` by checking whether a version number exists in the 2nd position.

Fix update-dependencies to handle PowerShell shas

---

eng/update-dependencies/DockerfileShaUpdater.cs

Given that the binaries stored in blob storage for preview bits are not immutable (some get signed just prior to release and overwrite the original non-signed files), we need to adjust what the update-dependencies tool uses for its checksum source.
The best authority for checksum values on release day is `https://dotnetcli.blob.core.windows.net/dotnet/checksums/<product-version>-sha.txt`.  This file aggregates all the checksums and is updated with final checksum values even before the final files have been copied to blog storage.  So I moved this checksum source to be the first one that is checked.
But there is an existing issue in the logic which prevents that checksum source from being used for preview releases.  A preview release version has a value like `6.0.0-preview.5.21301.5` (it …

Fix update-dependencies checksum resolution logic

---

eng/dockerfile-templates/sdk/6.0/Dockerfile.nanoserver
src/sdk/6.0/nanoserver-1809/amd64/Dockerfile
src/sdk/6.0/nanoserver-2004/amd64/Dockerfile
src/sdk/6.0/nanoserver-20H2/amd64/Dockerfile

The build results from https://github.com/dotnet/dotnet-docker/pull/2911 lied to me.  I don't think the build got run or didn't show up in GitHub or something with the change to shutdown build-server.  I'm fixing the syntax here because it's incorrect and causing a build failure.

Fix typo in build-server shutdown

---

eng/dockerfile-templates/monitor/5.0/Dockerfile.alpine
src/monitor/5.0/alpine/amd64/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/MonitorImageTests.cs

The current images use `DotnetMonitor_`* environment variables to set the default process selection. This causes an issue where no other means of configuration (settings.json, key-per-file, non-`DotnetMonitor_` environment variables) is able to override the first default process filter and forces the user to use the `DotnetMonitor_DefaultProcess__Filters__0__`* environment variables for configuring the first default process filter.
This change uses an environment variable with a lower precedence such that all other means of configuration may override its values.
This fixes https://github.com/dotnet/dotnet-monitor/issues/568

Use default process environment variable with lower precedence.

---

samples/aspnetapp/Dockerfile.windowsservercore-iis-x64
samples/aspnetapp/Dockerfile.windowsservercore-x64
samples/aspnetapp/Dockerfile.windowsservercore-x64-slim
samples/dotnetapp/Dockerfile.windowsservercore-x64
samples/dotnetapp/Dockerfile.windowsservercore-x64-slim
tests/Microsoft.DotNet.Docker.Tests/TestData.cs

The nanoserver-x64-slim sample Dockerfile had been updated to reference nanoserver:ltsc2022 for the WS 2022 update. But the test code was still configured to test that Dockerfile on a 20H2 machine.  This obviously caused a failure due to Windows container version incompatibility.
I've updated the test code to configure the tests to run on 2022 machines.  Also updated to include windowsservercore-x64-slim testing on WS 2022.

Fix samples for WS 2022

---

tests/Microsoft.DotNet.Docker.Tests/TestData.cs

Now that the Nano Server 2022 sample images have been published, we can enable testing of those images.

Include test for published WS 2022 sample images

---

eng/dockerfile-templates/runtime-deps/3.1/Dockerfile.alpine
src/runtime-deps/3.1/alpine3.13/amd64/Dockerfile
src/runtime-deps/3.1/alpine3.13/arm64v8/Dockerfile
src/runtime-deps/5.0/alpine3.13/arm32v7/Dockerfile

This reverts commit ae7fe5d2624954633a0fe684ec85fc1710b95878.
Reverting #3074 now that images for Alpine 3.13.6 have been released that contain the updated apk-tools and libssl1.1 packages.

Revert "Ensure Alpine images have their packages upgraded (#3074)"

---

tests/Microsoft.DotNet.Docker.Tests/ImageData.cs

Due to changes in https://github.com/dotnet/docker-tools/pull/861, empty lists are no longer being serialized in the image info JSON.  When the test code attempts to read the JSON file, it expects the simpleTags field to be there and is leading to a NRE.
This fixes the code to check that simpleTags exists.

Handle empty simpleTags field in tests

---

tests/performance/ImageSize.nightly.windows.json

This reflects a change to the size of the base Windows Server Core 2022 image.

Update Windows image size baselines

---

README.monitor.md
eng/dockerfile-templates/monitor/6.0/Dockerfile.alpine
eng/mcr-tags-metadata-templates/monitor-tags.yml
eng/readme-templates/README.md
manifest.json
manifest.versions.json
src/monitor/6.0/alpine/amd64/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/TestData.cs
tests/performance/ImageSize.nightly.linux.json

Dotnet-monitor is aligning its versioning to the runtime and building for that same runtime version. At this time, the tool is aligning to the 6.0.0 version and using the ASP.NET 6.0 image.

Move dotnet-monitor to .NET 6 and version 6.0.0

---

tests/Microsoft.DotNet.Docker.Tests/MonitorImageData.cs

The test code is attempting to use the "6.0-alpine" tag for the dotnet-monitor image. However, this is not a simple tag. The simple tags for dotnet-monitor are "6.0-alpine-amd64" and "6.0.0-preview.8-alpine-amd64".
The problem is that the MonitorImageData class is overriding the arch tag suffix to be empty. The fix is to allow the default arch tag determination behavior.

Allow arch to be included in monitor tag test data.

---

eng/pipelines/stages/build-test-publish-repo.yml

Builds in the nightly branch aren't working correctly due to incorrect settings for generating the build matrix.  This is a regression due to https://github.com/dotnet/dotnet-docker/pull/3088.  There were actually a couples issues with those:
1. Pipelines that made use of the eng/pipelines/stages/build-test-publish-repo.yml template never passed in a value for the `isPullRequestPipeline` parameter so it always defaulted to false.
2. The conditional logic that references the `isPullRequestPipeline` parameter was incorrectly defined, causing it to always return true. It needs to use an equality comparison rather than strictly basing it on the boolean value:
https://github.com/dotnet/dotnet-docker/blob/5aee0db4b68855b66f2bf9c683c3d6db4a2cb198/eng/pipelines/stages/build-test-publish-repo.yml#L …

Fix conditional pipeline logic

---

.github/ISSUE_TEMPLATE/releases/dotnet-monitor-release.md

.NET monitor image is now based on Alpine 3.14 so the path should be updated appropriately.

Update .NET Monitor release issue template

---

eng/common/templates/jobs/copy-base-images.yml
eng/common/templates/jobs/generate-matrix.yml
eng/common/templates/stages/build-test-publish-repo.yml
eng/common/templates/stages/dotnet/build-test-publish-repo.yml
eng/common/templates/variables/common.yml
eng/common/templates/variables/dotnet/build-test-publish.yml
eng/pipelines/stages/build-test-publish-repo.yml

This removes hard-coded pools in the common build-test-publish-repo template in order for it to be easily reusable by other products. Pools can be defined using template parameters but also have defaults configured.
In order for the pools, and other settings, to be used by the other .NET team-owned repositories, such as dotnet-framework-docker, I've created a wrapper template at `eng/common/stages/dotnet/build-test-publish-repo.yml` which consolidates these settings.
Related to dotnet/docker-tools#843

Support parameterized agent pools

---

eng/pipelines/dotnet-core-samples.yml
eng/pipelines/dotnet-core.yml

Builds for main branch are failing due to missing project name parameters from infrastructure updates.

Fix pipelines to have project name parameters

---

eng/dockerfile-templates/monitor/6.0/Dockerfile.alpine
src/monitor/6.0/alpine/amd64/Dockerfile

The `dotnet monitor` tool now ships with two TFMs (netcoreapp3.1 and net6.0) within the tool package. However, since this image only has the ASP.NET 6 and .NET 6 frameworks, it's not necessary to keep the netcoreapp3.1 bits. This will save a few megabytes on the image and not give anyone the illusion that the netcoreapp3.1 version is runnable from this image.

Only keep net6.0 TFM in dotnet-monitor

---

eng/dockerfile-templates/runtime-deps/6.0/Dockerfile.mariner
eng/dockerfile-templates/runtime-deps/6.0/Dockerfile.mariner-distroless
src/runtime-deps/6.0/cbl-mariner1.0-distroless/amd64/Dockerfile
src/runtime-deps/6.0/cbl-mariner1.0/amd64/Dockerfile

Update distroless Mariner to reference prebuilt-ca-certificates package

---

README.monitor.md
eng/dockerfile-templates/monitor/7.0/Dockerfile.alpine
eng/get-drop-versions-monitor.sh
eng/mcr-tags-metadata-templates/monitor-tags.yml
eng/readme-templates/README.md
eng/update-dependencies/DockerfileShaUpdater.cs
manifest.json
manifest.versions.json
src/monitor/7.0/alpine/amd64/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/ImageVersion.cs
tests/Microsoft.DotNet.Docker.Tests/TestData.cs
tests/performance/ImageSize.nightly.linux.json

The 7.0 builds of the tool are based on .NET 6 at this time, so the Dockerfile is effectively the same as the 6.0 version but with 7.0 branding.
closes #3277

Add dotnet-monitor 7.0 image

---

eng/pipelines/stages/build-test-publish-repo.yml
tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/NuGet.config.nightly

PR builds in dotnet-docker have not been executing correctly, using the wrong matrix type. This has resulted in builds being executed but the tests haven't been running anything (all tests were skipped). This became broken as a result of https://github.com/dotnet/dotnet-docker/pull/3241 which requires the matrix type to explicitly be set by the template consumer.
As a result of this, I'm also updating a feed change to fix the .NET 7 tests due to a change in the feed name.
I will cherry-pick this to main once it's confirmed to be working.

Set correct matrix type for PR builds

---

tests/Microsoft.DotNet.Docker.Tests/TestData.cs

Now that https://github.com/dotnet/runtime/issues/55405 is fixed, the testing of the sample Dockerfile for self-contained deployment on Windows Server Core can be enabled.
Fixes https://github.com/dotnet/dotnet-docker/issues/2938

Enable sample testing of SCD on WSC

---

eng/dockerfile-templates/monitor/7.0/Dockerfile.alpine
manifest.versions.json
src/monitor/7.0/alpine/amd64/Dockerfile

The dotnet-monitor repo can now publish its nupkg file to blob storage in addition to the dotnet-tools feed. This change switches the Dockerfiles to pull from blob storage. This will be especially useful when shipping the final versions of 7.0+ such that the package can be provided using the same mechanism as the rest of the dotnet packages and the checksum file value will match the package (as compared to the 6.0 releases, where the package had to be published to nuget.org, which changes the signing of the package and thus the checksum file doesn't match).

Get dotnet monitor from blob storage.

---

eng/dockerfile-templates/aspnet/7.0/Dockerfile.linux
eng/dockerfile-templates/aspnet/7.0/Dockerfile.mariner
eng/dockerfile-templates/runtime-deps/7.0/Dockerfile.mariner
eng/dockerfile-templates/runtime/7.0/Dockerfile.linux
eng/dockerfile-templates/runtime/7.0/Dockerfile.mariner
eng/dockerfile-templates/sdk/7.0/Dockerfile.linux
eng/dockerfile-templates/sdk/7.0/Dockerfile.mariner
src/aspnet/7.0/bullseye-slim/amd64/Dockerfile
src/aspnet/7.0/bullseye-slim/arm32v7/Dockerfile
src/aspnet/7.0/bullseye-slim/arm64v8/Dockerfile
src/aspnet/7.0/cbl-mariner1.0/amd64/Dockerfile
src/aspnet/7.0/focal/amd64/Dockerfile
src/aspnet/7.0/focal/arm32v7/Dockerfile
src/aspnet/7.0/focal/arm64v8/Dockerfile
src/runtime-deps/7.0/cbl-mariner1.0/amd64/Dockerfile
src/runtime/7.0/bullseye-slim/amd64/Dockerfile
src/runtime/7.0/bullseye-slim/arm32v7/Dockerfile
src/runtime/7.0/bullseye-slim/arm64v8/Dockerfile
src/runtime/7.0/cbl-mariner1.0/amd64/Dockerfile
src/runtime/7.0/focal/amd64/Dockerfile
src/runtime/7.0/focal/arm32v7/Dockerfile
src/runtime/7.0/focal/arm64v8/Dockerfile
src/sdk/7.0/bullseye-slim/amd64/Dockerfile
src/sdk/7.0/bullseye-slim/arm32v7/Dockerfile
src/sdk/7.0/bullseye-slim/arm64v8/Dockerfile
src/sdk/7.0/cbl-mariner1.0/amd64/Dockerfile
src/sdk/7.0/focal/amd64/Dockerfile
src/sdk/7.0/focal/arm32v7/Dockerfile
src/sdk/7.0/focal/arm64v8/Dockerfile

Fixing the .NET 7 Dockerfiles because the changes in https://github.com/dotnet/dotnet-docker/pull/3287 were never applied to them.

Update curl option for .NET 7 Dockerfiles

---

eng/dockerfile-templates/runtime-deps/7.0/Dockerfile.mariner
src/runtime-deps/7.0/cbl-mariner1.0/amd64/Dockerfile

The changes from https://github.com/dotnet/dotnet-docker/pull/3271 never got applied to the 7.0 runtime-deps Dockerfile.

Mariner reference to prebuilt-ca-certificates pkg

---

eng/dockerfile-templates/sdk/3.1/Dockerfile.alpine
eng/dockerfile-templates/sdk/3.1/Dockerfile.nanoserver
eng/dockerfile-templates/sdk/5.0/Dockerfile.alpine
eng/dockerfile-templates/sdk/5.0/Dockerfile.nanoserver
eng/dockerfile-templates/sdk/6.0/Dockerfile.alpine
eng/dockerfile-templates/sdk/6.0/Dockerfile.nanoserver
src/sdk/3.1/alpine3.14/amd64/Dockerfile
src/sdk/3.1/alpine3.15/amd64/Dockerfile
src/sdk/3.1/nanoserver-1809/amd64/Dockerfile
src/sdk/3.1/nanoserver-20H2/amd64/Dockerfile
src/sdk/3.1/nanoserver-ltsc2022/amd64/Dockerfile
src/sdk/5.0/alpine3.14/amd64/Dockerfile
src/sdk/5.0/alpine3.15/amd64/Dockerfile
src/sdk/5.0/nanoserver-1809/amd64/Dockerfile
src/sdk/5.0/nanoserver-20H2/amd64/Dockerfile
src/sdk/5.0/nanoserver-ltsc2022/amd64/Dockerfile
src/sdk/6.0/alpine3.14/amd64/Dockerfile
src/sdk/6.0/alpine3.15/amd64/Dockerfile
src/sdk/6.0/nanoserver-1809/amd64/Dockerfile
src/sdk/6.0/nanoserver-20H2/amd64/Dockerfile
src/sdk/6.0/nanoserver-ltsc2022/amd64/Dockerfile

Fixing up a couple minor differences between the Dockerfile templates. This provides more consistency between the OS variations of the Dockerfiles and reduces diffs when comparing Dockerfiles across the OS.

Fix up Dockerfiles for consistency

---

tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs

These test scenarios can be enabled now that https://github.com/dotnet/templating/issues/4098 is fixed.

Remove workaround to disable .NET 7 test scenarios

---

eng/pipelines/stages/build-test-publish-repo.yml

The changes from https://github.com/dotnet/docker-tools/pull/941 exposed an issue in the test matrix generation related to .NET Core 3.1 sdk images for Debian/Ubuntu. Those Dockerfiles are based on buildpack-deps and so they don't have a direct dependency on the runtime-related Dockerfiles. However, for testing purposes we want them tested together. To accomplish this, the manifest defines a customBuildLegGroup named `test-dependencies` that causes the matrix generation to integrate these platforms for testing:
https://github.com/dotnet/dotnet-docker/blob/69758fdf9d02311de1247964a2c0d9621c3bb911/manifest.json#L3151-L3159
However, in the test stage of the build, this `test-dependencies` customBuildLegGroup was not enabled. This led the matrix generation to include two separate test legs: …

Use test dependencies for test matrix

---

README.monitor.md
manifest.json

.NET Monitor now has multiple versions for 6.x images. It would be useful to add major-only version tags to allows customers to pull the latest 6.x image. All 6.x images are backward compatible with lower minor versions.
I've applied the same for the 7.x image line so that customers can use the 7 major tags from the beginning of the 7.x development.

Add major-only version tags for .NET Monitor

---

eng/dockerfile-templates/runtime/6.0/Dockerfile.mariner-distroless
eng/dockerfile-templates/runtime/7.0/Dockerfile.mariner-distroless
src/runtime/6.0/cbl-mariner1.0-distroless/amd64/Dockerfile
src/runtime/7.0/cbl-mariner1.0-distroless/amd64/Dockerfile

This variable assignment pattern used in the distroless Mariner Dockerfile templates is unnecessary and inconsistent with the other templates.

Remove single quotes from var assignment

---

manifest.samples.json

The samples build is currently broken due to the validation introduced by https://github.com/dotnet/docker-tools/pull/941. It's causing duplicate test leg names because there are two separate leaves of the dependency tree (dotnetapp, aspnetapp) that are being placed in separate test legs. But because everything about them is the same, except for their Dockerfile path, it causes the test leg name to be identical between the two.
In this case, we don't actually want the test legs to be distinct. That would just cause duplication in the testing being done across two legs. What we want is for them to be combined into one test leg.
The manifest is already configured to at least enable this combined test job scenario, but only for PR builds. The fix is to just change the customBuildLegGroup …

Fix test matrix generation of samples

---

README.monitor.md
eng/dockerfile-templates/monitor/6.0/Dockerfile.alpine
eng/dockerfile-templates/monitor/6.1/Dockerfile.alpine
eng/dockerfile-templates/monitor/7.0/Dockerfile.alpine
manifest.versions.json
src/monitor/6.0/alpine/amd64/Dockerfile
src/monitor/6.1/alpine/amd64/Dockerfile
src/monitor/7.0/alpine/amd64/Dockerfile

This change updates the .NET Monitor templates to use the product version for the package version and the build version as part of the blob container name for release and servicing builds. The builds of .NET Monitor publish their nupkg files under a blob container that has the build version as one of its folders to allow stable version builds to not collide. Prerelease builds produce package versions that are unique for every build, hence why the 7.0 template still uses the build version for its package version.
The 6.0 and 6.1 lines have been updated to the latest builds using stable branding.

Use build versions in .NET Monitor URLs and stable branding.

---

eng/dockerfile-templates/monitor/7.0/Dockerfile.alpine
src/monitor/7.0/alpine/amd64/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/TestData.cs
tests/performance/ImageSize.nightly.linux.json

Applies following changes to `dotnet-monitor`s 7.0 image:
- Change over to using 7.0 SDK image (image used for `dotnet tool install`)
- Removes `net6.0` compiled version of `dotnet-monitor` from image
- Changes base image that we ship on to `aspnet 7.0`

Convert dotnet-monitor 7.0 image to using 7.0 TFM

---

eng/dockerfile-templates/sdk/3.1/Dockerfile.alpine
eng/dockerfile-templates/sdk/3.1/Dockerfile.linux
eng/dockerfile-templates/sdk/3.1/Dockerfile.mariner
eng/dockerfile-templates/sdk/3.1/Dockerfile.nanoserver
src/sdk/3.1/alpine3.14/amd64/Dockerfile
src/sdk/3.1/alpine3.15/amd64/Dockerfile
src/sdk/3.1/bionic/amd64/Dockerfile
src/sdk/3.1/bionic/arm32v7/Dockerfile
src/sdk/3.1/bionic/arm64v8/Dockerfile
src/sdk/3.1/bullseye/amd64/Dockerfile
src/sdk/3.1/bullseye/arm32v7/Dockerfile
src/sdk/3.1/bullseye/arm64v8/Dockerfile
src/sdk/3.1/buster/amd64/Dockerfile
src/sdk/3.1/buster/arm32v7/Dockerfile
src/sdk/3.1/buster/arm64v8/Dockerfile
src/sdk/3.1/cbl-mariner1.0/amd64/Dockerfile
src/sdk/3.1/focal/amd64/Dockerfile
src/sdk/3.1/focal/arm32v7/Dockerfile
src/sdk/3.1/focal/arm64v8/Dockerfile
src/sdk/3.1/nanoserver-1809/amd64/Dockerfile
src/sdk/3.1/nanoserver-20H2/amd64/Dockerfile
src/sdk/3.1/nanoserver-ltsc2022/amd64/Dockerfile

All Dockerfiles 5.0 and above use `sdk_version` instead of `dotnet_sdk_version` for the variable in the Dockerfile so I'm standardizing on that. Plus it's just a shorter name which is preferable.

Use consistent variable names between .NET versions

---

eng/dockerfile-templates/sdk/5.0/Dockerfile.windowsservercore
eng/dockerfile-templates/sdk/6.0/Dockerfile.windowsservercore
eng/dockerfile-templates/sdk/7.0/Dockerfile.windowsservercore
src/sdk/5.0/windowsservercore-ltsc2019/amd64/Dockerfile
src/sdk/5.0/windowsservercore-ltsc2022/amd64/Dockerfile
src/sdk/6.0/windowsservercore-ltsc2019/amd64/Dockerfile
src/sdk/6.0/windowsservercore-ltsc2022/amd64/Dockerfile
src/sdk/7.0/windowsservercore-ltsc2019/amd64/Dockerfile
src/sdk/7.0/windowsservercore-ltsc2022/amd64/Dockerfile

The list of files and directories are not consistently ordered between Nano Server and Windows Server Core sdk Dockerfiles. I've updated the Windows Server Core Dockerfiles to list files before directories, which is consistent with Nano Server.

Use consistent ordering of extraction paths

---

eng/dockerfile-templates/monitor/6.0/Dockerfile.alpine
eng/dockerfile-templates/monitor/6.1/Dockerfile.alpine
src/monitor/6.0/alpine/amd64/Dockerfile
src/monitor/6.1/alpine/amd64/Dockerfile
tests/performance/ImageSize.nightly.linux.json

Applies image stripping done for `7.0` image to `6.0` and `6.1` images.
Update image size for all dotnet-monitor images.
`src/monitor/6.0/alpine/amd64` Image contents:
```
drwxr-xr-x 0/0               0 2022-02-04 11:42 app/
drwxr-xr-x 0/0               0 2022-02-04 11:42 app/.store/
drwxr-xr-x 0/0               0 2022-02-04 11:42 app/.store/dotnet-monitor/
drwxr-xr-x 0/0               0 2022-02-04 11:42 app/.store/dotnet-monitor/6.0.2/
drwxr-xr-x 0/0               0 2022-02-04 11:42 app/.store/dotnet-monitor/6.0.2/dotnet-monitor/
drwxr-xr-x 0/0               0 2022-02-04 11:42 app/.store/dotnet-monitor/6.0.2/dotnet-monitor/6.0.2/
drwxr-xr-x 0/0               0 2022-02-04 11:42 app/.store/dotnet-monitor/6.0.2/dotnet-monitor/6.0.2/tools/
drwxr-xr-x 0/0               0 2022-02-04 11:42 …
```

Dotnet-Monitor reduce image size

---

eng/dockerfile-templates/sdk/7.0/Dockerfile.mariner
manifest.versions.json
src/sdk/7.0/cbl-mariner1.0/amd64/Dockerfile

Currently the 7.0 sdk Dockerfile template differs from the other .NET versions when it comes to constructing the URL of targeting packs. This is because 7.0 is in active development and targeting packs get produced with each new product build. So the version of the targeting pack matches the version of the respective runtime. For past released versions, however, the targeting pack releases stabilize, having a version that differs from the runtime version.
To handle this, the 7.0 sdk Dockerfile uses the runtime version environment variable in the URL path because the version of the targeting pack always matches the version of the runtime. There's a better way to do this that provides a consistent Dockerfile template across .NET versions. Templates for past released versions reference a …

Use consistent templates for targeting pack RPM URLs

---

README.monitor.md
eng/mcr-tags-metadata-templates/monitor-tags.yml
eng/readme-templates/README.md

Remove sub table title for 6.1

Update .NET Monitor featured tags

---

eng/pipelines/cg-images.yml

Component detection of container images had been broken for a while and just fixed by https://github.com/dotnet/docker-tools/pull/968. However, now that scanning is running again we're running into disk space issues on the agent. The agent is running out of space when it attempts to scan the images because it saves each image to a tarball for scanning.
To workaround this, I'm splitting the scanning into arch-specific jobs so that each agent has to deal with less images.

Split image scanning into arch-specific jobs

---

eng/dockerfile-templates/monitor/Dockerfile

This change allows acquisition of the .NET Monitor package from the dotnetcli storage account regardless of the branch in which the Dockerfiles are generated if (1) the product and build versions are the same and (2) the product version is a stable version (doesn't have -* label). This allows merges back from main to nightly without accidentally regenerating the Dockerfiles to use dotnetstage storage account if the above conditions hold.
This currently does not cause changes in the nightly branch because the 6.0.* and 6.1.* lines have product versions different from their build versions and the 7.0.* line is not a stable version.

.NET Monitor: Get package from dotnetcli if stable product version

---

README.monitor.md
manifest.json
src/monitor/6.1/alpine/amd64/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/TestData.cs

Alpine 3.15 images will not be available for .NET 6 when .NET Monitor 6.1.0 ships, thus rollback to Alpine 3.14 base image.

Rollback .NET Monitor 6.1.0 to use Alpine 3.14

---

tests/Microsoft.DotNet.Docker.Tests/SampleImageTests.cs

Disable sample test for Windows Server version 20H2 due to a `dotnet restore` issue: https://github.com/dotnet/dotnet-docker/issues/3510.

Disable sample test for Windows

---

eng/dockerfile-templates/Dockerfile.linux.install-deps
src/runtime-deps/6.0/cbl-mariner1.0/amd64/Dockerfile
src/runtime-deps/7.0/cbl-mariner1.0/amd64/Dockerfile

The `prebuilt-ca-certificates` package should only be used for distroless implementations of CBL-Mariner. Otherwise, it can lead to conflicts with the existing cert packages that are installed in full Mariner. See https://dev.azure.com/microsoft/OS/_workitems/edit/38162114. Instead, the non-prebuilt version of the package should be used: `ca-certificates-microsoft`.

Use correct ca-certs pkg for full Mariner

---

tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs

Now that https://github.com/dotnet/core-eng/issues/15492 is fixed, these tests can be enabled again.
Fixes #3448

Re-enable distroless Mariner test

---

documentation/supported-tags.md

Updates the documentation to indicate our policy for updating floating tags. This new policy includes an evaluation period allowing customers to try out the new OS version before we update the floating tag.

Policy for updating floating tags

---

tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs

Changes were made in https://github.com/dotnet/dotnet-docker/commit/c2b14dc92c29fb8d60c7aae49cd4895de59c687e#diff-374c24707f197ad0b90b129473a517046626f7148c795b21c9155a978d83b2ad that removed the disable of PowerShell tests for Alpine 3.15. This should only be done for AMD64 but not for Arm32/Arm64 because PowerShell doesn't support musl-based Arm. There was an existing check for this that was incorrectly specific to 6.0 so I've generalized it to be broader.

Disable PowerShell-related tests on Alpine for Arm arch

---

eng/package-scripts/cbl-mariner-distroless/dotnet7/get-installed-packages.sh

In the main branch, 7.0 defines its own Mariner distroless Dockerfiles for Mariner 2.0, not shared with 6.0 because Mariner 2.0 isn't released yet. The get-installed-packages script needs to reflect that Dockerfile path difference.

Fix installed-packages script for 7.0 Mariner distroless

---

tests/Microsoft.DotNet.Docker.Tests/DockerRunArgsBuilder.cs
tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs
tests/Microsoft.DotNet.Docker.Tests/MonitorImageTests.cs

Only applies to .NET Monitor 6.1 and later, which have the `machinejson` output option for API key generation.
closes #3209

Add authentication validation for .NET Monitor images

---

README.monitor.md
manifest.json

The major version only tags should remain on the image that will be shipping next to ease the update process in the main branch until the next version is ready to be shipped. We anticipate that 6.2 will NOT ship in April, thus the 6 and 6-* tags should remain on the 6.1 image.

Move the .NET Monitor 6 and 6-* tags back to the 6.1 image

---

tests/performance/ImageSize.nightly.linux.json

New assemblies exist within the version introduced by https://github.com/dotnet/dotnet-docker/pull/3580 which increased the size.

Update image size baseline for .NET Monitor

---

tests/performance/ImageSize.nightly.linux.json

We've removed a handful of files from the .NET Monitor package in the latest build, so I'm updating the baseline sizes to account for the change.

Update .NET Monitor 7.0 baseline sizes

---

tests/performance/ImageSize.nightly.linux.json

This updates the baseline for `src/monitor/6.2/cbl-mariner/arm64v8` to the real value generated by the validate build.

Update Baseline for dotnet-monitor 6.2 cbl-mariner arm64v8

---

tests/performance/ImageSize.nightly.linux.json

This updates the baseline for `src/monitor/7.0/cbl-mariner/arm64v8` to the real value generated by the validate build.

Update Baseline for dotnet-monitor 7.0 cbl-mariner arm64v8

---

eng/dockerfile-templates/runtime-deps/Dockerfile
src/runtime-deps/6.0/cbl-mariner2.0-distroless/amd64/Dockerfile
src/runtime-deps/6.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile

When building the runtime-deps Dockerfile for the distroless version of Mariner 1.0, a warning shows up in the output:
```
adduser warning: app's uid 1000 outside of the SYS_UID_MIN 101 and SYS_UID_MAX 999 range.
```
This happens because `adduser` is called to create a system user with an ID of 1000. The 1000 value was used initially because that's the min value for a normal user (UID_MIN). This was mistakenly used because we're actually creating a system user which have a different range of IDs (101 - 999). (System groups have the same range but, for whatever reason, `groupadd` doesn't show such an error even though we're also setting it to 1000.) Functionally, the user still works. There may be some undiscovered issues with having such an ID though.
These changes update to use the min …

Update UID of non-root user for Mariner 2.0

---

eng/dockerfile-templates/Dockerfile.common-dotnet-envs
eng/dockerfile-templates/Dockerfile.linux.install-deps
src/runtime-deps/3.1/alpine3.14/amd64/Dockerfile
src/runtime-deps/3.1/alpine3.14/arm64v8/Dockerfile
src/runtime-deps/3.1/alpine3.15/amd64/Dockerfile
src/runtime-deps/3.1/alpine3.15/arm64v8/Dockerfile
src/runtime-deps/5.0/alpine3.14/arm32v7/Dockerfile
src/runtime-deps/5.0/alpine3.15/arm32v7/Dockerfile
src/runtime-deps/6.0/cbl-mariner2.0-distroless/amd64/Dockerfile
src/runtime-deps/6.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/CommonRuntimeImageTests.cs

This removes the ICU package from distroless Mariner 2.0 for both .NET 6 and 7.
Alpine Dockerfiles ended up having some comments updated in order to have a consistent comment that isn't specific to the name of the ICU package.
Fixes #3394

Remove ICU package from distroless version of Mariner 2.0

---

README.aspnet.md
README.md
README.monitor.md
README.runtime-deps.md
README.runtime.md
README.samples.md
README.sdk.md
documentation/supported-tags.md
eng/readme-templates/README.md

* Clarified the documentation to explicitly state that unlisted tags are not supported.
* Added links to the Supported Platforms and Supported Tags docs in the support section of the readmes.
* Expanded the Tag Lifecycle section in Supported Tags to describe how tags are maintained after a .NET version reaches EOL.

Update support policy docs

---

eng/Set-DotnetVersions.ps1
eng/get-drop-versions.sh
eng/update-dependencies/BaseUrlUpdater.cs
eng/update-dependencies/DockerfileShaUpdater.cs
eng/update-dependencies/ManifestHelper.cs
eng/update-dependencies/NuGetConfigUpdater.cs
eng/update-dependencies/Options.cs
eng/update-dependencies/UpdateDependencies.cs
eng/update-dependencies/VersionUpdater.cs

This is further work to support https://github.com/dotnet/dotnet-docker/issues/2152. It updates the update-dependencies tool to handle several aspects of internal builds:
* Targets internal URLs with SAS token when executing the logic to get the checksum of the installer file.
* Update the appropriate base URL manifest variable from `public` to `internal`.
* Updates the test project's NuGet.config file to include a URL for the internal build's NuGet feed.
Related to the update-dependencies tool is the `get-drop-versions.sh` script. This script determines the product versions of the latest build that are used as input to the update-dependencies tool. I've also updated this script to be able to target internal builds.

Update-dependencies support for internal .NET builds

---

eng/dockerfile-templates/aspnet/Dockerfile.linux
eng/dockerfile-templates/runtime-deps/Dockerfile
eng/dockerfile-templates/runtime/Dockerfile.linux
src/aspnet/6.0/cbl-mariner1.0-distroless/amd64/Dockerfile
src/aspnet/6.0/cbl-mariner2.0-distroless/amd64/Dockerfile
src/aspnet/6.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile
src/aspnet/7.0/cbl-mariner2.0-distroless/amd64/Dockerfile
src/aspnet/7.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile
src/runtime-deps/3.1/cbl-mariner1.0/amd64/Dockerfile
src/runtime-deps/5.0/cbl-mariner1.0/amd64/Dockerfile
src/runtime-deps/6.0/cbl-mariner1.0-distroless/amd64/Dockerfile
src/runtime-deps/6.0/cbl-mariner1.0/amd64/Dockerfile
src/runtime-deps/6.0/cbl-mariner2.0-distroless/amd64/Dockerfile
src/runtime-deps/6.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile
src/runtime-deps/6.0/cbl-mariner2.0/amd64/Dockerfile
src/runtime-deps/6.0/cbl-mariner2.0/arm64v8/Dockerfile
src/runtime-deps/7.0/cbl-mariner2.0/amd64/Dockerfile
src/runtime-deps/7.0/cbl-mariner2.0/arm64v8/Dockerfile
src/runtime/6.0/cbl-mariner1.0-distroless/amd64/Dockerfile
src/runtime/6.0/cbl-mariner2.0-distroless/amd64/Dockerfile
src/runtime/6.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile
src/runtime/7.0/cbl-mariner2.0-distroless/amd64/Dockerfile
src/runtime/7.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile

CBL-Mariner image tags are available on MCR now. I've updated all usage of `cblmariner.azurecr.io` to `mcr.microsoft.com/cbl-mariner`.

Change Mariner to use MCR instead of ACR

---

eng/pipelines/update-dependencies.yml

The update-dependencies pipeline is currently broken due to changes from https://github.com/dotnet/dotnet-docker/pull/3745. It's failing due to unbound variables for the get-drop-versions.sh script. These variables are not being passed in by the pipeline.
There are more extensive changes needed in order for this pipeline to support internal builds. For example, it would need to create a PR in AzDO instead of GitHub. So just to unblock things for now, I've defaulted the new parameters so that internal builds are not accounted for.

Update-deps pipeline changes to support get-drop-versions.sh script

---

manifest.versions.json

The 6.0 Dockerfiles were removed in #3742, however the version and hash value variables were left behind.

Remove unused .NET Monitor 6.0 version variables

---

eng/update-dependencies/BaseUrlUpdater.cs
eng/update-dependencies/ManifestHelper.cs
eng/update-dependencies/NuGetConfigUpdater.cs

There are two issues with the update-dependencies tool caused by the changes in https://github.com/dotnet/dotnet-docker/pull/3745:
* An NRE occurs when attempting to update the version for .NET Monitor. This happens because `BaseUrlUpdater` is not constructing the URL variable correctly. This is described in https://github.com/dotnet/dotnet-docker/issues/3769. I've fixed this by updating the logic to construct a variable name specific to .NET Monitor when appropriate.
* The will throw this error for the base .NET Dockerfiles: `System.Exception: 'git status' does not match DependencyInfo information. Git has modified files: False. DependencyInfo is updated: True.` This happens because of `NuGetConfigUpdater` causing it to seem like the file is updated without actually updating the file. …

Update dependencies fixes

---

tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/CommonRuntimeImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/Config.cs
tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
tests/Microsoft.DotNet.Docker.Tests/EnvironmentVariableInfo.cs
tests/Microsoft.DotNet.Docker.Tests/ImageData.cs
tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs
tests/Microsoft.DotNet.Docker.Tests/OS.cs
tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/RuntimeDepsImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/RuntimeImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.linux
tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.windows
tests/run-tests.ps1

Related to https://github.com/dotnet/dotnet-docker/issues/2152
This updates the test project to allow internal .NET builds to be targeted. It needs the SAS query string in order to be able to download the SDK for file comparison validation. It also needs the NuGet feed password to be able to authenticate for NuGet restore operations in the containers being tested.
A new test is added to verify that our built images do not accidentally contain any SAS tokens.

Test support for internal .NET builds

---

eng/update-dependencies/DockerfileShaUpdater.cs

When attempting to run the update-dependencies tool targeting an internal build of .NET Core 3.1, it ends up failing to resolve the checksums for the targeting packs. This produces errors which cause the execution to fail.
This happens because it's attempting to access these targeting pack files are stable versioned and don't exist at the dotnetclimsrc.blob.core.windows.net location. Because of the URL variable replacement, it ends up using the dotnetclimsrc.blob.core.windows.net hostname.
To fix this, I've added an additional fallback which is hardcoded to the dotnetcli.blob.core.windows.net hostname.

3.1 targeting pack support in update-dependencies tool

---

.mar/portal/README.aspnet.portal.md
.mar/portal/README.monitor.portal.md
.mar/portal/README.runtime-deps.portal.md
.mar/portal/README.runtime.portal.md
.mar/portal/README.samples.portal.md
.mar/portal/README.sdk.portal.md
eng/readme-templates/About.md
eng/readme-templates/Announcement.md
eng/readme-templates/Get-GeneratedReadmes.ps1
eng/readme-templates/README.mcr.md
eng/readme-templates/README.md
eng/readme-templates/RelatedRepos.md
eng/readme-templates/Url.md
eng/readme-templates/Use.aspnet.md
eng/readme-templates/Use.md
eng/readme-templates/Use.monitor.md
eng/readme-templates/Use.product-family.md
eng/readme-templates/Use.runtime-deps.md
eng/readme-templates/Use.runtime.md
eng/readme-templates/Use.samples.md
eng/readme-templates/Use.sdk.md
manifest.json
manifest.samples.json

The two sets of readmes that we have between DH and MAR should have links which are relative to those sites. In other words, readmes hosted in DH should contain links to DH pages while readmes hosted in MAR should contain links to MAR pages.
I've updated the readme templates to use a sub-template which will generate the appropriate URL depending on the context of the readme host site.
Since MAR doesn't have product family pages currently, I resorted to using a search query to approximate that.

Reference MAR URLs in readmes for MAR portal

---

eng/get-drop-versions.sh
eng/update-dependencies/NuGetConfigUpdater.cs
tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs

These changes contain several infrastructure and test fixes related to supporting [internal .NET builds](https://github.com/dotnet/dotnet-docker/issues/2152):
* The `get-drop-versions.sh` script needs to compensate for the SDK URL containing slashes in the SAS query string when parsing to find the SDK version.
* The logic to update the nuget.config file in the update-dependencies tool requires some fixes:
* Don't remove the `packageSourceCredentials` element on successive runs.
* Use a slightly different NuGet feed URL for .NET Core 3.1 compared to later .NET versions.
* Test execution needs to always provide the NuGet feed password if it's provided when building a test Dockerfile. Before it was only providing it if the version being tested was internal. But other non-internal versions …

Misc fixes to support internal .NET builds

---

eng/dockerfile-templates/runtime-deps/Dockerfile
eng/dockerfile-templates/runtime-deps/Dockerfile.download-runtime-deps-pkg
eng/dockerfile-templates/runtime/Dockerfile.linux.install-runtime
eng/dockerfile-templates/sdk/Dockerfile.linux
eng/dockerfile-templates/sdk/Dockerfile.linux.install-sdk

As part of the work to [support internal builds](https://github.com/dotnet/dotnet-docker/issues/2152), I discovered that the Dockerfiles were being incorrectly generated for this scenario.
There are various issues fixed by these changes.
You can see the effect of these changes by looking at this branch comparison: https://github.com/mthalman/dotnet-docker/compare/3.1-internal-before...mthalman:3.1-internal-after?expand=1

Dockerfile template fixes for internal .NET builds

---

eng/dockerfile-templates/runtime-deps/Dockerfile
src/runtime-deps/6.0/cbl-mariner1.0-distroless/amd64/Dockerfile
src/runtime-deps/6.0/cbl-mariner2.0-distroless/amd64/Dockerfile
src/runtime-deps/6.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile
tests/performance/ImageSize.nightly.linux.json

Fixes https://github.com/dotnet/dotnet-docker/issues/3795
In addition to fixing the `dnf` -> `tdnf` issue, I also removed documentation-related files in the `/usr/share/man` and `/usr/share/doc` directories.

Reduce Mariner distroless image size

---

eng/Set-DotnetVersions.ps1

The update-dependencies tool requires that the `--version-source-name` parameter is passed for .NET Monitor due to .NET Monitor having its own url version variables in versions.manifest.json. Without it, it causes a NRE when attempting to look up the variable key constructed from the .NET Monitor version.

Set version source name in Set-DotnetVersions.ps1 script

---

README.sdk.md
eng/dockerfile-templates/monitor/Dockerfile
manifest.json
src/monitor/6.1/alpine/amd64/Dockerfile
src/monitor/6.2/alpine/amd64/Dockerfile
src/monitor/6.2/alpine/arm64v8/Dockerfile
src/monitor/7.0/alpine/amd64/Dockerfile
src/monitor/7.0/alpine/arm64v8/Dockerfile

Updates the nightly branch to have the [hotfix tag change](https://github.com/dotnet/dotnet-docker/pull/3847) reverted since we don't want to have this tag suffix applied for the next release.

Remove tag change for Alpine 3.16 localization hotfix

---

eng/dockerfile-templates/monitor/Dockerfile
manifest.json
src/monitor/6.1/alpine/amd64/Dockerfile
src/monitor/6.1/cbl-mariner/amd64/Dockerfile
src/monitor/6.2/alpine/amd64/Dockerfile
src/monitor/6.2/alpine/arm64v8/Dockerfile
src/monitor/6.2/cbl-mariner-distroless/amd64/Dockerfile
src/monitor/6.2/cbl-mariner-distroless/arm64v8/Dockerfile
src/monitor/6.2/cbl-mariner/amd64/Dockerfile
src/monitor/6.2/cbl-mariner/arm64v8/Dockerfile
src/monitor/7.0/alpine/amd64/Dockerfile
src/monitor/7.0/alpine/arm64v8/Dockerfile
src/monitor/7.0/cbl-mariner-distroless/amd64/Dockerfile
src/monitor/7.0/cbl-mariner-distroless/arm64v8/Dockerfile
src/monitor/7.0/cbl-mariner/amd64/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/OS.cs
tests/Microsoft.DotNet.Docker.Tests/TestData.cs
tests/performance/ImageSize.nightly.linux.json

These changes add CBL-Mariner distroless images for .NET Monitor for the 6.2 and 7.0 versions.
Image baseline sizes were calculated using the relative difference between the ASP.NET and .NET Monitor images for the CBL-Mariner images (non-distroless).
Other adjustments were made so that file permissions were changed while on the SDK container instead of the ASP.NET container since `chmod` is not available in distroless images. Tested the permissions on a few of the images locally.

.NET Monitor CBL-Mariner Distroless Images

---

tests/performance/ImageSize.nightly.linux.json
tests/performance/ImageSize.nightly.windows.json

Reasons for size differences:
* Alpine 3.16 SDK: Addition of the icu-data-full package (https://github.com/dotnet/dotnet-docker/pull/3847)
* CBL-Mariner 2.0 Arm64: A combination of https://github.com/dotnet/dotnet-docker/pull/3825, which added installation of local RPM files, and https://github.com/dotnet/dotnet-docker/issues/3864.
* Windows Server Core: Size increase in the servicing layer of the base Windows image.

Updates to image size baselines

---

eng/pipelines/update-dependencies.yml

The changes from https://github.com/dotnet/dotnet-docker/pull/3829 now cause the running of that script to include the `--version-source-name` in the output when using the `PrintArgsVariableOnly` option. This causes the update-dependencies tool to be executed with duplicate `--version-source-name` args which it doesn't like; it gives this error: `Option '--version-source-name' expects a single argument but 2 were provided.`
The fix is to simply remove the redundant arg option.

Remove redundant version-source-name arg for update-deps

---

eng/dockerfile-templates/monitor/Dockerfile
manifest.json
src/monitor/6.1/alpine/amd64/Dockerfile
src/monitor/6.1/cbl-mariner/amd64/Dockerfile
src/monitor/6.2/alpine/amd64/Dockerfile
src/monitor/6.2/alpine/arm64v8/Dockerfile
src/monitor/6.2/cbl-mariner-distroless/amd64/Dockerfile
src/monitor/6.2/cbl-mariner-distroless/arm64v8/Dockerfile
src/monitor/6.2/cbl-mariner/amd64/Dockerfile
src/monitor/7.0/alpine/amd64/Dockerfile
src/monitor/7.0/alpine/arm64v8/Dockerfile
src/monitor/7.0/cbl-mariner-distroless/amd64/Dockerfile
src/monitor/7.0/cbl-mariner-distroless/arm64v8/Dockerfile
src/monitor/7.0/cbl-mariner/amd64/Dockerfile
src/monitor/7.0/cbl-mariner/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/MonitorImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/OS.cs
tests/Microsoft.DotNet.Docker.Tests/TestData.cs
tests/performance/ImageSize.nightly.linux.json

This is a reimplementation of #3868 with one small difference.
The difference is that the tests that use the sample images are effectively filtered out for distroless images. The distroless images run as a non-root user, so .NET Monitor would need a sample image with a corresponding non-root user. None of the sample images are distroless, thus these tests cannot be run with the distroless version of .NET Monitor.

.NET Monitor CBL Mariner Distroless Images

---

eng/dockerfile-templates/Dockerfile.linux.install-rpms
src/aspnet/6.0/cbl-mariner2.0/amd64/Dockerfile
src/aspnet/6.0/cbl-mariner2.0/arm64v8/Dockerfile
src/aspnet/7.0/cbl-mariner2.0/amd64/Dockerfile
src/aspnet/7.0/cbl-mariner2.0/arm64v8/Dockerfile
src/runtime-deps/6.0/cbl-mariner2.0/amd64/Dockerfile
src/runtime-deps/6.0/cbl-mariner2.0/arm64v8/Dockerfile
src/runtime-deps/7.0/cbl-mariner2.0/amd64/Dockerfile
src/runtime-deps/7.0/cbl-mariner2.0/arm64v8/Dockerfile
src/runtime/6.0/cbl-mariner2.0/amd64/Dockerfile
src/runtime/6.0/cbl-mariner2.0/arm64v8/Dockerfile
src/runtime/7.0/cbl-mariner2.0/amd64/Dockerfile
src/runtime/7.0/cbl-mariner2.0/arm64v8/Dockerfile
src/sdk/6.0/cbl-mariner2.0/amd64/Dockerfile
src/sdk/6.0/cbl-mariner2.0/arm64v8/Dockerfile
src/sdk/7.0/cbl-mariner2.0/amd64/Dockerfile
src/sdk/7.0/cbl-mariner2.0/arm64v8/Dockerfile

This fixes #3864 by preventing the tdnf repo caches from ever being populated with the use of the `disablerepo` option. This is only done in cases where we're installing from a local RPM file that doesn't have any dependencies that aren't already installed.
Fixes #3864

Prevent tdnf cache from being populated

---

tests/Microsoft.DotNet.Docker.Tests/SampleImageTests.cs

Now that https://github.com/NuGet/Home/issues/11607 has been fixed, the test can be enabled again.
Fixes https://github.com/dotnet/dotnet-docker/issues/3510

Re-enable complex app sample test for Windows

---

tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs

These tests can be enabled now that https://github.com/dotnet/dotnet-docker/issues/3793 is fixed.
This is only relevant to the nightly branch. This change was already made as part of the merge from nightly to main in June servicing. But it never made its way back to nightly from the main-to-nightly merge.

Enable PowerShell tests for Alpine 3.16

---

eng/update-dependencies/Dockerfile

Updates the path to the NuGet.config file in the Dockerfile for update-dependencies because of the path change in https://github.com/dotnet/dotnet-docker/pull/3936.

Fix update-deps Dockerfile for NuGet.config path change

---

tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.linux
tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.windows

Updates the Dockerfiles used for unit testing so that they can support restoring NuGet packages from internal feeds. This occurs in the test stage of the Dockerfile which was added by https://github.com/dotnet/dotnet-docker/pull/3847. This was discovered after attempting to run a build/test pass on an internal 6.0 build. It ended up failing when attempting to run a container that ran the dynamically-generated unit test project: see https://github.com/dotnet/dotnet-docker/blob/1297d21bbf695bcb87580bea2ccefdced894eeeb/tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs#L68
This is because `dotnet test` will attempt to restore packages by default for the test project. But the Dockerfile stage hadn't been configured to use the `NuGetFeedPassword` environment variable needed by the …

Support internal NuGet feed in test stage of Dockerfiles for unit tests

---

eng/dockerfile-templates/Dockerfile.windows.set-path
eng/dockerfile-templates/runtime/Dockerfile.windows
eng/dockerfile-templates/runtime/Dockerfile.windows.set-path
eng/dockerfile-templates/sdk/Dockerfile.windows
eng/dockerfile-templates/sdk/Dockerfile.windows.set-powershell-path

The Windows Server Core Dockerfiles that are generated when targeting an internal .NET build are setting the user to ContainerAdministrator in order to set the `PATH` environment variable and then setting the user back to `ContainerUser`. This behavior is incorrect for the following reasons:
* It doesn't need to explicitly set the user to `ContainerAdministrator` in Windows Server Core because that's what it's running as by default.
* It's incorrect to switch the user to `ContainerUser` after setting the variable because we want to maintain the user as the default.
This was caught by new testing that was added in https://github.com/dotnet/dotnet-docker/pull/3863 verifying the correct user is set for Windows containers.
This only occurs for Dockerfiles generated for internal builds. In …

Windows templates: only switch user to set path for Nano Server

---

samples/complexapp/Dockerfile

The complexapp sample Dockerfile should explicitly restore the test project. Otherwise, the test project won't get restored until the container is actually executed, implicitly by the `dotnet test` ENTRYPOINT. That's wasteful because every execution of the container would cause it to get restored again. It only needs to get restored once and embedded within the image.

Sample Dockerfile: explicitly restore test project

---

eng/dockerfile-templates/monitor/Dockerfile
src/monitor/6.2/alpine/amd64/Dockerfile
src/monitor/6.2/alpine/arm64v8/Dockerfile
src/monitor/6.2/cbl-mariner-distroless/amd64/Dockerfile
src/monitor/6.2/cbl-mariner-distroless/arm64v8/Dockerfile
src/monitor/6.2/cbl-mariner/amd64/Dockerfile
src/monitor/6.2/cbl-mariner/arm64v8/Dockerfile
src/monitor/7.0/alpine/amd64/Dockerfile
src/monitor/7.0/alpine/arm64v8/Dockerfile
src/monitor/7.0/cbl-mariner-distroless/amd64/Dockerfile
src/monitor/7.0/cbl-mariner-distroless/arm64v8/Dockerfile
src/monitor/7.0/cbl-mariner/amd64/Dockerfile
src/monitor/7.0/cbl-mariner/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/MonitorImageTests.cs

Changes add a new environment variable to the 6.2+ images that will remove any existing Unix Domain Socket found at the listening server path (when that is configured) on startup. This allows for removing orphaned UDS from prior instances of dotnet-monitor and will avoid the Socket Error 48/98 address already is use issues.

.NET Monitor: Remove stale UDS on startup

---

eng/pipelines/update-dependencies.yml

A reference to renamed template file was missed in the changes from #3910.

Fix template name from changes in #3910

---

manifest.versions.json
src/monitor/6.2/alpine/amd64/Dockerfile
src/monitor/6.2/alpine/arm64v8/Dockerfile
src/monitor/6.2/cbl-mariner-distroless/amd64/Dockerfile
src/monitor/6.2/cbl-mariner-distroless/arm64v8/Dockerfile
src/monitor/6.2/cbl-mariner/amd64/Dockerfile
src/monitor/6.2/cbl-mariner/arm64v8/Dockerfile

Manually updating to latest candidate build due to broken update dependencies pipeline.

.NET Monitor 6.2.2 update

---

eng/update-dependencies/Options.cs

The changes from https://github.com/dotnet/dotnet-docker/pull/3910 are causing the normal (non-internal builds) scenarios from generating a PR when updates are made to files. It contains this message in the output: `Changes made but no GitHub credentials specified, skipping PR creation`.
This happens because a change was made to only generate a PR if the `target-branch` option is set. That option is only being set for the pipeline that handles internal builds.
To fix this, I've updated it to default the value of `target-branch` to be the value of `source-branch` if `target-branch` wasn't explicitly set. That's the value that's desired in these scenarios that target public builds.

Fix skipping of update-deps PR generation

---

eng/dockerfile-templates/runtime-deps/Dockerfile
src/runtime-deps/6.0/cbl-mariner1.0-distroless/amd64/Dockerfile
src/runtime-deps/6.0/cbl-mariner2.0-distroless/amd64/Dockerfile
src/runtime-deps/6.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile

The RPM DB is mistakenly being included in the distroless CBL-Mariner images. It's not needed because there is no package manager in distroless. This leads to about 500 KB of unnecessary image bloat.
Fixes #3941

Delete RPM DB in distroless CBL-Mariner

---

eng/pipelines/stages/build-test-publish-repo.yml
eng/pipelines/steps/set-base-image-override-options.yml
eng/pipelines/steps/set-imagebuilder-build-args-var.yml

Uses the base tag override options introduced by https://github.com/dotnet/docker-tools/pull/1031 to override the Ubuntu image tags so that they are retrieved from an ACR instead of Docker Hub.

Override Ubuntu image source location

---

eng/pipelines/steps/update-dotnet-dependencies.yml

The update-dependencies pipeline is currently broken after being updated to target .NET 7 RC1. This is due to the changes https://github.com/dotnet/dotnet-docker/pull/3910 and the fact that it's now attempting to create a PR.
When attempting to create the PR, it's failing because the parameters were configured to use a target branch of `internal/release/nightly`. That's the wrong target branch to be using for a non-internal build.
This is fixed by changing the build step which sets the target branch to only use the `internal/release/` prefix when targeting internal builds.

Fix target-branch for update-dependencies

---

eng/update-dependencies/MinGitShaUpdater.cs
eng/update-dependencies/MinGitUpdater.cs
eng/update-dependencies/MinGitUrlUpdater.cs

The update-dependencies pipeline is getting an error when attempting to update a .NET Monitor version that has no changes.
The error is the following:
```
Failed to update dependencies:
System.Exception: 'git status' does not match DependencyInfo information. Git has modified files: True. DependencyInfo is updated: False.
at Microsoft.DotNet.VersionTools.Automation.DependencyUpdateResults.ChangesDetected() in /_/src/Microsoft.DotNet.VersionTools/lib/src/Automation/DependencyUpdateResults.cs:line 46
at Dotnet.Docker.UpdateDependencies.ExecuteAsync(Options options) in /update-dependencies/UpdateDependencies.cs:line 82
```
This means there are git changes that have been detected but not expected based on the logic of what update-dependencies did.
This is happening because of the changes in …

Only update MinGet version for sdk changes

---

eng/dockerfile-templates/runtime/Dockerfile.linux
src/runtime/6.0/jammy-chiseled/amd64/Dockerfile
src/runtime/6.0/jammy-chiseled/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/ProductImageData.cs

This sets the default ENTRYPOINT in the Chiseled Ubuntu Dockerfiles so that they run `dotnet`. Having a default allows there to be a good UX when just running the container as is. This follows the same pattern that was used in https://github.com/dotnet/dotnet-docker/pull/3886.

Add default ENTRYPOINT for Chiseled Ubuntu

---

eng/pipelines/steps/set-imagebuilder-build-args-var.yml

This removes the platform check workaround that was added for Ubuntu's Arm64 images as part of https://github.com/dotnet/dotnet-docker/pull/3971. Those images had `docker inspect` metadata that didn't have the architecture variant set. Since ImageBuilder has a validation check to ensure the image meets our architecture expectations, the workaround was needed at that time. The images now have that metadata correctly populated which removes the need for this workaround.

Remove platform check workaround for Ubuntu Arm64

---

eng/pipelines/dotnet-core-internal-pr.yml
eng/pipelines/stages/build-test-publish-repo.yml

Due to the changes in https://github.com/dotnet/dotnet-docker/pull/3910, we now have the ability to create internal AzDO PRs that target internal builds of .NET. But we need to be able to run a build for that PR to validate the changes.
These changes add the pipeline that will be configured to run for any PR that targets the internal/release/nightly branch.
Related to https://github.com/dotnet/docker-tools/pull/1044 and https://github.com/dotnet/dotnet-docker/issues/2152.

Add pipeline to run builds for internal PRs

---

eng/dockerfile-templates/runtime-deps/Dockerfile
eng/dockerfile-templates/runtime-deps/Dockerfile.distroless-mariner
manifest.json

The runtime-deps Dockerfile template is pretty complex and hard for a human to parse. This is mainly due to the fact that it has logic used to generate distroless Mariner Dockerfiles in addition to the usual distroful Dockerfiles. Because distroless Mariner Dockerfiles are so different from the others, it causes a lot of extra stuff in the template to wade through.
As part of the implementation for [Chiseled Ubuntu](https://github.com/dotnet/dotnet-docker/pull/3996), those runtime-deps Dockerfiles had the same issue, being markedly different than all the other runtime-deps Dockerfiles. Because of that, a separate runtime-deps template was defined specifically for Chiseled Ubuntu. This kept all that content specific to Chiseled Ubuntu isolated from everything else.
These changes follow …

Refactor runtime-deps Dockerfile template

---

eng/pipelines/stages/build-test-publish-repo.yml
eng/pipelines/steps/set-custom-test-variables.yml

Related to https://github.com/dotnet/dotnet-docker/pull/4016
Internal PR builds fail when attempting to run tests. The call to invoke the tests is not configured with the secrets to access blob storage and NuGet feed. This is because the tests are run in the build stage. The pipeline was configured in a way that these secrets are only set in the test stage.
I've updated this to factor things out for setting custom test variables such that it is shared by both the build and test stage.

Set custom test variables in build job

---

tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
tests/Microsoft.DotNet.Docker.Tests/MonitorImageTests.cs

Currently, the distroless .NET Monitor image does not participate in the scenario tests because the filtering criteria requires that the .NET Monitor image and the sample image are the same type in terms of distroless vs non-distroless. This is not strictly necessary because non-distroless .NET Monitor can connect to either image type and distroless .NET Monitor can listen for either image type. These changes broaden the test combinations as described to allow distroless images to be mixed with non-distroless images in the scenario tests.

Enable .NET Monitor distroless image scenario testing

---

eng/pipelines/update-dependencies-internal.yml

The pipeline for the internal version of update-dependencies runs every day. But that schedule doesn't actually align with the workflow that occurs for testing internal builds of the product. Even though new builds are available, those builds aren't staged. Once a build is staged then its internal NuGet package feed is created. Prior to then, it's not possible to run the container tests because they rely on the NuGet package feed. So checking for new builds every day doesn't make sense. It only needs to be done as new builds are staged. As a result, these changes update the pipeline to remove the schedule trigger and just have it run manually at this point.

Disable scheduled build of internal update-dependencies

---

eng/pipelines/dotnet-core-internal-nightly.yml

Adds the pipeline that will handle building the `internal/release/nightly` branch to publish internal build of .NET.
It's been hardcoded to prevent the publishing of readmes, Kusto data, and the image info file.
Related to https://github.com/dotnet/dotnet-docker/issues/2152

Pipeline for building internal/release/nightly

---

eng/dockerfile-templates/runtime-deps/Dockerfile.chiseled-ubuntu
eng/dockerfile-templates/runtime-deps/Dockerfile.distroless-mariner
eng/dockerfile-templates/runtime-deps/Dockerfile.linux.distroless-user
manifest.json
src/runtime-deps/7.0/cbl-mariner2.0-distroless/amd64/Dockerfile
src/runtime-deps/7.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile
tests/performance/ImageSize.nightly.linux.json

The intention of the distroless containers for Mariner is to have a hardened environment specific for running a .NET application. To achieve this, a non-root user named `app` is defined and configured to be used by default. However, this only adds a user. It doesn't remove the existing users that are already defined. This means you can still run the container as root:
```console
> docker run --rm --user root mcr.microsoft.com/dotnet/runtime:7.0-cbl-mariner2.0-distroless
Host:
Version:      7.0.0-preview.7.22375.6
Architecture: x64
Commit:       eecb028078
...
```
Here is the full set of users in the container as indicated by the contents of the `/etc/passwd` file:
```
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/dev/null:/bin/false
daemon:x:6:6:Daemon User:/dev/null:/bin/false …
```

Define single user for distroless Mariner in .NET 7

---

eng/update-dependencies/NuGetConfigUpdater.cs

The update-dependencies tool doesn't correctly handle updates to the test NuGet.config file when multiple internal versions are being targeted in a branch. It ends up deleting the internal configuration from a previous run.
For example, let's say you've run update-dependencies for an internal build of .NET 6. It will have updated the test [NuGet.config](https://github.com/dotnet/dotnet-docker/blob/main/tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/NuGet.config.nightly) file to include package source and credentials named `dotnet6_0_internal`. After committing those changes you then run update-dependencies again, this time targeting an internal build of .NET 7. Doing that will remove the `dotnet6_0_internal` entries and replace them with `dotnet7_0_internal`. This will cause testing …

update-dependencies: support multiple internal versions

---

eng/dockerfile-templates/sdk/Dockerfile.windows.install-components

Building an SDK Dockerfile for Windows Server Core that is generated to target internal .NET builds fails because the MSBuild server is running while attempting to remove files to prepare the dotnet directory for copying:
```
Step 5/12 : RUN powershell -Command "         $ErrorActionPreference = 'Stop';         $ProgressPreference = 'SilentlyContinue';                 $sdk_version = '7.0.100-rc.1.22429.3';         Invoke-WebRequest -OutFile dotnet.zip https://dotnetbuilds.blob.core.windows.net/internal/Sdk/$sdk_version/dotnet-sdk-$sdk_version-win-x64.zip$Env:SAS_QUERY_STRING;         $dotnet_sha512 = '8f46d0c6e7c0d04c42592546447fc4b7376ab32ec1227413a73c2835fe79e3fbee5df7a0481690e4bbcd93f0ca1f51b4c1116b034184a2a1ff389ca936777aa5';         if ((Get-FileHash dotnet.zip -Algorithm …
```

Shutdown build server in multi-stage Windows Dockerfiles

---

eng/dockerfile-templates/aspnet/Dockerfile.linux.install-aspnet
eng/dockerfile-templates/aspnet/Dockerfile.windows.install-aspnet
eng/dockerfile-templates/runtime-deps/Dockerfile.download-runtime-deps-pkg
eng/dockerfile-templates/runtime/Dockerfile.linux.install-runtime
eng/dockerfile-templates/runtime/Dockerfile.windows.install-runtime
eng/dockerfile-templates/sdk/Dockerfile.linux.install-sdk
eng/dockerfile-templates/sdk/Dockerfile.windows.install-sdk

Generating Dockerfiles for internal preview builds of .NET 7 is generating incorrect URLs for the binary files to be downloaded from blob storage. It's using a stable branding pattern for the filename when it should be use the full build version. For example, it's using `dotnet-runtime-deps-7.0.0-rc.1-cm.2-aarch64.rpm` when it should be using `dotnet-runtime-deps-7.0.0-rc.1.22426.10-cm.2-aarch64.rpm`.
I've updated the Dockerfile templates to account for this by checking the label in the build version. Unfortunately, this needs to be repeated in all the templates.

Update Dockerfiles to not use stable branding for internal previews

---

eng/pipelines/dotnet-core-internal-nightly.yml
eng/pipelines/stages/build-test-publish-repo.yml
eng/pipelines/steps/set-custom-test-variables.yml

The repo prefix for the internal repo is defined incorrectly in the `publishRepoPrefix` variable for the internal pipeline. See https://github.com/dotnet/docker-tools/pull/1048.
Updated with the correct repo name.

Use correct publishRepoPrefix for internal builds

---

eng/dockerfile-templates/sdk/Dockerfile.linux
src/sdk/6.0/cbl-mariner2.0/amd64/Dockerfile
src/sdk/6.0/cbl-mariner2.0/arm64v8/Dockerfile
src/sdk/7.0/cbl-mariner2.0/amd64/Dockerfile
src/sdk/7.0/cbl-mariner2.0/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs

Ensure tar installed in SDK for Mariner 2.0

---

eng/Get-DropVersions.ps1
eng/Get-IsStableBranding.ps1
eng/Get-MonitorDropVersions.ps1
eng/Set-DotnetVersions.ps1
eng/pipelines/steps/update-dependencies.yml
eng/pipelines/steps/update-dotnet-dependencies.yml
eng/pipelines/update-dependencies-internal.yml
eng/pipelines/update-dependencies.yml

This updates the infrastructure related to update-dependencies so that it can support the targeting of multiple SDK versions. This is necessary for https://github.com/dotnet/dotnet-docker/issues/2152. By having the update-dependencies pipeline generate a PR that targets multiple internal builds of .NET. This approach is mentioned in https://github.com/dotnet/dotnet-docker/issues/2152#issuecomment-1150402553. This allows the `internal/release/nightly` branch to remain up-to-date with the latest updates from `nightly` but also have the latest internal .NET builds applied to it for each PR.
When targeting internal builds, we'll have an `sdkVersions` pipeline variable that will be used to explicitly define which builds should be targeted. But for the public builds, those will continue to be …

Support multiple SDK versions in update-dependencies

---

eng/pipelines/dotnet-core-internal-nightly.yml
eng/pipelines/dotnet-core-internal-pr.yml
eng/pipelines/variables/internal-core.yml

This updates the pipeline for publishing images of internal .NET builds so that it can support image caching. Image caching relies on an image info file being stored in a repo. Because these images are only available internally, this was originally disabled in order to prevent them from showing up in the default location: https://github.com/dotnet/versions/tree/main/build-info/docker.
Due to the changes in https://github.com/dotnet/docker-tools/pull/1055, it's now possible to target an internal repo as the location for storing image info files. So now the pipeline is updated to target the dotnet-docker-internal repo and caching has been enabled.
Related to https://github.com/dotnet/dotnet-docker/pull/4039 and https://github.com/dotnet/docker-tools/pull/1055

Enable image caching support for internal pipelines

---

eng/dockerfile-templates/monitor/Dockerfile
manifest.versions.json
src/monitor/6.2/alpine/amd64/Dockerfile
src/monitor/6.2/alpine/arm64v8/Dockerfile
src/monitor/6.2/cbl-mariner-distroless/amd64/Dockerfile
src/monitor/6.2/cbl-mariner-distroless/arm64v8/Dockerfile
src/monitor/6.2/cbl-mariner/amd64/Dockerfile
src/monitor/6.2/cbl-mariner/arm64v8/Dockerfile
src/monitor/6.2/ubuntu-chiseled/amd64/Dockerfile
src/monitor/6.2/ubuntu-chiseled/arm64v8/Dockerfile
src/monitor/7.0/alpine/amd64/Dockerfile
src/monitor/7.0/alpine/arm64v8/Dockerfile
src/monitor/7.0/cbl-mariner-distroless/amd64/Dockerfile
src/monitor/7.0/cbl-mariner-distroless/arm64v8/Dockerfile
src/monitor/7.0/cbl-mariner/amd64/Dockerfile
src/monitor/7.0/cbl-mariner/arm64v8/Dockerfile
src/monitor/7.0/ubuntu-chiseled/amd64/Dockerfile
src/monitor/7.0/ubuntu-chiseled/arm64v8/Dockerfile

The 7.0 package version in this change contains several new files that support new features that are in development. To mostly mitigate the size increase, I've amended the Dockerfiles to remove files that do not support the matching architecture for the Docker image as well as symbol files. This should be a net size reduction for the 6.x images and a minor net size increase for the 7.0 images.

.NET Monitor: Remove symbol files and non-matching arch assemblies

---

eng/pipelines/steps/update-dependencies.yml

This fixes an issue introduced from https://github.com/dotnet/dotnet-docker/pull/4057 where a single SDK version is provided. In that case, a PR will not be generated for the changes. The intent is that a PR will only be generated after the latest iteration of the set of SDK versions being targeted. But when providing only a single SDK version as input, the PowerShell logic ends up not executing as intended. 
When converting the customArgsArray parameter to JSON, PowerShell has a weird quirk where a JSON array with only a single element will be deserialized as just a string and not an array. This messes up the `for` loop where it checks if the value is the last item in the array. It's not recognized as being the last item, and so the credentials are never provided to update-dependencies …

Fix update-deps when targeting a single SDK version

---

tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs

I've confirmed that globally writable files are expected for .NET global mutexes. This means that such files can show up in the /tmp/.dotnet directory. I've updated the unit test to allow for such files in this path only.

Allow writable files for global mutexes

---

eng/dockerfile-templates/runtime-deps/Dockerfile.linux.distroless-user
src/runtime-deps/6.0/jammy-chiseled/amd64/Dockerfile
src/runtime-deps/6.0/jammy-chiseled/arm64v8/Dockerfile
src/runtime-deps/7.0/cbl-mariner2.0-distroless/amd64/Dockerfile
src/runtime-deps/7.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile

Ensures that a home directory exists for the non-root user that is created in distroless/chiseled images. This allows tools that are expecting this directory to exist to work without issue.
Fixes #4083

Include home directory for non-root user

---

tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs

The changes in https://github.com/dotnet/dotnet-docker/pull/4088 didn't properly handle the testing scenario for distroless containers. In that scenario, the paths to be excluded start with a rootfs directory which was not being handled.
To fix this, I've updated to use the variable which indicates the root directory for either distroful or distroless scenarios.

Fix world-writable file path exclusion

---

tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs

These changes fix an issue with the change made in https://github.com/dotnet/dotnet-docker/pull/4097 because it wasn't setting the path correctly. It was missing a trailing slash after `/rootfs`.
This issue wasn't caught by the PR build and only showed up in the internal build. The reason for this is a bit complicated. The test which produces the world-writable files is for the SDK and that's the test that was failing. In the PR build, this test was run but only ended up targeting the distroful version of the image, not the distroless. This is because both the distroful and distroless versions were being tested in the same job. So when the SDK test class ran, it filters out the image data down to distinct SDK OS. Since both distroful and distroless share the same SDK OS, the distroless …

Fix distroless-related testing

---

eng/pipelines/steps/update-dependencies.yml
eng/update-dependencies/Dockerfile

The pipeline to run update-dependencies for internal .NET builds isn't working correctly when targeting multiple .NET versions. The PR that gets generated only has the changes of the last .NET version specified in the set. This is because the pipeline is creating a new container for each iteration of the tool. So repo changes from previous iterations of the tool are not carried over to the next iteration.
I've fixed this by ensuring that the loop which executes the tool targets a single container instance that is setup to run by the previous pipeline step.

update-deps: Maintain same container for each version

---

eng/pipelines/dotnet-core.yml
eng/pipelines/stages/build-test-publish-repo.yml

A new set of build pools have been created which are meant for release builds. This means that builds from the main branch should be using the `NetCore1ESPool-Svc-Internal` pool instead of `NetCore1ESPool-Internal`.
I've confirmed with the Eng Services team that this only applies to the main branch and not the nightly branch.

Update internal pool for builds from main branch

---

eng/dockerfile-templates/Dockerfile.linux.install-pkgs
eng/dockerfile-templates/runtime-deps/Dockerfile.distroless-mariner
src/runtime-deps/6.0/cbl-mariner1.0-distroless/amd64/Dockerfile
src/runtime-deps/6.0/cbl-mariner2.0-distroless/amd64/Dockerfile
src/runtime-deps/6.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile
src/runtime-deps/7.0/cbl-mariner2.0-distroless/amd64/Dockerfile
src/runtime-deps/7.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
tests/Microsoft.DotNet.Docker.Tests/RuntimeDepsImageTests.cs

The distroless Mariner images that we produce aren't configured properly to allow scanning tools to correctly identify the RPM packages that exist in them, specifically the RPM packages that are being directly installed by the .NET Dockerfiles. The scanning tools are only recognizing the RPM packages that exist in the base distroless Mariner image that the .NET image is based on.
This is because these scanning tools are looking for an [RPM manifest file](https://github.com/microsoft/CBL-Mariner/blob/2.0/toolkit/docs/how_it_works/5_misc.md#rpm-manifest-file) that's specific to Mariner. This file exists in the base distroless Mariner image but is not updated to reflect the RPM packages that are installed by the .NET Dockerfile.
There is a broader [work …

Enable distroless Mariner images to be scanned correctly

---

samples/aspnetapp/Dockerfile.alpine-arm32
samples/aspnetapp/Dockerfile.alpine-arm64
samples/aspnetapp/Dockerfile.alpine-x64
samples/aspnetapp/Dockerfile.alpine-x64-slim
samples/dotnetapp/Dockerfile.alpine-arm32
samples/dotnetapp/Dockerfile.alpine-arm64
samples/dotnetapp/Dockerfile.alpine-x64
samples/dotnetapp/Dockerfile.alpine-x64-slim

In Alpine 3.16, the ICU data was split across two packages: icu-libs and icu-data-full. See https://github.com/dotnet/dotnet-docker/issues/3844 for more info. Since our Alpine sample Dockerfiles are based on Alpine 3.16, the content needs to be updated to reflect this requirement for localization scenarios.
Related:
https://github.com/dotnet/dotnet-docker/issues/3844#issuecomment-1268233473
https://github.com/dotnet/dotnet-docker/issues/4126

Update Alpine samples for localization scenario

---

eng/dockerfile-templates/runtime-deps/Dockerfile.chiseled-ubuntu
eng/dockerfile-templates/runtime-deps/Dockerfile.distroless-mariner
eng/dockerfile-templates/runtime-deps/Dockerfile.linux.distroless-user
src/runtime-deps/6.0/jammy-chiseled/amd64/Dockerfile
src/runtime-deps/6.0/jammy-chiseled/arm64v8/Dockerfile
src/runtime-deps/7.0/cbl-mariner2.0-distroless/amd64/Dockerfile
src/runtime-deps/7.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs
tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs

The changes in https://github.com/dotnet/dotnet-docker/pull/4092 didn't correctly set the ownership of the home directory. So if an app running in the context of the non-root user `app` attempted to write to its `/home/app` directory, it would get an access denied error.
This happens because the directory is created while running as the root user and nothing is done further to set ownership.
This has now been updated to both create the directory and set ownership using the `install` command. That in itself isn't enough, however. Due to https://github.com/moby/moby/issues/38710, a workaround is necessary to ensure that the `/home/app` directory that gets copied into the final stage has the ownership that was initially set. This is done by including another `COPY` instruction that …

Set correct ownership of non-root user's home dir

---

eng/dockerfile-templates/runtime-deps/Dockerfile.linux.distroless-user
src/runtime-deps/6.0/jammy-chiseled/amd64/Dockerfile
src/runtime-deps/6.0/jammy-chiseled/arm64v8/Dockerfile
src/runtime-deps/7.0/cbl-mariner2.0-distroless/amd64/Dockerfile
src/runtime-deps/7.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs

The intent with the distroless-style containers is to have a non-root user by default. As part of that implementation, the users that were actually registered in the container have been scoped down to just that non-root user `app`.
However, all of the files in the system are actually owned by the root user (technically owned by UID 0 since there is no user named root). So it's a bit odd that there are files in the container that are owned by a user that is not registered.
Not having a root user exist doesn't actually buy us any sort of protection. The container can still be run with root-level permissions by running the container with `--user 0` instead of `--user root`.
So to make things more correct and consistent, the root user will be preserved.

Preserve root user in distroless-style containers

---

.mar/portal/README.aspnet.portal.md
.mar/portal/README.monitor.portal.md
.mar/portal/README.runtime-deps.portal.md
.mar/portal/README.runtime.portal.md
.mar/portal/README.sdk.portal.md
README.aspnet.md
README.monitor.md
README.runtime-deps.md
README.runtime.md
README.sdk.md
eng/mcr-tags-metadata-templates/aspnet-tags.yml
eng/mcr-tags-metadata-templates/monitor-tags.yml
eng/mcr-tags-metadata-templates/runtime-deps-tags.yml
eng/mcr-tags-metadata-templates/runtime-tags.yml
eng/mcr-tags-metadata-templates/sdk-tags.yml
eng/readme-templates/FeaturedTags.md

This outlines our plans for classifying tags in the readmes for each .NET release:
* While a .NET version is in preview, its tags will be listed separately from the other supported versions in its own "Preview Tags" table.
* Once a .NET version has reached an RC release:
* That separate table will now longer be used and the RC tags will be incorporated with the tags of the other supported versions.
* The "Featured Tags" section will be updated to include the RC version.

Update readmes for how tags are listed and featured

---

build-and-test.ps1

This fixes the name of the OS parameter used when calling the /eng/common/build.ps1 script. It's name is `OS`, not `OSVersions`.

Fix OS parameter usage in build script

---

samples/run-aspnetcore-https-development.md

Fixes #4118
Microsoft style guide fixes too.
Avoid `please` except in situations where the customer is asked to do something inconvenient or the application or site is to blame for the situation.

Update run-aspnetcore-https-development.md with <CREDENTIAL_PLACEHOLDER>

---

eng/dockerfile-templates/monitor/Dockerfile
src/monitor/6.2/alpine/amd64/Dockerfile
src/monitor/6.2/alpine/arm64v8/Dockerfile
src/monitor/6.2/cbl-mariner-distroless/amd64/Dockerfile
src/monitor/6.2/cbl-mariner-distroless/arm64v8/Dockerfile
src/monitor/6.2/cbl-mariner/amd64/Dockerfile
src/monitor/6.2/cbl-mariner/arm64v8/Dockerfile
src/monitor/6.3/alpine/amd64/Dockerfile
src/monitor/6.3/alpine/arm64v8/Dockerfile
src/monitor/6.3/cbl-mariner-distroless/amd64/Dockerfile
src/monitor/6.3/cbl-mariner-distroless/arm64v8/Dockerfile
src/monitor/6.3/cbl-mariner/amd64/Dockerfile
src/monitor/6.3/cbl-mariner/arm64v8/Dockerfile
src/monitor/6.3/ubuntu-chiseled/amd64/Dockerfile
src/monitor/6.3/ubuntu-chiseled/arm64v8/Dockerfile
src/monitor/7.0/alpine/amd64/Dockerfile
src/monitor/7.0/alpine/arm64v8/Dockerfile
src/monitor/7.0/cbl-mariner-distroless/amd64/Dockerfile
src/monitor/7.0/cbl-mariner-distroless/arm64v8/Dockerfile
src/monitor/7.0/cbl-mariner/amd64/Dockerfile
src/monitor/7.0/cbl-mariner/arm64v8/Dockerfile
src/monitor/7.0/ubuntu-chiseled/amd64/Dockerfile
src/monitor/7.0/ubuntu-chiseled/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/MonitorImageTests.cs

This PR explicitly sets the default GC mode for `dotnet monitor` images to Server. This PR **does not** change the default behavior of any of the images as this is their current default, and instead ensures that future images keep their current behavior going forward as we change `dotnet monitor`'s GC defaults for other environments.

dotnet-monitor: Set default GC mode

---

eng/Get-DropVersions.ps1
eng/pipelines/stages/build-test-publish-repo.yml
eng/pipelines/steps/set-custom-test-variables.yml
eng/pipelines/steps/update-dotnet-dependencies.yml
eng/pipelines/update-dependencies-internal.yml
eng/pipelines/variables/core.yml
eng/pipelines/variables/internal-core.yml
manifest.versions.json

Updates the infra to use the https://dotnetstage.blob.core.windows.net/internal blob container instead of https://dotnetbuilds.blob.core.windows.net/internal when targeting internal .NET builds. This is because the files in dotnetstage are fully signed.
Fixes https://github.com/dotnet/dotnet-docker/issues/4147

Use dotnetstage storage account for internal builds

---

eng/Get-DropVersions.ps1
eng/update-dependencies/BaseUrlUpdater.cs
eng/update-dependencies/DockerfileShaUpdater.cs
manifest.versions.json

With these changes, update-dependencies will set the `base-url|<version>|nightly` variable to an explicit URL rather than a variable. This allows the URL to be build-specific.
Fixes #4151

Use build-specific blob container for internal builds

---

.mar/portal/README.aspnet.portal.md
.mar/portal/README.monitor.portal.md
.mar/portal/README.runtime-deps.portal.md
.mar/portal/README.runtime.portal.md
.mar/portal/README.sdk.portal.md
README.aspnet.md
README.monitor.md
README.runtime-deps.md
README.runtime.md
README.sdk.md
eng/readme-templates/FeaturedTags.md
samples/aspnetapp/Dockerfile.nanoserver-x64
samples/complexapp/README.md
samples/dotnetapp/README.md
samples/run-tests-in-sdk-container.md

This makes miscellaneous updates to the docs so that they're updated appropriately for the .NET 7 release.
Regarding the change of `LTS` to `Long-Term Support`, this is the change that's being adopted for official .NET docs with the introduction of the `Standard Support` support type. It makes the terms more consistent when they're shown together.

Doc updates for .NET 7 release

---

eng/dockerfile-templates/aspnet/Dockerfile.linux
eng/dockerfile-templates/aspnet/Dockerfile.linux.install-aspnet
eng/dockerfile-templates/runtime-deps/Dockerfile
eng/dockerfile-templates/runtime/Dockerfile.linux
eng/dockerfile-templates/runtime/Dockerfile.linux.install-runtime
eng/dockerfile-templates/sdk/Dockerfile.linux
eng/dockerfile-templates/sdk/Dockerfile.linux.install-sdk
src/aspnet/7.0/cbl-mariner2.0/amd64/Dockerfile
src/aspnet/7.0/cbl-mariner2.0/arm64v8/Dockerfile
src/runtime-deps/7.0/cbl-mariner2.0/amd64/Dockerfile
src/runtime-deps/7.0/cbl-mariner2.0/arm64v8/Dockerfile
src/runtime/7.0/cbl-mariner2.0/amd64/Dockerfile
src/runtime/7.0/cbl-mariner2.0/arm64v8/Dockerfile
src/sdk/7.0/cbl-mariner2.0/amd64/Dockerfile
src/sdk/7.0/cbl-mariner2.0/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/RuntimeDepsImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/RuntimeImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs

Updates the Mariner Dockerfiles for .NET 7 so that they install .NET from a tarball instead of RPM package.
Since Mariner 2.0 doesn't have `tar` installed by default, the Dockerfiles have also been updated to install that when necessary. Since `tar` is getting installed to do the install, a multi-stage Dockerfile is used to avoid `tar` showing up in the final image (except for the sdk where we do want `tar` installed).
Tests have also been updated to skip RPM package verification for .NET 7 and higher.
Fixes #4157

Install tarball in Mariner instead of RPM package

---

eng/pipelines/dotnet-core-internal-nightly.yml

Related to https://github.com/dotnet/dotnet-docker/pull/4106, this should also be applied to the pipeline which publishes images for internal .NET builds.

Update pool for builds targeting internal .NET builds

---

eng/update-dependencies/UpdateDependencies.cs

The name of the remote branch of the PR generated by the update-dependencies tool is very deeply nested and also causes an internal branch policy to be applied which prevents the branch from being deleted when the PR is completed.
These changes update the generated name to avoid both these issues by replace `/` with `-`.
As an example, the branch name currently generated for PRs of internal builds is `users/dotnet-docker-bot/internal/release/nightly-UpdateDependencies-internal/release/nightly-From-dotnet-installer`. In Git tools which provide folders based on the branch name, this gets displayed as:
```
users
/dotnet-docker-bot
/internal
/release
/nightly-UpdateDependencies-internal
/release
/nightly-From-dotnet-installer
```
With these changes, the branch name would be …

Format remote branch name generated by update-deps

---

eng/common/Install-DotNetSdk.ps1

Changes to the channel classification of .NET versions has caused "Current" channel to install .NET 5. Removing the channel parameter fixes this.

.NET install script workaround

---

.mar/portal/README.aspnet.portal.md
.mar/portal/README.monitor.portal.md
.mar/portal/README.runtime-deps.portal.md
.mar/portal/README.runtime.portal.md
.mar/portal/README.samples.portal.md
.mar/portal/README.sdk.portal.md
README.aspnet.md
README.md
README.monitor.md
README.runtime-deps.md
README.runtime.md
README.samples.md
README.sdk.md
eng/readme-templates/RelatedRepos.md

This new name matches the naming for the [MAR portal guidelines](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/containers-bburns/microsoft-container-registry/microsoft-artifact-registry-also-known-as-microsoft-container-registry-docs/onboardingdocs/documentationstandards).
Fixes #4161

Update Related Repos header name

---

build-and-test.ps1
eng/dockerfile-templates/runtime-deps/Dockerfile.chiseled-ubuntu
src/runtime-deps/6.0/jammy-chiseled/amd64/Dockerfile
src/runtime-deps/6.0/jammy-chiseled/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/RuntimeDepsImageTests.cs

This mirrors the changes that were made in https://github.com/ubuntu-rocks/dotnet/pull/81. It includes OS release info to the Chiseled Ubuntu images (e.g. the `/etc/os-release` file). This allows image scanning tools that look for this OS info to be able to correctly identify the type of OS for these Chiseled Ubuntu images.
For example, before these changes [Syft](https://github.com/anchore/syft) would not be able to identify the OS:
```bash
> syft packages --output json -q mcr.microsoft.com/dotnet/nightly/runtime-deps:7.0-jammy-chiseled | jq -r .distro
{}
```
But with these changes it will output this instead:
```json
{
"prettyName": "Ubuntu 22.04.1 LTS",
"name": "Ubuntu",
"id": "ubuntu",
"idLike": [
"debian"
],
"version": "22.04.1 LTS (Jammy Jellyfish)",
"versionID": "22.04", …
```

Include OS release info in Chiseled Ubuntu images

---

eng/dockerfile-templates/Dockerfile.linux.install-deps
manifest.versions.json
src/runtime-deps/6.0/alpine3.17/amd64/Dockerfile
src/runtime-deps/6.0/alpine3.17/arm32v7/Dockerfile
src/runtime-deps/6.0/alpine3.17/arm64v8/Dockerfile

While OpenSSL 1.1 is available in Alpine 3.17, [OpenSSL 3.0 is the default version](https://alpinelinux.org/posts/Alpine-3.17.0-released.html). We should reflect that default version with the version of libssl that is installed.
These changes upgrade the version of libssl from 1.1 to 3.0 for the Alpine 3.17 Dockerfiles.

Upgrade to libssl3 for Alpine 3.17

---

samples/aspnetapp/aspnetapp/EnvironmentInfo.cs
samples/aspnetapp/aspnetapp/Views/Home/Index.cshtml
samples/dotnetapp/Program.cs

I noticed that our samples were stale w/rt cgroups. They are using cgroup v1, but the primary distros we're using are cgroup v2.  I'm not sure if this is exclusively a host/kernel topic or requires guest/userland support. The change should work either way. The current samples don't work correctly anymore because of this and likely haven't for some time.
I also added the user. That'll be useful for our rootless work.
Some quick evidence:
```bash
% docker run --rm -m 50mb -it --entrypoint bash dotnetapp
root@44ead91c120f:/app# stat -fc %T /sys/fs/cgroup/
cgroup2fs
```
This is what our `dotnetapp` sample does today:
```bash
% docker run --rm -m 50mb mcr.microsoft.com/dotnet/samples:dotnetapp
42
42              ,d                             ,d
42              42 …
```

Update samples for user and cgroup info 

---

README.monitor.md
eng/dockerfile-templates/monitor/Dockerfile.entrypoint.monitorV8
eng/mcr-tags-metadata-templates/monitor-tags.yml
manifest.json
manifest.versions.json
src/monitor/8.0/cbl-mariner-distroless/amd64/Dockerfile
src/monitor/8.0/cbl-mariner-distroless/arm64v8/Dockerfile
src/monitor/8.0/ubuntu-chiseled/amd64/Dockerfile
src/monitor/8.0/ubuntu-chiseled/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/TestData.cs
tests/performance/ImageSize.nightly.linux.json

For .NET Monitor 8, the initial offering will be to only provide distroless and chiseled images. These images will follow the same tagging policy introduced for .NET 8.

Add .NET Monitor 8 Dockerfiles

---

CONTRIBUTING.md
eng/pipelines/update-dependencies-monitor.yml
eng/update-dependencies/DockerfileShaUpdater.cs
eng/update-dependencies/Options.cs

The `--channel-name` option was introduced long ago when .NET Monitor could not be staged in the storage accounts the same way that the rest of the .NET assets were able to in the .NET 6 timeframe. Shortly after .NET 6 shipped, this was fixed so that .NET Monitor now conforms to the usual shipping mechanism via storage accounts. Thus, the channel name concept is no longer necessary; remove it to reduce the concept count.

Remove channel name concept from update-dependencies

---

tests/performance/ImageSize.nightly.linux.json

This change is due to an update in the size of the base Mariner distroless image from the addition of tzdata and certificates package.

Update image size baseline

---

documentation/vulnerability-reporting.md

The vulnerability doc intended to use the `click` functionality of mermaid to provide hyperlink behavior to the elements in the flowchart. This doesn't work as intended. When clicking such a link, it appears that the mermaid renderer attempts to open the link in the mermaid "box" rather than on the main browser. It then shows an error that says "This content is blocked. Contact the site owner to fix the issue".
So I've removed the use of those `click` definitions. Without that, the document lacks a good experience to walk through the flowchart. To improve things, I've updated each details section of the doc that represents a flowchart question so that it will now include hyperlinks to each of the possible responses. This allows the reader to guide themselves via the details section rather …

Vulnerability doc improvements

---

eng/update-dependencies/Dockerfile

Similar to https://github.com/dotnet/docker-tools/pull/1106, update-dependencies depends on libgit2sharp, which needs openssl 1.1 instead of openssl 3 in Alpine 3.17.

Add openssl1.1-compat to update-dependencies Dockerfile

---

eng/pipelines/update-dependencies-monitor.yml

This change simplifies the update dependencies pipeline for .NET Monitor to only scan for updates for the version configured by the `MajorMinorVersion` and `ChannelQuality` pipeline variables, which will be set to `8.0` and `daily` respectively.
Post-merge, the [Azure DevOps pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=1207&_a=summary) will be updated to reflect the variable changes.
Addresses the first issue in #4314

Only update one .NET Monitor version in update dependencies pipeline

---

documentation/supported-platforms.md

Based on this [comment](https://github.com/dotnet/dotnet-docker/issues/2438#issuecomment-1399179170), I've clarified the documentation to indicate that we're only supporting Windows Server Core 2019 and above.

Clarify WSC version support in doc

---

eng/Get-MonitorDropVersions.ps1
eng/pipelines/update-dependencies-monitor.yml

This PR changes the .NET Monitor update dependencies pipeline in two ways:
1. Automatically run when there is a .NET Monitor release build completed which we have marked as needing to be updated in docker.
2. When running on the nightly schedule, pull version information from the latest .NET Monitor nightly build instead of relying on the Channel variables. This allows us to remove the `MajorMinorVersion` and `ChannelQuality` pipeline variables, and use the same logic as the above triggered runs.
- Post-merge, the [Azure DevOps pipeline](https://dev.azure.com/dnceng/internal/_build?definitionId=1207&_a=summary) will be updated to reflect the variable changes.
- Addresses the second issue in: https://github.com/dotnet/dotnet-docker/issues/4314
/cc @dotnet/dotnet-monitor

Use pipeline resources when updating .NET Monitor dependencies

---

documentation/scenarios/nuget-credentials.md

Hi,
I've added a sample that shows how to use private nuget feeds from Azure Devops using **NugetAuthenticate** task.
I've been looking everywhere for a solution that doesn't involve generating PAT and this seems to be working great.

Example of using NugetAuthenticate to get PAT

---

eng/pipelines/update-dependencies-monitor.yml

Currently, the update pipeline will run on a schedule that will automatically overwrite triggered updates from the release branches. This change make the nightly updates use the same trigger mechanism as the release branches to prevent this overwriting behavior. [Changes](https://github.com/dotnet/dotnet-monitor/pull/3523) are being made to the dotnet-dotnet-monitor pipeline (by only tagging main branch builds on a schedule) to make sure dotnet-docker only receives an automatic nightly update once per day.

Only use pipeline trigger for all .NET Monitor updates

---

eng/dockerfile-templates/runtime-deps/Dockerfile.linux.distroless-user
eng/dockerfile-templates/runtime-deps/Dockerfile.linux.non-root-user
src/runtime-deps/8.0/alpine3.17/amd64/Dockerfile
src/runtime-deps/8.0/alpine3.17/arm32v7/Dockerfile
src/runtime-deps/8.0/alpine3.17/arm64v8/Dockerfile
src/runtime-deps/8.0/bookworm-slim/amd64/Dockerfile
src/runtime-deps/8.0/bookworm-slim/arm32v7/Dockerfile
src/runtime-deps/8.0/bookworm-slim/arm64v8/Dockerfile
src/runtime-deps/8.0/cbl-mariner2.0/amd64/Dockerfile
src/runtime-deps/8.0/cbl-mariner2.0/arm64v8/Dockerfile
src/runtime-deps/8.0/jammy/amd64/Dockerfile
src/runtime-deps/8.0/jammy/arm32v7/Dockerfile
src/runtime-deps/8.0/jammy/arm64v8/Dockerfile

Fixes https://github.com/dotnet/dotnet-docker/issues/4467

Use default shell for non-root user in non-distroless images

---

README.aspnet.md
README.runtime.md
README.sdk.md
manifest.json

See https://github.com/dotnet/dotnet-docker/issues/4492

Remove multi-platform tags for Windows

---

eng/Set-DotnetVersions.ps1
eng/pipelines/update-dependencies-monitor.yml

The Set-DotnetVersions.ps1 script understands how to break out the "monitor" product into separate subproducts for 8.0 and going forward. The update-dependencies-monitor.yml pipeline was constructing its own command line arguments to pass to the update-dependencies tool as wasn't updated to understand the subproduct notion.
This changes the update-dependencies-monitor.yml pipeline to use the Set-DotnetVersions.ps1 script so that consistent .NET Monitor product versioning behavior is used and maintained in one place.

Use Set-DotnetVersions for updating .NET Monitor

---

samples/aspnetapp/aspnetapp/EnvironmentInfo.cs
samples/dotnetapp/Program.cs

Introduce HostName to EnvironmentInfo.
Remove unused variable.

Introduce HostName to EnvironmentInfo.

---

samples/aspnetapp/Dockerfile.chiseled
samples/aspnetapp/Dockerfile.debian
samples/dotnetapp/Dockerfile.chiseled

With only "./aspnetapp.dll" as the entrypoint the resulting container image fails to run on arm64 Linux (most likely also on amd64) with:
```
exec: "./aspnetapp.dll": permission denied: unknown.
```

Fix exec: "./aspnetapp.dll": permission denied

---

eng/dockerfile-templates/Dockerfile.linux.install-deps
src/runtime-deps/8.0/alpine3.17/amd64/Dockerfile
src/runtime-deps/8.0/alpine3.17/arm32v7/Dockerfile
src/runtime-deps/8.0/alpine3.17/arm64v8/Dockerfile
src/runtime-deps/8.0/alpine3.18/amd64/Dockerfile
src/runtime-deps/8.0/alpine3.18/arm32v7/Dockerfile
src/runtime-deps/8.0/alpine3.18/arm64v8/Dockerfile

Remove libintl from .NET 8.0 Alpine runtime-deps images

---

manifest.versions.json
src/aspnet/8.0/alpine3.18-composite/amd64/Dockerfile
src/aspnet/8.0/alpine3.18-composite/arm32v7/Dockerfile
src/aspnet/8.0/alpine3.18-composite/arm64v8/Dockerfile

The checksums for the aspnet composite tarballs never got updated for the release and actually had stale values leftover from the initial commit of the composite Dockerfiles in the nightly branch.
I've updated the checksums to be correct.

Fix checksums for aspnet composite tarballs

---

tests/performance/ImageSize.nightly.linux.json

The size baselines for the `dotnet/nightly/monitor/base` images were incorrectly placed under the `dotnet/nightly/monitor` repository.

Fix dotnet/nightly/monitor/base size baseline declarations

---

eng/dockerfile-templates/runtime-deps/Dockerfile.chiseled-ubuntu
src/runtime-deps/6.0/jammy-chiseled/amd64/Dockerfile
src/runtime-deps/6.0/jammy-chiseled/arm32v7/Dockerfile
src/runtime-deps/6.0/jammy-chiseled/arm64v8/Dockerfile
src/runtime-deps/8.0/jammy-chiseled/amd64/Dockerfile
src/runtime-deps/8.0/jammy-chiseled/arm32v7/Dockerfile
src/runtime-deps/8.0/jammy-chiseled/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/RuntimeDepsImageTests.cs

Fixes #4667 
- Enable image scanning
- Enable image scanning test
- Tested against `syft` and `Trivy`:
```pwsh
PS> docker run --rm -v //var/run/docker.sock:/var/run/docker.sock anchore/syft chiseled
NAME             VERSION                   TYPE 
base-files       12ubuntu4.3               deb
ca-certificates  20230311ubuntu0.22.04.1   deb
libc6            2.35-0ubuntu3.1           deb
libgcc-s1        12.1.0-2ubuntu1~22.04     deb
libssl3          3.0.2-0ubuntu1.10         deb
libstdc++6       12.1.0-2ubuntu1~22.04     deb
zlib1g           1:1.2.11.dfsg-2ubuntu9.2  deb
```
It seems to have way fewer packages than CBL Mariner distroless.
Since we seem to be okay pulling directly from `main` in the `canonical/chisel` repo, I followed the same pattern for `rocks-toolbox`. If we want to take …

Enable image scanning for Ubuntu Chiseled

---

samples/enable-globalization.md

Updates the globalization doc to make customers aware of the lack of invariant mode support from SqlClient (see https://github.com/dotnet/SqlClient/issues/220).

Add SqlClient info to globalization doc

---

eng/dockerfile-templates/runtime-deps/Dockerfile
eng/dockerfile-templates/runtime-deps/Dockerfile.chiseled-ubuntu
eng/dockerfile-templates/runtime-deps/Dockerfile.distroless-mariner
src/runtime-deps/6.0/jammy-chiseled/amd64/Dockerfile
src/runtime-deps/6.0/jammy-chiseled/arm32v7/Dockerfile
src/runtime-deps/6.0/jammy-chiseled/arm64v8/Dockerfile
src/runtime-deps/8.0/alpine3.18/amd64/Dockerfile
src/runtime-deps/8.0/alpine3.18/arm32v7/Dockerfile
src/runtime-deps/8.0/alpine3.18/arm64v8/Dockerfile
src/runtime-deps/8.0/bookworm-slim/amd64/Dockerfile
src/runtime-deps/8.0/bookworm-slim/arm32v7/Dockerfile
src/runtime-deps/8.0/bookworm-slim/arm64v8/Dockerfile
src/runtime-deps/8.0/cbl-mariner2.0-distroless/amd64/Dockerfile
src/runtime-deps/8.0/cbl-mariner2.0-distroless/arm64v8/Dockerfile
src/runtime-deps/8.0/cbl-mariner2.0/amd64/Dockerfile
src/runtime-deps/8.0/cbl-mariner2.0/arm64v8/Dockerfile
src/runtime-deps/8.0/jammy-chiseled/amd64/Dockerfile
src/runtime-deps/8.0/jammy-chiseled/arm32v7/Dockerfile
src/runtime-deps/8.0/jammy-chiseled/arm64v8/Dockerfile
src/runtime-deps/8.0/jammy/amd64/Dockerfile
src/runtime-deps/8.0/jammy/arm32v7/Dockerfile
src/runtime-deps/8.0/jammy/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/ImageData.cs
tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs

Fixes #4693 
UID is `1654` according to https://github.com/dotnet/dotnet-docker/issues/4693#issuecomment-1612002902

Update non-root UID to avoid warning in Debian

---

tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
tests/Microsoft.DotNet.Docker.Tests/DockerRunArgsBuilder.cs
tests/Microsoft.DotNet.Docker.Tests/MonitorImageTests.cs

The .NET Monitor tests were filtering .NET Monitor and sample image combinations based on the "distrolessness" of each image where only distroless was being tested with distroless and non-distroless tested with non-distroless. This doesn't cover the real possibility that customers are running their apps as a different user as compared to the .NET Monitor image; this is especially true of the .NET Monitor 8 images which are all distroless and exclusively use a non-root user.
I've removed this filter to allow all combinations and updated the volume creation to determine the least-privileged user of the two images to be used as the owner of the volumes and defer to the sample image user if there is a tie; this would be the guidance for our customers who have mixed user usage of containers in …

Test .NET Monitor with samples regardless of mode and distrolessness

---

eng/dockerfile-templates/Dockerfile.git-clone
eng/dockerfile-templates/runtime-deps/Dockerfile.chiseled-ubuntu
eng/update-dependencies/ChiselRefUpdater.cs
eng/update-dependencies/ChiselToolUpdater.cs
eng/update-dependencies/GitHubHelper.cs
eng/update-dependencies/RocksToolboxRefUpdater.cs
eng/update-dependencies/UpdateDependencies.cs
manifest.versions.json

Fixes #4745 
The next time the update-dependencies tool runs, it should update the rocks-toolbox ref to a tag, and then change the way the tag is cloned in the Dockerfile.

Use release tag to update rocks-toolbox

---

eng/dockerfile-templates/Dockerfile.linux.install-pkgs
src/runtime-deps/6.0/alpine3.17/amd64/Dockerfile
src/runtime-deps/6.0/alpine3.17/arm32v7/Dockerfile
src/runtime-deps/6.0/alpine3.17/arm64v8/Dockerfile
src/runtime-deps/6.0/alpine3.18/amd64/Dockerfile
src/runtime-deps/6.0/alpine3.18/arm32v7/Dockerfile
src/runtime-deps/6.0/alpine3.18/arm64v8/Dockerfile
src/runtime-deps/8.0/alpine3.18/amd64/Dockerfile
src/runtime-deps/8.0/alpine3.18/arm32v7/Dockerfile
src/runtime-deps/8.0/alpine3.18/arm64v8/Dockerfile
src/sdk/6.0/alpine3.17/amd64/Dockerfile
src/sdk/6.0/alpine3.17/arm32v7/Dockerfile
src/sdk/6.0/alpine3.17/arm64v8/Dockerfile
src/sdk/6.0/alpine3.18/amd64/Dockerfile
src/sdk/6.0/alpine3.18/arm32v7/Dockerfile
src/sdk/6.0/alpine3.18/arm64v8/Dockerfile
src/sdk/7.0/alpine3.17/amd64/Dockerfile
src/sdk/7.0/alpine3.17/arm32v7/Dockerfile
src/sdk/7.0/alpine3.17/arm64v8/Dockerfile
src/sdk/7.0/alpine3.18/amd64/Dockerfile
src/sdk/7.0/alpine3.18/arm32v7/Dockerfile
src/sdk/7.0/alpine3.18/arm64v8/Dockerfile
src/sdk/8.0/alpine3.18/amd64/Dockerfile
src/sdk/8.0/alpine3.18/arm32v7/Dockerfile
src/sdk/8.0/alpine3.18/arm64v8/Dockerfile

fixes #4776 
At present (for runtime-deps\6.0\alpine3.18\amd64) this causes a size increase of 12.3 -> 17.4 MB because `libcrypto3` and `libssl3` are updated.

Force upgrade of .NET runtime deps in alpine images

---

README.monitor.md
eng/mcr-tags-metadata-templates/monitor-tags.yml
manifest.json
src/monitor/7.3/ubuntu-chiseled/amd64/Dockerfile
src/monitor/7.3/ubuntu-chiseled/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/TestData.cs
tests/performance/ImageSize.nightly.linux.json

Add the .NET Monitor 7.3 Ubuntu Chiseled images separately from the other 7.3 images to facilitate easier merge to main branch. These images should remain only in the nightly branch until Ubuntu Chiseled images are supported for .NET 7 based images.
Follow up from #4786

.NET Monitor 7.3 Ubuntu Chiseled images

---

documentation/scenarios/nuget-credentials.md

The Windows sample for Azure Artifacts either got stale or never worked as specified, as the credential provider install did so as the wrong user, preventing dotnet restore from succeeding.
Updating the sample to use an explicit temp directory as Windows Nano Server doesn't have a good location for unelevated temp files. This is done in the build layer so therefore doesn't end up in the final image that contains the published build.

Update Azure Artifacts docker sample for Windows

---

tests/performance/ImageSize.nightly.linux.json
tests/performance/ImageSize.nightly.windows.json

There were a couple of .NET 7.0.400 SDK images left out from https://github.com/dotnet/dotnet-docker/pull/4831 that have now crossed the size increase threshold.

Update .NET 7.0 SDK image sizes

---

tests/performance/ImageSize.nightly.linux.json

Size increase is due to https://github.com/PowerShell/PowerShell/issues/20177

Update Alpine 8.0 SDK image size baseline

---

manifest.json

This should fix the internal build failures in nightly by forcing `aot` and `extra` images to be grouped in with their non-distroless counterparts for testing. This way, we don't have multiple build legs with the same name, which for extra and aot would only be testing one image.

Add extra test dependencies for `aot` and `extra` images

---

manifest.json

This still fixes the root cause issue that prompted https://github.com/dotnet/dotnet-docker/pull/4856, but prevents the internal build (`PlatformDependencyGraph` matrix) from complaining that we have dependencies on multiple Dockerfile graphs.

Remove unnecessary custom build leg groups that were causing errors

---

eng/dockerfile-templates/sdk/Dockerfile.linux.aot
src/sdk/8.0/alpine3.18-aot/amd64/Dockerfile
src/sdk/8.0/alpine3.18-aot/arm64v8/Dockerfile

I discovered this during testing and this should go in before RC1. I missed a library in Alpine that is specified in the AOT samples from https://github.com/dotnet/dotnet-docker/pull/4742.

Add missing build-base package from Alpine AOT SDK

---

eng/dockerfile-templates/monitor-base/Dockerfile.linux
eng/dockerfile-templates/monitor/Dockerfile.linux
manifest.versions.json

Pin the base image versions of the .NET Monitor images to allow easier separate update of the .NET Monitor images

Pin .NET Monitor base image versions

---

manifest.json

These were left out of https://github.com/dotnet/dotnet-docker/pull/4857 by error.

Fix alpine custom build leg groups to match other extra/aot images

---

README.monitor-base.md
README.monitor.md
manifest.versions.json
src/monitor-base/8.0/cbl-mariner-distroless/amd64/Dockerfile
src/monitor-base/8.0/cbl-mariner-distroless/arm64v8/Dockerfile
src/monitor-base/8.0/ubuntu-chiseled/amd64/Dockerfile
src/monitor-base/8.0/ubuntu-chiseled/arm64v8/Dockerfile
src/monitor/8.0/cbl-mariner-distroless/amd64/Dockerfile
src/monitor/8.0/cbl-mariner-distroless/arm64v8/Dockerfile
src/monitor/8.0/ubuntu-chiseled/amd64/Dockerfile
src/monitor/8.0/ubuntu-chiseled/arm64v8/Dockerfile

- Update the base URL for .NET Monitor 8 to use dotnetbuilds instead of dotnetcli. This allows the nightly ingestion to pickup builds correctly instead of failing to get them from dotnetcli.
- Update .NET Monitor 8 to the latest RC2 build.

Update .NET Monitor 8 nightly builds url and use latest RC2 build

---

samples/aspnetapp/README.md
samples/releasesapi/README.md

Fixes a formatting issue with the markdown for `ASPNETCORE_HTTP_PORTS`.
Also explicitly sets `ASPNETCORE_HTTP_PORTS` when calling `docker run`. I feel it's a best practice to be explicit about what port the container runs with rather than assuming. Had users done this prior to .NET 8 with `ASPNETCORE_URLS`, they wouldn't be broken by the port change from 80 to 8080.

Update aspnetapp samples port

---

tests/Microsoft.DotNet.Docker.Tests/ImageScenarioVerifier.cs

Port of https://github.com/dotnet/dotnet-docker/pull/4948/commits/f5b05e4a44dab896846f5cf1594d037bf9768dce to main according to https://github.com/dotnet/dotnet-docker/issues/4950#issuecomment-1771504201.
Fixes https://github.com/dotnet/dotnet-docker/issues/4950

Specify platform for tests to pull the correct images on arm32

---

README.aspnet.md
README.monitor-base.md
README.monitor.md
README.runtime-deps.md
README.runtime.md
README.sdk.md
eng/mcr-tags-metadata-templates/aspnet-tags.yml
eng/mcr-tags-metadata-templates/monitor-base-tags.yml
eng/mcr-tags-metadata-templates/monitor-tags.yml
eng/mcr-tags-metadata-templates/runtime-deps-tags.yml
eng/mcr-tags-metadata-templates/runtime-tags.yml
eng/mcr-tags-metadata-templates/sdk-tags.yml

Related to https://github.com/dotnet/dotnet-docker/issues/4772

Move .NET 8 tags out of Preview sub-tables in Readmes

---

documentation/supported-tags.md

Related to https://github.com/dotnet/dotnet-docker/issues/4492

Document Windows lack of multi-platform tags

---

eng/update-dependencies/Dockerfile

This works around an issue where the libgit2 library cannot be located when used by the update-dependencies tool. This prevents the successful creation of dependency update PRs that target the internal branches.
This workaround was previously used to avoid this issue but was regressed as part of #4959. This fix restores the functionality used prior to the regression, but accounts for slight differences in using the `$TARGETARCH` variable and project upgrade to .NET 8 (which impacted the RID graph availability for non-portable RIDs).

Use alpine RID to workaround libgit2sharp load issue

---

eng/Get-DropVersions.ps1

This was a regression in https://github.com/dotnet/dotnet-docker/pull/4941, instead of what I did there we should actually pass the full SDK version and let update-dependencies decide whether or not we should trim that based on the stable version argument. This is needed to unblock internal dependency flow.

Pass full SDK version from Get-DropVersions to UpdateDependencies tool

---

eng/Set-DotnetVersions.ps1
eng/update-dependencies/DockerfileShaUpdater.cs
eng/update-dependencies/Options.cs

These changes allow using a locally available checksums table file instead of requiring the checksums to be publicly available on a blob storage account. I refactored the existing code to maintain the caching and validation behavior but allow for supplying a separate source of checksum information (in this case, the local file system).

Allow using local checksums table file for looking up checksums

---

README.monitor-base.md
README.monitor.md
eng/dockerfile-templates/monitor/Dockerfile.linux.extensions
eng/mcr-tags-metadata-templates/monitor-base-tags.yml
eng/mcr-tags-metadata-templates/monitor-tags.yml
manifest.json
manifest.versions.json
src/monitor-base/8.1/cbl-mariner-distroless/amd64/Dockerfile
src/monitor-base/8.1/cbl-mariner-distroless/arm64v8/Dockerfile
src/monitor-base/8.1/ubuntu-chiseled/amd64/Dockerfile
src/monitor-base/8.1/ubuntu-chiseled/arm64v8/Dockerfile
src/monitor/8.1/cbl-mariner-distroless/amd64/Dockerfile
src/monitor/8.1/cbl-mariner-distroless/arm64v8/Dockerfile
src/monitor/8.1/ubuntu-chiseled/amd64/Dockerfile
src/monitor/8.1/ubuntu-chiseled/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/ImageVersion.cs
tests/Microsoft.DotNet.Docker.Tests/TestData.cs
tests/performance/ImageSize.nightly.linux.json

- Add preliminary .NET Monitor 8.1 nightly images
- Move the `8-*`, `8`, and `latest` tags to target the 8.1 images
- Fix extensions template to use .NET Monitor version for base image

.NET Monitor 8.1

---

samples/build-in-sdk-container.md
samples/host-aspnetcore-https.md
samples/kubernetes/dotnet-monitor/dotnet-monitor.yaml
samples/kubernetes/manual-deployment/README.md
samples/push-image-to-acr.md
samples/run-aspnetcore-https-development.md
samples/run-in-sdk-container.md
samples/run-tests-in-sdk-container.md

update to `8080` since the default port changed to `8080`
https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/aspnet-port
it not working with current `80` port
works when updated to `8080`

Update port to 8080

---

samples/aspnetapp/Dockerfile
samples/aspnetapp/Dockerfile.alpine
samples/aspnetapp/Dockerfile.alpine-composite
samples/aspnetapp/Dockerfile.alpine-icu
samples/aspnetapp/Dockerfile.chiseled
samples/aspnetapp/Dockerfile.chiseled-composite
samples/aspnetapp/Dockerfile.debian
samples/aspnetapp/Dockerfile.nanoserver
samples/aspnetapp/Dockerfile.ubuntu
samples/aspnetapp/Dockerfile.windowsservercore

Context: https://github.com/dotnet/dotnet-docker/issues/3968#issuecomment-1852480821
I am open to the idea of using `EXPOSE $ASPNETCORE_HTTP_PORTS` as well - however this would only work because we specify one port (8080). [Official ASP.NET Core documentation](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-8.0#specify-ports-only) shows defining multiple ports this way. It would be a bad user experience to set multiple ports as documented there and have that break the `EXPOSE` instruction.

Add expose instruction to ASP.NET Core samples

---

samples/host-aspnetcore-https.md

Azure DevOps credential scanning doesn't like our placeholder password in this documentation. I changed it to "placeholder" which hopefully it prefers and won't trip on in the future. I also added an empty commit with the special string to bypass CredScan for one push.
This PR should be merged, not squashed, to preserve that commit.

Amend ASP.NET Core HTTPS documentation to avoid tripping CredScan

---

samples/host-aspnetcore-https.md

https://github.com/dotnet/dotnet-docker/pull/5072 updated the credential placeholders, but they didn't match what we already had in other documentation. Also, it contained an important empty commit that got deleted. This updates the credential placeholder in the https documentation and includes the bypass secret scanning string in a non-empty commit so that code mirroring can hopefully function again.

Update ASP.NET Core https docs to have matching credential placeholders

---

manifest.json

There are some issues with internal test matrix generation right now - this gets around the issue by forcing `chiseled-extra` images to be grouped with their non-extra counterparts for testing, which eliminates the duplicate matrix leg name error in [this failing pipeline run [MSFT internal link]](https://dev.azure.com/dnceng/internal/_build/results?buildId=2345047&view=logs&s=859b8d9a-8fd6-5a5c-6f5e-f84f1990894e&j=697562df-6fec-569d-32c1-ae207a276beb).
This is more hacky than I would like but it should be OK until we have time to work on https://github.com/dotnet/docker-tools/issues/1178.

Fix internal test matrix generation (Force Chiseled extra images to be grouped with non-extra images for testing)

---

tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.linux

This reverts commit f6c932bc75d2764868ad880e65ad2ef96a0e98ed. It was accidentally committed directly to `nightly` when it was meant to be in #5083.

Revert "Enable diagnostic output"

---

.mar/portal/README.aspnet.portal.md
.mar/portal/README.monitor-base.portal.md
.mar/portal/README.monitor.portal.md
.mar/portal/README.runtime-deps.portal.md
.mar/portal/README.runtime.portal.md
.mar/portal/README.samples.portal.md
.mar/portal/README.sdk.portal.md
README.aspnet.md
README.md
README.monitor-base.md
README.monitor.md
README.runtime-deps.md
README.runtime.md
README.samples.md
README.sdk.md
eng/readme-templates/Support.md

This fixes an error from https://github.com/dotnet/dotnet-docker/pull/5129 where the generated main README was directly edited without touching the template.

Add CVE Update Policy to readme template

---

samples/enable-globalization.md

Ubuntu chiseled `extra` variant and Mariner 2.0 `extra` variant images were not listed in the list of images containing `ICU`.

Add more images to globalization doc

---

eng/dockerfile-templates/aspire-dashboard/Dockerfile.envs
src/aspire-dashboard/8.0/cbl-mariner-distroless/amd64/Dockerfile
src/aspire-dashboard/8.0/cbl-mariner-distroless/arm64v8/Dockerfile

This is a workaround for https://github.com/dotnet/dotnet-docker/issues/5164 until the issue is fixed in Aspire.

Use 0.0.0.0 URIs for Aspire Dashboard environment variables

---

README.aspire-dashboard.md
eng/mcr-tags-metadata-templates/aspire-dashboard-tags.yml
manifest.json

There are currently no plans to ship other distros for `aspire-dashboard`. Since there is no choice to be made between distros for these images, this PR removes the distro from the tags.

Remove distro from aspire-dashboard tags

---

tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/NuGet.config

Some wasm-tools workload installations were failing due to this NuGet config being incorrectly configured.

Add dotnet-public to test NuGet.Config

---

eng/update-dependencies/Dockerfile
eng/update-dependencies/update-dependencies.csproj

Alpine 3.19 doesn't have OpenSSL 1 compat libraries. This requires an update to libgit2sharp. I updated a couple other package versions at the same time. I also took another look at updating S.CL but it was not trivial.

Fix update-dependencies Docker build based on new Alpine version

---

tests/Microsoft.DotNet.Docker.Tests/SampleImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/TestScenarios/WebScenario.cs

This PR resolves some unreliability in the sample image tests that was introduced by https://github.com/dotnet/dotnet-docker/pull/5143.

Don't remove containers twice during sample image tests

---

eng/dockerfile-templates/aspire-dashboard/Dockerfile.linux
src/aspire-dashboard/8.0/cbl-mariner-distroless/amd64/Dockerfile
src/aspire-dashboard/8.0/cbl-mariner-distroless/arm64v8/Dockerfile

Fixes #5258
I tested this locally and was able to start the container and access the dashboard.
`pwsh .\build-and-test.ps1 -paths "*8.0*mariner*" -mode "Build"`
`docker run -p 18888:18888 -p 18889:18889 --rm mcr.microsoft.com/dotnet/nightly/aspire-dashboard:8.0.0-preview.5-amd64`

Enable localization in Aspire Dashboard image

---

eng/pipelines/dotnet-core.yml

I tested this, based on the main branch (not nightly) with the other 1ES PT commits here: https://dev.azure.com/dnceng/internal/_build/results?buildId=2407515&view=results
We should merge all pipelines into nightly and then make one merge from nightly to main when we are confident the changes are working well in nightly.
Part of https://github.com/dotnet/dotnet-docker-internal/issues/4475

Move dotnet-docker main pipeline to 1ES PT

---

eng/pipelines/dotnet-core-internal-nightly.yml

Part of https://github.com/dotnet/dotnet-docker-internal/issues/4475
Test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2408392&view=results

Move dotnet-docker-internal-nightly pipeline to 1ES pipeline templates

---

eng/pipelines/cg-images.yml

Validation is still running but I expect it to pass: https://dev.azure.com/dnceng/internal/_build/results?buildId=2408656&view=results
(previous run which timed out: https://dev.azure.com/dnceng/internal/_build/results?buildId=2408557&view=results)
I had to up the timeout a few times. It sits at 1 hour right now which should give us some buffer in case we ever end up with more images than we have right now.
Part of https://github.com/dotnet/dotnet-docker-internal/issues/4475

Move cg-images pipeline to 1ES Pipeline Templates

---

eng/pipelines/cg-code.yml

Fixes #5289. The common variables were not included which caused the cgGrepArgs variable to be interpreted literally by grep when looking for projects to build.

Fix CG Code build

---

README.sdk.md
manifest.json

Fixes #5311 
The cause was a bad merge in https://github.com/dotnet/dotnet-docker/pull/5185 where 9.0 Dockerfiles were added to main. They have the latest tag in nightly, only half the merge got done correctly (i.e. we ended up with no latest tag across 8.0/9.0).

Add latest tag back to 8.0 SDK

---

eng/pipelines/update-dependencies-monitor.yml

.NET Monitor produces nightly builds of its 9.0 version out of the `feature/9.x` branch; update the trigger on the dependency update pipeline to trigger on this branch.

Trigger dependency update for .NET Monitor 9.0 nightly builds

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/feature-request.md

New issues that are created with the templates do not automatically get assigned the `untriaged` label by https://github.com/apps/dotnet-issue-labeler. This works around that by explicitly defining the templates to set `untriaged`.

Force new issues to have untriaged label

---

.mar/portal/README.aspire-dashboard.portal.md
README.aspire-dashboard.md
eng/readme-templates/README.mcr.md
eng/readme-templates/README.md
eng/readme-templates/Use.aspire-dashboard.md
eng/readme-templates/Use.md

Fixes #5153 
@drewnoakes @kvenkatrajan @JamesNK @davidfowl Grabbed most of the content from https://github.com/dotnet/aspire/blob/main/src/Aspire.Dashboard/README.md and just adapted variable names by swapping `:` for `__`. Please let me know if there is anything that should be changed here, or if there is any other feedback around the documentation structure.
@lbussell I tried several times but wasn't able to run the generate script to evaluate all the templates and generate the actual READMEs. Happy to follow any additional instructions on how to do this.

Adding Readme contents for the Aspire container image.

---

samples/complexapp/tests/tests.csproj

Resolves CG alert for CVE-2024-21907 due to Xunit and Microsoft.NET.Test.Sdk referencing an old version of Newtonsoft.json.

Update packages in complexapp sample

---

manifest.json

Fixes test build matrix generation in internal due to https://github.com/dotnet/dotnet-docker/pull/5338.

Add additional test-dependencies in manifest for 8.0 Mariner distroless

---

eng/update-dependencies/update-dependencies.csproj

Fixes CG issue due to vulnerable version of `System.Data.SqlClient` referenced by the previous version of this library. I ran a test with this new package version and it was able to create a AzDo PR with no issues. ([Test run](https://dev.azure.com/dnceng/internal/_build/results?buildId=2425684&view=results) [internal link])

Update `Microsoft.TeamFoundationServer.Client` package in update-dependencies tool

---

eng/update-dependencies/update-dependencies.csproj

This is a workaround for CVE-2024-0056, introduced as a transient dependency of 
Microsoft.TeamFoundationServer.Client in https://github.com/dotnet/dotnet-docker/pull/5341.

Update System.Data.SqlClient transient dependency in update-dependencies project

---

samples/dotnetapp/README.md

Multiple windows versions link returns a 404 error, due to an extra .md in url

Update link in README.md for samples dotnetapp

---

README.aspire-dashboard.md
manifest.versions.json
src/aspire-dashboard/8.0/cbl-mariner-distroless/amd64/Dockerfile
src/aspire-dashboard/8.0/cbl-mariner-distroless/arm64v8/Dockerfile

Aspire preview 6 has shipped, so updating the docker image to match this version.
cc: @lbussell

Updating aspire version to shipped Preview 6 build.

---

eng/pipelines/cg-images.yml

Port of https://github.com/dotnet/dotnet-docker/pull/5405 to `main`

Increase CG Images pipeline timeout

---

.mar/portal/README.aspire-dashboard.portal.md
.mar/portal/README.aspnet.portal.md
.mar/portal/README.monitor-base.portal.md
.mar/portal/README.monitor.portal.md
.mar/portal/README.runtime-deps.portal.md
.mar/portal/README.runtime.portal.md
.mar/portal/README.samples.portal.md
.mar/portal/README.sdk.portal.md
README.aspire-dashboard.md
README.md
eng/readme-templates/RelatedRepos.md

Fixes #5348
Related to #5349
I did not update the Docker Hub readmes to reference the main aspire-dashboard page because it still hasn't been created https://github.com/dotnet/dotnet-docker/issues/5327.

Add aspire-dashboard related repo links

---

eng/dockerfile-templates/Dockerfile.linux.install-deps
eng/dockerfile-templates/Dockerfile.linux.install-pkgs
src/runtime-deps/8.0/azurelinux3.0-distroless-aot/amd64/Dockerfile
src/runtime-deps/8.0/azurelinux3.0-distroless-aot/arm64v8/Dockerfile
src/runtime-deps/8.0/azurelinux3.0-distroless-extra/amd64/Dockerfile
src/runtime-deps/8.0/azurelinux3.0-distroless-extra/arm64v8/Dockerfile
src/runtime-deps/8.0/azurelinux3.0-distroless/amd64/Dockerfile
src/runtime-deps/8.0/azurelinux3.0-distroless/arm64v8/Dockerfile
src/runtime-deps/8.0/azurelinux3.0/amd64/Dockerfile
src/runtime-deps/8.0/azurelinux3.0/arm64v8/Dockerfile

Workaround https://github.com/dotnet/dotnet-docker/issues/5479 by removing the symcrypt package with the bug. I tested by running the following:
Before:
```pwsh
PS> docker run --rm azurelinuxpreview.azurecr.io/public/azurelinux/base/core:3.0 /bin/sh -c "curl https://bing.com"
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0[ERROR] error:41080106:SCOSSL::passed invalid argument:set_iv_fixed only works with TLS IV length at /usr/src/azl/BUILD/SymCrypt-OpenSSL-1.4.2/ScosslCommon/src/scossl_aes_aead.c, line 305
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) OpenSSL/3.3.0: error:41080106:SCOSSL::passed …
```

Workaround symcrypt openssl issue in Azure Linux 3.0 base image

---

eng/Get-DropVersions.ps1
eng/Set-DotnetVersions.ps1
eng/pipelines/update-dependencies-internal.yml
eng/pipelines/update-dependencies.yml

Builds of 9.0 SDK now come from dotnet/sdk instead of dotnet/installer. This updates the scripts to compensate for this.

Update scripts to compensate for installer->sdk migration

---

.github/ISSUE_TEMPLATE/releases/dotnet-release-lifecycle.md

Related: https://github.com/microsoft/dotnet-framework-docker/pull/1134

Add missing .NET Fx template link to lifecycle checklist

---

eng/dockerfile-templates/sdk/Dockerfile.linux.install-sdk
src/sdk/9.0/noble/arm32v7/Dockerfile

This was the result of a bad merge from nightly to main, which prevented this image from being able to build.

Fix SDK installation in 9.0 Noble arm32 Dockerfile

---

README.aspnet.md
README.monitor-base.md
README.monitor.md
README.runtime-deps.md
README.runtime.md
README.samples.md
README.sdk.md
eng/readme-templates/RelatedRepos.md

Fixes https://github.com/dotnet/dotnet-docker/issues/5349.
The aspire-dashboard link is present in every Readmes' Related Repositories section except for the main GitHub readmes.

Add aspire-dashboard to every Related Repositories readme section

---

README.sdk.md
eng/dockerfile-templates/sdk/Dockerfile.linux.aot
manifest.json
src/sdk/8.0/alpine3.19-aot/amd64/Dockerfile
src/sdk/8.0/alpine3.19-aot/arm64v8/Dockerfile
src/sdk/8.0/alpine3.20-aot/amd64/Dockerfile
src/sdk/8.0/alpine3.20-aot/arm64v8/Dockerfile
src/sdk/8.0/cbl-mariner2.0-aot/amd64/Dockerfile
src/sdk/8.0/cbl-mariner2.0-aot/arm64v8/Dockerfile
src/sdk/8.0/jammy-aot/amd64/Dockerfile
src/sdk/8.0/jammy-aot/arm64v8/Dockerfile
src/sdk/8.0/noble-aot/amd64/Dockerfile
src/sdk/8.0/noble-aot/arm64v8/Dockerfile

This removes the special `-1` tag suffix that was added in https://github.com/dotnet/dotnet-docker/pull/5579. This ensures that we don't accidentally leave it in for the next release.

Remove `-1` tag suffix for sdk

---

tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs

Disabling these tests due to https://github.com/dotnet/dotnet-docker/issues/5592. This will allow builds to get through more easily while the issue is investigated.

Disable PowerShell tests for .NET 9 on Arm32

---

.portal-docs/docker-hub/README.aspire-dashboard.md
.portal-docs/docker-hub/README.aspnet.md
.portal-docs/docker-hub/README.monitor-base.md
.portal-docs/docker-hub/README.monitor.md
.portal-docs/docker-hub/README.runtime-deps.md
.portal-docs/docker-hub/README.runtime.md
.portal-docs/docker-hub/README.samples.md
.portal-docs/docker-hub/README.sdk.md
README.aspire-dashboard.md
README.aspnet.md
README.md
README.monitor-base.md
README.monitor.md
README.runtime-deps.md
README.runtime.md
README.samples.md
README.sdk.md
eng/readme-templates/Url.md

Updates Docker Hub links to match the new URL format. The old links still redirect to the new one but might as well avoid that.

Use new URL format for Docker Hub pages

---

tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
tests/Microsoft.DotNet.Docker.Tests/FileHelper.cs
tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs

Closes https://github.com/dotnet/dotnet-docker/issues/4843
This PR primarily focuses on changing the `VerifyDotnetFolderContents` test to compare the folder contents using `git diff`. These changes involve the introduction of new helper methods for file comparison, the creation of temporary files, and the simplification of the test assertions.
- FileHelper.cs:
* Removed unused imports and added new ones for `System.Diagnostics` and `Xunit.Abstractions`.
* Replaced the `CompareLists` method with a new `CompareFiles` method that compares two files using `git diff` via the `DiffFiles` method. Also, added a new `UseTempFile` method that creates a temporary file.
* Introduced a new `TempFileContext` class that creates a temporary file in its constructor and deletes it in its `Dispose` method. …

Compare VerifyDotnetFolderContents using Git Diff

---

eng/dockerfile-templates/runtime-deps/Dockerfile.chiseled-ubuntu
src/runtime-deps/6.0/jammy-chiseled-extra/amd64/Dockerfile
src/runtime-deps/6.0/jammy-chiseled-extra/arm32v7/Dockerfile
src/runtime-deps/6.0/jammy-chiseled-extra/arm64v8/Dockerfile
src/runtime-deps/6.0/jammy-chiseled/amd64/Dockerfile
src/runtime-deps/6.0/jammy-chiseled/arm32v7/Dockerfile
src/runtime-deps/6.0/jammy-chiseled/arm64v8/Dockerfile
src/runtime-deps/8.0/jammy-chiseled-extra/amd64/Dockerfile
src/runtime-deps/8.0/jammy-chiseled-extra/arm32v7/Dockerfile
src/runtime-deps/8.0/jammy-chiseled-extra/arm64v8/Dockerfile
src/runtime-deps/8.0/jammy-chiseled/amd64/Dockerfile
src/runtime-deps/8.0/jammy-chiseled/arm32v7/Dockerfile
src/runtime-deps/8.0/jammy-chiseled/arm64v8/Dockerfile
src/runtime-deps/8.0/noble-chiseled-extra/amd64/Dockerfile
src/runtime-deps/8.0/noble-chiseled-extra/arm64v8/Dockerfile
src/runtime-deps/8.0/noble-chiseled/amd64/Dockerfile
src/runtime-deps/8.0/noble-chiseled/arm64v8/Dockerfile
src/runtime-deps/9.0/noble-chiseled-extra/arm32v7/Dockerfile
src/runtime-deps/9.0/noble-chiseled/arm32v7/Dockerfile

Fixes a build issue with the Ubuntu Chiseled images:
```
------
> [chisel 3/5] RUN go install github.com/canonical/chisel/cmd/chisel@v0.10.0     && wget -O /usr/bin/chisel-wrapper https://raw.githubusercontent.com/canonical/rocks-toolbox/v1.1.2/chisel-wrapper     && chmod 755 /usr/bin/chisel-wrapper:
1.371 go: downloading github.com/canonical/chisel v0.10.0
2.325 go: downloading github.com/jessevdk/go-flags v1.5.0
2.327 go: downloading golang.org/x/term v0.18.0
2.344 go: downloading github.com/blakesmith/ar v0.0.0-20190502131153-809d4375e1fb
2.349 go: downloading github.com/klauspost/compress v1.15.4
2.351 go: downloading github.com/ulikunitz/xz v0.5.10
2.372 go: downloading golang.org/x/crypto v0.21.0
2.399 go: downloading github.com/juju/fslock v0.0.0-20160525022230-4d5c94c67b4b
2.408 …
```

Update golang to 1.21

---

eng/dockerfile-templates/runtime-deps/Dockerfile.chiseled-ubuntu
manifest.versions.json
src/runtime-deps/6.0/jammy-chiseled-extra/amd64/Dockerfile
src/runtime-deps/6.0/jammy-chiseled-extra/arm32v7/Dockerfile
src/runtime-deps/6.0/jammy-chiseled-extra/arm64v8/Dockerfile
src/runtime-deps/6.0/jammy-chiseled/amd64/Dockerfile
src/runtime-deps/6.0/jammy-chiseled/arm32v7/Dockerfile
src/runtime-deps/6.0/jammy-chiseled/arm64v8/Dockerfile
src/runtime-deps/8.0/jammy-chiseled-extra/amd64/Dockerfile
src/runtime-deps/8.0/jammy-chiseled-extra/arm32v7/Dockerfile
src/runtime-deps/8.0/jammy-chiseled-extra/arm64v8/Dockerfile
src/runtime-deps/8.0/jammy-chiseled/amd64/Dockerfile
src/runtime-deps/8.0/jammy-chiseled/arm32v7/Dockerfile
src/runtime-deps/8.0/jammy-chiseled/arm64v8/Dockerfile
src/runtime-deps/8.0/noble-chiseled-extra/amd64/Dockerfile
src/runtime-deps/8.0/noble-chiseled-extra/arm64v8/Dockerfile
src/runtime-deps/8.0/noble-chiseled/amd64/Dockerfile
src/runtime-deps/8.0/noble-chiseled/arm64v8/Dockerfile
src/runtime-deps/9.0/noble-chiseled-extra/arm32v7/Dockerfile
src/runtime-deps/9.0/noble-chiseled/arm32v7/Dockerfile

Seeing as Chisel v0.10.0 is untested in the nightly branch, the safest thing to do for the release is downgrade to the last known-good version until next month's servicing.

Downgrade chisel to v0.9.1

---

eng/dockerfile-templates/Dockerfile.linux.install-deps
eng/dockerfile-templates/runtime-deps/Dockerfile
eng/dockerfile-templates/runtime-deps/Dockerfile.aot
eng/dockerfile-templates/runtime-deps/Dockerfile.chiseled-ubuntu
eng/dockerfile-templates/runtime-deps/Dockerfile.chiseled-ubuntu.aot
eng/dockerfile-templates/runtime-deps/Dockerfile.distroless-mariner
eng/dockerfile-templates/runtime-deps/Dockerfile.distroless-mariner.aot

This PR resets the templates in the main branch to the state that they're currently in in the nightly branch.
The Dockerfile templates are carefully architected to prevent the addition of new features from affecting existing Dockerfiles. As such, including new templates (like AOT) in the main branch does not affect the Dockerfiles in the main branch. To simplify merges from nightly to main and vice versa, the templates should stay the same between the two branches.
I'm submitting this PR now so that we can sync up the templates before there are any additional changes added to nightly for the August release.

Synchronize Dockerfile templates with nightly branch

---

samples/releasesapi/Dockerfile.ubuntu-chiseled

Follow-up from https://github.com/dotnet/dotnet-docker/pull/5671 - this change was missing from the main branch.
This is the second half of https://github.com/dotnet/dotnet-docker/issues/5659.

Synchronize samples with nightly branch

---

tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs

This fixes half of #5657. The linked runtime issue is fixed so this test should be re-enabled.

[nightly] Re-enable aspnet app scenario test due to fixed runtime issue

---

tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs

This is the second half of https://github.com/dotnet/dotnet-docker/issues/5657. The linked runtime issue is fixed so this test should be re-enabled.

[main] Re-enable aspnet app scenario test due to fixed runtime issue

---

tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs

This should fix #5683 if CI passes.

Re-enable .NET 9 Windows ASP.NET scenario tests

---

eng/dockerfile-templates/runtime-deps/Dockerfile.chiseled-ubuntu
src/runtime-deps/6.0/jammy-chiseled-extra/amd64/Dockerfile
src/runtime-deps/6.0/jammy-chiseled-extra/arm32v7/Dockerfile
src/runtime-deps/6.0/jammy-chiseled-extra/arm64v8/Dockerfile
src/runtime-deps/6.0/jammy-chiseled/amd64/Dockerfile
src/runtime-deps/6.0/jammy-chiseled/arm32v7/Dockerfile
src/runtime-deps/6.0/jammy-chiseled/arm64v8/Dockerfile
src/runtime-deps/8.0/jammy-chiseled-aot/amd64/Dockerfile
src/runtime-deps/8.0/jammy-chiseled-aot/arm32v7/Dockerfile
src/runtime-deps/8.0/jammy-chiseled-aot/arm64v8/Dockerfile
src/runtime-deps/8.0/jammy-chiseled-extra/amd64/Dockerfile
src/runtime-deps/8.0/jammy-chiseled-extra/arm32v7/Dockerfile
src/runtime-deps/8.0/jammy-chiseled-extra/arm64v8/Dockerfile
src/runtime-deps/8.0/jammy-chiseled/amd64/Dockerfile
src/runtime-deps/8.0/jammy-chiseled/arm32v7/Dockerfile
src/runtime-deps/8.0/jammy-chiseled/arm64v8/Dockerfile
src/runtime-deps/8.0/noble-chiseled-aot/amd64/Dockerfile
src/runtime-deps/8.0/noble-chiseled-aot/arm64v8/Dockerfile
src/runtime-deps/8.0/noble-chiseled-extra/amd64/Dockerfile
src/runtime-deps/8.0/noble-chiseled-extra/arm64v8/Dockerfile
src/runtime-deps/8.0/noble-chiseled/amd64/Dockerfile
src/runtime-deps/8.0/noble-chiseled/arm64v8/Dockerfile
src/runtime-deps/9.0/noble-chiseled-aot/arm32v7/Dockerfile
src/runtime-deps/9.0/noble-chiseled-extra/arm32v7/Dockerfile
src/runtime-deps/9.0/noble-chiseled/arm32v7/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.linux
tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.windows

Our tests are failing because the Noble ca-certificates slice added a dependency on a file from the openssl slice. See https://github.com/canonical/chisel-releases/pull/266 for more context.

Add openssl to Noble Chiseled expected packages list

---

eng/pipelines/stages/build-test-publish-repo.yml
eng/pipelines/steps/set-imagebuilder-build-args-var.yml

Fixes https://github.com/dotnet/dotnet-docker/issues/3520

Remove workaround for Mariner ARM container images not setting architecture variant metadata

---

eng/common/templates/steps/test-images-linux-client.yml
eng/common/templates/steps/test-images-windows-client.yml
eng/common/templates/variables/dotnet/build-test-publish.yml
eng/pipelines/steps/set-custom-test-variables.yml
eng/pipelines/variables/samples.yml

This argument was unnecessarily placed in the shared templates under eng/common. It would be overwritten by https://github.com/dotnet/dotnet-docker/pull/5736. Instead, we should change the common template to allow additional arguments to be set beforehand by consuming repos, in case some pipelines may not have the variable set. Then, in this repo, we'll set the argument in the `build-test-publish` variables.

Factor test cache ACR argument out of common pipeline infrastructure

---

eng/update-dependencies/update-dependencies.csproj

Addresses CVE-2024-38095 caused by transitive dependency from Microsoft.DotNet.VersionTools.

Package upgrade for update-dependencies

---

.github/workflows/markdownlint-problem-matcher.json
.github/workflows/markdownlint.yml
.markdownlint.json

Related to https://github.com/dotnet/dotnet-docker/issues/5316
This initial set of changes just adds the linter action but disables numerous rules.  Once enabled I will open follow-up PRs to address the syntax violations.
The linter action was copied from [dotnet/runtime](https://github.com/dotnet/runtime/blob/main/.github/workflows/markdownlint.yml).

Add Markdown linter GH action

---

README.aspnet.md
README.runtime-deps.md
README.runtime.md
README.samples.md
README.sdk.md
eng/readme-templates/DefaultLayout.md

These changes remove the obsolete dotnet/core full tag listing from the GitHub readme tag listing section.  The dotnet/core repos were used back when the product was referred to as .NET Core.  Core was dropped from the name when 5.0 was released.  The only images that we stop listing are 1.0 and 1.1.  All other images are available in the current dotnet repos.

Remove the link to the obsolete dotnet/core full tag listing

---

samples/host-aspnetcore-https.md
samples/run-aspnetcore-https-development.md

As of 9.0 RC1 and 8.0.9, `--trust` should work on Linux as well (though it is only officially supported on Ubuntu and Fedora).

Drop caveats about dev cert trust on Linux

---

tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.copy
tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/Dockerfile.distroless

Fixes https://github.com/dotnet/dotnet-docker/issues/4845
These changes implement the use of a multi-stage Dockerfile to copy the SDK contents of the image being tested into a local directory. The test builds the image using this Dockerfile and then runs `find {sdkCopyPath} -type f -exec sha512sum {{}} +` to output the hashes.

Run VerifyDotnetFolderContents test on all images

---

eng/Get-DropVersions.ps1

There were a couple of minor issues with the Get-DropVersions.ps1 script that I discovered when creating #5772.
1. Fix situation where Sdks can be an array with a single value. PowerShell treats arrays with single values as the value itself. So we need to force it to be an array or else we'll get an empty value for SdkVersion.
2. Fix PSObject reference in string.

Fix issues with Get-DropVersions.ps1 using Build ID

---

tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs

Related: #5704 
Some BlazorWASM tests are passing when we expected them to fail in the main branch. To get around this for now, I have skipped the test when failures are expected. This is a temporary solution until a follow-up to https://github.com/dotnet/dotnet-docker/issues/5704 is addressed. I'll file an issue for the follow-up and link it back to here.

Don't validate failures for BlazorWASM test

---

tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs

Fixes https://github.com/dotnet/dotnet-docker/issues/5785
This enables the SDK content tests to run on every OS + .NET version combination except for CBL-Mariner 2.0 + .NET 6.0.

Only skip SDK content tests on CBL-Mariner + .NET 6.0

---

tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs

Port of https://github.com/dotnet/dotnet-docker/pull/5814 to nightly

[Nightly] Only skip SDK content tests on CBL-Mariner + .NET 6.0 (#5814)

---

eng/DependencyManagement.psm1
eng/Set-DotnetVersions.ps1
eng/pipelines/steps/update-dotnet-dependencies.yml
eng/pipelines/update-dependencies-monitor.yml
eng/update-dependencies/BaseUrlUpdater.cs
eng/update-dependencies/ManifestHelper.cs
eng/update-dependencies/Options.cs

The intent of this change is to allow the update-dependencies tool to set the product base URL as it is updating the product version. This allows automation to automatically fix up the product base URL to correspond with where the product version assets are staged at the time of updating.
An example situation where this would be useful is when a security release is inserted directly into the main branch (which means its only the dotnetcli storage account at time of publishing) but the assets were never available on the dotnetbuilds storage account. When those changes are merged back to the nightly branch, automated updates for prerelease versions are stuck until the base URL is manually updated (along with a new product version) in the nightly branch.
With the proposed changes, the …

Allow update-dependencies to update product base URL

---

eng/dockerfile-templates/aspire-dashboard/Dockerfile.linux.install-aspire-dashboard
eng/dockerfile-templates/monitor-base/Dockerfile.linux.install-monitor-base
eng/dockerfile-templates/monitor/Dockerfile.linux.install-extensions
eng/dockerfile-templates/monitor/Dockerfile.linux.install-monitor

The appliance-style image templates use a non-trivial base URL lookup based on version patterns and equality of product and build version. This was born out of necessity when there were only one set of base URLs for a given version and branch in the [manifest.versions.json](https://github.com/dotnet/dotnet-docker/blob/d5943b12928c24b8d16da6c0a2d805823c3f436a/manifest.versions.json) file that dictated the base URL for all products. [Subsequent changes](https://github.com/dotnet/dotnet-docker/commit/6a957822418dfdfd78a4816154dfdd3926b51e29#diff-f657b02176508554b475067f99d956c3c0fb1c08be55990212cb9179813b4aca) further split the URLs by product, thus each product can independently declare its base URLs for each version and branch combination.
The complicated logic for calculating the base URL …

Simplify appliance product base URL calculation

---

eng/common/templates/jobs/publish.yml

The changes from https://github.com/dotnet/dotnet-docker/pull/5837 have caused the following exception when executing the `generateEolAnnotationsData` command:
```
Error occurred while generating EOL annotation data: System.AggregateException: Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry or by configuring a custom retry policy in ClientOptions.RetryPolicy. (Name or service not known (public:443)) (Name or service not known (public:443)) (Name or service not known (public:443)) (Name or service not known (public:443))
---> Azure.RequestFailedException: Name or service not known (public:443)
---> System.Net.Http.HttpRequestException: Name or service not known (public:443)
---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
at …
```

Switch arg order to fix EOL publishing

---

.portal-docs/docker-hub/README.aspire-dashboard.md
.portal-docs/docker-hub/README.aspnet.md
.portal-docs/docker-hub/README.monitor-base.md
.portal-docs/docker-hub/README.monitor.md
.portal-docs/docker-hub/README.runtime-deps.md
.portal-docs/docker-hub/README.runtime.md
.portal-docs/docker-hub/README.samples.md
.portal-docs/docker-hub/README.sdk.md
.portal-docs/mar/README.aspire-dashboard.portal.md
.portal-docs/mar/README.aspnet.portal.md
.portal-docs/mar/README.monitor-base.portal.md
.portal-docs/mar/README.monitor.portal.md
.portal-docs/mar/README.runtime-deps.portal.md
.portal-docs/mar/README.runtime.portal.md
.portal-docs/mar/README.samples.portal.md
.portal-docs/mar/README.sdk.portal.md
README.aspire-dashboard.md
README.aspnet.md
README.md
README.monitor-base.md
README.monitor.md
README.runtime-deps.md
README.runtime.md
README.samples.md
README.sdk.md
documentation/supported-tags.md
eng/readme-templates/Support.md

Our current Image Update policy specifies that we only force re-build for base image updates and CRITICAL severity CVEs. Ubuntu Chiseled images are made from `scratch`, so that never happens. In the case where .NET servicing skips a month, that leaves Chiseled users with no updates for two whole months. Since Ubuntu Chiseled has limited support for extending or updating images (https://github.com/dotnet/dotnet-docker/issues/4811, https://github.com/canonical/chisel/issues/118), that leaves users without any action to take to resolve any HIGH or lower severity CVEs that have been disclosed since the last re-build.
In practice, this hasn't been a huge issue because Chiseled images inherently have a much smaller attack surface than other images we publish. However, it's still a scenario …

Update Image Update Policy to include monthly rebuild clause

---

eng/update-dependencies/UpdateDependencies.cs

These were accidentally uncommented for debugging purposes in https://github.com/dotnet/dotnet-docker/commit/deca2174e601b501e322bc6ccdc5f6b4063eb848. This PR re-enables Dockerfile and Readme generation in the update-dependencies tool.

Re-enable Dockerfile and Readme updaters in update-dependencies tool

---

.github/linters/.check-markdown-links.json
README.md

Contributes to #5872 
1. Added config to skip https://support.microsoft.com/contactus/ which has been causing issues
2. Enabled retries
3. Alphabetized the config file

Adjustments to markdown link checker's configuration

---

documentation/supported-tags.md

This PR documents some of the policy decisions described in #4117 and https://github.com/dotnet/dotnet-docker/issues/5885

Add preview tags info to supported tags policy

---

README.aspire-dashboard.md
README.aspnet.md
README.md
README.monitor-base.md
README.monitor.md
README.runtime-deps.md
README.runtime.md
README.samples.md
README.sdk.md
eng/readme-templates/Url.md
samples/README.md

Fixes https://github.com/dotnet/dotnet-docker/issues/5905

Update GitHub related repo links to be github based

---

manifest.versions.json
src/sdk/9.0/alpine3.20/amd64/Dockerfile
src/sdk/9.0/azurelinux3.0/amd64/Dockerfile
src/sdk/9.0/azurelinux3.0/arm64v8/Dockerfile
src/sdk/9.0/bookworm-slim/amd64/Dockerfile
src/sdk/9.0/bookworm-slim/arm32v7/Dockerfile
src/sdk/9.0/bookworm-slim/arm64v8/Dockerfile
src/sdk/9.0/nanoserver-1809/amd64/Dockerfile
src/sdk/9.0/nanoserver-ltsc2022/amd64/Dockerfile
src/sdk/9.0/noble/amd64/Dockerfile
src/sdk/9.0/noble/arm32v7/Dockerfile
src/sdk/9.0/noble/arm64v8/Dockerfile
src/sdk/9.0/windowsservercore-ltsc2019/amd64/Dockerfile
src/sdk/9.0/windowsservercore-ltsc2022/amd64/Dockerfile

This pull request updates the PowerShell version used in various Dockerfiles and the `manifest.versions.json` file to `7.5.0-preview.5`. The changes ensure that the latest preview version of PowerShell is used across different platforms and architectures.
* [`manifest.versions.json`](diffhunk://#diff-f657b02176508554b475067f99d956c3c0fb1c08be55990212cb9179813b4acaL197-R202): Updated PowerShell `9.0` build version to `7.5.0-preview.5` and corresponding SHA values for various platforms and architectures.
* [`src/sdk/9.0/alpine3.20/amd64/Dockerfile`](diffhunk://#diff-7a7770082e05da6ac8f88009de501496e56f4a8c11804b15087cb7b0357e8223L39-R41): Updated PowerShell version to `7.5.0-preview.5` and corresponding SHA value.
* [`src/sdk/9.0/azurelinux3.0/amd64/Dockerfile`](diffhunk://#diff-e9cbabde8995 …

Updating PowerShell DotNet SDK

---

eng/common/templates/jobs/generate-matrix.yml
eng/common/templates/stages/build-test-publish-repo.yml
eng/common/templates/stages/dotnet/build-test-publish-repo.yml
eng/pipelines/stages/build-test-publish-repo.yml

The changes from https://github.com/dotnet/dotnet-docker/pull/5942 caused a regression in `GenerateBuildMatrix` job for this repo. It failed in the `Set Image Info Path Vars` step with this error:
```
5 |  $publicSourceBranch = "$(publicSourceBranch)"
|                           ~~~~~~~~~~~~~~~~~~
| The term 'publicSourceBranch' is not recognized as a name of a cmdlet,
| function, script file, or executable program. Check the spelling of the
| name, or if a path was included, verify that the path is correct and try
| again.
```
[Example build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2557404) (internal link)
This occurs because this repo has special logic for setting the `publicSourceBranch` variable that wasn't being executed for the `GenerateBuildMatrix` job. It is …

Set publicSourceBranch var for matrix generation

---

.portal-docs/docker-hub/README.aspire-dashboard.md
.portal-docs/docker-hub/README.aspnet.md
.portal-docs/docker-hub/README.monitor-base.md
.portal-docs/docker-hub/README.monitor.md
.portal-docs/docker-hub/README.runtime-deps.md
.portal-docs/docker-hub/README.runtime.md
.portal-docs/docker-hub/README.sdk.md
.portal-docs/mar/README.aspire-dashboard.portal.md
.portal-docs/mar/README.aspnet.portal.md
.portal-docs/mar/README.monitor-base.portal.md
.portal-docs/mar/README.monitor.portal.md
.portal-docs/mar/README.runtime-deps.portal.md
.portal-docs/mar/README.runtime.portal.md
.portal-docs/mar/README.sdk.portal.md
README.aspire-dashboard.md
README.aspnet.md
README.monitor-base.md
README.monitor.md
README.runtime-deps.md
README.runtime.md
README.sdk.md
eng/readme-templates/RelatedRepos.md

Fixes #5937
I put the main repo on top of the other nightly repos. My thinking was that the related repos lists should all follow the same order, across branches and repos:
1. Product family repos
2. Supported/main repos
3. Nightly repos
4. Samples repos
Obviously, which repos are "related" is different from repo to repo.
This will also change the order in the main branch - but I think it is more consistent
```diff
* [dotnet](https://github.com/dotnet/dotnet-docker/blob/main/README.md): .NET
* [dotnet/sdk](https://github.com/dotnet/dotnet-docker/blob/main/README.sdk.md): .NET SDK
* [dotnet/runtime](https://github.com/dotnet/dotnet-docker/blob/main/README.runtime.md): .NET Runtime
* [dotnet/runtime-deps](https://github.com/dotnet/dotnet-docker/blob/main/README.runtime-deps.md): .NET …
```

Add main repo to nightly repos related readmes

---

documentation/vulnerability-reporting.md

Fixes #5060. There were already some Azure Linux commands in the document but this PR adds the remaining ones.
I also replaced "linux-hardened" terminology with "distroless" since we don't use that terminology anywhere else, and added links to the Syft project rather than referring to it in magic commands.

Add more Azure Linux commands to vulnerability reporting documentation

---

.portal-docs/docker-hub/README.monitor-base.md
.portal-docs/docker-hub/README.monitor.md
.portal-docs/mar/README.monitor-base.portal.md
.portal-docs/mar/README.monitor.portal.md
README.monitor-base.md
README.monitor.md
eng/readme-templates/About.md
eng/readme-templates/About.monitor-base.md
eng/readme-templates/About.monitor.md
eng/readme-templates/Url.md
eng/readme-templates/Use.monitor-base.md
eng/readme-templates/Use.monitor.md

These changes to the .NET Monitor readmes are intended to better describe the intended usage of base and derived .NET Monitor images and link to more examples of how the derived image is intended to be used. The `dotnet/monitor/base` readme attempts to steer customers to the `dotnet/monitor` readme for those who are intending to use the full functionality of .NET Monitor rather than building a customized .NET Monitor image.
closes #5933

Update .NET Monitor readmes

---

documentation/image-artifact-details.md

Add instructions for getting the license and notice file paths from the .NET Monitor images. The instructions are difference for .NET Monitor 7 and lower vs .NET Monitor 8 and higher due to the switch to distroless base image usage in .NET Monitor 8; I hope the distinction is evident in this doc update, at least enough to explain why the instructions are different.
Closes #4611

Add image detail instructions for .NET Monitor

---

tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs

Fixes #6007 
Internal test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2568476&view=logs&j=1cd3c31d-f87a-5340-7f4c-1efc1ae5d874&t=e94617f8-c028-5efe-9cc4-f7765cc028e5
This was a regression from https://github.com/dotnet/dotnet-docker/pull/5928

Condition out internal authentication for VerifyDotnetFolderContents test

---

README.aspire-dashboard.md
manifest.versions.json
src/aspire-dashboard/9.0/cbl-mariner-distroless/amd64/Dockerfile
src/aspire-dashboard/9.0/cbl-mariner-distroless/arm64v8/Dockerfile

Updating Aspire-dashboard image to contain a more recent build of the dashboard.

Update Aspire to latest version from release/9.0 branch

---

eng/Get-DropVersions.ps1
eng/dockerfile-templates/aspnet/Dockerfile.envs
eng/dockerfile-templates/aspnet/Dockerfile.linux
eng/dockerfile-templates/aspnet/Dockerfile.linux-composite
eng/dockerfile-templates/aspnet/Dockerfile.windows
eng/dockerfile-templates/runtime/Dockerfile.envs
eng/dockerfile-templates/runtime/Dockerfile.linux
eng/dockerfile-templates/runtime/Dockerfile.windows
eng/dockerfile-templates/sdk/Dockerfile.envs
eng/dockerfile-templates/sdk/Dockerfile.linux
eng/dockerfile-templates/sdk/Dockerfile.windows

Servicing builds have stable versions. Artifacts are in URLs that contain non-stable version in their path. We will now obtain non-stable build versions, from config.json. This covers all scenarios of dependency update of internal builds.
Additional changes:
- set ENV vars with correct stable version, if build uses stable branding
- pass the `StableBranding` argument to `Set-DotnetVersions.ps1` - this enables developer flow, when using `-updateDependencies` with stable builds
- scope the changes to internal testing scenarios

Enable testing of internal stable-versioned servicing builds

---

README.aspire-dashboard.md
manifest.versions.json
src/aspire-dashboard/9.0/cbl-mariner-distroless/amd64/Dockerfile
src/aspire-dashboard/9.0/cbl-mariner-distroless/arm64v8/Dockerfile

Updating Aspire to 9.0.1 preview 1

---

build-and-test.ps1
tests/run-tests.ps1

This fixes a bug which prevented you from running the correct tests when passing paths to `build-and-test.ps1`
Other changes:
- Avoid running the `pre-build` tests twice by removing it from the test categories if it is ran before the build step.
- Don't run the build twice if we aren't building samples.
- Adjust the default test categories to make building and testing faster by default.

Pass paths to test script from build-and-test

---

tests/Microsoft.DotNet.Docker.Tests/TestScenarios/WebScenario.cs

This change fixes some issues when testing images locally. Some web tests would fail with the message: "The response ended prematurely".
Now, we only short-circuit the retry loop if the container crashed or never started for some reason.

Accept more types of failures when retrying HTTP requests in tests

---

tests/Microsoft.DotNet.Docker.Tests/CommonRuntimeImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
tests/Microsoft.DotNet.Docker.Tests/RuntimeDepsImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/TestData.cs
tests/Microsoft.DotNet.Docker.Tests/TestScenarios/ConsoleAppScenario.cs
tests/Microsoft.DotNet.Docker.Tests/TestScenarios/WebScenario.cs

This PR is built off of [Accept more types of failures when retrying HTTP requests in tests (#6063)](https://github.com/dotnet/dotnet-docker/pull/6063) since that change was necessary for more reliable local testing. That's commit 3f88859af81adde500b8bcd4bafc4f45cc1b994b.
Fixes #6049 
Basically, once the test filtering was fixed in https://github.com/dotnet/dotnet-docker/pull/5983/commits/1c0e89dca3f55199194063b2fd47f9fc3ec2d97b, some AOT tests were failing. Here is a summary of what was happening:
- AOT scenario tests were running on non-AOT images which was failing.
- This is resolved by filtering test data by variant.
- Self-contained publish scenario tests were running on AOT images which will never work since AOT images don't contain the correct dependencies.
- Console app "AOT" …

Fix AOT tests in nightly

---

eng/pipelines/variables/samples.yml

Running the samples pipeline does not cause EOL annotations to be published. This is because the `publishEolAnnotations` variable is not set. It's set here: https://github.com/dotnet/dotnet-docker/blob/569867de6c98363ae8a41b854b6615e4548c5caa/eng/pipelines/variables/core.yml#L9-L10
But that is not used by the samples pipeline. Added the variable to the template that will be used by the samples pipeline.

Enable EOL annotation publishing for samples pipeline

---

.portal-docs/docker-hub/README.aspnet.md
.portal-docs/docker-hub/README.monitor.md
.portal-docs/docker-hub/README.runtime-deps.md
.portal-docs/docker-hub/README.runtime.md
.portal-docs/docker-hub/README.sdk.md
.portal-docs/mar/README.aspnet.portal.md
.portal-docs/mar/README.monitor.portal.md
.portal-docs/mar/README.runtime-deps.portal.md
.portal-docs/mar/README.runtime.portal.md
.portal-docs/mar/README.sdk.portal.md
README.aspnet.md
README.monitor.md
README.runtime-deps.md
README.runtime.md
README.sdk.md
documentation/image-artifact-details.md
documentation/scenarios/installing-dotnet.md
documentation/scripts/Dockerfile.distroless-wrapper
documentation/supported-tags.md
documentation/vulnerability-reporting.md
eng/readme-templates/FeaturedTags.md
samples/aspnetapp/README.md
samples/dotnetapp/README.md
samples/selecting-tags.md

Of note:
- I updated the "Determining License and Source Pedigree for .NET Container Images" instructions for distroless images since I needed to update that command output anyways.
- Updated ASP.NET port selection documentation
Remaining to do (I will update this PR):

Remove .NET 6 references from documentation

---

eng/pipelines/dotnet-core-nightly-pr-no-cache.yml
eng/pipelines/dotnet-core-nightly-pr.yml
eng/pipelines/dotnet-core-nightly.yml
eng/pipelines/variables/core.yml

This also cleans up usage of `publishEolAnnotations` in nightly pipeline. These are obsolete now that it's incorporated into `core.yml` which is referenced by all those pipelines.

Merge main to nightly

---

documentation/supported-tags.md
documentation/vulnerability-reporting.md
samples/selecting-tags.md

Attempting to fix [Define doc providing guidance on Linux distros (#5063)](https://github.com/dotnet/dotnet-docker/issues/5063) while also cleaning up some stale documentation at the same time.
Related: [Remove .NET 6 references from documentation (#6101)](https://github.com/dotnet/dotnet-docker/pull/6101)

Update selecting tags documentation

---

eng/update-dependencies/BaseUrlUpdater.cs
eng/update-dependencies/ChecksumHelper.cs
eng/update-dependencies/ChiselUpdater.cs
eng/update-dependencies/DockerfileShaUpdater.cs
eng/update-dependencies/ErrorTraceListener.cs
eng/update-dependencies/GitHubHelper.cs
eng/update-dependencies/GitHubReleaseUpdaterBase.cs
eng/update-dependencies/GitHubReleaseUrlUpdater.cs
eng/update-dependencies/GitHubReleaseVersionUpdater.cs
eng/update-dependencies/JsonHelper.cs
eng/update-dependencies/ManifestHelper.cs
eng/update-dependencies/MinGitUpdater.cs
eng/update-dependencies/NuGetConfigUpdater.cs
eng/update-dependencies/Options.cs
eng/update-dependencies/RocksToolboxUpdater.cs
eng/update-dependencies/ScriptRunnerUpdater.cs
eng/update-dependencies/SyftUpdater.cs
eng/update-dependencies/UpdateDependencies.cs
eng/update-dependencies/VariableUpdaterBase.cs
eng/update-dependencies/VersionUpdater.cs
eng/update-dependencies/update-dependencies.csproj

Related: https://github.com/dotnet/dotnet-docker/issues/5006, https://github.com/dotnet/dotnet-docker/pull/6114#discussion_r1887343464

Enable nullable annotations in update-dependencies project

---

eng/pipelines/jobs/update-tools.yml
eng/pipelines/update-dependencies.yml

Fixes #5990 
Each tool will run in a separate job. If one fails, then the others should still run and submit PRs.
https://github.com/dotnet/dotnet-docker/pull/6121 was a test showing that this functionality works.

Submit separate PRs for each tool's dependency updates

---

.dockerignore

There are a couple of checked-in files in the `.vscode` directory now. Because `.vscode` is in `.dockerignore`, when we run update-dependencies in a Docker container, it tries to remove those files. For example: https://github.com/dotnet/dotnet-docker/pull/6126/commits/737bd714ed608bc359d9f30e7e872b0d8589f192

Remove `.vscode` directory from `.dockerignore`

---

.github/workflows/check-markdown-links.yml

GitHub Actions recently updated the `ubuntu-latest` runner to 24.04. There is an issue with the linkspector (markdown link check) GH action on 24.04. See https://github.com/UmbrellaDocs/action-linkspector/issues/32.

Downgrade linkspector GitHub action to Ubuntu 22.04 due to a bug

---

.github/workflows/check-markdown-links.yml

[main] Downgrade linkspector GitHub action to Ubuntu 22.04 due to a bug 

---

tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/CommonRuntimeImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/Microsoft.DotNet.Docker.Tests.csproj
tests/Microsoft.DotNet.Docker.Tests/RuntimeImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/NLSTest.Dockerfile
tests/Microsoft.DotNet.Docker.Tests/TestAppArtifacts/NLSTest.cs
tests/Microsoft.DotNet.Docker.Tests/TestScenarios/NLSScenario.cs
tests/Microsoft.DotNet.Docker.Tests/TestScenarios/NlsScenario.cs
tests/Microsoft.DotNet.Docker.Tests/WindowsImageTheoryAttribute.cs

- Fixes #6034 
NLS is Windows-only, so I defined a completely separate scenario for it that runs only on Windows.
The test uses the [recommended method](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-icu#determine-if-your-app-is-using-icu) for determining whether or not we're using ICU, and then validates some of the differences between NLS and ICU behavior based on what it finds.
For now, we will expect that NLS is used on all Nano Server images, and ICU is used on all Windows Server Core images. ICU has been the default on Server Core since .NET 7 and Server Core LTSC 2019. See https://learn.microsoft.com/en-us/dotnet/core/compatibility/globalization/7.0/icu-globalization-api for more context there.

Add NLS test scenario

---

eng/update-dependencies/DockerfileShaUpdater.cs
samples/releasesapi/ReleaseValues.cs
samples/releasesapp/ReleaseValues.cs

Removing last bits of "dotnetcli." usage.
Related: https://github.com/dotnet/core/issues/9671

Update dotnetcli domain in samples

---

eng/update-dependencies/DockerfileShaUpdater.cs

Related: https://github.com/dotnet/core/issues/9671

Remove blob storage domain from eng/updater

---

eng/dockerfile-templates/aspnet/Dockerfile.windows

Follow-up to https://github.com/dotnet/dotnet-docker/pull/6160. The issue also affected the aspnet Dockerfile templates.

Fix regressions in Windows ASP.NET internal templates

---

README.aspnet.md
README.runtime-deps.md
README.runtime.md
README.sdk.md
manifest.json
manifest.versions.json

Fixes #6178 
I made this edit using regexes and documented it for future reference. Expand the details to see the patterns that were used.
<details>
First, match all Alpine tags.
```
( )*("\$\((?:dotnet|sdk)\|\d+\.0\|minor-tag\))(-alpine)((?:3.\d+)?)((?:-aot)?(?:-extra)?(?:-composite)?(?:-(?:amd64|arm64v8|arm32v7))?")(: \{\})
```
We can modify this to select floating tags only. I chose to match two lines in order to get the previous line which will need to be modified since it has a comma.
```
Regex capture groups:
1   2                                         3         4           5
(\s+)("\$\((?:dotnet|sdk)\|\d+\.0\|minor-tag\))(-alpine)((?:3.\d+)?)((?:-aot)?(?:-extra)?(?:-composite)?(?:-(?:amd64|arm64v8|arm32v7))?"): \{\}(?:,)?\n\1\2\3\5\{6}: \{\}
```
``` …
```

Move Alpine floating tags from 3.20 to 3.21

---

tests/Microsoft.DotNet.Docker.Tests/Config.cs

PR builds have suddenly started failing with errors like `/dotnet/nightly/sdk:10.0-preview-alpine3.21-amd64` could not be found on disk.` The image name here is not valid because it is missing the registry name.
The registry doesn't get defaulted to `mcr.microsoft.com` because of this check: https://github.com/dotnet/dotnet-docker/blob/f528525ecaa407f6ba09384c321d4611afc461e0/tests/Microsoft.DotNet.Docker.Tests/Config.cs#L28
In this case, the value returned from `GetEnvironmentVariable` is an empty value instead of `null`. Because it's not null, it doesn't default it to the value from the manifest which is `mcr.microsoft.com`.  This return value is a change in behavior that I haven't been able to account for. Comparing previously successful builds, the same version of .NET SDK is …

Fix environment variable checks to account for empty value

---

.github/ISSUE_TEMPLATE/releases/dotnet-release-lifecycle.md

The .NET containers roadmap has been added to https://github.com/dotnet/core/blob/main/roadmap.md. I added a checklist item for updating it with each new .NET version.

Add task for updating roadmap to dotnet-release-lifecycle.md

---

tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs

I got frustrated with slow Test Discovery and used PerfView on a run of our unit tests to see why it took so long. `DockerOS` was being accessed many times during test discovery because we have the custom `LinuxImageTheory` attribute. Each time it was accessed, it took two seconds to call `docker.exe`, even though the result never changes during a single test run.
Wrapping it in a Lazy<> speeds up test discovery by a factor of ~60.
Before - **27.64 seconds**
```
Starting test discovery, please wait...
[xUnit.net 00:00:00.00] xUnit.net VSTest Adapter v2.4.5+1caef2f33e (64-bit .NET 9.0.1)
[xUnit.net 00:00:00.70]   Discovering: Microsoft.DotNet.Docker.Tests
[xUnit.net 00:00:28.34]   Discovered:  Microsoft.DotNet.Docker.Tests
```
After - **0.44 seconds**
```
Starting test discovery, please …
```

Cache result of Docker OS to speed up XUnit test discovery

---

manifest.versions.json

This is a small change to help prevent accidental deletion of the major version variables when removing minor versions from the versions manifest. The major version variables are move to their own block so as not to be conflated with minor version variables.

Move .NET Monitor major version variables to their own block

---

tests/Microsoft.DotNet.Docker.Tests/StaticTagTests.cs

This change updates the StaticTagTests to allow major version preview tags to be used on the latest preview version of a product while the GA tags are on the latest GA version of a product within a major version group. For example, we are trying to add .NET Monitor 9.1 images to the manifest and would like to have the following tags:
- .NET Monitor 9.0: `9`, `9.0`
- .NET Monitor 9.1: `9-preview`, `9.1-preview`
As the StaticTagTests are today, they would require that the `9` tag be placed on the .NET Monitor 9.1 images even though they are still in preview. These changes make sure that the major version GA tags are only on the latest major.minor version within a major version group.
These changes should work with the existing images in the manifest (because there are no images that have a …

Allow major version preview tags to exist with GA tags within a major version group

---

.vscode/tasks.json

As it's useful to run the VerifyInternalDockerfiles test when updating Dockerfile templates, I've added this VS Code task which runs just the one test.

Add VS Code task for verifying internal Dockerfile template baselines

---

.devcontainer/devcontainer.json

Some features of GitHub Copilot Workspaces rely on features present in bash/zsh that are not present in sh. Copilot uses the default terminal from the container. In our SDK images, that is sh.
The option that was previously set in devcontainer.json is a VS Code setting, so it doesn't apply to Copilot Workspaces. ~~Running `chsh -s /bin/bash` doesn't work either, since we're running as non-root. That command requires elevation.~~
That leaves two options, which were:
- Use a Dockerfile to set SHELL to bash
- Use the official devcontainers "common-utils" features to install zsh and set it as the default. ~~This is the one I chose. This is also what the dotnet devcontainers images use: https://github.com/devcontainers/images/blob/cd4daf6c6b692cea79c83ff26c60bca44f51e8f7/src/dotnet/.devcontaine …

Use bash instead of sh in devcontainer

---

.github/copilot-instructions.md

These changes add instructions for GitHub Copilot to the `.github/copilot-instructions.md` file.
The documentation for Copilot instructions is at: https://github.blog/changelog/2025-01-21-custom-repository-instructions-are-now-available-for-copilot-on-github-com-public-preview/
Developing these instructions will be an iterative process and this is only the first iteration. There is probably more we can add later.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/dotnet/dotnet-docker/pull/6247?shareId=4d3b4d82-8cc3-43e9-b2a4-4c2390ee1d91).

Add Copilot Instructions

---

README.monitor.md
manifest.json

The platform tags for .NET Monitor 8.1 were not undocumented in the nightly branch, whereas in the main branch they are undocumented as expected. This change reconciles that difference so that the platform tags are undocumented in the nightly branch.

Undocument dotnet/monitor 8.1 platform tags

---

tests/Microsoft.DotNet.Docker.Tests/GeneratedArtifactTests.cs

Port of https://github.com/dotnet/dotnet-docker/pull/6273 to main branch.

[main] Disable internal Dockerfile tests for internal builds

---

tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/TestScenarios/WebScenario.cs

The VerifyDotnetFolderContents test is causing flaky PR validation due to issues with downloading the SDK from the internet. This PR adds retry logic to the test.
Other changes:
- Pulled HttpClient and auth stuff out as static members
- Enabled nullable annotations in the file
- Cleaned up what I saw as unnecessary code
- `IEqualityComparer`
- use record value equality instead of `IComparable`

Add retries to SDK download in VerifyDotnetFolderContents test

---

README.aspire-dashboard.md
manifest.json
src/aspire-dashboard/9.1/azurelinux-distroless/amd64/Dockerfile
src/aspire-dashboard/9.1/azurelinux-distroless/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/aspire-dashboard-9.1-azurelinux-distroless-amd64-Dockerfile.approved.txt
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/aspire-dashboard-9.1-azurelinux-distroless-arm64v8-Dockerfile.approved.txt
tests/Microsoft.DotNet.Docker.Tests/TestData.cs
tests/performance/ImageSize.nightly.linux.json

Part 2/2 of [Update .NET 8-based aspire-dashboard and monitor mariner images to 3.0 (#5375)](https://github.com/dotnet/dotnet-docker/issues/5375)
Related to #6257

Update Aspire Dashboard image to Azure Linux 3.0

---

eng/dockerfile-templates/aspire-dashboard/Dockerfile.linux
eng/dockerfile-templates/aspire-dashboard/Dockerfile.linux.install-aspire-dashboard
eng/dockerfile-templates/yarp/Dockerfile.linux
eng/dockerfile-templates/yarp/Dockerfile.linux.install-yarp
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/aspire-dashboard-9.1-azurelinux-distroless-amd64-Dockerfile.approved.txt
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/aspire-dashboard-9.1-azurelinux-distroless-arm64v8-Dockerfile.approved.txt
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/yarp-2.3-azurelinux-distroless-amd64-Dockerfile.approved.txt
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/yarp-2.3-azurelinux-distroless-arm64v8-Dockerfile.approved.txt

This is part of #6254 and #6255. 
As there isn't yet support for Aspire Dashboard or YARP in the update-dependencies tooling, I can't tell what the precise download paths will be, so I didn't change them yet. However, this PR sets up the plumbing for using the ACCESSTOKEN arg for these Dockerfile builds so we don't have to do it later.

Add ACCESSTOKEN support to Aspire Dashboard and YARP internal Dockerfiles 

---

eng/pipelines/update-dependencies-internal.yml
eng/pipelines/variables/core.yml
eng/pipelines/variables/internal-core.yml

I evaluated all of the pipeline variable groups we reference. I searched our codebase for each variable in each of the groups that aren't managed by the containers team and removed the groups where we no longer reference any of the variables.

Remove unused Azure Pipelines variable group references

---

eng/common/templates/variables/dotnet/build-test-publish.yml

Reverts dotnet/dotnet-docker#6341 - the fine-grained token didn't work for now and the original token has been updated to use a shorter expiration date.

Revert "Update mcrdocs access token variable"

---

eng/pipelines/cg-code.yml

This PR fixes the CG build pipeline, which is failing due to #6307.
Related:
- https://github.com/dotnet/docker-tools/pull/1659

Update CG pipeline to use .NET 10

---

manifest.versions.json
src/runtime-deps/10.0/trixie-slim/amd64/Dockerfile
src/runtime-deps/10.0/trixie-slim/arm32v7/Dockerfile
src/runtime-deps/10.0/trixie-slim/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/runtime-deps-10.0-trixie-slim-amd64-Dockerfile.approved.txt
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/runtime-deps-10.0-trixie-slim-arm32v7-Dockerfile.approved.txt
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/runtime-deps-10.0-trixie-slim-arm64v8-Dockerfile.approved.txt
tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs

Debian Trixie is transitioning from `libicu72` to `libicu76`.
The arm32 builds currently fail without this update because, in that package feed, `libicu72` doesn't exist. But for the other architectures, both package versions exist.

Update Debian Trixie to use libicu76

---

tests/Microsoft.DotNet.Docker.Tests/ProductImageData.cs

Closes #2544.
Both Alpine ARM issues are closed and there is not strong enough demand for us to continue pushing the PowerShell team to support musl-arm.

Remove comment link to closed PowerShell Alpine ARM issue

---

tests/Microsoft.DotNet.Docker.Tests/Microsoft.DotNet.Docker.Tests.csproj

This is a short-term fix for #6377.
This does not resolve #6195 - we should still really only use Shouldly, but that migration will take more work.

Replace FluentAssertions with AwesomeAssertions

---

eng/pipelines/jobs/update-tools.yml
eng/pipelines/steps/update-dependencies-specific.yml
eng/pipelines/steps/update-dependencies.yml
eng/pipelines/steps/update-dotnet-dependencies-specific.yml
eng/pipelines/steps/update-dotnet-dependencies.yml
eng/pipelines/update-dependencies-internal.yml
eng/pipelines/update-dependencies.yml
eng/update-dependencies/BuildAssetService.cs
eng/update-dependencies/CreatePullRequestOptions.cs
eng/update-dependencies/FromChannelCommand.cs
eng/update-dependencies/FromChannelOptions.cs
eng/update-dependencies/Program.cs
eng/update-dependencies/SpecificCommandOptions.cs
eng/update-dependencies/update-dependencies.csproj

This PR is a draft since it's based on #6378. It will be rebased once that PR is merged.
Adds a new command `from-channel` which takes a channel and repo to get the latest build from. It should only work for the VMR for now. In the future maybe we'll allow other repos like monitor, yarp, aspire, etc..
This iteration of the code simply gets the new .NET versions from BAR by reading a single build asset containing those versions. Then it sets up a call to the `specific` versions command and executes it. So, we are still relying on `SpecificCommand` and all its code for resolving product version hashes. In the future, all versions and hashes should be read directly from the BAR build. But this is the MVP for consuming VMR builds.
Todo:

Enable consuming public .NET SDK builds from the VMR using DarcLib

---

eng/pipelines/steps/update-dependencies.yml
eng/pipelines/update-dependencies.yml

1. The `channel` variable expansion didn't work (testing was only done with hard-coded parameters)
2. There was a weird issue with Invoke-Expression for tool updates: `Missing expression after unary operator '--'`. Adding quotes seems to have fixed it in my testing.
3. Updated the stage name.
Related: #6379

Fix minor issues with update-dependencies pipeline

---

eng/pipelines/jobs/update-tools.yml
eng/pipelines/steps/update-dependencies.yml

Related: #6387 
- Quoting around `$command` resulted in no commands being ran at all
- The newline at the end of `update-tools.yml` was being added to the end of the arguments list, causing a problem when interpreting the arguments string in the Invoke-Expression cmdlet:
> ```
> Invoke-Expression: /home/vsts/work/_temp/518b6f0d-7f3c-42fc-b864-a14a7949d4e1.ps1:11
> Line |
>   11 |  Invoke-Expression "$command";
>      |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      | Missing expression after unary operator '--'.
> ```
You could see this in the rendered yaml output of the pipeline:
```yml
- task: PowerShell@2
displayName: Run Update Dependencies
inputs:
targetType: inline
script: >
$args = "specific 9.0 --tool chisel --version-source-name chisel --source-branch nightly --target-branch nightly --org …
```

Fix remaining issues with update-dependencies pipeline yaml

---

eng/pipelines/release-staging.yml

This PR is part of https://github.com/dotnet/dotnet-docker-internal/issues/7413 and a direct follow-up to [Use split build/test and publish templates (#6386)](https://github.com/dotnet/dotnet-docker/pull/6386).
This is an initial implementation for the release-staging pipeline.
It currently does not support publishing internal images. I will revisit that functionality once I have also prototyped out the release-promotion pipeline (https://github.com/dotnet/dotnet-docker-internal/issues/7414).
Successful internal test: https://dev.azure.com/dnceng/internal/_build/results?buildId=2695716&view=results

Use the new build-and-test template for release staging

---

eng/update-dependencies/Program.cs

Fixes #6394
`System.Commandline.Hosting` forcibly sets `yourCommand.TreatUnmatchedTokensAsErrors = false` and also overrides the command's action, so we can't fix this behavior by either of those means.
However, unmatched tokens are passed to the `hostBuilderFactory`, which allows you to configure additional hosting options based on those extra tokens. Since we don't need those extra arguments, we can use that opportunity to print the help output and throw an exception.
https://github.com/dotnet/command-line-api/blob/a91bcf488ba7d0112b2637b505f8de32aded6825/src/System.CommandLine.Hosting/HostingAction.cs#L26-L27

Show help output when there are unmatched tokens passed to update-dependencies CLI

---

.github/linters/.linkspector.yml

Related: https://github.com/UmbrellaDocs/action-linkspector/issues/43

Allow status code 429 for link check action

---

eng/common/templates/variables/dotnet/build-test-publish.yml

Related: https://github.com/dotnet/docker-tools/issues/1656
Temporarily revert these changes in order to unblock pushing tags for new images. These changes should be added back once the GitHub App has the correct permissions to push changes.

Temporarily revert MAR Docs publishing GitHub App auth authentication changes

---

.portal-docs/docker-hub/README.aspnet.md
.portal-docs/docker-hub/README.monitor-base.md
.portal-docs/docker-hub/README.monitor.md
.portal-docs/docker-hub/README.runtime-deps.md
.portal-docs/docker-hub/README.runtime.md
.portal-docs/docker-hub/README.samples.md
.portal-docs/docker-hub/README.sdk.md
.portal-docs/docker-hub/README.yarp.md
.portal-docs/mar/README.aspnet.portal.md
.portal-docs/mar/README.monitor-base.portal.md
.portal-docs/mar/README.monitor.portal.md
.portal-docs/mar/README.runtime-deps.portal.md
.portal-docs/mar/README.runtime.portal.md
.portal-docs/mar/README.samples.portal.md
.portal-docs/mar/README.sdk.portal.md
.portal-docs/mar/README.yarp.portal.md
README.aspnet.md
README.md
README.monitor-base.md
README.monitor.md
README.runtime-deps.md
README.runtime.md
README.samples.md
README.sdk.md
README.yarp.md
eng/readme-templates/Use.md
eng/readme-templates/Use.runtime-deps.md

- Updated main .NET Docker tutorial link
- Added explicit link to [Host ASP.NET Core in Docker containers](https://learn.microsoft.com/aspnet/core/host-and-deploy/docker) for repos that it's relevant for
- Added link to native AOT sample for runtime-deps

Update some usage and samples links

---

eng/pipelines/update-dependencies-monitor.yml

This pipeline had not responded to breaking changes in [Enable consuming public .NET SDK builds from the VMR using DarcLib (dotnet/dotnet-docker#6379)](https://github.com/dotnet/dotnet-docker/pull/6379), and it started failing since [Show help output when there are unmatched tokens passed to update-dependencies CLI (dotnet/dotnet-docker#6402)](https://github.com/dotnet/dotnet-docker/pull/6402) was fixed. Prior to that fix, it was silently failing with a no-op.

Fix update-dependencies-monitor pipeline

---

eng/Set-DotnetVersions.ps1
eng/pipelines/steps/update-dependencies-specific.yml

Follow-up to https://github.com/dotnet/dotnet-docker/pull/6410 - that PR was an incomplete fix.
When using Set-DotnetVersions.ps1, it would only use the correct update-dependencies subcommand correctly when calling the tool directly, but not when setting the arguments as an azure pipelines variable. This PR fixes that and also logs the command before it's run so that it's easier to troubleshoot.

Use 'specific' command when setting updateDepsArgs from Set-DotnetVersions.ps1

---

tests/Microsoft.DotNet.Docker.Tests/CommonRuntimeImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs

This is a mitigation for https://github.com/dotnet/dotnet-docker/issues/6419
An update to SymCrypt brought in lots of extra packages.

Update package baseline for Azure Linux 3.0

---

tests/Microsoft.DotNet.Docker.Tests/CommonRuntimeImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs

The Azure Linux SymCrypt package was updated, and it no longer has a dependency on bash.
- Reverts dotnet/dotnet-docker#6422
- Related
- dotnet/dotnet-docker#6423
- https://github.com/dotnet/dotnet-docker/pull/6442
- Fixes #6419

Revert "Update package baseline for Azure Linux 3.0"

---

tests/Microsoft.DotNet.Docker.Tests/CommonRuntimeImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs

The Azure Linux SymCrypt package was updated, and it no longer has a dependency on bash.
- Reverts dotnet/dotnet-docker#6423
- Fixes #6419

Revert "[main] Update package baseline for Azure Linux 3.0"

---

eng/update-dependencies/SpecificCommand.cs

Workaround issue where Update Dependencies tool would sometimes overwrite PRs

---

.github/linters/.linkspector.yml

This ignores https://aka.ms/ in the markdown link checker since it leads to an internal site. Please note that it does not ignore all aka.ms/* links, only https://aka.ms/ itself.

[main] Ignore https://aka.ms/ in markdown link checker

---

eng/update-dependencies/BuildUpdaterService.cs
eng/update-dependencies/CreatePullRequestOptions.cs
eng/update-dependencies/FromBuildOptions.cs
eng/update-dependencies/FromChannelOptions.cs
eng/update-dependencies/FromStagingPipelineCommand.cs
eng/update-dependencies/FromStagingPipelineOptions.cs
eng/update-dependencies/Model/Release/BuildManifest.cs
eng/update-dependencies/Model/Release/ReleaseManifest.cs
eng/update-dependencies/Program.cs
eng/update-dependencies/ReleaseConfig.cs
eng/update-dependencies/SpecificCommandOptions.cs
eng/update-dependencies/StorageAccount.cs
eng/update-dependencies/VersionHelper.cs
eng/update-dependencies/update-dependencies.csproj

- New command: `from-staging-pipeline`
- This command supplants `Get-DropVersions.ps1 -BuildId ...` and accomplishes the same things.
- This command does _not_ yet update dependencies with internal versions. This means the base urls won't be updated and the Dockerfiles won't be generated with the internal versions of the templates just yet.
- The reason for that is the old update-dependencies code depends on using the base URL for accessing the sha files, so that will need to be updated or replaced separately.

Add staging pipeline support to update-dependencies tool

---

eng/dockerfile-templates/Get-GeneratedDockerfiles.ps1
eng/readme-templates/Get-GeneratedReadmes.ps1

ImageBuilder prints `docker version` and `docker info` by default. This output is not useful when generating templates, so this disables it. Disabling it saves up to 2-3 seconds when generating Dockerfiles/Readmes.

Disable version logging when generating Dockerfiles/Readmes

---

eng/update-dependencies/FromStagingPipelineCommand.cs
eng/update-dependencies/FromStagingPipelineOptions.cs

Usage:
```
update-dependencies \
from-staging-pipeline \
2733981 \
--internal \
--staging-storage-account $account \
--azdo-organization $org \
--azdo-project $project
```
Add or remove the `--internal` flag to control whether Dockerfiles will be updated to target an internal build. If `--internal` is passed, then `--staging-storage-account` is required.

Add support for internal build URLs to update-dependencies `from-staging-pipeline` command

---

eng/dockerfile-templates/sdk/Dockerfile.linux
src/sdk/10.0/alpine3.22/amd64/Dockerfile
src/sdk/10.0/alpine3.22/arm32v7/Dockerfile
src/sdk/10.0/alpine3.22/arm64v8/Dockerfile
src/sdk/10.0/azurelinux3.0/amd64/Dockerfile
src/sdk/10.0/azurelinux3.0/arm64v8/Dockerfile
src/sdk/10.0/noble/amd64/Dockerfile
src/sdk/10.0/noble/arm32v7/Dockerfile
src/sdk/10.0/noble/arm64v8/Dockerfile
src/sdk/10.0/trixie-slim/amd64/Dockerfile
src/sdk/10.0/trixie-slim/arm32v7/Dockerfile
src/sdk/10.0/trixie-slim/arm64v8/Dockerfile
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/sdk-10.0-alpine3.22-amd64-Dockerfile.approved.txt
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/sdk-10.0-alpine3.22-arm32v7-Dockerfile.approved.txt
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/sdk-10.0-alpine3.22-arm64v8-Dockerfile.approved.txt
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/sdk-10.0-azurelinux3.0-amd64-Dockerfile.approved.txt
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/sdk-10.0-azurelinux3.0-arm64v8-Dockerfile.approved.txt
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/sdk-10.0-noble-amd64-Dockerfile.approved.txt
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/sdk-10.0-noble-arm32v7-Dockerfile.approved.txt
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/sdk-10.0-noble-arm64v8-Dockerfile.approved.txt
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/sdk-10.0-trixie-slim-amd64-Dockerfile.approved.txt
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/sdk-10.0-trixie-slim-arm32v7-Dockerfile.approved.txt
tests/Microsoft.DotNet.Docker.Tests/Baselines/GeneratedArtifactTests/VerifyInternalDockerfilesOutput/sdk-10.0-trixie-slim-arm64v8-Dockerfile.approved.txt

A reference to `dnx` was mistakenly added in https://github.com/dotnet/dotnet-docker/pull/6521. `dnx` was added in .NET 10 Preview 6, which is not out yet.

Remove reference to dnx in .NET 10 Preview 5 images

---

documentation/supported-platforms.md

- Clarify that Windows images will be published for versions which are in **Mainstream Support** (vs. Extended Support).
- Add more links to Windows Server support documentation.
- **Updated verbiage**: instead of saying we "support" a platform, be clear that we "publish .NET images" for these platforms. "Support" has a separate meaning and is documented in the [official release notes](https://github.com/dotnet/core/blob/main/release-notes/9.0/supported-os.json).

Clarify Windows image publishing policy

---

eng/dockerfile-templates/Dockerfile.download-dotnet

This is a workaround for https://github.com/dotnet/release/issues/1395. This is needed in order to build internal .NET 8.0 `aspnet` images.

Use nonshipping url for internal ASP.NET 8.0 checksums

---

eng/pipelines/release-promotion.yml

Recent release promotion pipeline changes + pipeline renaming caused this pipeline resource reference to be incorrect.

Fix staging pipeline reference

---

manifest.versions.json
tests/Microsoft.DotNet.Docker.Tests/AspireDashboardImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/AspnetImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/DockerHelper.cs
tests/Microsoft.DotNet.Docker.Tests/ProductImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/RuntimeDepsImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/RuntimeImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/SdkImageTests.cs
tests/Microsoft.DotNet.Docker.Tests/SyftHelper.cs
tests/Microsoft.DotNet.Docker.Tests/TestScenarios/ReverseProxyBasicScenario.cs

Related:
- https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/1435#issuecomment-2946447028
Syft images >= v1.27 use a non-root user by default, event for the `-debug` versions of images. That's incompatible with the way we were using the syft image. Instead of writing to a directory inside the syft image, mount the syft image and the image to scan in the same layer and copy syft's output to a `scratch` layer. This has the benefit of being much faster _and_ compatible with distroless + non-root images on both sides (syft and the target images).
Other changes:
- Fixed warning due to unused otel variable
- Update Syft image to latest version v1.31.0
- Some minor refactoring/better encapsulation for syft related code.

Use Syft inside a Dockerfile build to scan images during tests

---

eng/update-dependencies/SyftUpdater.cs
tests/Microsoft.DotNet.Docker.Tests/SyftHelper.cs

This automatic PR is updating the wrong variable:
- https://github.com/dotnet/dotnet-docker/pull/6612
It was trying to update **syft|tag** instead of **syft|version**. **syft|version** was added in https://github.com/dotnet/dotnet-docker/pull/6611 so that we could use a different tag suffix for the syft image.

Target version variable instead of tag for automatic syft updates

---

tests/Microsoft.DotNet.Docker.Tests/DotNetImageRepo.cs
tests/Microsoft.DotNet.Docker.Tests/ProductImageData.cs
tests/Microsoft.DotNet.Docker.Tests/TestData.cs
tests/Microsoft.DotNet.Docker.Tests/TestDataTests.cs
tests/Microsoft.DotNet.Docker.Tests/YarpImageTests.cs

Some appliance images were not being properly tested in internal pipeline runs due to the `OSDir` property being set incorrectly in TestData.
This is a band-aid fix - https://github.com/dotnet/dotnet-docker/issues/5337 is a better long term solution.

Fix appliance app test filtering due to incorrect OS directories in TestData

---

eng/update-dependencies/FromStagingPipelineCommand.cs
eng/update-dependencies/update-dependencies.csproj

Part of https://github.com/dotnet/dotnet-docker-internal/issues/6741.
It's described pretty well in the code change, but we need to record all internal versions that we apply to the repo so that we can rewind and replay updates whenever we need to update the internal/release branch. Using this method will avoid merge conflicts.

Record internal build version when using --internal flag
